PROGRAM FORCE_MULTIPLIER_TEST
  USE, INTRINSIC :: IEEE_ARITHMETIC, ONLY: IEEE_IS_FINITE
  IMPLICIT NONE
  INTEGER,PARAMETER :: NB=3,NP=4
  COMPLEX(8) :: P(NP,NB),DP(NP,NB),DH(NP,NP),Q(NP,NP)
  COMPLEX(8) :: C(NB,NB),RLAM(NB,NB),LAMBDA(NB,NB),OLD(NB,NB)
  COMPLEX(8) :: GRAD(NP,NB),OLD_GRAD(NP,NB)
  COMPLEX(8) :: PROJECTED(1,NB,NP),OPROJECTED(1,NB,NP),QP(NP,NB)
  REAL(8) :: OCC(NB),H,FD,ANALYTIC,LEGACY,ERROR
  INTEGER :: I,J,K,DIRECTION

  DO J=1,NB
    DO I=1,NP
      P(I,J)=CMPLX(SIN(REAL(I+2*J,8)),COS(REAL(3*I-J,8)),8)*0.2D0
    END DO
  END DO
  DO J=1,NP
    DO I=1,NP
      DH(I,J)=CMPLX(COS(REAL(I+J,8)),SIN(REAL(I-J,8)),8)
      Q(I,J)=CMPLX(COS(REAL(I-J,8)),0.D0,8)*0.1D0
    END DO
  END DO
  H=1.D-5
  DO K=1,5
    SELECT CASE(K)
    CASE(1)
      OCC=[2.D0,2.D0,2.D0]
    CASE(2,4)
      OCC=[2.D0,0.7D0,0.2D0]
    CASE(3)
      OCC=[2.D0,0.7D0,0.D0]
    CASE(5)
      OCC=0.D0
    END SELECT
    ! Specify the Lagrangian multiplier independently of the tested helper.
    DO J=1,NB
      DO I=1,NB
        C(I,J)=CMPLX(COS(REAL(I+J,8)),SIN(REAL(I-J,8)),8)*0.3D0
        IF(OCC(I).EQ.0.D0.OR.OCC(J).EQ.0.D0) C(I,J)=(0.D0,0.D0)
      END DO
    END DO
    IF(K.EQ.4) C(1,2)=C(1,2)+CMPLX(0.03D0,-0.02D0,8)
    DO J=1,NB
      IF(OCC(J).GT.0.D0) THEN
        RLAM(:,J)=C(:,J)/OCC(J)
      ELSE
        ! An empty column of the equation-of-motion matrix is unconstrained.
        RLAM(:,J)=CMPLX(0.8D0,-0.6D0,8)
      END IF
    END DO
    CALL WAVES_FORCE_MULTIPLIER(NB,OCC,RLAM,LAMBDA)
    IF(ANY(.NOT.IEEE_IS_FINITE(REAL(LAMBDA,8)))) STOP 1
    IF(ANY(.NOT.IEEE_IS_FINITE(AIMAG(LAMBDA)))) STOP 1
    IF(MAXVAL(ABS(LAMBDA-CONJG(TRANSPOSE(LAMBDA)))).GT.1.D-14) STOP 1
    IF(K.NE.4.AND.MAXVAL(ABS(LAMBDA+C)).GT.1.D-14) STOP 1
    IF(K.EQ.3.AND.MAXVAL(ABS(LAMBDA(:,3))).NE.0.D0) STOP 1
    IF(K.EQ.5.AND.MAXVAL(ABS(LAMBDA)).NE.0.D0) STOP 1
    DO J=1,NB
      DO I=1,NB
        OLD(I,J)=-RLAM(I,J)*0.5D0*(OCC(I)+OCC(J))
      END DO
    END DO
    IF(K.EQ.1.AND.MAXVAL(ABS(OLD-LAMBDA)).GT.1.D-14) STOP 1
    DO J=1,NB
      GRAD(:,J)=MATMUL(DH,P(:,J))*OCC(J)
    END DO
    QP=MATMUL(Q,P)
    DO I=1,NP
      PROJECTED(1,:,I)=GRAD(I,:)
      OPROJECTED(1,:,I)=QP(I,:)
    END DO
    CALL WAVES_ADDOPROJ(NP,1,NB,NB,PROJECTED,OPROJECTED,LAMBDA)
    OLD_GRAD=GRAD+MATMUL(MATMUL(Q,P),OLD)
    GRAD=GRAD+MATMUL(MATMUL(Q,P),LAMBDA)
    DO I=1,NP
      IF(MAXVAL(ABS(PROJECTED(1,:,I)-GRAD(I,:))).GT.1.D-13) STOP 1
    END DO
    DO DIRECTION=1,4
      DO J=1,NB
        DO I=1,NP
          DP(I,J)=CMPLX(COS(REAL(DIRECTION*I+J,8)), &
                       SIN(REAL(I-DIRECTION*J,8)),8)*0.2D0
        END DO
      END DO
      FD=(ENERGY(P+H*DP)-ENERGY(P-H*DP))/(2.D0*H)
      ANALYTIC=2.D0*REAL(SUM(CONJG(GRAD)*DP),8)
      LEGACY=2.D0*REAL(SUM(CONJG(OLD_GRAD)*DP),8)
      ERROR=ABS(FD-ANALYTIC)
      WRITE(*,'(A,2I3,3ES24.14)') 'FORCE MULTIPLIER CASE, DIRECTION, FD, ERROR, LEGACY ERROR ', &
          K,DIRECTION,FD,ERROR,ABS(FD-LEGACY)
      IF(.NOT.IEEE_IS_FINITE(ERROR).OR.ERROR.GT.1.D-8) STOP 1
      IF((K.EQ.2.OR.K.EQ.3).AND.ABS(FD-LEGACY).LT.1.D-5) STOP 1
    END DO
  END DO
  CALL CHECK_PACKED
CONTAINS
  SUBROUTINE CHECK_PACKED
    REAL(8) :: F(4),W(NP,4),TARGET(NP,4),C4(4,4)
    COMPLEX(8) :: R4(4,4),L4(4,4),OP(1,2,NP),OUT(1,2,NP)
    INTEGER :: A,B
    F=[2.D0,0.7D0,0.2D0,0.D0]
    DO B=1,4
      DO A=1,4
        C4(A,B)=COS(REAL(A+B,8))
        IF(F(A).EQ.0.D0.OR.F(B).EQ.0.D0) C4(A,B)=0.D0
      END DO
      IF(F(B).GT.0.D0) THEN
        R4(:,B)=CMPLX(C4(:,B)/F(B),0.D0,8)
      ELSE
        R4(:,B)=0.8D0
      END IF
      DO A=1,NP
        W(A,B)=SIN(REAL(A+2*B,8))
      END DO
    END DO
    CALL WAVES_FORCE_MULTIPLIER(4,F,R4,L4)
    TARGET=-MATMUL(W,C4)
    DO A=1,NP
      OP(1,1,A)=CMPLX(W(A,1),W(A,2),8)
      OP(1,2,A)=CMPLX(W(A,3),W(A,4),8)
    END DO
    OUT=(0.D0,0.D0)
    CALL WAVES_ADDOPROJ(NP,1,2,4,OUT,OP,L4)
    DO A=1,NP
      IF(ABS(OUT(1,1,A)-CMPLX(TARGET(A,1),TARGET(A,2),8)).GT.1.D-13) STOP 1
      IF(ABS(OUT(1,2,A)-CMPLX(TARGET(A,3),TARGET(A,4),8)).GT.1.D-13) STOP 1
    END DO
    WRITE(*,'(A)') 'PACKED REAL AND COMPLEX PROJECTOR CONTRACTIONS PASSED'
  END SUBROUTINE

  FUNCTION ENERGY(X) RESULT(VALUE)
    COMPLEX(8),INTENT(IN) :: X(NP,NB)
    COMPLEX(8) :: OVERLAP(NB,NB)
    REAL(8) :: VALUE
    INTEGER :: A,B
    VALUE=0.D0
    DO B=1,NB
      VALUE=VALUE+OCC(B)*REAL(DOT_PRODUCT(X(:,B),MATMUL(DH,X(:,B))),8)
    END DO
    OVERLAP=MATMUL(CONJG(TRANSPOSE(X)),MATMUL(Q,X))
    DO B=1,NB
      DO A=1,NB
        VALUE=VALUE-REAL(C(A,B)*OVERLAP(B,A),8)
      END DO
    END DO
  END FUNCTION
END PROGRAM
