#!/bin/ksh
#this is a test and does not work yet.....
#==========================================================
#  take the last argument file as control file           ==
#==========================================================
PARAMETERS=""
while (( $# )); do
if (( $# == 1 )); then
  CONTROLFILE=$1
else
  PARAMETERS="$PARAMETERS $1"
fi
shift
done
#==========================================================
#  select paw-tool                                       ==
#==========================================================
while read < $CONTROLFILE;
 do set -- "$REPLY"
   case $0 in
     !CNTL)  # perform paw-simulation
       paw_run $PARAMETERS
       exit 0
     !TCNTL) # run trajectory tool  
       paw_tra $PARAMETERS
       exit 0
     !GCNTL) # run grab tool  
       paw_grab $PARAMETERS
       exit 0
     !DCNTL) # run density of states tool
       paw_dos $PARAMETERS
       exit 0
   esac;
 done
  
