#!/bin/sh
export PROJECT=$1
if [ -z $1 ]; then
  echo error in paw_get_gap: missing argument
  echo specify root name of the paw_project
  exit 1
fi
#
# Does protocoll file exist?
#
if [ ! -e $PROJECT.prot ]; then
  echo error in paw_get_gap: protocoll file does not exist
  echo specified: $PROJECT.prot
  exit 1
fi
#
#  extract result
#
export RESULT=`grep "ABSOLUTE GAP" $PROJECT.prot | tail -n1 | awk -F: '{print $2}' `
if [ -z  "$RESULT" ] ; then
  echo error in paw_get_gap: no gap listed
  exit 1
fi
#
#  report result
#
echo $RESULT
exit 0
