#!/bin/sh
#################################################################
#
#  name: paw_collect: 
#
#  purpose: collects total energies from CP-PAW projects
#
# searches through all *.prot files in the current directory, 
# as well as one and two subdirectories down
# and lists the name of the project and the last total energy
# written in the extended printout. The resulting list appears 
# in the file pawcollect.out
#
#################################################################
for DIR in . * */* */*/* ; do
   if test -d $DIR ; then
     for FILE in $DIR/*.prot; do
       if test -e $FILE ; then
         ENERGY=$(grep -i 'Total energy' $FILE \
                 | tail -1 |sed s/H//g |sed s/TOTAL//g \
                 |sed s/ENERGY//g |sed s/://g)
         echo $FILE: $ENERGY
       fi
     done
   fi
done
