PROGRAM BACKGROUND_STRAIN_TEST
  USE, INTRINSIC :: IEEE_ARITHMETIC, ONLY: IEEE_IS_FINITE
  IMPLICIT NONE
  INTEGER,PARAMETER :: NR=801,LMRX=4
  REAL(8),PARAMETER :: H=1.D-5,RCSM=0.7D0
  REAL(8),PARAMETER :: CHARGES(4)=[0.D0,1.D-4,-2.D-4,1.D-8]
  REAL(8) :: R(NR),AECORE(NR),PSCORE(NR),AERHO(NR,LMRX),PSRHO(NR,LMRX)
  REAL(8) :: VADD(NR),VQLM(LMRX),QLM(LMRX),POT(NR,LMRX)
  REAL(8) :: EA,EP,BA,BP,E0A,E0P,EM,PLUS,ANALYTIC,ERR,MAXERR,RHOB
  INTEGER :: GID,I,K,DIRECTION
  CALL MPE$INIT
  CALL RADIAL$NEW('LOG',GID)
  CALL RADIAL$SETI4(GID,'NR',NR)
  CALL RADIAL$SETR8(GID,'R1',1.D-6)
  CALL RADIAL$SETR8(GID,'DEX',LOG(2.D7)/REAL(NR-1,8))
  CALL RADIAL$R(GID,NR,R)
  AECORE=2.D0*EXP(-8.D0*R**2)
  PSCORE=0.2D0*EXP(-1.5D0*R**2)
  AERHO(:,1)=EXP(-2.D0*R**2)
  PSRHO(:,1)=0.8D0*EXP(-1.2D0*R**2)
  DO I=2,LMRX
    AERHO(:,I)=0.03D0*REAL(I-1,8)*R*EXP(-2.D0*R**2)
    PSRHO(:,I)=0.02D0*REAL(I-1,8)*R*EXP(-1.2D0*R**2)
  END DO
  VADD=-0.3D0*EXP(-R**2)
  VQLM=[0.1D0,0.02D0,-0.03D0,0.01D0]
  CALL AUGMENTATION_QLM(GID,NR,LMRX,4.D0,AECORE,PSCORE,AERHO,PSRHO,QLM)
  CALL AUGMENTATION_AEHARTREE(GID,NR,LMRX,4.D0,AECORE,AERHO,VQLM,0.D0,POT,E0A,BA)
  CALL AUGMENTATION_PSHARTREE(GID,NR,LMRX,PSCORE,PSRHO,VADD,RCSM,QLM,VQLM,0.D0,POT,E0P,BP)
  IF(BA.NE.0.D0.OR.BP.NE.0.D0) STOP 1
  MAXERR=0.D0
  DO K=1,SIZE(CHARGES)
    RHOB=CHARGES(K)
    CALL AUGMENTATION_AEHARTREE(GID,NR,LMRX,4.D0,AECORE,AERHO,VQLM,RHOB,POT,EA,BA)
    CALL AUGMENTATION_PSHARTREE(GID,NR,LMRX,PSCORE,PSRHO,VADD,RCSM,QLM,VQLM,RHOB,POT,EP,BP)
    ERR=MAX(ABS(EA-E0A-BA),ABS(EP-E0P-BP))
    IF(.NOT.IEEE_IS_FINITE(ERR).OR.ERR.GT.2.D-12) STOP 2
    WRITE(*,'(A,I3,ES14.5)') 'BACKGROUND ENERGY ACCOUNTING ',K,ERR
    DO DIRECTION=1,3
      ! One diagonal strain, uniform dilation, and symmetric xy shear.
      ANALYTIC=-(BA-BP)
      IF(DIRECTION.EQ.2) ANALYTIC=3.D0*ANALYTIC
      IF(DIRECTION.EQ.3) ANALYTIC=0.D0
      CALL ENERGY(-H,DIRECTION,EM)
      CALL ENERGY(H,DIRECTION,PLUS)
      ERR=ABS((PLUS-EM)/(2.D0*H)-ANALYTIC)
      IF(.NOT.IEEE_IS_FINITE(ERR)) STOP 3
      MAXERR=MAX(MAXERR,ERR)
      WRITE(*,'(A,2I3,ES14.5)') 'BACKGROUND STRAIN FD ',K,DIRECTION,ERR
    END DO
  END DO
  WRITE(*,'(A,ES14.5)') 'MAX BACKGROUND STRAIN ERROR ',MAXERR
  IF(MAXERR.GT.2.D-8) STOP 4
CONTAINS
  SUBROUTINE ENERGY(S,DIRECTION,VALUE)
    REAL(8),INTENT(IN) :: S
    INTEGER,INTENT(IN) :: DIRECTION
    REAL(8),INTENT(OUT) :: VALUE
    REAL(8) :: DET,BACKGROUND,A,P,BG
    DET=1.D0+S
    IF(DIRECTION.EQ.2) DET=(1.D0+S)**3
    IF(DIRECTION.EQ.3) DET=1.D0-0.25D0*S**2
    BACKGROUND=RHOB/DET
    CALL AUGMENTATION_AEHARTREE(GID,NR,LMRX,4.D0,AECORE,AERHO,VQLM,BACKGROUND,POT,A,BG)
    CALL AUGMENTATION_PSHARTREE(GID,NR,LMRX,PSCORE,PSRHO,VADD,RCSM,QLM,VQLM,BACKGROUND,POT,P,BG)
    VALUE=A-P
  END SUBROUTINE ENERGY
END PROGRAM BACKGROUND_STRAIN_TEST
