      PROGRAM MAIN
      USE PAW_SKALA_PRIMITIVES_MODULE, ONLY: PAW_SKALA_PRIMITIVES_TEST
      IMPLICIT NONE
      REAL(8) :: MAXERROR

      CALL PAW_SKALA_PRIMITIVES_TEST(MAXERROR)
      WRITE(*,FMT='("SKALA PRIMITIVE MAX ERROR ",ES24.14)')MAXERROR
      IF(MAXERROR.GT.2.D-9) STOP 1
      STOP 0
      END
