      PROGRAM MAIN
      USE PAW_SKALA_PRIMITIVES_MODULE, ONLY: PAW_SKALA_PRIMITIVES_TEST
      USE PAW_SKALA_GRID_MODULE, ONLY: PAW_SKALA_GRID_TEST
      IMPLICIT NONE
      REAL(8) :: MAXERROR,GRIDERROR

      CALL PAW_SKALA_PRIMITIVES_TEST(MAXERROR)
      CALL PAW_SKALA_GRID_TEST(GRIDERROR)
      MAXERROR=MAX(MAXERROR,GRIDERROR)
      WRITE(*,FMT='("SKALA GRID MAX ERROR ",ES24.14)')GRIDERROR
      WRITE(*,FMT='("SKALA PRIMITIVE MAX ERROR ",ES24.14)')MAXERROR
      IF(MAXERROR.GT.2.D-9) STOP 1
      STOP 0
      END
