#!/bin/ksh
#################################################################
##                                                             ##
##  Name: paw_install                                          ##
##                                                             ##
##                                                             ##
#################################################################
CURRENTDIR=.
export PAWDIR=$1
ARCH=$2
cp ./* $PAWDIR
paw_profile
paw_compile -arch$ARCH -o -new
paw_compile -arch$ARCH -g -new
paw_compile -arch$ARCH -n -new
paw_maketool

