#!/bin/ksh
#=============================================================
#==  prints date and version                                ==
#=============================================================
date
echo
echo "AIX version"
echo "==========="
oslevel
echo
echo "Version of the xlf Fortran compiler"
echo "==================================="
lslpp -h xlfrte
echo
echo "Version of the ESSL library"
echo "==========================="
lslpp -h essl.*.rte
exit 0
