#!/bin/sh
#
# USAGE
#
# first argument: binary to be produced
# rest of arguments: sources to be compiled and linked
#      MIND: just one '.' (before the f or f90) in the name
#
BINARY=$1
shift
OPTIONS=$@
TEMPLATES=T
for i in $OPTIONS; do
  echo "compiling $i"
  f90 -c -YEXT_NAMES=LCS -YEXT_SFX=_  -B100 -O $i 
  OBJ="$OBJ `echo $i | cut -d'.' -f1`.o"
  shift
done
echo "linking $OBJ"
f90   -L/home/ptpb/Tree/Archive/PAW_current/bin/intel/Objects/fast  -L/home/ptpb/Tree/Archive/PAW_current/lib/fftw-intel/fftw/.libs/ -L/home/ptpb/Tree/Archive/PAW_current/lib/ATLAS/lib/Linux_PIII -o $BINARY $OBJ -lpaw -lU77 -lm  -lfftw -llapack -lf77blas -latlas 
