PROGRAM SKALA_INTERPOLATION_TEST
  USE PAW_SKALA_GRID_MODULE
  IMPLICIT NONE
  INTEGER,PARAMETER :: N=16
  REAL(8) :: FIELD(N,N,N),CELL(3,3),X(3),XP(3),XM(3),G(3),GL(3),GR(3)
  REAL(8) :: PI,H,VP,VM,V,EXPECTED,ERROR_VALUE,ERROR_GRAD,ERROR_HESS,ERROR_FD
  REAL(8) :: SECOND_LEFT(3),SECOND_RIGHT(3),PERIODIC(3)
  INTEGER :: I,J,K,POWER,AXIS,FACE

  CELL=0.D0
  DO I=1,3
    CELL(I,I)=REAL(N,KIND=8)
  END DO
  ERROR_VALUE=0.D0
  ERROR_GRAD=0.D0
  DO AXIS=1,3
    DO POWER=0,8
      DO K=1,N
        DO J=1,N
          DO I=1,N
            X=REAL((/I-1,J-1,K-1/),KIND=8)
            FIELD(I,J,K)=((X(AXIS)-8.D0)/8.D0)**POWER
          END DO
        END DO
      END DO
      X=(/7.371D0,8.419D0,7.713D0/)
      CALL PAW_SKALA_GRID_INTERPOLATE(N,N,N,CELL,FIELD,X,V)
      CALL PAW_SKALA_GRID_INTERPOLATE_GRADIENT(N,N,N,CELL,FIELD,X,G)
      EXPECTED=((X(AXIS)-8.D0)/8.D0)**POWER
      ERROR_VALUE=MAX(ERROR_VALUE,ABS(V-EXPECTED))
      DO I=1,3
        EXPECTED=0.D0
        IF(I.EQ.AXIS.AND.POWER.GT.0) &
 &        EXPECTED=REAL(POWER,KIND=8)*((X(AXIS)-8.D0)/8.D0)**(POWER-1)/8.D0
        ERROR_GRAD=MAX(ERROR_GRAD,ABS(G(I)-EXPECTED))
      END DO
    END DO
  END DO
  WRITE(*,'(A,2ES16.7)') 'DEGREE-EIGHT VALUE/GRADIENT ERROR ',ERROR_VALUE,ERROR_GRAD
  IF(MAX(ERROR_VALUE,ERROR_GRAD).GT.2.D-12) STOP 1

  PI=ACOS(-1.D0)
  DO K=1,N
    DO J=1,N
      DO I=1,N
        FIELD(I,J,K)=COS(6.D0*PI*REAL(I-1,KIND=8)/N) &
 &                  +0.37D0*SIN(4.D0*PI*REAL(I-1,KIND=8)/N) &
 &                  +0.11D0*COS(2.D0*PI*REAL(J-1,KIND=8)/N) &
 &                  +0.17D0*SIN(6.D0*PI*REAL(K-1,KIND=8)/N) &
 &                  +0.1D0*COS(2.D0*PI*REAL(I+J-K-1,KIND=8)/N)
      END DO
    END DO
  END DO
  ERROR_GRAD=0.D0
  ERROR_HESS=0.D0
  ERROR_FD=0.D0
  H=1.D-5
  DO AXIS=1,3
    DO FACE=-1,2
      X=(/7.371D0,8.419D0,7.713D0/)
      X(AXIS)=REAL(8*FACE,KIND=8)
      XP=X
      XM=X
      XP(AXIS)=XP(AXIS)+H
      XM(AXIS)=XM(AXIS)-H
      CALL PAW_SKALA_GRID_INTERPOLATE_GRADIENT(N,N,N,CELL,FIELD,X,G)
      CALL PAW_SKALA_GRID_INTERPOLATE_GRADIENT(N,N,N,CELL,FIELD,XM,GL)
      CALL PAW_SKALA_GRID_INTERPOLATE_GRADIENT(N,N,N,CELL,FIELD,XP,GR)
      CALL PAW_SKALA_GRID_INTERPOLATE(N,N,N,CELL,FIELD,XP,VP)
      CALL PAW_SKALA_GRID_INTERPOLATE(N,N,N,CELL,FIELD,XM,VM)
      ERROR_GRAD=MAX(ERROR_GRAD,MAXVAL(ABS(G-0.5D0*(GL+GR))))
      ERROR_FD=MAX(ERROR_FD,ABS(G(AXIS)-(VP-VM)/(2.D0*H)))
      SECOND_LEFT=(G-GL)/H
      SECOND_RIGHT=(GR-G)/H
      ERROR_HESS=MAX(ERROR_HESS,MAXVAL(ABS(SECOND_LEFT-SECOND_RIGHT)))
      CALL PAW_SKALA_GRID_INTERPOLATE_GRADIENT(N,N,N,CELL,FIELD,X+CELL(:,AXIS),PERIODIC)
      ERROR_VALUE=MAX(ERROR_VALUE,MAXVAL(ABS(PERIODIC-G)))
    END DO
  END DO
  WRITE(*,'(A,4ES16.7)') 'BOUNDARY GRADIENT/HESSIAN/FD/PERIODIC ERROR ', &
 &                       ERROR_GRAD,ERROR_HESS,ERROR_FD,ERROR_VALUE
  IF(MAX(ERROR_GRAD,ERROR_FD).GT.2.D-9) STOP 2
  IF(ERROR_HESS.GT.2.D-4.OR.ERROR_VALUE.GT.2.D-12) STOP 3
END PROGRAM SKALA_INTERPOLATION_TEST
