! SPDX-License-Identifier: GPL-3.0-or-later
PROGRAM LEBEDEV_EXACTNESS
  USE PAW_LEBEDEV_MODULE
  IMPLICIT NONE
  INTEGER :: L,NP,LEXACT,I,J,A,B,C,K,D,EXPONENT(3),ORDER
  INTEGER,PARAMETER :: RULES(3)=[53,59,65],SIZES(3)=[974,1202,1454]
  REAL(8),ALLOCATABLE :: X(:,:),W(:),POWERS(:,:,:),TERM(:)
  REAL(8) :: ERROR,EVENERROR,ODDERROR,EXPECTED,MOMENT
  CHARACTER(32) :: ARG
  CALL MPE__INIT
  IF(COMMAND_ARGUMENT_COUNT().GT.0) THEN
    CALL GET_COMMAND_ARGUMENT(1,ARG)
    READ(ARG,*) L
    CALL PAW_LEBEDEV_SIZE(L,NP)
    CALL MPE__EXIT
    STOP 0
  END IF
  CALL PAW_LEBEDEV_TEST(ERROR)
  DO I=1,SIZE(RULES)
    L=RULES(I)
    CALL PAW_LEBEDEV_SIZE(L,NP,LEXACT)
    IF(NP.NE.SIZES(I).OR.LEXACT.NE.L) STOP 1
    ALLOCATE(X(3,NP),W(NP),POWERS(0:L+1,3,NP),TERM(NP))
    CALL PAW_LEBEDEV_GET(L,NP,X,W)
    IF(ANY(W.LE.0.D0)) STOP 2
    POWERS(0,:,:)=1.D0
    DO J=1,L+1
      POWERS(J,:,:)=POWERS(J-1,:,:)*X
    END DO
    EVENERROR=0.D0
    ODDERROR=0.D0
    DO A=0,L/2
      DO B=0,L/2-A
        DO C=0,L/2-A-B
          ! Exact normalized spherical moment from double-factorial ratios.
          EXPECTED=1.D0
          K=0
          EXPONENT=[A,B,C]
          DO D=1,3
            DO J=1,EXPONENT(D)
              K=K+1
              EXPECTED=EXPECTED*REAL(2*J-1,8)/REAL(2*K+1,8)
            END DO
          END DO
          TERM=W*POWERS(2*A,1,:)*POWERS(2*B,2,:)*POWERS(2*C,3,:)
          MOMENT=SUM(TERM)
          EVENERROR=MAX(EVENERROR,ABS(MOMENT/EXPECTED-1.D0))
          ORDER=2*(A+B+C)
          IF(ORDER+1.LE.L) ODDERROR=MAX(ODDERROR,ABS(SUM(TERM*X(1,:)))/EXPECTED)
          IF(ORDER+2.LE.L) ODDERROR=MAX(ODDERROR,ABS(SUM(TERM*X(1,:)*X(2,:)))/EXPECTED)
          IF(ORDER+3.LE.L) ODDERROR=MAX(ODDERROR,ABS(SUM(TERM*X(1,:)*X(2,:)*X(3,:)))/EXPECTED)
        END DO
      END DO
    END DO
    WRITE(*,'(A,I3,A,I5,A,2ES16.7)') 'LEBEDEV ORDER ',L,' POINTS ',NP &
     &     ,' EVEN/ODD MOMENT ERRORS ',EVENERROR,ODDERROR
    ERROR=MAX(ERROR,EVENERROR,ODDERROR)
    DEALLOCATE(X,W,POWERS,TERM)
  END DO
  CALL PAW_LEBEDEV_SIZE(54,NP,LEXACT)
  IF(NP.NE.1202.OR.LEXACT.NE.59) STOP 3
  DO L=60,65
    CALL PAW_LEBEDEV_SIZE(L,NP,LEXACT)
    IF(NP.NE.1454.OR.LEXACT.NE.65) STOP 4
  END DO
  IF(ERROR.GT.5.D-13) STOP 5
  CALL MPE__EXIT
END PROGRAM
