! SPDX-License-Identifier: GPL-3.0-or-later
PROGRAM PARTITION_CACHE
  USE PAW_SKALA_PARTITION_MODULE
  IMPLICIT NONE
  TYPE(PAW_SKALA_PARTITION_CACHE) :: CACHE
  TYPE(PAW_SKALA_PARTITION_CACHE),ALLOCATABLE :: BLOCK(:)
  REAL(8) :: ATOMS(2,3),CELL(3,3),X(2,3),BASEATOMS(2,3),BASECELL(3,3),BASEX(2,3)
  REAL(8) :: DE(3,2),ME(3,3),WD,DD(3,1),MD(3,3)
  INTEGER(8) :: BYTES
  INTEGER :: I
  LOGICAL :: HIT
  CHARACTER(16) :: ARG
  CALL MPE__INIT
  CALL GET_COMMAND_ARGUMENT(1,ARG)
  IF(TRIM(ARG).EQ.'limit') THEN
    BYTES=PAW_SKALA_PARTITION_CACHE_LIMIT()
    PRINT '(I0)',BYTES
    CALL MPE__EXIT
    STOP
  END IF
  CELL=RESHAPE((/4.D0,0.1D0,0.2D0,0.7D0,5.D0,0.3D0,-0.2D0,0.4D0,6.D0/),(/3,3/))
  ATOMS(1,:)=(/0.2D0,0.3D0,-0.1D0/)
  ATOMS(2,:)=(/1.8D0,2.2D0,1.3D0/)
  X(1,:)=(/1.1D0,1.3D0,1.7D0/)
  X(2,:)=(/2.2D0,-0.5D0,0.8D0/)
  BASEATOMS=ATOMS
  BASECELL=CELL
  BASEX=X
  CALL VERIFY(ATOMS,CELL,X,1,1,.TRUE.,.FALSE.)
  CALL VERIFY(ATOMS,CELL,X,1,1,.TRUE.,.TRUE.)
  BYTES=PAW_SKALA_PARTITION_CACHE_BYTES(CACHE)
  CALL PAW_SKALA_PARTITION_CACHE_PREPARE(CACHE,ATOMS,CELL,1,1,X,.TRUE.,BYTES)
  CALL PAW_SKALA_PARTITION_CACHE_GET(CACHE,1,DE,ME,WD,DD,MD,HIT)
  IF(.NOT.HIT) STOP 1
  CALL PAW_SKALA_PARTITION_CACHE_PREPARE(CACHE,ATOMS,CELL,1,1,X,.TRUE.,BYTES-1_8)
  IF(PAW_SKALA_PARTITION_CACHE_BYTES(CACHE).NE.0_8) STOP 2
  CALL PAW_SKALA_PARTITION_CACHE_PUT(CACHE,1,DE,ME,WD,DD,MD)
  CALL PAW_SKALA_PARTITION_CACHE_GET(CACHE,1,DE,ME,WD,DD,MD,HIT)
  IF(HIT) STOP 3
  CALL VERIFY(ATOMS,CELL,X,1,1,.TRUE.,.FALSE.)
  CALL VERIFY(ATOMS,CELL,X,1,1,.FALSE.,.FALSE.)
  CALL VERIFY(ATOMS,CELL,X,1,1,.FALSE.,.TRUE.)
  CALL VERIFY(ATOMS,CELL,X,1,1,.TRUE.,.FALSE.)
  DO I=1,3
    ATOMS(2,I)=ATOMS(2,I)+0.01D0
    CALL VERIFY(ATOMS,CELL,X,1,1,.TRUE.,.FALSE.)
    CELL(I,1)=CELL(I,1)+0.02D0
    CALL VERIFY(ATOMS,CELL,X,1,1,.TRUE.,.FALSE.)
    X(2,I)=X(2,I)+0.03D0
    CALL VERIFY(ATOMS,CELL,X,1,1,.TRUE.,.FALSE.)
  END DO
  CALL VERIFY(ATOMS,CELL,X,2,1,.TRUE.,.FALSE.)
  CALL VERIFY(ATOMS,CELL,X,2,2,.TRUE.,.FALSE.)
  CALL VERIFY(ATOMS,CELL,X(1:1,:),2,2,.TRUE.,.FALSE.)
  CALL VERIFY(ATOMS(1:1,:),CELL,X,1,1,.TRUE.,.FALSE.)
  CALL VERIFY(BASEATOMS,BASECELL,BASEX,1,1,.TRUE.,.FALSE.)
  CALL PAW_SKALA_PARTITION_CACHE_PREPARE(CACHE,BASEATOMS,BASECELL,1,1,BASEX,.TRUE.,0_8)
  IF(PAW_SKALA_PARTITION_CACHE_BYTES(CACHE).NE.0_8) STOP 4
  CALL PAW_SKALA_PARTITION_CACHE_GET(CACHE,1,DE,ME,WD,DD,MD,HIT)
  IF(HIT) STOP 5
  ALLOCATE(BLOCK(1))
  CALL PAW_SKALA_PARTITION_CACHE_PREPARE(BLOCK(1),ATOMS,CELL,1,1,X,.FALSE.,1048576_8)
  CALL PAW_SKALA_PARTITION_CACHE_PUT(BLOCK(1),1,DE,ME,WD,DD,MD)
  DEALLOCATE(BLOCK)
  ALLOCATE(BLOCK(1))
  CALL PAW_SKALA_PARTITION_CACHE_GET(BLOCK(1),1,DE,ME,WD,DD,MD,HIT)
  IF(HIT.OR.PAW_SKALA_PARTITION_CACHE_BYTES(BLOCK(1)).NE.0_8) STOP 6
  PRINT '(A)','PARTITION CACHE: exact reuse, geometry/grid/stress invalidation and bounded fallback PASS'
  CALL MPE__EXIT
CONTAINS
  SUBROUTINE VERIFY(R,C,POINTS,IAT,SHELL,STRESS,EXPECTHIT)
    REAL(8),INTENT(IN) :: R(:,:),C(3,3),POINTS(:,:)
    INTEGER,INTENT(IN) :: IAT,SHELL
    LOGICAL,INTENT(IN) :: STRESS,EXPECTHIT
    TYPE(PAW_SKALA_PERIODIC_LAYOUT) :: ENERGY,SELF
    REAL(8) :: F(3,SIZE(R,1)),FM(3,3),DWEIGHT,DF(3,1),DM(3,3),W
    REAL(8) :: CF(3,SIZE(R,1)),CM(3,3),CW,CD(3,1),CDM(3,3)
    INTEGER :: IP
    LOGICAL :: FOUND
    CALL PAW_SKALA_PARTITION_CACHE_PREPARE(CACHE,R,C,SHELL,IAT,POINTS,STRESS,1048576_8)
    CALL PAW_SKALA_PERIODIC_INIT(ENERGY,SIZE(R,1),R,C,SHELL)
    CALL PAW_SKALA_PERIODIC_INIT(SELF,1,R(IAT:IAT,:),C,SHELL)
    DO IP=1,SIZE(POINTS,1)
      CALL PAW_SKALA_PARTITION_CACHE_GET(CACHE,IP,CF,CM,CW,CD,CDM,FOUND)
      IF(FOUND.NEQV.EXPECTHIT) STOP 7
      CALL PAW_SKALA_PERIODIC_WEIGHT(ENERGY,IAT,POINTS(IP,:),W,F,FM)
      CALL PAW_SKALA_PERIODIC_WEIGHT(SELF,1,POINTS(IP,:),DWEIGHT,DF,DM)
      IF(.NOT.FOUND) THEN
        CALL PAW_SKALA_PARTITION_CACHE_PUT(CACHE,IP,F,FM,DWEIGHT,DF,DM)
        CALL PAW_SKALA_PARTITION_CACHE_GET(CACHE,IP,CF,CM,CW,CD,CDM,FOUND)
      END IF
      IF(.NOT.FOUND.OR.ANY(CF.NE.F)) STOP 8
      IF(STRESS) THEN
        IF(ANY(CM.NE.FM).OR.CW.NE.DWEIGHT.OR.ANY(CD.NE.DF).OR.ANY(CDM.NE.DM)) STOP 9
      ELSE
        IF(ANY(CM.NE.0.D0).OR.CW.NE.0.D0.OR.ANY(CD.NE.0.D0).OR.ANY(CDM.NE.0.D0)) STOP 10
      END IF
    END DO
  END SUBROUTINE
END PROGRAM
