PROGRAM PARTITION_MEASURE
  USE PAW_SKALA_GRID_MODULE
  USE, INTRINSIC :: IEEE_ARITHMETIC, ONLY: IEEE_IS_FINITE
  IMPLICIT NONE
  TYPE(PAW_SKALA_IMAGE_LAYOUT) :: LAYOUT
  REAL(8) :: CELL(3,3),INV(3,3),ATOMS(2,3),POINT(3),F(3),W,V,C1,PI,EXACT,TOL
  REAL(8),ALLOCATABLE :: X(:,:),Q(:)
  INTEGER :: NP,NA,I,A,SHELL,NR,ANG,ORIENT,STATUS
  CHARACTER(80) :: ARG
  SHELL=1
  NR=200
  ANG=53
  ORIENT=1
  TOL=-1.D0
  DO I=1,COMMAND_ARGUMENT_COUNT()
    CALL GET_COMMAND_ARGUMENT(I,ARG)
    SELECT CASE(I)
    CASE(1)
      READ(ARG,*,IOSTAT=STATUS) SHELL
    CASE(2)
      READ(ARG,*,IOSTAT=STATUS) NR
    CASE(3)
      READ(ARG,*,IOSTAT=STATUS) ANG
    CASE(4)
      READ(ARG,*,IOSTAT=STATUS) ORIENT
    CASE(5)
      READ(ARG,*,IOSTAT=STATUS) TOL
    CASE DEFAULT
      STOP 'Usage: partition_measure.x shells radial angular orientations [tolerance]'
    END SELECT
    IF(STATUS.NE.0) STOP 2
  END DO
  IF(MIN(SHELL,NR,ANG,ORIENT).LT.1.OR.ANG.GT.53) STOP 2
  PI=4.D0*ATAN(1.D0)
  CELL=RESHAPE((/0.D0,.5D0,.5D0,.5D0,0.D0,.5D0,.5D0,.5D0,0.D0/),(/3,3/))*10.26D0
  ATOMS(1,:)=0.D0
  ATOMS(2,:)=2.565D0
  EXACT=10.26D0**3/4.D0
  CALL PAW_SKALA_INVERSE3(CELL,INV)
  CALL PAW_SKALA_LOCAL_GRID_SIZE(NR,ANG,NA,NP,ORIENT)
  ALLOCATE(X(NP,3),Q(NP))
  CALL PAW_SKALA_LOCAL_GRID(NR,1.D0,ANG,NP,X,Q,ORIENT,.TRUE.)
  V=0.D0
  C1=0.D0
  DO A=1,2
    CALL PAW_SKALA_IMAGE_LAYOUT_INIT(LAYOUT,2,ATOMS,CELL,A,SHELL)
    DO I=1,NP
      POINT=ATOMS(A,:)+X(I,:)
      CALL PAW_SKALA_IMAGE_WEIGHT(LAYOUT,POINT,W)
      F=MATMUL(INV,POINT)
      V=V+Q(I)*W
      C1=C1+Q(I)*W*COS(2.D0*PI*F(1))
    END DO
  END DO
  WRITE(*,'(A,4I6)') 'SHELLS/RADIAL/ANGULAR/ORIENTATIONS ',SHELL,NR,ANG,ORIENT
  WRITE(*,'(A,ES24.15)') 'PARTITION VOLUME ',V
  WRITE(*,'(A,ES24.15)') 'EXACT CELL VOLUME ',EXACT
  WRITE(*,'(A,ES24.15)') 'RELATIVE VOLUME ERROR ',(V-EXACT)/EXACT
  WRITE(*,'(A,ES24.15)') 'FIRST FOURIER MODE ',C1
  IF(.NOT.IEEE_IS_FINITE(V).OR..NOT.IEEE_IS_FINITE(C1)) STOP 3
  ! Successful execution is not a convergence certificate unless requested.
  IF(TOL.GE.0.D0) THEN
    IF(MAX(ABS(V-EXACT),ABS(C1))/EXACT.GT.TOL) STOP 1
  END IF
END PROGRAM PARTITION_MEASURE
