! SPDX-License-Identifier: GPL-3.0-or-later
PROGRAM PERIODIC_PARTITION
  USE PAW_SKALA_PARTITION_MODULE
  IMPLICIT NONE
  TYPE(PAW_SKALA_PERIODIC_LAYOUT) :: L,P
  REAL(8) :: CELL(3,3),ATOMS(2,3),PCELL(3,3),PATOMS(2,3)
  REAL(8) :: X(3),XP(3),LOCAL(3),W,WP,WM,F(3,2),M(3,3),ERR,H,SUMW
  REAL(8) :: EXPECTED,WINDOWERROR
  INTEGER :: A,I,J,N1,N2,N3
  H=2.D-6
  CELL=RESHAPE((/4.D0,0.1D0,0.2D0,0.7D0,5.D0,0.3D0,-0.2D0,0.4D0,6.D0/),(/3,3/))
  ATOMS(1,:)=(/0.2D0,0.3D0,-0.1D0/)
  ATOMS(2,:)=(/1.8D0,2.2D0,1.3D0/)
  X=(/1.1D0,1.3D0,1.7D0/)
  LOCAL=X-ATOMS(1,:)
  CALL PAW_SKALA_PERIODIC_INIT(L,2,ATOMS,CELL,1)
  CALL PAW_SKALA_PERIODIC_WEIGHT(L,1,X,W,F,M)
  ERR=0.D0
  DO A=1,2
    DO I=1,3
      PATOMS=ATOMS
      PATOMS(A,I)=PATOMS(A,I)+H
      CALL PAW_SKALA_PERIODIC_INIT(P,2,PATOMS,CELL,1)
      CALL PAW_SKALA_PERIODIC_WEIGHT(P,1,PATOMS(1,:)+LOCAL,WP)
      PATOMS(A,I)=PATOMS(A,I)-2.D0*H
      CALL PAW_SKALA_PERIODIC_INIT(P,2,PATOMS,CELL,1)
      CALL PAW_SKALA_PERIODIC_WEIGHT(P,1,PATOMS(1,:)+LOCAL,WM)
      EXPECTED=F(I,A)
      IF(A.EQ.1) EXPECTED=EXPECTED-SUM(F(I,:))
      ERR=MAX(ERR,ABS((WP-WM)/(2.D0*H)-EXPECTED))
    END DO
  END DO
  DO I=1,3
    XP=X
    XP(I)=XP(I)+H
    CALL PAW_SKALA_PERIODIC_WEIGHT(L,1,XP,WP)
    XP(I)=XP(I)-2.D0*H
    CALL PAW_SKALA_PERIODIC_WEIGHT(L,1,XP,WM)
    ERR=MAX(ERR,ABS((WP-WM)/(2.D0*H)+SUM(F(I,:))))
    DO J=1,3
      PCELL=CELL
      PCELL(I,:)=PCELL(I,:)+H*CELL(J,:)
      PATOMS=ATOMS
      PATOMS(:,I)=PATOMS(:,I)+H*ATOMS(:,J)
      CALL PAW_SKALA_PERIODIC_INIT(P,2,PATOMS,PCELL,1)
      CALL PAW_SKALA_PERIODIC_WEIGHT(P,1,PATOMS(1,:)+LOCAL,WP)
      PCELL(I,:)=CELL(I,:)-H*CELL(J,:)
      PATOMS(:,I)=ATOMS(:,I)-H*ATOMS(:,J)
      CALL PAW_SKALA_PERIODIC_INIT(P,2,PATOMS,PCELL,1)
      CALL PAW_SKALA_PERIODIC_WEIGHT(P,1,PATOMS(1,:)+LOCAL,WM)
      EXPECTED=M(I,J)-SUM(F(I,:))*ATOMS(1,J)
      ERR=MAX(ERR,ABS((WP-WM)/(2.D0*H)-EXPECTED))
    END DO
  END DO
  WRITE(*,'(A,ES16.7)') 'PERIODIC PARTITION FORCE/STRAIN ERROR ',ERR
  SUMW=0.D0
  DO A=1,2
    DO N3=-2,2
      DO N2=-2,2
        DO N1=-2,2
          XP=X-MATMUL(CELL,REAL((/N1,N2,N3/),KIND=8))
          CALL PAW_SKALA_PERIODIC_WEIGHT(L,A,XP,WP)
          SUMW=SUMW+WP
        END DO
      END DO
    END DO
  END DO
  WRITE(*,'(A,ES16.7)') 'PERIODIC PARTITION UNITY ERROR ',ABS(SUMW-1.D0)
  ERR=MAX(ERR,ABS(SUMW-1.D0))
  CALL PAW_SKALA_PARTITION_WINDOW_TEST(WINDOWERROR)
  WRITE(*,'(A,ES16.7)') 'COMPACT WINDOW FORCE/STRAIN ERROR ',WINDOWERROR
  ERR=MAX(ERR,WINDOWERROR)
  ! Translating an atom by a cell vector must not change its image family.
  PATOMS=ATOMS
  PATOMS(2,:)=PATOMS(2,:)+CELL(:,1)-2.D0*CELL(:,3)
  CALL PAW_SKALA_PERIODIC_INIT(P,2,PATOMS,CELL,1)
  CALL PAW_SKALA_PERIODIC_WEIGHT(P,1,X,WP)
  ERR=MAX(ERR,ABS(WP-W))
  ! Include self-image descriptors and both enumeration boundary types.
  CALL CHECK_DERIVATIVES(ATOMS,CELL,LOCAL,2,ERR)
  CALL CHECK_DERIVATIVES(ATOMS(1:1,:),CELL,MATMUL(CELL,(/0.5D0,0.2D0,0.1D0/)),1,ERR)
  PATOMS=ATOMS
  PATOMS(2,:)=ATOMS(1,:)+MATMUL(CELL,(/0.5D0,0.2D0,0.1D0/))
  CALL CHECK_DERIVATIVES(PATOMS,CELL,LOCAL,1,ERR)
  LOCAL=MATMUL(CELL,(/0.5D0,0.2D0,0.1D0/))
  CALL CHECK_DERIVATIVES(ATOMS,CELL,LOCAL,1,ERR)
  WRITE(*,'(A,ES16.7)') 'PERIODIC PARTITION MAX ERROR ',ERR
  IF(ERR.GT.2.D-8) STOP 1
CONTAINS
  SUBROUTINE CHECK_DERIVATIVES(R,C,DX,S,ERROR)
    REAL(8),INTENT(IN) :: R(:,:),C(3,3),DX(3)
    INTEGER,INTENT(IN) :: S
    REAL(8),INTENT(INOUT) :: ERROR
    TYPE(PAW_SKALA_PERIODIC_LAYOUT) :: LAYOUT,PERT
    REAL(8) :: RP(SIZE(R,1),3),CP(3,3),D(3,SIZE(R,1)),MOM(3,3),V,VP,VM,E
    INTEGER :: A,I,J,N
    N=SIZE(R,1)
    CALL PAW_SKALA_PERIODIC_INIT(LAYOUT,N,R,C,S)
    CALL PAW_SKALA_PERIODIC_WEIGHT(LAYOUT,1,R(1,:)+DX,V,D,MOM)
    DO A=1,N
      DO I=1,3
        RP=R
        RP(A,I)=R(A,I)+H
        CALL PAW_SKALA_PERIODIC_INIT(PERT,N,RP,C,S)
        CALL PAW_SKALA_PERIODIC_WEIGHT(PERT,1,RP(1,:)+DX,VP)
        RP(A,I)=R(A,I)-H
        CALL PAW_SKALA_PERIODIC_INIT(PERT,N,RP,C,S)
        CALL PAW_SKALA_PERIODIC_WEIGHT(PERT,1,RP(1,:)+DX,VM)
        E=D(I,A)
        IF(A.EQ.1) E=E-SUM(D(I,:))
        ERROR=MAX(ERROR,ABS((VP-VM)/(2.D0*H)-E))
      END DO
    END DO
    DO I=1,3
      DO J=1,3
        CP=C
        RP=R
        CP(I,:)=C(I,:)+H*C(J,:)
        RP(:,I)=R(:,I)+H*R(:,J)
        CALL PAW_SKALA_PERIODIC_INIT(PERT,N,RP,CP,S)
        CALL PAW_SKALA_PERIODIC_WEIGHT(PERT,1,RP(1,:)+DX,VP)
        CP(I,:)=C(I,:)-H*C(J,:)
        RP(:,I)=R(:,I)-H*R(:,J)
        CALL PAW_SKALA_PERIODIC_INIT(PERT,N,RP,CP,S)
        CALL PAW_SKALA_PERIODIC_WEIGHT(PERT,1,RP(1,:)+DX,VM)
        E=MOM(I,J)-SUM(D(I,:))*R(1,J)
        ERROR=MAX(ERROR,ABS((VP-VM)/(2.D0*H)-E))
      END DO
    END DO
  END SUBROUTINE
END PROGRAM
