PROGRAM SKALA_RECONSTRUCTION_TEST
  USE PAW_SKALA_PRIMITIVES_MODULE
  USE PAW_SKALA_GRID_MODULE
  IMPLICIT NONE
  TYPE(PAW_SKALA_SOURCE) :: SOURCE
  TYPE(PAW_SKALA_IMAGE_LAYOUT) :: LAYOUT,SELF,PERT
  REAL(8) :: X(3),XP(3),CENTER(3),DX(3),MOMENT(3,3),H,ERR,FD,V,CONTRACTION
  REAL(8) :: VALUE(5,2),VP(5,2),VM(5,2),BAR(5,2),REF(5,2),IMAGE(3)
  REAL(8) :: CELL(3,3),AINV(3,3),ATOMS(2,3),WE,WD,WP,WM,EXPECTED
  REAL(8) :: DC(3,54),DCSELF(3,27),PERTCELL(3,3),PERTINV(3,3),PERTCENTER(3)
  COMPLEX(8) :: DH(9,9,2),DM(9,9,2)
  REAL(8),ALLOCATABLE :: GRID(:,:),WEIGHTS(:)
  INTEGER :: I,J,K,D,N1,N2,N3,NANG,NPOINT

  H=2.D-5
  ERR=0.D0
  CALL CHECK_RADIAL_MODES()
  SOURCE%NR=401
  SOURCE%LNX=3
  SOURCE%LMNX=9
  SOURCE%NDIMD=2
  SOURCE%RCUT=4.D0
  ALLOCATE(SOURCE%R(401),SOURCE%PHI(401,3,2),SOURCE%CORE(401,2),SOURCE%LOX(3))
  ALLOCATE(SOURCE%DM(9,9,2),SOURCE%DH(9,9,2))
  SOURCE%LOX=(/0,1,2/)
  SOURCE%R=[(0.01D0*I,I=1,401)]
  SOURCE%PHI(:,1,1)=EXP(-SOURCE%R**2)
  SOURCE%PHI(:,2,1)=SOURCE%R*EXP(-0.9D0*SOURCE%R**2)
  SOURCE%PHI(:,3,1)=SOURCE%R**2*EXP(-0.8D0*SOURCE%R**2)
  SOURCE%PHI(:,:,2)=0.8D0*SOURCE%PHI(:,:,1)
  SOURCE%CORE(:,1)=0.7D0*EXP(-1.7D0*SOURCE%R**2)
  SOURCE%CORE(:,2)=0.9D0*SOURCE%R**2*EXP(-1.7D0*SOURCE%R**2)
  CALL PAW_SKALA_SOLID_BASIS_INIT(SOURCE%BASIS,2)
  DO D=1,2
    DO J=1,9
      DO I=1,9
        SOURCE%DM(I,J,D)=CMPLX(1.D0/(I+J+D),0.02D0*(I-J),KIND=8)
        DM(I,J,D)=CMPLX(SIN(REAL(I+J+D,KIND=8)),0.D0,KIND=8)
      END DO
    END DO
  END DO
  DO D=1,2
    DO I=1,5
      BAR(I,D)=COS(REAL(I+2*D,KIND=8))
    END DO
  END DO
  X=(/0.737D0,0.291D0,-0.423D0/)
  SOURCE%DH=0.D0
  CALL PAW_SKALA_SOURCE_POINT(SOURCE,X,VALUE,BAR,DX,CONTRACTION)
  DH=SOURCE%DH
  ERR=MAX(ERR,ABS(CONTRACTION-REAL(SUM(CONJG(SOURCE%DM)*DH),KIND=8)))
  DO K=1,3
    XP=X
    XP(K)=XP(K)+H
    CALL PAW_SKALA_SOURCE_POINT(SOURCE,XP,VP)
    XP(K)=XP(K)-2.D0*H
    CALL PAW_SKALA_SOURCE_POINT(SOURCE,XP,VM)
    FD=SUM(BAR*(VP-VM))/(2.D0*H)
    ERR=MAX(ERR,ABS(FD-DX(K)))
    ERR=MAX(ERR,MAXVAL(ABS((VP(1,:)-VM(1,:))/(2.D0*H)-VALUE(K+1,:))))
  END DO
  SOURCE%DM=SOURCE%DM+H*DM
  CALL PAW_SKALA_SOURCE_POINT(SOURCE,X,VP)
  SOURCE%DM=SOURCE%DM-2.D0*H*DM
  CALL PAW_SKALA_SOURCE_POINT(SOURCE,X,VM)
  SOURCE%DM=SOURCE%DM+H*DM
  FD=SUM(BAR*(VP-VM))/(2.D0*H)
  ERR=MAX(ERR,ABS(FD-REAL(SUM(CONJG(DM)*DH),KIND=8)))
  WRITE(*,'(A,ES16.7)') 'SOURCE FIELD/GEOMETRY/DM ADJOINT ERROR ',ERR

  CELL=RESHAPE((/2.8D0,0.D0,0.D0,0.4D0,3.1D0,0.D0,0.2D0,0.3D0,3.2D0/),(/3,3/))
  CALL PAW_SKALA_INVERSE3(CELL,AINV)
  CENTER=(/2.7D0,0.1D0,0.2D0/)
  CALL CHECK_SOURCE_MODES(SOURCE,X,BAR,CELL,AINV,CENTER)
  SOURCE%DH=0.D0
  CALL PAW_SKALA_SOURCE_IMAGES(SOURCE,CELL,AINV,CENTER,X,VALUE,BAR,DX,MOMENT,CONTRACTION)
  ERR=MAX(ERR,ABS(CONTRACTION-REAL(SUM(CONJG(SOURCE%DM)*SOURCE%DH),KIND=8)))
  REF=0.D0
  DO N3=-3,3
    DO N2=-3,3
      DO N1=-3,3
        IMAGE=CENTER+MATMUL(CELL,REAL((/N1,N2,N3/),KIND=8))
        CALL PAW_SKALA_SOURCE_POINT(SOURCE,X-IMAGE,VP)
        REF=REF+VP
      END DO
    END DO
  END DO
  ERR=MAX(ERR,MAXVAL(ABS(VALUE-REF)))
  CALL PAW_SKALA_SOURCE_IMAGES(SOURCE,CELL,AINV,CENTER+CELL(:,1),X,VP)
  ERR=MAX(ERR,MAXVAL(ABS(VALUE-VP)))
  DO K=1,3
    XP=CENTER
    XP(K)=XP(K)+H
    CALL PAW_SKALA_SOURCE_IMAGES(SOURCE,CELL,AINV,XP,X,VP)
    XP(K)=XP(K)-2.D0*H
    CALL PAW_SKALA_SOURCE_IMAGES(SOURCE,CELL,AINV,XP,X,VM)
    ERR=MAX(ERR,ABS(SUM(BAR*(VP-VM))/(2.D0*H)+DX(K)))
  END DO
  ! Both target point and source image positions follow the cell deformation.
  DO D=1,3
    DO K=1,3
      PERTCELL=CELL
      PERTCELL(K,:)=CELL(K,:)+H*CELL(D,:)
      CALL PAW_SKALA_INVERSE3(PERTCELL,PERTINV)
      XP=X
      XP(K)=X(K)+H*X(D)
      PERTCENTER=CENTER
      PERTCENTER(K)=CENTER(K)+H*CENTER(D)
      CALL PAW_SKALA_SOURCE_IMAGES(SOURCE,PERTCELL,PERTINV,PERTCENTER,XP,VP)
      PERTCELL(K,:)=CELL(K,:)-H*CELL(D,:)
      CALL PAW_SKALA_INVERSE3(PERTCELL,PERTINV)
      XP(K)=X(K)-H*X(D)
      PERTCENTER(K)=CENTER(K)-H*CENTER(D)
      CALL PAW_SKALA_SOURCE_IMAGES(SOURCE,PERTCELL,PERTINV,PERTCENTER,XP,VM)
      EXPECTED=DX(K)*X(D)-MOMENT(K,D)
      ERR=MAX(ERR,ABS(SUM(BAR*(VP-VM))/(2.D0*H)-EXPECTED))
    END DO
  END DO
  WRITE(*,'(A,ES16.7)') 'PERIODIC SOURCE SUM/ADJOINT ERROR ',ERR

  CELL=5.D0*CELL
  ATOMS(1,:)=0.D0
  ATOMS(2,:)=(/2.D0,0.2D0,-0.1D0/)
  CALL PAW_SKALA_IMAGE_LAYOUT_INIT(LAYOUT,2,ATOMS,CELL,1,1)
  CALL PAW_SKALA_IMAGE_LAYOUT_INIT(SELF,1,ATOMS(1:1,:),CELL,1,1)
  X=ATOMS(2,:)
  CALL PAW_SKALA_IMAGE_WEIGHT(LAYOUT,X,WE)
  CALL PAW_SKALA_IMAGE_WEIGHT(SELF,X,WD)
  ! A neighbouring nucleus is not excised from the target descriptor domain.
  IF(WE.GT.1.D-10.OR.PAW_SKALA_PARTITION_TAPER(WD).LT.0.999D0) STOP 2
  X=(/1.7D0,0.52D0,0.83D0/)
  CALL PAW_SKALA_IMAGE_WEIGHT(LAYOUT,X,WE,DC)
  CALL PAW_SKALA_IMAGE_WEIGHT(SELF,X,WD,DCSELF)
  DO J=1,LAYOUT%N
    DO K=1,3
      PERT=LAYOUT
      PERT%CENTER(J,K)=PERT%CENTER(J,K)+H
      CALL UPDATE_PAIRS(PERT)
      CALL PAW_SKALA_IMAGE_WEIGHT(PERT,X,WP)
      PERT%CENTER(J,K)=PERT%CENTER(J,K)-2.D0*H
      CALL UPDATE_PAIRS(PERT)
      CALL PAW_SKALA_IMAGE_WEIGHT(PERT,X,WM)
      ERR=MAX(ERR,ABS((WP-WM)/(2.D0*H)-DC(K,J)))
    END DO
  END DO
  DO K=1,3
    XP=X
    XP(K)=XP(K)+H
    CALL PAW_SKALA_IMAGE_WEIGHT(LAYOUT,XP,WP)
    XP(K)=XP(K)-2.D0*H
    CALL PAW_SKALA_IMAGE_WEIGHT(LAYOUT,XP,WM)
    ERR=MAX(ERR,ABS((WP-WM)/(2.D0*H)+SUM(DC(K,:))))
  END DO
  ! Cell derivative includes translations of every image, also self images.
  DO D=1,3
    DO K=1,3
      EXPECTED=SUM(DC(K,:)*LAYOUT%CENTER(:,D))
      PERT=LAYOUT
      PERT%CENTER(:,K)=LAYOUT%CENTER(:,K)+H*LAYOUT%CENTER(:,D)
      CALL UPDATE_PAIRS(PERT)
      CALL PAW_SKALA_IMAGE_WEIGHT(PERT,X,WP)
      PERT%CENTER(:,K)=LAYOUT%CENTER(:,K)-H*LAYOUT%CENTER(:,D)
      CALL UPDATE_PAIRS(PERT)
      CALL PAW_SKALA_IMAGE_WEIGHT(PERT,X,WM)
      ERR=MAX(ERR,ABS((WP-WM)/(2.D0*H)-EXPECTED))
    END DO
  END DO
  WRITE(*,'(A,ES16.7)') 'PARTITION FORCE/STRAIN ERROR ',ERR

  CALL PAW_SKALA_LOCAL_GRID_SIZE(100,11,NANG,NPOINT)
  ALLOCATE(GRID(NPOINT,3),WEIGHTS(NPOINT))
  CALL PAW_SKALA_LOCAL_GRID(100,1.D0,11,NPOINT,GRID,WEIGHTS,INFINITE=.TRUE.)
  V=SUM(WEIGHTS*EXP(-SUM(GRID**2,DIM=2)))
  ERR=MAX(ERR,ABS(V-(4.D0*ATAN(1.D0))**1.5D0))
  WRITE(*,'(A,ES16.7)') 'RECONSTRUCTION MAX ERROR ',ERR
  IF(ERR.GT.2.D-7) STOP 1
  STOP 0
CONTAINS
  SUBROUTINE CHECK_RADIAL_MODES()
    REAL(8) :: R(12),F(12),POINTS(25),T,V,DV,DDV,A,B,C,E
    INTEGER :: I
    R=[(0.03D0*I**1.4D0,I=1,12)]
    F=1.D0+R-2.D0*R**2+0.3D0*R**3-0.2D0*R**4+0.1D0*R**5
    POINTS(1:12)=R
    POINTS(13:23)=0.5D0*(R(1:11)+R(2:12))
    POINTS(24:25)=(/R(1)-0.01D0,R(12)+0.01D0/)
    E=0.D0
    DO I=1,SIZE(POINTS)
      T=POINTS(I)
      CALL PAW_SKALA_RADIAL_SAMPLE(R,F,T,V,DV,DDV)
      E=MAX(E,ABS(V-(1.D0+T-2.D0*T**2+0.3D0*T**3-0.2D0*T**4+0.1D0*T**5)))
      E=MAX(E,ABS(DV-(1.D0-4.D0*T+0.9D0*T**2-0.8D0*T**3+0.5D0*T**4)))
      E=MAX(E,ABS(DDV-(-4.D0+1.8D0*T-2.4D0*T**2+2.D0*T**3)))
      CALL PAW_SKALA_RADIAL_SAMPLE(R,F,T,A)
      E=MAX(E,ABS(A-V))
      CALL PAW_SKALA_RADIAL_SAMPLE(R,F,T,A,B)
      E=MAX(E,ABS(A-V),ABS(B-DV))
      CALL PAW_SKALA_RADIAL_SAMPLE(R,F,T,A,DDV=C)
      E=MAX(E,ABS(A-V),ABS(C-DDV))
    END DO
    WRITE(*,'(A,ES16.7)') 'RADIAL OPTIONAL DERIVATIVE ERROR ',E
    IF(E.GT.1.D-10) STOP 3
  END SUBROUTINE CHECK_RADIAL_MODES

  SUBROUTINE CHECK_SOURCE_MODES(ORIGINAL,X,BAR,CELL,AINV,CENTER)
    TYPE(PAW_SKALA_SOURCE),INTENT(IN) :: ORIGINAL
    REAL(8),INTENT(IN) :: X(3),BAR(5,2),CELL(3,3),AINV(3,3),CENTER(3)
    TYPE(PAW_SKALA_SOURCE) :: S
    REAL(8) :: REF(5,2),V(5,2),DX(3),D(3),M(3,3),CREF,C,E
    COMPLEX(8) :: DH(SIZE(ORIGINAL%DH,1),SIZE(ORIGINAL%DH,2),SIZE(ORIGINAL%DH,3))
    INTEGER :: NSPIN
    S=ORIGINAL
    E=0.D0
    DO NSPIN=1,2
      S%NDIMD=NSPIN
      S%DH=0.D0
      CALL PAW_SKALA_SOURCE_POINT(S,X,REF,BAR,DX,CREF)
      DH=S%DH
      CALL PAW_SKALA_SOURCE_POINT(S,X,V,DX=D)
      E=MAX(E,MAXVAL(ABS(V-REF)),MAXVAL(ABS(D)),MAXVAL(ABS(S%DH-DH)))
      S%DH=0.D0
      CALL PAW_SKALA_SOURCE_POINT(S,X,V,BAR,DMCONTRACTION=C)
      E=MAX(E,MAXVAL(ABS(V-REF)),ABS(C-CREF),MAXVAL(ABS(S%DH-DH)))

      S%DH=0.D0
      CALL PAW_SKALA_SOURCE_IMAGES(S,CELL,AINV,CENTER,X,REF,BAR,DX,M,CREF)
      DH=S%DH
      CALL PAW_SKALA_SOURCE_IMAGES(S,CELL,AINV,CENTER,X,V)
      E=MAX(E,MAXVAL(ABS(V-REF)),MAXVAL(ABS(S%DH-DH)))
      S%DH=0.D0
      CALL PAW_SKALA_SOURCE_IMAGES(S,CELL,AINV,CENTER,X,V,BAR,DMCONTRACTION=C)
      E=MAX(E,MAXVAL(ABS(V-REF)),ABS(C-CREF),MAXVAL(ABS(S%DH-DH)))
      S%DH=0.D0
      CALL PAW_SKALA_SOURCE_IMAGES(S,CELL,AINV,CENTER,X,V,BAR,D,DMCONTRACTION=C)
      E=MAX(E,MAXVAL(ABS(V-REF)),ABS(C-CREF),MAXVAL(ABS(S%DH-DH)),MAXVAL(ABS(D-DX)))
    END DO
    WRITE(*,'(A,ES16.7)') 'SOURCE OPTIONAL DERIVATIVE ERROR ',E
    IF(E.GT.1.D-12) STOP 4
  END SUBROUTINE CHECK_SOURCE_MODES

  SUBROUTINE UPDATE_PAIRS(L)
    TYPE(PAW_SKALA_IMAGE_LAYOUT),INTENT(INOUT) :: L
    INTEGER :: A,B
    DO B=1,L%N
      DO A=1,B-1
        L%INVPAIR(A,B)=1.D0/SQRT(SUM((L%CENTER(A,:)-L%CENTER(B,:))**2))
        L%INVPAIR(B,A)=L%INVPAIR(A,B)
      END DO
    END DO
  END SUBROUTINE UPDATE_PAIRS
END PROGRAM SKALA_RECONSTRUCTION_TEST
