PROGRAM SKALA_RECONSTRUCTION_TEST
  USE PAW_SKALA_PRIMITIVES_MODULE
  USE PAW_SKALA_GRID_MODULE
  IMPLICIT NONE
  TYPE(PAW_SKALA_SOURCE) :: SOURCE
  TYPE(PAW_SKALA_IMAGE_LAYOUT) :: LAYOUT,SELF,PERT
  REAL(8) :: X(3),XP(3),CENTER(3),DX(3),MOMENT(3,3),H,ERR,FD,V,CONTRACTION
  REAL(8) :: VALUE(5,2),VP(5,2),VM(5,2),BAR(5,2),REF(5,2),IMAGE(3)
  REAL(8) :: CELL(3,3),AINV(3,3),ATOMS(2,3),WE,WD,WP,WM,EXPECTED
  REAL(8) :: DC(3,54),DCSELF(3,27),PERTCELL(3,3),PERTINV(3,3),PERTCENTER(3)
  COMPLEX(8) :: DH(9,9,2),DM(9,9,2)
  REAL(8),ALLOCATABLE :: GRID(:,:),WEIGHTS(:)
  INTEGER :: I,J,K,D,N1,N2,N3,NANG,NPOINT
  CHARACTER(16) :: ARG

  CALL GET_COMMAND_ARGUMENT(1,ARG)
  IF(TRIM(ARG).EQ.'limit') THEN
    WRITE(*,'(I0)') PAW_SKALA_SOURCE_CACHE_LIMIT()
    STOP
  END IF

  H=2.D-5
  ERR=0.D0
  CALL CHECK_RADIAL_MODES()
  SOURCE%NR=401
  SOURCE%LNX=3
  SOURCE%LMNX=9
  SOURCE%NDIMD=2
  SOURCE%RCUT=4.D0
  ALLOCATE(SOURCE%R(401),SOURCE%PHI(401,3,2),SOURCE%CORE(401,2),SOURCE%LOX(3))
  ALLOCATE(SOURCE%DM(9,9,2),SOURCE%DH(9,9,2))
  SOURCE%LOX=(/0,1,2/)
  SOURCE%R=[(0.01D0*I,I=1,401)]
  SOURCE%PHI(:,1,1)=EXP(-SOURCE%R**2)
  SOURCE%PHI(:,2,1)=SOURCE%R*EXP(-0.9D0*SOURCE%R**2)
  SOURCE%PHI(:,3,1)=SOURCE%R**2*EXP(-0.8D0*SOURCE%R**2)
  SOURCE%PHI(:,:,2)=0.8D0*SOURCE%PHI(:,:,1)
  SOURCE%CORE(:,1)=0.7D0*EXP(-1.7D0*SOURCE%R**2)
  SOURCE%CORE(:,2)=0.9D0*SOURCE%R**2*EXP(-1.7D0*SOURCE%R**2)
  CALL PAW_SKALA_SOLID_BASIS_INIT(SOURCE%BASIS,2)
  DO D=1,2
    DO J=1,9
      DO I=1,9
        SOURCE%DM(I,J,D)=CMPLX(1.D0/(I+J+D),0.02D0*(I-J),KIND=8)
        DM(I,J,D)=CMPLX(SIN(REAL(I+J+D,KIND=8)),0.D0,KIND=8)
      END DO
    END DO
  END DO
  DO D=1,2
    DO I=1,5
      BAR(I,D)=COS(REAL(I+2*D,KIND=8))
    END DO
  END DO
  X=(/0.737D0,0.291D0,-0.423D0/)
  SOURCE%DH=0.D0
  CALL PAW_SKALA_SOURCE_POINT(SOURCE,X,VALUE,BAR,DX,CONTRACTION)
  DH=SOURCE%DH
  ERR=MAX(ERR,ABS(CONTRACTION-REAL(SUM(CONJG(SOURCE%DM)*DH),KIND=8)))
  DO K=1,3
    XP=X
    XP(K)=XP(K)+H
    CALL PAW_SKALA_SOURCE_POINT(SOURCE,XP,VP)
    XP(K)=XP(K)-2.D0*H
    CALL PAW_SKALA_SOURCE_POINT(SOURCE,XP,VM)
    FD=SUM(BAR*(VP-VM))/(2.D0*H)
    ERR=MAX(ERR,ABS(FD-DX(K)))
    ERR=MAX(ERR,MAXVAL(ABS((VP(1,:)-VM(1,:))/(2.D0*H)-VALUE(K+1,:))))
  END DO
  SOURCE%DM=SOURCE%DM+H*DM
  CALL PAW_SKALA_SOURCE_POINT(SOURCE,X,VP)
  SOURCE%DM=SOURCE%DM-2.D0*H*DM
  CALL PAW_SKALA_SOURCE_POINT(SOURCE,X,VM)
  SOURCE%DM=SOURCE%DM+H*DM
  FD=SUM(BAR*(VP-VM))/(2.D0*H)
  ERR=MAX(ERR,ABS(FD-REAL(SUM(CONJG(DM)*DH),KIND=8)))
  WRITE(*,'(A,ES16.7)') 'SOURCE FIELD/GEOMETRY/DM ADJOINT ERROR ',ERR

  CELL=RESHAPE((/2.8D0,0.D0,0.D0,0.4D0,3.1D0,0.D0,0.2D0,0.3D0,3.2D0/),(/3,3/))
  CALL PAW_SKALA_INVERSE3(CELL,AINV)
  CENTER=(/2.7D0,0.1D0,0.2D0/)
  CALL CHECK_SOURCE_MODES(SOURCE,X,BAR,CELL,AINV,CENTER)
  CALL CHECK_SOURCE_CACHE(SOURCE,X,BAR,CELL,AINV,CENTER)
  CALL CHECK_SOURCE_BACK_BATCH(SOURCE,X,BAR,CELL,AINV,CENTER)
  SOURCE%DH=0.D0
  CALL PAW_SKALA_SOURCE_IMAGES(SOURCE,CELL,AINV,CENTER,X,VALUE,BAR,DX,MOMENT,CONTRACTION)
  ERR=MAX(ERR,ABS(CONTRACTION-REAL(SUM(CONJG(SOURCE%DM)*SOURCE%DH),KIND=8)))
  REF=0.D0
  DO N3=-3,3
    DO N2=-3,3
      DO N1=-3,3
        IMAGE=CENTER+MATMUL(CELL,REAL((/N1,N2,N3/),KIND=8))
        CALL PAW_SKALA_SOURCE_POINT(SOURCE,X-IMAGE,VP)
        REF=REF+VP
      END DO
    END DO
  END DO
  ERR=MAX(ERR,MAXVAL(ABS(VALUE-REF)))
  CALL PAW_SKALA_SOURCE_IMAGES(SOURCE,CELL,AINV,CENTER+CELL(:,1),X,VP)
  ERR=MAX(ERR,MAXVAL(ABS(VALUE-VP)))
  DO K=1,3
    XP=CENTER
    XP(K)=XP(K)+H
    CALL PAW_SKALA_SOURCE_IMAGES(SOURCE,CELL,AINV,XP,X,VP)
    XP(K)=XP(K)-2.D0*H
    CALL PAW_SKALA_SOURCE_IMAGES(SOURCE,CELL,AINV,XP,X,VM)
    ERR=MAX(ERR,ABS(SUM(BAR*(VP-VM))/(2.D0*H)+DX(K)))
  END DO
  ! Both target point and source image positions follow the cell deformation.
  DO D=1,3
    DO K=1,3
      PERTCELL=CELL
      PERTCELL(K,:)=CELL(K,:)+H*CELL(D,:)
      CALL PAW_SKALA_INVERSE3(PERTCELL,PERTINV)
      XP=X
      XP(K)=X(K)+H*X(D)
      PERTCENTER=CENTER
      PERTCENTER(K)=CENTER(K)+H*CENTER(D)
      CALL PAW_SKALA_SOURCE_IMAGES(SOURCE,PERTCELL,PERTINV,PERTCENTER,XP,VP)
      PERTCELL(K,:)=CELL(K,:)-H*CELL(D,:)
      CALL PAW_SKALA_INVERSE3(PERTCELL,PERTINV)
      XP(K)=X(K)-H*X(D)
      PERTCENTER(K)=CENTER(K)-H*CENTER(D)
      CALL PAW_SKALA_SOURCE_IMAGES(SOURCE,PERTCELL,PERTINV,PERTCENTER,XP,VM)
      EXPECTED=DX(K)*X(D)-MOMENT(K,D)
      ERR=MAX(ERR,ABS(SUM(BAR*(VP-VM))/(2.D0*H)-EXPECTED))
    END DO
  END DO
  WRITE(*,'(A,ES16.7)') 'PERIODIC SOURCE SUM/ADJOINT ERROR ',ERR

  CELL=5.D0*CELL
  ATOMS(1,:)=0.D0
  ATOMS(2,:)=(/2.D0,0.2D0,-0.1D0/)
  CALL PAW_SKALA_IMAGE_LAYOUT_INIT(LAYOUT,2,ATOMS,CELL,1,1)
  CALL PAW_SKALA_IMAGE_LAYOUT_INIT(SELF,1,ATOMS(1:1,:),CELL,1,1)
  X=ATOMS(2,:)
  CALL PAW_SKALA_IMAGE_WEIGHT(LAYOUT,X,WE)
  CALL PAW_SKALA_IMAGE_WEIGHT(SELF,X,WD)
  ! A neighbouring nucleus is not excised from the target descriptor domain.
  IF(WE.GT.1.D-10.OR.PAW_SKALA_PARTITION_TAPER(WD).LT.0.999D0) STOP 2
  X=(/1.7D0,0.52D0,0.83D0/)
  CALL PAW_SKALA_IMAGE_WEIGHT(LAYOUT,X,WE,DC)
  CALL PAW_SKALA_IMAGE_WEIGHT(SELF,X,WD,DCSELF)
  DO J=1,LAYOUT%N
    DO K=1,3
      PERT=LAYOUT
      PERT%CENTER(J,K)=PERT%CENTER(J,K)+H
      CALL UPDATE_PAIRS(PERT)
      CALL PAW_SKALA_IMAGE_WEIGHT(PERT,X,WP)
      PERT%CENTER(J,K)=PERT%CENTER(J,K)-2.D0*H
      CALL UPDATE_PAIRS(PERT)
      CALL PAW_SKALA_IMAGE_WEIGHT(PERT,X,WM)
      ERR=MAX(ERR,ABS((WP-WM)/(2.D0*H)-DC(K,J)))
    END DO
  END DO
  DO K=1,3
    XP=X
    XP(K)=XP(K)+H
    CALL PAW_SKALA_IMAGE_WEIGHT(LAYOUT,XP,WP)
    XP(K)=XP(K)-2.D0*H
    CALL PAW_SKALA_IMAGE_WEIGHT(LAYOUT,XP,WM)
    ERR=MAX(ERR,ABS((WP-WM)/(2.D0*H)+SUM(DC(K,:))))
  END DO
  ! Cell derivative includes translations of every image, also self images.
  DO D=1,3
    DO K=1,3
      EXPECTED=SUM(DC(K,:)*LAYOUT%CENTER(:,D))
      PERT=LAYOUT
      PERT%CENTER(:,K)=LAYOUT%CENTER(:,K)+H*LAYOUT%CENTER(:,D)
      CALL UPDATE_PAIRS(PERT)
      CALL PAW_SKALA_IMAGE_WEIGHT(PERT,X,WP)
      PERT%CENTER(:,K)=LAYOUT%CENTER(:,K)-H*LAYOUT%CENTER(:,D)
      CALL UPDATE_PAIRS(PERT)
      CALL PAW_SKALA_IMAGE_WEIGHT(PERT,X,WM)
      ERR=MAX(ERR,ABS((WP-WM)/(2.D0*H)-EXPECTED))
    END DO
  END DO
  WRITE(*,'(A,ES16.7)') 'PARTITION FORCE/STRAIN ERROR ',ERR

  CALL PAW_SKALA_LOCAL_GRID_SIZE(100,11,NANG,NPOINT)
  ALLOCATE(GRID(NPOINT,3),WEIGHTS(NPOINT))
  CALL PAW_SKALA_LOCAL_GRID(100,1.D0,11,NPOINT,GRID,WEIGHTS,INFINITE=.TRUE.)
  V=SUM(WEIGHTS*EXP(-SUM(GRID**2,DIM=2)))
  ERR=MAX(ERR,ABS(V-(4.D0*ATAN(1.D0))**1.5D0))
  WRITE(*,'(A,ES16.7)') 'RECONSTRUCTION MAX ERROR ',ERR
  IF(ERR.GT.2.D-7) STOP 1
  STOP 0
CONTAINS
  SUBROUTINE CHECK_SOURCE_BACK_BATCH(ORIGINAL,X,BAR,CELL,AINV,CENTER)
    TYPE(PAW_SKALA_SOURCE),INTENT(IN) :: ORIGINAL
    REAL(8),INTENT(IN) :: X(3),BAR(5,2),CELL(3,3),AINV(3,3),CENTER(3)
    INTEGER,PARAMETER :: NP=257
    TYPE(PAW_SKALA_SOURCE) :: S
    TYPE(PAW_SKALA_SOURCE_CACHE) :: CACHE
    REAL(8) :: POINTS(NP,3),B(5,2,NP),D(3),M(3,3),C,DR(3),MR(3,3),CR,V(5,2),E
    REAL(8) :: DX(3),MOM(3,3),CON
    COMPLEX(8) :: INITIAL(9,9,2),EXPECTED(9,9,2)
    INTEGER :: IP,I,J,DIM,MODE,CASE,COVERED,TOTAL,STATUS
    INTEGER(8) :: LIMIT
    LOGICAL :: GEOMETRY,STRESS,REQUIRE
    CHARACTER(16) :: TEXT
    CALL GET_ENVIRONMENT_VARIABLE('CPPAW_SKALA_TEST_REQUIRE_SOURCE_ACC',TEXT,STATUS=STATUS)
    REQUIRE=STATUS.EQ.0.AND.TRIM(TEXT).EQ.'1'
    DO IP=1,NP
      POINTS(IP,:)=X+REAL(IP-1,KIND=8)/NP*CELL(:,1)
      B(:,:,IP)=BAR*COS(REAL(IP,KIND=8)/NP)
    END DO
    DO DIM=1,2
      DO J=1,9
        DO I=1,9
          INITIAL(I,J,DIM)=CMPLX(0.001D0*(I+2*J+DIM),0.002D0*(I-J),KIND=8)
        END DO
      END DO
    END DO
    E=0.D0
    TOTAL=0
    DO DIM=1,2
      DO MODE=1,3
        GEOMETRY=MODE.GE.2
        STRESS=MODE.EQ.3
        S=ORIGINAL
        S%NDIMD=DIM
        S%DM=S%DM+0.17D0*INITIAL
        S%DH=INITIAL
        DR=0.D0
        MR=0.D0
        CR=0.D0
        DO IP=1,NP
          CALL SOURCE_BACK_TEST_ROW(S,CELL,AINV,CENTER,POINTS(IP,:),B(:,:,IP),GEOMETRY,STRESS,DX,MOM,CON)
          DR=DR+DX
          MR=MR+MOM
          CR=CR+CON
        END DO
        EXPECTED=S%DH
        DO CASE=1,3
          LIMIT=64_8*1048576_8
          IF(CASE.EQ.2) THEN
            CALL PAW_SKALA_SOURCE_CACHE_PREPARE(CACHE,S,CELL,AINV,CENTER,POINTS(1:1,:),GEOMETRY,LIMIT)
            LIMIT=PAW_SKALA_SOURCE_CACHE_BYTES(CACHE)+INT(NP-1,8)*28_8
          ELSE IF(CASE.EQ.3) THEN
            LIMIT=0_8
          END IF
          CALL PAW_SKALA_SOURCE_CACHE_PREPARE(CACHE,S,CELL,AINV,CENTER,POINTS,GEOMETRY,LIMIT)
          S%DH=INITIAL
          CALL PAW_SKALA_SOURCE_BACK_BATCH(CACHE,S,B,GEOMETRY,STRESS,D,M,C,COVERED)
          IF(REQUIRE.AND.CASE.EQ.1.AND.COVERED.NE.NP) STOP 21
          IF(REQUIRE.AND.CASE.EQ.2.AND.COVERED.NE.1) STOP 22
          IF(CASE.EQ.3.AND.COVERED.NE.0) STOP 23
          TOTAL=TOTAL+COVERED
          DO IP=COVERED+1,NP
            CALL SOURCE_BACK_TEST_ROW(S,CELL,AINV,CENTER,POINTS(IP,:),B(:,:,IP),GEOMETRY,STRESS,DX,MOM,CON)
            D=D+DX
            M=M+MOM
            C=C+CON
          END DO
          E=MAX(E,MAXVAL(ABS(S%DH-EXPECTED)),MAXVAL(ABS(D-DR)),MAXVAL(ABS(M-MR)),ABS(C-CR))
        END DO
      END DO
    END DO
    WRITE(*,'(A,ES16.7)') 'SOURCE GPU BATCH ERROR ',E
    WRITE(*,'(A,I0)') 'SOURCE GPU BATCH ROWS ',TOTAL
    IF(E.GT.1.D-10) STOP 24
  END SUBROUTINE CHECK_SOURCE_BACK_BATCH

  SUBROUTINE SOURCE_BACK_TEST_ROW(S,CELL,AINV,CENTER,POINT,BAR,GEOMETRY,STRESS,DX,MOM,CON)
    TYPE(PAW_SKALA_SOURCE),INTENT(INOUT) :: S
    REAL(8),INTENT(IN) :: CELL(3,3),AINV(3,3),CENTER(3),POINT(3),BAR(5,2)
    LOGICAL,INTENT(IN) :: GEOMETRY,STRESS
    REAL(8),INTENT(OUT) :: DX(3),MOM(3,3),CON
    REAL(8) :: V(5,2)
    DX=0.D0
    MOM=0.D0
    IF(STRESS) THEN
      CALL PAW_SKALA_SOURCE_IMAGES(S,CELL,AINV,CENTER,POINT,V,BAR,DX,MOM,CON)
    ELSE IF(GEOMETRY) THEN
      CALL PAW_SKALA_SOURCE_IMAGES(S,CELL,AINV,CENTER,POINT,V,BAR,DX,DMCONTRACTION=CON)
    ELSE
      CALL PAW_SKALA_SOURCE_IMAGES(S,CELL,AINV,CENTER,POINT,V,BAR,DMCONTRACTION=CON)
    END IF
  END SUBROUTINE SOURCE_BACK_TEST_ROW

  SUBROUTINE CHECK_SOURCE_CACHE(ORIGINAL,X,BAR,CELL,AINV,CENTER)
    TYPE(PAW_SKALA_SOURCE),INTENT(IN) :: ORIGINAL
    REAL(8),INTENT(IN) :: X(3),BAR(5,2),CELL(3,3),AINV(3,3),CENTER(3)
    TYPE(PAW_SKALA_SOURCE) :: S
    TYPE(PAW_SKALA_SOURCE_CACHE) :: CACHE
    REAL(8) :: POINTS(3,3),C(3,3),INV(3,3),CTR(3),B(5,2),E
    REAL(8) :: V(5,2),REF(5,2),D(3),DR(3),M(3,3),MR(3,3),CON,CR
    COMPLEX(8) :: DH(SIZE(ORIGINAL%DH,1),SIZE(ORIGINAL%DH,2),SIZE(ORIGINAL%DH,3))
    INTEGER :: CASE,IP,NSPIN,MODE
    INTEGER(8) :: BYTES
    LOGICAL :: REUSED,HIT,GEOMETRY
    E=0.D0
    DO NSPIN=1,2
      DO MODE=1,2
        S=ORIGINAL
        S%NDIMD=NSPIN
        C=CELL
        INV=AINV
        CTR=CENTER
        POINTS(1,:)=X
        POINTS(2,:)=CENTER
        POINTS(3,:)=X+CELL(:,1)
        B=BAR
        GEOMETRY=MODE.EQ.2
        CALL PAW_SKALA_SOURCE_CACHE_PREPARE(CACHE,S,C,INV,CTR,POINTS,GEOMETRY,0_8)
        DO CASE=1,12
          SELECT CASE(CASE)
          CASE(2)
            CTR(1)=CTR(1)+0.01D0
          CASE(3)
            C(1,2)=C(1,2)+0.01D0
            CALL PAW_SKALA_INVERSE3(C,INV)
          CASE(4)
            POINTS(3,2)=POINTS(3,2)+0.01D0
          CASE(5)
            S%RCUT=0.9D0*S%RCUT
          CASE(6)
            S%PHI(:,:,1)=0.9D0*S%PHI(:,:,1)
          CASE(7)
            S%CORE=0.8D0*S%CORE
          CASE(8)
            S%R=1.01D0*S%R
          CASE(9)
            S%LOX(1:2)=(/1,0/)
          CASE(10)
            S%BASIS%COEFF=0.99D0*S%BASIS%COEFF
          CASE(11)
            S%BASIS%POWER(:,2)=(/0,1,0/)
          CASE(12)
            S%RCUT=1.D-5
          END SELECT
          CALL PAW_SKALA_SOURCE_CACHE_PREPARE(CACHE,S,C,INV,CTR,POINTS,GEOMETRY,1048576_8,REUSED)
          IF(REUSED) STOP 5
          BYTES=PAW_SKALA_SOURCE_CACHE_BYTES(CACHE)
          IF(BYTES.LE.0_8.OR.BYTES.GT.1048576_8) STOP 6
          S%DM=0.91D0*S%DM
          B=0.93D0*B
          CALL PAW_SKALA_SOURCE_CACHE_PREPARE(CACHE,S,C,INV,CTR,POINTS,GEOMETRY,BYTES,REUSED)
          IF(.NOT.REUSED) STOP 7
          DO IP=1,3
            S%DH=0.D0
            IF(GEOMETRY) THEN
              CALL PAW_SKALA_SOURCE_IMAGES(S,C,INV,CTR,POINTS(IP,:),REF,B,DR,MR,CR)
            ELSE
              CALL PAW_SKALA_SOURCE_IMAGES(S,C,INV,CTR,POINTS(IP,:),REF,B,DMCONTRACTION=CR)
            END IF
            DH=S%DH
            S%DH=0.D0
            IF(GEOMETRY) THEN
              CALL PAW_SKALA_SOURCE_IMAGES(S,C,INV,CTR,POINTS(IP,:),V,B,D,M,CON,CACHE,IP,HIT)
              E=MAX(E,MAXVAL(ABS(D-DR)),MAXVAL(ABS(M-MR)))
            ELSE
              CALL PAW_SKALA_SOURCE_IMAGES(S,C,INV,CTR,POINTS(IP,:),V,B &
 &                 ,DMCONTRACTION=CON,CACHE=CACHE,IP=IP,HIT=HIT)
            END IF
            IF(.NOT.HIT) STOP 8
            E=MAX(E,MAXVAL(ABS(V-REF)),MAXVAL(ABS(S%DH-DH)),ABS(CON-CR))
            CALL PAW_SKALA_SOURCE_IMAGES(S,C,INV,CTR,POINTS(IP,:),V,CACHE=CACHE,IP=IP,HIT=HIT)
            IF(.NOT.HIT) STOP 9
            E=MAX(E,MAXVAL(ABS(V-REF)),MAXVAL(ABS(S%DH-DH)))
          END DO
        END DO
        ! A coordinate not in the prepared row and missing Hessians use the direct path.
        CALL PAW_SKALA_SOURCE_IMAGES(S,C,INV,CTR,POINTS(1,:)+1.D-3,V,CACHE=CACHE,IP=1,HIT=HIT)
        IF(HIT) STOP 10
        CALL PAW_SKALA_SOURCE_IMAGES(S,C,INV,CTR,POINTS(1,:),V,B,D,CACHE=CACHE,IP=1,HIT=HIT)
        IF(HIT.NEQV.GEOMETRY) STOP 11
        CALL PAW_SKALA_SOURCE_CACHE_PREPARE(CACHE,S,C,INV,CTR,POINTS,GEOMETRY,BYTES-1_8)
        IF(PAW_SKALA_SOURCE_CACHE_BYTES(CACHE).NE.0_8) STOP 12
        CALL PAW_SKALA_SOURCE_IMAGES(S,C,INV,CTR,POINTS(1,:),V,CACHE=CACHE,IP=1,HIT=HIT)
        IF(HIT) STOP 13
        CALL PAW_SKALA_SOURCE_IMAGES(S,C,INV,CTR,POINTS(1,:),REF)
        E=MAX(E,MAXVAL(ABS(V-REF)))
        CALL PAW_SKALA_SOURCE_CACHE_PREPARE(CACHE,S,C,INV,CTR,POINTS(1:2,:),GEOMETRY,1048576_8,REUSED)
        IF(REUSED) STOP 14
        CALL PAW_SKALA_SOURCE_CACHE_PREPARE(CACHE,S,C,INV,CTR,POINTS(1:2,:),.NOT.GEOMETRY,1048576_8,REUSED)
        IF(REUSED) STOP 15
        S=ORIGINAL
        S%NDIMD=NSPIN
        CALL PAW_SKALA_SOURCE_CACHE_PREPARE(CACHE,S,C,INV,CTR,POINTS(1:1,:),GEOMETRY,1048576_8)
        ! Extra key rows need three reals and one offset each, but no images.
        BYTES=PAW_SKALA_SOURCE_CACHE_BYTES(CACHE)+2_8*(3*(STORAGE_SIZE(0.D0)/8)+STORAGE_SIZE(0)/8)
        CALL PAW_SKALA_SOURCE_CACHE_PREPARE(CACHE,S,C,INV,CTR,POINTS,GEOMETRY,BYTES)
        IF(PAW_SKALA_SOURCE_CACHE_BYTES(CACHE).GT.BYTES) STOP 17
        DO IP=1,3
          S%DH=0.D0
          CALL PAW_SKALA_SOURCE_IMAGES(S,C,INV,CTR,POINTS(IP,:),REF,B,DMCONTRACTION=CR)
          DH=S%DH
          S%DH=0.D0
          CALL PAW_SKALA_SOURCE_IMAGES(S,C,INV,CTR,POINTS(IP,:),V,B &
 &             ,DMCONTRACTION=CON,CACHE=CACHE,IP=IP,HIT=HIT)
          IF(HIT.NEQV.(IP.EQ.1)) STOP 18
          E=MAX(E,MAXVAL(ABS(V-REF)),MAXVAL(ABS(S%DH-DH)),ABS(CON-CR))
        END DO
      END DO
    END DO
    WRITE(*,'(A,ES16.7)') 'SOURCE CACHE FIELD/DM/FORCE/STRAIN REUSE ERROR ',E
    IF(E.GT.1.D-12) STOP 16
  END SUBROUTINE CHECK_SOURCE_CACHE

  SUBROUTINE CHECK_RADIAL_MODES()
    REAL(8) :: R(12),F(12),POINTS(25),T,V,DV,DDV,A,B,C,E
    INTEGER :: I
    R=[(0.03D0*I**1.4D0,I=1,12)]
    F=1.D0+R-2.D0*R**2+0.3D0*R**3-0.2D0*R**4+0.1D0*R**5
    POINTS(1:12)=R
    POINTS(13:23)=0.5D0*(R(1:11)+R(2:12))
    POINTS(24:25)=(/R(1)-0.01D0,R(12)+0.01D0/)
    E=0.D0
    DO I=1,SIZE(POINTS)
      T=POINTS(I)
      CALL PAW_SKALA_RADIAL_SAMPLE(R,F,T,V,DV,DDV)
      E=MAX(E,ABS(V-(1.D0+T-2.D0*T**2+0.3D0*T**3-0.2D0*T**4+0.1D0*T**5)))
      E=MAX(E,ABS(DV-(1.D0-4.D0*T+0.9D0*T**2-0.8D0*T**3+0.5D0*T**4)))
      E=MAX(E,ABS(DDV-(-4.D0+1.8D0*T-2.4D0*T**2+2.D0*T**3)))
      CALL PAW_SKALA_RADIAL_SAMPLE(R,F,T,A)
      E=MAX(E,ABS(A-V))
      CALL PAW_SKALA_RADIAL_SAMPLE(R,F,T,A,B)
      E=MAX(E,ABS(A-V),ABS(B-DV))
      CALL PAW_SKALA_RADIAL_SAMPLE(R,F,T,A,DDV=C)
      E=MAX(E,ABS(A-V),ABS(C-DDV))
    END DO
    WRITE(*,'(A,ES16.7)') 'RADIAL OPTIONAL DERIVATIVE ERROR ',E
    IF(E.GT.1.D-10) STOP 3
  END SUBROUTINE CHECK_RADIAL_MODES

  SUBROUTINE CHECK_SOURCE_MODES(ORIGINAL,X,BAR,CELL,AINV,CENTER)
    TYPE(PAW_SKALA_SOURCE),INTENT(IN) :: ORIGINAL
    REAL(8),INTENT(IN) :: X(3),BAR(5,2),CELL(3,3),AINV(3,3),CENTER(3)
    TYPE(PAW_SKALA_SOURCE) :: S
    REAL(8) :: REF(5,2),V(5,2),DX(3),D(3),M(3,3),CREF,C,E
    COMPLEX(8) :: DH(SIZE(ORIGINAL%DH,1),SIZE(ORIGINAL%DH,2),SIZE(ORIGINAL%DH,3))
    INTEGER :: NSPIN
    S=ORIGINAL
    E=0.D0
    DO NSPIN=1,2
      S%NDIMD=NSPIN
      S%DH=0.D0
      CALL PAW_SKALA_SOURCE_POINT(S,X,REF,BAR,DX,CREF)
      DH=S%DH
      CALL PAW_SKALA_SOURCE_POINT(S,X,V,DX=D)
      E=MAX(E,MAXVAL(ABS(V-REF)),MAXVAL(ABS(D)),MAXVAL(ABS(S%DH-DH)))
      S%DH=0.D0
      CALL PAW_SKALA_SOURCE_POINT(S,X,V,BAR,DMCONTRACTION=C)
      E=MAX(E,MAXVAL(ABS(V-REF)),ABS(C-CREF),MAXVAL(ABS(S%DH-DH)))

      S%DH=0.D0
      CALL PAW_SKALA_SOURCE_IMAGES(S,CELL,AINV,CENTER,X,REF,BAR,DX,M,CREF)
      DH=S%DH
      CALL PAW_SKALA_SOURCE_IMAGES(S,CELL,AINV,CENTER,X,V)
      E=MAX(E,MAXVAL(ABS(V-REF)),MAXVAL(ABS(S%DH-DH)))
      S%DH=0.D0
      CALL PAW_SKALA_SOURCE_IMAGES(S,CELL,AINV,CENTER,X,V,BAR,DMCONTRACTION=C)
      E=MAX(E,MAXVAL(ABS(V-REF)),ABS(C-CREF),MAXVAL(ABS(S%DH-DH)))
      S%DH=0.D0
      CALL PAW_SKALA_SOURCE_IMAGES(S,CELL,AINV,CENTER,X,V,BAR,D,DMCONTRACTION=C)
      E=MAX(E,MAXVAL(ABS(V-REF)),ABS(C-CREF),MAXVAL(ABS(S%DH-DH)),MAXVAL(ABS(D-DX)))
    END DO
    WRITE(*,'(A,ES16.7)') 'SOURCE OPTIONAL DERIVATIVE ERROR ',E
    IF(E.GT.1.D-12) STOP 4
  END SUBROUTINE CHECK_SOURCE_MODES

  SUBROUTINE UPDATE_PAIRS(L)
    TYPE(PAW_SKALA_IMAGE_LAYOUT),INTENT(INOUT) :: L
    INTEGER :: A,B
    DO B=1,L%N
      DO A=1,B-1
        L%INVPAIR(A,B)=1.D0/SQRT(SUM((L%CENTER(A,:)-L%CENTER(B,:))**2))
        L%INVPAIR(B,A)=L%INVPAIR(A,B)
      END DO
    END DO
  END SUBROUTINE UPDATE_PAIRS
END PROGRAM SKALA_RECONSTRUCTION_TEST
