! SPDX-License-Identifier: GPL-3.0-or-later
PROGRAM SOURCE_RESIDENCY_TEST
  USE PAW_SKALA_PRIMITIVES_MODULE
  USE PAW_SKALA_GRID_MODULE, ONLY: PAW_SKALA_INVERSE3
#IF DEFINED(CPPVAR_OPENACC)
  USE OPENACC, ONLY: ACC_GET_NUM_DEVICES,ACC_GET_DEVICE_NUM,ACC_SET_DEVICE_NUM,ACC_DEVICE_NVIDIA
#ENDIF
  IMPLICIT NONE
  INTEGER,PARAMETER :: NP=6000
  TYPE(PAW_SKALA_SOURCE) :: S
  TYPE CACHE_BLOCK
    TYPE(PAW_SKALA_SOURCE_CACHE),ALLOCATABLE :: SOURCE(:)
  END TYPE CACHE_BLOCK
  TYPE(PAW_SKALA_SOURCE_CACHE),ALLOCATABLE :: CACHES(:)
  TYPE(CACHE_BLOCK),ALLOCATABLE :: BLOCKS(:)
  TYPE(PAW_SKALA_SOURCE_CACHE) :: EMPTY
  REAL(8) :: POINTS(NP,3),MOVED(NP,3),CELL(3,3),AINV(3,3),CENTER(3),ERROR
  INTEGER(8) :: PAYLOAD,LIMIT
  INTEGER :: I,DEVICE
  LOGICAL :: ENABLED,HOST_REUSED
  CHARACTER(16) :: ARG
  CALL GET_COMMAND_ARGUMENT(1,ARG)
  LIMIT=PAW_SKALA_SOURCE_RESIDENT_LIMIT()
  IF(TRIM(ARG).EQ.'limit') THEN
    WRITE(*,'(I0)') LIMIT
    STOP 0
  END IF
  CALL PAW_SKALA_SOURCE_RESIDENT_CLEAR()
  IF(PAW_SKALA_SOURCE_RESIDENT_BYTES().NE.0_8) STOP 1
  IF(.NOT.PAW_SKALA_SOURCE_FORWARD_ACTIVE()) THEN
    IF(TRIM(ARG).EQ.'gpu') STOP 10
    WRITE(*,'(A)') 'SOURCE RESIDENCY INACTIVE CPU/FALLBACK CHECK PASSED'
    STOP 0
  END IF
  ENABLED=LIMIT.GT.0_8
  IF(ENABLED.AND.LIMIT.NE.1048576_8) STOP 2
  S%NR=21
  S%LNX=1
  S%LMNX=1
  S%NDIMD=2
  S%RCUT=1.D0
  ALLOCATE(S%R(21),S%PHI(21,1,2),S%CORE(21,2),S%LOX(1),S%DM(1,1,2),S%DH(1,1,2))
  S%R=[(0.05D0*I,I=1,21)]
  S%PHI(:,1,1)=EXP(-S%R**2)
  S%PHI(:,1,2)=0.8D0*S%PHI(:,1,1)
  S%CORE(:,1)=0.03D0*EXP(-2.D0*S%R**2)
  S%CORE(:,2)=0.5D0*S%CORE(:,1)
  S%LOX=0
  S%DM=CMPLX(0.7D0,0.1D0,KIND=8)
  S%DM(:,:,2)=CMPLX(0.2D0,-0.3D0,KIND=8)
  S%DH=CMPLX(0.23D0,-0.17D0,KIND=8)
  CALL PAW_SKALA_SOLID_BASIS_INIT(S%BASIS,0)
  CELL=0.D0
  DO I=1,3
    CELL(I,I)=4.D0
  END DO
  CALL PAW_SKALA_INVERSE3(CELL,AINV)
  CENTER=0.D0
  POINTS=0.1D0
  DO I=1,NP
    POINTS(I,1)=0.1D0+0.4D0*I/NP
  END DO
  MOVED=POINTS+0.03D0
  PAYLOAD=4_8*(NP+1_8)+8_8*NP*(8_8*S%LMNX+5_8)
  ERROR=0.D0
  ALLOCATE(CACHES(2))
  CALL PREPARE(CACHES(1),POINTS)
  CALL PREPARE(CACHES(2),POINTS)
  CALL CHECK(CACHES(1),POINTS,.FALSE.)
  CALL CHECK_BYTES(PAYLOAD,'initial population')
  S%DM=1.13D0*S%DM
  CALL PAW_SKALA_SOURCE_CACHE_PREPARE(CACHES(1),S,CELL,AINV,CENTER,POINTS,.TRUE.,4194304_8,HOST_REUSED)
  IF(.NOT.HOST_REUSED) STOP 3
  CALL CHECK(CACHES(1),POINTS,.TRUE.)
  CACHES(1)=CACHES(1)
  CALL CHECK(CACHES(1),POINTS,.TRUE.)
  CALL CHECK_BYTES(PAYLOAD,'self-assignment')
  ! Two complete entries exceed the pool, but transfer-mode coverage is unchanged.
  CALL CHECK(CACHES(2),POINTS,.FALSE.)
  CALL CHECK_BYTES(PAYLOAD,'pool overflow fallback')
  CALL PREPARE(CACHES(1),MOVED)
  CALL CHECK_BYTES(0_8,'point invalidation')
  CALL CHECK(CACHES(1),MOVED,.FALSE.)
  CALL CHECK(CACHES(1),MOVED,.TRUE.)
  CALL PAW_SKALA_SOURCE_CACHE_PREPARE(CACHES(1),S,CELL,AINV,CENTER,MOVED,.TRUE.,0_8)
  CALL CHECK_BYTES(0_8,'zero host budget')
  CALL CHECK(CACHES(2),POINTS,.FALSE.)
  DEALLOCATE(CACHES)
  CALL CHECK_BYTES(0_8,'array deallocation')
  CALL LOCAL_SCOPE()
  CALL CHECK_BYTES(0_8,'scope exit')
  ALLOCATE(BLOCKS(2))
  ALLOCATE(BLOCKS(1)%SOURCE(2))
  CALL PREPARE(BLOCKS(1)%SOURCE(2),POINTS)
  CALL CHECK(BLOCKS(1)%SOURCE(2),POINTS,.FALSE.)
  DEALLOCATE(BLOCKS)
  CALL CHECK_BYTES(0_8,'nested array deallocation')

  ALLOCATE(CACHES(2))
  CALL PREPARE(CACHES(1),POINTS)
  CALL PREPARE(CACHES(2),MOVED)
  CALL CHECK(CACHES(2),MOVED,.FALSE.)
  CACHES(2)=CACHES(1)
  CALL CHECK_BYTES(0_8,'cache assignment')
  CALL CHECK(CACHES(1),POINTS,.FALSE.)
  CALL CHECK(CACHES(2),POINTS,.TRUE.)
  CALL PREPARE(CACHES(1),MOVED)
  CALL CHECK_BYTES(0_8,'copied cache invalidation')
  CALL CHECK(CACHES(2),POINTS,.FALSE.)
  CALL PAW_SKALA_SOURCE_RESIDENT_CLEAR()
  CALL CHECK_BYTES(0_8,'explicit clear')
  CALL CHECK(CACHES(2),POINTS,.FALSE.)
#IF DEFINED(CPPVAR_OPENACC)
  IF(ACC_GET_NUM_DEVICES(ACC_DEVICE_NVIDIA).GT.1) THEN
    DEVICE=ACC_GET_DEVICE_NUM(ACC_DEVICE_NVIDIA)
    CALL ACC_SET_DEVICE_NUM(MOD(DEVICE+1,ACC_GET_NUM_DEVICES(ACC_DEVICE_NVIDIA)),ACC_DEVICE_NVIDIA)
    CALL CHECK(CACHES(2),POINTS,.FALSE.)
    CALL CHECK(CACHES(2),POINTS,.TRUE.)
    CALL ACC_SET_DEVICE_NUM(DEVICE,ACC_DEVICE_NVIDIA)
    CALL CHECK(CACHES(2),POINTS,.FALSE.)
    WRITE(*,'(A)') 'SOURCE RESIDENCY DEVICE SWITCH CHECK PASSED'
  ELSE
    WRITE(*,'(A)') 'SOURCE RESIDENCY DEVICE SWITCH CHECK SKIPPED (ONE DEVICE)'
  END IF
#ENDIF
  DEALLOCATE(CACHES)
  CALL CHECK_BYTES(0_8,'copied array deallocation')
  ALLOCATE(CACHES(2))
  CALL PREPARE(CACHES(1),POINTS)
  CALL CHECK(CACHES(1),POINTS,.FALSE.)
  CACHES=EMPTY
  CALL CHECK_BYTES(0_8,'array assignment from empty cache')
  DEALLOCATE(CACHES)
  CALL CHECK_INVALIDATION()
  CALL CHECK_BYTES(0_8,'invalidation scope exit')
  WRITE(*,'(A,ES16.7)') 'SOURCE RESIDENCY FIELD ERROR ',ERROR
  WRITE(*,'(A)') 'SOURCE RESIDENCY LIFETIME AND BUDGET CHECKS PASSED'
CONTAINS
  SUBROUTINE PREPARE(CACHE,X)
    TYPE(PAW_SKALA_SOURCE_CACHE),INTENT(INOUT) :: CACHE
    REAL(8),INTENT(IN) :: X(NP,3)
    CALL PAW_SKALA_SOURCE_CACHE_PREPARE(CACHE,S,CELL,AINV,CENTER,X,.TRUE.,4194304_8)
  END SUBROUTINE PREPARE

  SUBROUTINE CHECK(CACHE,X,EXPECT_REUSE)
    TYPE(PAW_SKALA_SOURCE_CACHE),INTENT(IN) :: CACHE
    REAL(8),INTENT(IN) :: X(NP,3)
    LOGICAL,INTENT(IN) :: EXPECT_REUSE
    REAL(8),ALLOCATABLE :: VALUES(:,:,:)
    REAL(8) :: REF(5,2)
    INTEGER :: COVERED,IP,J
    INTEGER,PARAMETER :: SELECTED(3)=[1,NP/2,NP]
    LOGICAL :: REUSED
    CALL PAW_SKALA_SOURCE_FORWARD_BATCH(CACHE,S,VALUES,COVERED,REUSED)
    IF(COVERED.NE.NP.OR..NOT.ALLOCATED(VALUES)) STOP 4
    IF(REUSED.NEQV.(EXPECT_REUSE.AND.ENABLED)) STOP 5
    DO J=1,SIZE(SELECTED)
      IP=SELECTED(J)
      CALL PAW_SKALA_SOURCE_IMAGES(S,CELL,AINV,CENTER,X(IP,:),REF)
      ERROR=MAX(ERROR,MAXVAL(ABS(VALUES(:,:,IP)-REF)))
    END DO
    IF(ERROR.GT.1.D-12) STOP 6
    IF(ANY(S%DH.NE.CMPLX(0.23D0,-0.17D0,KIND=8))) STOP 7
  END SUBROUTINE CHECK

  SUBROUTINE CHECK_BYTES(EXPECTED,STAGE)
    INTEGER(8),INTENT(IN) :: EXPECTED
    CHARACTER(*),INTENT(IN) :: STAGE
    IF(PAW_SKALA_SOURCE_RESIDENT_BYTES().NE.MERGE(EXPECTED,0_8,ENABLED)) THEN
      WRITE(*,'(A)') 'SOURCE RESIDENCY FAILURE AT '//STAGE
      WRITE(*,*) 'RESIDENT BYTES',PAW_SKALA_SOURCE_RESIDENT_BYTES(),'EXPECTED',MERGE(EXPECTED,0_8,ENABLED)
      STOP 8
    END IF
    IF(PAW_SKALA_SOURCE_RESIDENT_BYTES().GT.LIMIT) STOP 9
  END SUBROUTINE CHECK_BYTES

  SUBROUTINE LOCAL_SCOPE()
    TYPE(PAW_SKALA_SOURCE_CACHE) :: LOCAL
    CALL PREPARE(LOCAL,POINTS)
    CALL CHECK(LOCAL,POINTS,.FALSE.)
    CALL CHECK_BYTES(PAYLOAD,'local scope population')
  END SUBROUTINE LOCAL_SCOPE

  SUBROUTINE CHECK_INVALIDATION()
    TYPE(PAW_SKALA_SOURCE_CACHE) :: LOCAL
    CALL PREPARE(LOCAL,POINTS)
    CALL CHECK(LOCAL,POINTS,.FALSE.)
    CELL(1,1)=4.1D0
    CALL PAW_SKALA_INVERSE3(CELL,AINV)
    CALL PREPARE(LOCAL,POINTS)
    CALL CHECK_BYTES(0_8,'cell invalidation')
    CALL CHECK(LOCAL,POINTS,.FALSE.)
    CENTER(2)=0.01D0
    CALL PREPARE(LOCAL,POINTS)
    CALL CHECK_BYTES(0_8,'center invalidation')
    CALL CHECK(LOCAL,POINTS,.FALSE.)
    S%PHI=1.01D0*S%PHI
    CALL PREPARE(LOCAL,POINTS)
    CALL CHECK_BYTES(0_8,'partial-wave invalidation')
    CALL CHECK(LOCAL,POINTS,.FALSE.)
    S%CORE=1.02D0*S%CORE
    CALL PREPARE(LOCAL,POINTS)
    CALL CHECK_BYTES(0_8,'core invalidation')
    CALL CHECK(LOCAL,POINTS,.FALSE.)
    CALL PAW_SKALA_SOURCE_CACHE_PREPARE(LOCAL,S,CELL,AINV,CENTER,POINTS,.FALSE.,4194304_8)
    CALL CHECK_BYTES(0_8,'derivative-mode invalidation')
    CALL CHECK(LOCAL,POINTS,.FALSE.)
    CALL CHECK(LOCAL,POINTS,.TRUE.)
  END SUBROUTINE CHECK_INVALIDATION
END PROGRAM SOURCE_RESIDENCY_TEST
