! SPDX-License-Identifier: GPL-3.0-or-later
PROGRAM SOURCE_PROFILE_TEST
  USE PAW_SKALA_PRIMITIVES_MODULE
  USE PAW_SKALA_GRID_MODULE, ONLY: PAW_SKALA_INVERSE3
  USE ACCELPROFILE_MODULE, ONLY: ENTRY,NENTRY
  USE, INTRINSIC :: IEEE_ARITHMETIC, ONLY: IEEE_IS_FINITE
  IMPLICIT NONE
  TYPE(PAW_SKALA_SOURCE) :: S
  TYPE(PAW_SKALA_SOURCE_CACHE) :: CACHE
  REAL(8) :: POINTS(7,3),BAR(5,2,7),CELL(3,3),AINV(3,3),CENTER(3),DX(3),MOM(3,3),CON
  REAL(8) :: BYTES(5),EXPECTED(5)
  REAL(8),ALLOCATABLE :: VALUE(:,:,:)
  INTEGER(8) :: CALLS(5),ROWS(5),LIMIT
  INTEGER :: I,J,MODE,CASE,COVERED,TOTAL
  CHARACTER(16) :: ARG
  LOGICAL :: FORWARD,OFF,DISABLED
  CHARACTER(32) :: NAMES(5)=[CHARACTER(32) :: &
 &  'ACC_COPY_SKALA_SOURCE_GEOM','ACC_COPY_SKALA_SOURCE_INPUT','SKALA_SOURCE_DEVICE', &
 &  'ACC_COPY_SKALA_SOURCE_OUT','SKALA_SOURCE_HOST_SUM']
  CALL GET_COMMAND_ARGUMENT(1,ARG)
  FORWARD=INDEX(TRIM(ARG),'forward').EQ.1
  OFF=TRIM(ARG).EQ.'off'.OR.TRIM(ARG).EQ.'forward-off'
  DISABLED=TRIM(ARG).EQ.'disabled'.OR.TRIM(ARG).EQ.'forward-disabled'
  IF(FORWARD) NAMES=[CHARACTER(32) :: 'ACC_COPY_SKALA_FWD_GEOM', &
 &  'ACC_COPY_SKALA_FWD_INPUT','SKALA_SOURCE_FWD_DEVICE','ACC_COPY_SKALA_FWD_OUT','SKALA_SOURCE_FWD_PACK']
  S%NR=21
  S%LNX=1
  S%LMNX=1
  S%NDIMD=2
  S%RCUT=1.D0
  ALLOCATE(S%R(21),S%PHI(21,1,2),S%CORE(21,2),S%LOX(1),S%DM(1,1,2),S%DH(1,1,2))
  S%R=[(0.05D0*I,I=1,21)]
  S%PHI(:,1,1)=EXP(-S%R**2)
  S%PHI(:,1,2)=0.8D0*S%PHI(:,1,1)
  S%CORE=0.D0
  S%LOX=0
  S%DM=1.D0
  S%DH=0.D0
  CALL PAW_SKALA_SOLID_BASIS_INIT(S%BASIS,0)
  CELL=0.D0
  DO I=1,3
    CELL(I,I)=4.D0
  END DO
  CALL PAW_SKALA_INVERSE3(CELL,AINV)
  CENTER=0.D0
  POINTS=0.1D0
  DO I=1,7
    POINTS(I,1)=0.1D0+0.05D0*I
  END DO
  BAR=0.25D0
  TOTAL=0
  DO MODE=1,2
    DO CASE=1,3
      LIMIT=1048576_8
      IF(CASE.EQ.2) THEN
        CALL PAW_SKALA_SOURCE_CACHE_PREPARE(CACHE,S,CELL,AINV,CENTER,POINTS(1:1,:),MODE.EQ.2,LIMIT)
        LIMIT=PAW_SKALA_SOURCE_CACHE_BYTES(CACHE)+6_8*28_8
      ELSE IF(CASE.EQ.3) THEN
        LIMIT=0_8
      END IF
      CALL PAW_SKALA_SOURCE_CACHE_PREPARE(CACHE,S,CELL,AINV,CENTER,POINTS,MODE.EQ.2,LIMIT)
      IF(FORWARD) THEN
        CALL PAW_SKALA_SOURCE_FORWARD_BATCH(CACHE,S,VALUE,COVERED)
      ELSE
        CALL PAW_SKALA_SOURCE_BACK_BATCH(CACHE,S,BAR,MODE.EQ.2,MODE.EQ.2,DX,MOM,CON,COVERED)
      END IF
      TOTAL=TOTAL+COVERED
    END DO
  END DO
  IF(OFF) THEN
    IF(TOTAL.NE.0) STOP 1
  ELSE
    IF(TOTAL.NE.16) STOP 2
  END IF
  CALLS=0_8
  ROWS=0_8
  BYTES=0.D0
  DO I=1,NENTRY
    DO J=1,5
      IF(ENTRY(I)%NAME.NE.NAMES(J)) CYCLE
      IF(.NOT.IEEE_IS_FINITE(ENTRY(I)%SECONDS).OR.ENTRY(I)%SECONDS.LT.0.D0) STOP 3
      IF(FORWARD.AND.ENTRY(I)%N4.NE.4_8) STOP 6
      CALLS(J)=CALLS(J)+ENTRY(I)%CALLS
      ROWS(J)=ROWS(J)+ENTRY(I)%CALLS*ENTRY(I)%N1
      BYTES(J)=BYTES(J)+ENTRY(I)%BYTES
    END DO
  END DO
  IF(OFF.OR.DISABLED) THEN
    IF(ANY(CALLS.NE.0_8).OR.ANY(ROWS.NE.0_8).OR.ANY(BYTES.NE.0.D0)) STOP 4
  ELSE
    ! Each source has exactly one image per cached row in this fixture.
    EXPECTED=(/4560.D0,1344.D0,0.D0,1920.D0,0.D0/)
    IF(FORWARD) THEN
      EXPECTED=(/1744.D0,64.D0,0.D0,1280.D0,0.D0/)
      IF(CALLS(5).NE.2_8.OR.ROWS(5).NE.8_8) STOP 5
      IF(ANY(CALLS(1:4).NE.4_8).OR.ANY(ROWS(1:4).NE.16_8)) STOP 5
    ELSE
      IF(ANY(CALLS.NE.4_8).OR.ANY(ROWS.NE.16_8)) STOP 5
    END IF
    IF(ANY(BYTES.NE.EXPECTED)) STOP 5
  END IF
  DO J=1,5
    WRITE(*,'(A,2(1X,I0),1X,F12.0)') TRIM(NAMES(J)),CALLS(J),ROWS(J),BYTES(J)
  END DO
  WRITE(*,'(A)') 'SOURCE PROFILE ACCOUNTING PASSED'
END PROGRAM SOURCE_PROFILE_TEST
