PROGRAM SETUP_RECIPROCAL_TEST
  USE, INTRINSIC :: IEEE_ARITHMETIC, ONLY: IEEE_IS_FINITE
  USE SETUP_MODULE, ONLY: THIS
  IMPLICIT NONE
  INTEGER,PARAMETER :: NR=96,NP=12
  CHARACTER(6),PARAMETER :: IDS(5)=[CHARACTER(6)::'PRO','PSCORE','VADD','G0','V0']
  REAL(8),PARAMETER :: PI=4.D0*ATAN(1.D0),VOLUME=7.D0
  REAL(8) :: R(NR),G2(NP),F(NP),DF(NP),SINGLE(1),REVERSED(NP)
  REAL(8) :: COEFF(5),EXPECTED,ERROR,MAXERROR,H,MINUS(NP),PLUS(NP),PERTURBED(NP)
  INTEGER :: I,J,K
  ALLOCATE(THIS)
  CALL RADIAL$NEW('LOG',THIS%GIDG)
  CALL RADIAL$SETI4(THIS%GIDG,'NR',NR)
  CALL RADIAL$SETR8(THIS%GIDG,'R1',0.01D0)
  CALL RADIAL$SETR8(THIS%GIDG,'DEX',LOG(500.D0)/REAL(NR-1,8))
  CALL RADIAL$R(THIS%GIDG,NR,R)
  THIS%LNX=1
  THIS%RCBG=2.D0
  THIS%RCSM=1.D0
  ALLOCATE(THIS%PROOFG(NR,1),THIS%PSCOREOFG(NR),THIS%VADDOFG(NR))
  ALLOCATE(THIS%NHATPRIMEOFG(NR),THIS%VHATOFG(NR))
  COEFF=[1.D0,2.D0,-0.5D0,4.D0*PI,12.D0*PI**2]
  THIS%PROOFG(:,1)=POLYNOMIAL(R,COEFF(1))
  THIS%PSCOREOFG=POLYNOMIAL(R,COEFF(2))
  THIS%VADDOFG=POLYNOMIAL(R,COEFF(3))
  THIS%NHATPRIMEOFG=POLYNOMIAL(R,COEFF(4))
  THIS%VHATOFG=POLYNOMIAL(R,COEFF(5))
  G2=[0.D0,0.64D0,0.64D0+2.D-7,0.64D0+4.D-7,0.64D0+6.D-7, &
      1.21D0,1.21D0,1.21D0+2.D-6,0.D0,2.56D0,2.56D0+3.D-7,0.D0]
  MAXERROR=0.D0
  DO K=1,SIZE(IDS)
    CALL SETUP$GETFOFG(TRIM(IDS(K)),.FALSE.,1,NP,G2,VOLUME,F)
    CALL SETUP$GETFOFG(TRIM(IDS(K)),.TRUE.,1,NP,G2,VOLUME,DF)
    IF(ANY(.NOT.IEEE_IS_FINITE(F)).OR.ANY(.NOT.IEEE_IS_FINITE(DF))) STOP 1
    DO I=1,NP
      EXPECTED=POLYNOMIAL(SQRT(G2(I)),COEFF(K))/VOLUME
      ERROR=ABS(F(I)-EXPECTED)
      MAXERROR=MAX(MAXERROR,ERROR)
      CALL SETUP$GETFOFG(TRIM(IDS(K)),.FALSE.,1,1,G2(I:I),VOLUME,SINGLE)
      MAXERROR=MAX(MAXERROR,ABS(F(I)-SINGLE(1)))
      EXPECTED=SQRT(G2(I))*(0.25D0+G2(I)**0.5D0+0.6D0*G2(I))/VOLUME
      MAXERROR=MAX(MAXERROR,ABS(DF(I)-EXPECTED))
      CALL SETUP$GETFOFG(TRIM(IDS(K)),.TRUE.,1,1,G2(I:I),VOLUME,SINGLE)
      MAXERROR=MAX(MAXERROR,ABS(DF(I)-SINGLE(1)))
    END DO
    DO J=1,2
      CALL SETUP$GETFOFG(TRIM(IDS(K)),J.EQ.2,1,NP,G2(NP:1:-1),VOLUME,REVERSED)
      IF(J.EQ.1) MAXERROR=MAX(MAXERROR,MAXVAL(ABS(F-REVERSED(NP:1:-1))))
      IF(J.EQ.2) MAXERROR=MAX(MAXERROR,MAXVAL(ABS(DF-REVERSED(NP:1:-1))))
    END DO
    ! Isotropic reciprocal scaling includes the inverse-volume contribution.
    H=1.D-5
    CALL SETUP$GETFOFG(TRIM(IDS(K)),.FALSE.,1,NP,G2/(1.D0-H)**2,VOLUME*(1.D0-H)**3,MINUS)
    CALL SETUP$GETFOFG(TRIM(IDS(K)),.FALSE.,1,NP,G2/(1.D0+H)**2,VOLUME*(1.D0+H)**3,PLUS)
    ERROR=MAXVAL(ABS((PLUS-MINUS)/(2.D0*H)+DF+3.D0*F))
    WRITE(*,'(A,1X,A,1X,ES12.4)') 'STRAIN FD ERROR',TRIM(IDS(K)),ERROR
    IF(ERROR.GT.1.D-7) STOP 2
    H=5.D-8
    PERTURBED=G2
    PERTURBED(3)=G2(3)-H
    CALL SETUP$GETFOFG(TRIM(IDS(K)),.FALSE.,1,NP,PERTURBED,VOLUME,MINUS)
    PERTURBED(3)=G2(3)+H
    CALL SETUP$GETFOFG(TRIM(IDS(K)),.FALSE.,1,NP,PERTURBED,VOLUME,PLUS)
    EXPECTED=DF(3)/(2.D0*G2(3))
    ERROR=ABS((PLUS(3)-MINUS(3))/(2.D0*H)-EXPECTED)
    WRITE(*,'(A,1X,A,1X,ES12.4)') 'SINGLE-RADIUS FD ERROR',TRIM(IDS(K)),ERROR
    IF(ERROR.GT.5.D-7) STOP 2
  END DO
  WRITE(*,'(A,ES12.4)') 'MAX RECIPROCAL VALUE/DERIVATIVE ERROR ',MAXERROR
  IF(MAXERROR.GT.2.D-11) STOP 3
CONTAINS
  ELEMENTAL REAL(8) FUNCTION POLYNOMIAL(X,C) RESULT(Y)
    REAL(8),INTENT(IN) :: X,C
    Y=C+0.25D0*X+0.5D0*X**2+0.2D0*X**3
  END FUNCTION POLYNOMIAL
END PROGRAM SETUP_RECIPROCAL_TEST
