PROGRAM ORTHOGONALITY_TOLERANCE
  USE, INTRINSIC :: IEEE_ARITHMETIC, ONLY: IEEE_VALUE, IEEE_QUIET_NAN, IEEE_POSITIVE_INF
  IMPLICIT NONE
  REAL(8) :: TOL,VALUE,ERROR_REAL,ERROR_COMPLEX
  INTEGER :: K
  CHARACTER(32) :: ARGUMENT

  CALL GET_COMMAND_ARGUMENT(1,ARGUMENT)
  IF(LEN_TRIM(ARGUMENT).NE.0) THEN
    SELECT CASE(TRIM(ARGUMENT))
    CASE('nan')
      VALUE=IEEE_VALUE(0.D0,IEEE_QUIET_NAN)
    CASE('inf')
      VALUE=IEEE_VALUE(0.D0,IEEE_POSITIVE_INF)
    CASE('loose')
      VALUE=1.D-7
    CASE('tight')
      VALUE=1.D-15
    CASE('zero')
      VALUE=0.D0
    CASE DEFAULT
      STOP 2
    END SELECT
    CALL WAVES$SETR8('ORTHOTOL',VALUE)
    STOP 0
  END IF

  CALL WAVES$GETR8('ORTHOTOL',VALUE)
  IF(VALUE.NE.1.D-8) STOP 1
  CALL CHECK_DEFAULT
  DO K=1,3
    SELECT CASE(K)
    CASE(1)
      TOL=1.D-8
    CASE(2)
      TOL=1.D-12
    CASE(3)
      TOL=1.D-14
    END SELECT
    CALL WAVES$SETR8('ORTHOTOL',TOL)
    CALL WAVES$GETR8('ORTHOTOL',VALUE)
    IF(VALUE.NE.TOL) STOP 1
    CALL CHECK_MATRICES(TOL,ERROR_REAL,ERROR_COMPLEX)
    WRITE(*,'(A,3ES24.14)')'ORTHOTOL, REAL AND COMPLEX DEFECT ',TOL,ERROR_REAL,ERROR_COMPLEX
  END DO
  CALL WAVES$SETR8('ORTHOTOL',1.D-8)
CONTAINS
  SUBROUTINE CHECK_DEFAULT
    REAL(8) :: X(1,1),GRAM(1,1),UNIT(1,1),LAMBDA(1,1),OCC(1)
    COMPLEX(8) :: CX(1,1),CG(1,1),CU(1,1),CL(1,1)
    X=SQRT(1.D0+5.D-9)
    GRAM=X*X
    UNIT=1.D0
    OCC=1.D0
    CX=CMPLX(X,0.D0,KIND=8)
    CG=CMPLX(GRAM,0.D0,KIND=8)
    CU=(1.D0,0.D0)
    LAMBDA=0.D0
    CL=(0.D0,0.D0)
    CALL WAVES_ORTHO_X(1,OCC,UNIT,GRAM,X,LAMBDA)
    CALL WAVES_ORTHO_X_C(1,OCC,CU,CG,CX,CL)
    IF(ANY(LAMBDA.NE.0.D0).OR.ANY(CL.NE.(0.D0,0.D0))) STOP 1
    CALL WAVES$SETR8('ORTHOTOL',1.D-12)
    CALL WAVES_ORTHO_X(1,OCC,UNIT,GRAM,X,LAMBDA)
    CALL WAVES_ORTHO_X_C(1,OCC,CU,CG,CX,CL)
    IF(MAXVAL(ABS((X+LAMBDA)**2-1.D0)).GT.1.D-12) STOP 1
    IF(MAXVAL(ABS(ABS(CX+CL)**2-1.D0)).GT.1.D-12) STOP 1
    IF(ALL(LAMBDA.EQ.0.D0).OR.ALL(CL.EQ.(0.D0,0.D0))) STOP 1
  END SUBROUTINE

  SUBROUTINE CHECK_MATRICES(BOUND,REAL_ERROR,COMPLEX_ERROR)
    REAL(8),INTENT(IN) :: BOUND
    REAL(8),INTENT(OUT) :: REAL_ERROR,COMPLEX_ERROR
    INTEGER,PARAMETER :: N=3
    REAL(8) :: X(N,N),CHI(N,N),UNIT(N,N),OCC(N),LAMBDA(N,N),Y(N,N)
    COMPLEX(8) :: CX(N,N),CCHI(N,N),CL(N,N),CY(N,N)
    INTEGER :: I,J
    UNIT=0.D0
    CHI=0.D0
    DO I=1,N
      UNIT(I,I)=1.D0
      CHI(I,I)=0.8D0+0.2D0*I
    END DO
    DO J=1,N
      DO I=1,N
        X(I,J)=UNIT(I,J)+0.003D0*SIN(REAL(2*I+J,8))
        CX(I,J)=CMPLX(X(I,J),0.002D0*COS(REAL(I+3*J,8)),KIND=8)
      END DO
    END DO
    CCHI=CMPLX(CHI,0.D0,KIND=8)
    OCC=[2.D0,0.7D0,0.D0]
    LAMBDA=0.D0
    CL=(0.D0,0.D0)
    CALL WAVES_ORTHO_X(N,OCC,MATMUL(TRANSPOSE(CHI),CHI), &
        MATMUL(TRANSPOSE(X),X),MATMUL(TRANSPOSE(CHI),X),LAMBDA)
    CALL WAVES_ORTHO_X_C(N,OCC,MATMUL(CONJG(TRANSPOSE(CCHI)),CCHI), &
        MATMUL(CONJG(TRANSPOSE(CX)),CX),MATMUL(CONJG(TRANSPOSE(CCHI)),CX),CL)
    Y=X+MATMUL(CHI,LAMBDA)
    CY=CX+MATMUL(CCHI,CL)
    REAL_ERROR=MAXVAL(ABS(MATMUL(TRANSPOSE(Y),Y)-UNIT))
    COMPLEX_ERROR=MAXVAL(ABS(MATMUL(CONJG(TRANSPOSE(CY)),CY)-UNIT))
    IF(MAX(REAL_ERROR,COMPLEX_ERROR).GT.BOUND+5.D-15) STOP 1
    DO J=1,N
      DO I=1,N
        IF(ABS(LAMBDA(I,J)*(OCC(J)+1.D-12) &
            -LAMBDA(J,I)*(OCC(I)+1.D-12)).GT.1.D-13) STOP 1
        IF(ABS(CL(I,J)*(OCC(J)+1.D-12) &
            -CONJG(CL(J,I))*(OCC(I)+1.D-12)).GT.1.D-13) STOP 1
      END DO
    END DO
  END SUBROUTINE
END PROGRAM
