PROGRAM HARTREE_STRAIN_TEST
  USE, INTRINSIC :: IEEE_ARITHMETIC, ONLY: IEEE_IS_FINITE
  USE PLANEWAVE_MODULE, ONLY: THIS
  IMPLICIT NONE
  INTEGER,PARAMETER :: NG=6,NS=2,NA=3,LM=9
  REAL(8),PARAMETER :: H=1.D-5
  INTEGER :: SPECIES(NA),LMRX(NS),I,J,CASE_ID
  REAL(8) :: POS(3,NA),QLM(LM,NA),E,EM,EP,STRESS(3,3),WORK(3,3),ERR,MAXERR
  REAL(8) :: PERMUTED(3,3),OLDPOS(3,NA),OLDQLM(LM,NA),DE
  INTEGER :: OLDSPECIES(NA),ORDER(NA)
  CALL MPE$INIT
  ALLOCATE(THIS)
  THIS%CID='MONOMER'
  THIS%TSUPER=.TRUE.
  THIS%NGAMMA=1
  THIS%KVEC=0.D0
  THIS%NR1=8
  THIS%NR2=8
  THIS%NR3=8
  ALLOCATE(THIS%NGHARR(1),THIS%IGVECH(3,NG))
  THIS%NGHARR=NG
  THIS%IGVECH=RESHAPE([0,0,0, 1,0,0, 0,1,1, 1,-1,1, 2,1,-1, 1,2,2],[3,NG])
  MAXERR=0.D0
  DO CASE_ID=1,3
    LMRX=[9,9]
    IF(CASE_ID.EQ.2) LMRX=[1,9]
    IF(CASE_ID.EQ.3) LMRX=[4,9]
    SPECIES=[1,2,2]
    POS=RESHAPE([0.1D0,0.3D0,0.2D0, 1.2D0,-0.4D0,0.7D0, -0.6D0,0.2D0,1.4D0],[3,NA])
    QLM=0.D0
    DO I=1,NA
      DO J=1,LMRX(SPECIES(I))
        QLM(J,I)=SIN(REAL(2*J+I,8))/REAL(J,8)
      END DO
    END DO
    CALL EVALUATE(0.D0,1,1,E,STRESS)
    DO I=1,3
      DO J=I,3
        CALL EVALUATE(-H,I,J,EM,WORK)
        CALL EVALUATE(H,I,J,EP,WORK)
        ERR=ABS((EP-EM)/(2.D0*H)-0.5D0*(STRESS(I,J)+STRESS(J,I)))
        IF(.NOT.IEEE_IS_FINITE(ERR)) STOP 1
        WRITE(*,'(A,3I3,ES14.5)') 'HARTREE STRAIN FD ',CASE_ID,I,J,ERR
        MAXERR=MAX(MAXERR,ERR)
      END DO
    END DO
    OLDPOS=POS
    OLDQLM=QLM
    OLDSPECIES=SPECIES
    ORDER=[2,1,3]
    POS=OLDPOS(:,ORDER)
    QLM=OLDQLM(:,ORDER)
    SPECIES=OLDSPECIES(ORDER)
    CALL EVALUATE(0.D0,1,1,EP,PERMUTED)
    ERR=MAXVAL(ABS(STRESS-PERMUTED))
    DE=ABS(E-EP)
    IF(.NOT.IEEE_IS_FINITE(ERR).OR..NOT.IEEE_IS_FINITE(DE)) STOP 1
    WRITE(*,'(A,I3,2ES14.5)') 'HARTREE ATOM ORDER ',CASE_ID,DE,ERR
    MAXERR=MAX(MAXERR,ERR,DE)
  END DO
  WRITE(*,'(A,ES14.5)') 'MAX HARTREE STRAIN ERROR ',MAXERR
  IF(MAXERR.GT.2.D-8) STOP 2
CONTAINS
  SUBROUTINE EVALUATE(S,A,B,ENERGY,TENSOR)
    REAL(8),INTENT(IN) :: S
    INTEGER,INTENT(IN) :: A,B
    REAL(8),INTENT(OUT) :: ENERGY,TENSOR(3,3)
    REAL(8) :: G(3,NG),G2(NG),Y(LM,NG),R(3,NA),VOL,DET,ALPHA
    REAL(8) :: G0(NG,NS),DG0(NG,NS),V0(NG,NS),DV0(NG,NS)
    REAL(8) :: VB(NG,NS),DVB(NG,NS),VQLM(LM,NA),FORCE(3,NA),RHOB
    COMPLEX(8) :: RHO(NG),POT(NG)
    INTEGER :: N,SP
    ! Hold fractional nuclei and Fourier density coefficients times volume fixed.
    DET=1.D0
    IF(A.EQ.B) THEN
      DET=1.D0+S
    ELSE
      DET=1.D0-0.25D0*S*S
    END IF
    VOL=17.D0*DET
    THIS%GBAS=0.D0
    DO N=1,3
      THIS%GBAS(N,N)=0.7D0
    END DO
    THIS%GBAS(A,A)=0.7D0/DET
    THIS%GBAS(B,B)=0.7D0/DET
    IF(A.NE.B) THEN
      THIS%GBAS(A,B)=-0.35D0*S/DET
      THIS%GBAS(B,A)=-0.35D0*S/DET
    END IF
    G=MATMUL(THIS%GBAS,REAL(THIS%IGVECH,8))
    G2=SUM(G**2,DIM=1)
    R=POS
    IF(A.EQ.B) THEN
      R(A,:)=R(A,:)+S*POS(B,:)
    ELSE
      R(A,:)=R(A,:)+0.5D0*S*POS(B,:)
      R(B,:)=R(B,:)+0.5D0*S*POS(A,:)
    END IF
    DO N=1,NG
      RHO(N)=CMPLX(COS(REAL(N,8)),SIN(REAL(N-1,8)),8)/VOL
    END DO
    DO SP=1,NS
      ALPHA=0.3D0+0.2D0*REAL(SP,8)
      G0(:,SP)=EXP(-ALPHA*G2)/VOL
      DG0(:,SP)=-2.D0*ALPHA*G2*G0(:,SP)
      V0(:,SP)=0.2D0*EXP(-0.2D0*G2)/VOL
      DV0(:,SP)=-0.4D0*G2*V0(:,SP)
      VB(:,SP)=-0.1D0*EXP(-0.4D0*G2)/VOL
      DVB(:,SP)=-0.8D0*G2*VB(:,SP)
    END DO
    CALL POTENTIAL_YLMOFG(LM,LM,NG,G,Y)
    CALL POTENTIAL_HARTREE(LM,2,NG,NS,NA,SPECIES,LMRX,RHO,POT,QLM,VQLM,R,FORCE,ENERGY, &
      VOL,G2,G,Y,VB,DVB,G0,V0,RHOB,.TRUE.,DG0,DV0,TENSOR)
  END SUBROUTINE EVALUATE
END PROGRAM HARTREE_STRAIN_TEST
