PROGRAM CUBLAS_WORKSPACE_TEST
#IF DEFINED(CPPVAR_CUBLAS_FP64_EMULATION)
  USE CPPAW_CUBLAS_ACC_MODULE, ONLY: CPPAW_CUBLAS_ACC_DGEMM_MATMUL_COPY &
 & ,CPPAW_CUBLAS_ACC_ZGEMM_NN_COPY,FP64_WORKSPACE_PTR,FP64_BIT_COUNT_PTR &
 & ,FP64_EMULATION_ENABLED,FP64_TELEMETRY_ENABLED,FP64_WORKSPACE_MB &
 & ,CPPAW_CUDA_MEMCPY_C
  USE, INTRINSIC :: ISO_C_BINDING, ONLY: C_PTR,C_ASSOCIATED,C_INT,C_LOC,C_SIZEOF
  USE, INTRINSIC :: IEEE_ARITHMETIC, ONLY: IEEE_IS_FINITE
  IMPLICIT NONE
  INTEGER :: N,I,J,REPEAT,ISTAT
  INTEGER(C_INT),TARGET :: BITS
  REAL(8),ALLOCATABLE :: A(:,:),B(:,:),C(:,:),REFERENCE(:,:)
  COMPLEX(8),ALLOCATABLE :: ZA(:,:),ZB(:,:),ZC(:,:),ZREFERENCE(:,:)
  REAL(8) :: ERROR
  LOGICAL :: USED
  TYPE(C_PTR) :: WORKSPACE,COUNTER
  CHARACTER(32) :: ARG,EXPECTED

  N=256
  IF(COMMAND_ARGUMENT_COUNT().GT.0) THEN
    CALL GET_COMMAND_ARGUMENT(1,ARG)
    READ(ARG,*,IOSTAT=ISTAT) N
    IF(ISTAT.NE.0) STOP 1
  END IF
  IF(N.LT.8.OR.N.GT.2048) STOP 1
  EXPECTED='any'
  IF(COMMAND_ARGUMENT_COUNT().GT.1) CALL GET_COMMAND_ARGUMENT(2,EXPECTED)
  IF(EXPECTED.NE.'any'.AND.EXPECTED.NE.'used'.AND.EXPECTED.NE.'fallback') STOP 1
  IF(C_ASSOCIATED(FP64_WORKSPACE_PTR).OR.C_ASSOCIATED(FP64_BIT_COUNT_PTR)) STOP 1
  ALLOCATE(A(N,N),B(N,N),C(N,N),REFERENCE(N,N))
  ALLOCATE(ZA(N,N),ZB(N,N),ZC(N,N),ZREFERENCE(N,N))
  DO J=1,N
    DO I=1,N
      A(I,J)=SIN(0.17D0*I)*COS(0.11D0*J)+0.3D0*COS(0.07D0*I)*SIN(0.19D0*J)
      B(I,J)=COS(0.13D0*I)*SIN(0.23D0*J)-0.2D0*SIN(0.31D0*I)*COS(0.29D0*J)
    END DO
  END DO
  REFERENCE=MATMUL(A,B)
  ZA=CMPLX(A,0.5D0*B,KIND=8)
  ZB=CMPLX(B,-0.25D0*A,KIND=8)
  ZREFERENCE=MATMUL(ZA,ZB)+CMPLX(0.125D0,-0.25D0,KIND=8)
  DO REPEAT=1,3
    C=-7.D0
    CALL CPPAW_CUBLAS_ACC_DGEMM_MATMUL_COPY(N,N,N,A,B,C,USED)
    IF(.NOT.USED) STOP 1
    IF(.NOT.ALL(IEEE_IS_FINITE(C))) STOP 1
    ERROR=MAXVAL(ABS(C-REFERENCE))/MAX(1.D0,MAXVAL(ABS(REFERENCE)))
    WRITE(*,'(A,I0,A,ES16.8)') 'DGEMM repetition ',REPEAT,' relative error ',ERROR
    IF(ERROR.GT.5.D-12) STOP 1
    IF(REPEAT.EQ.1) THEN
      WORKSPACE=FP64_WORKSPACE_PTR
      COUNTER=FP64_BIT_COUNT_PTR
    END IF
    CALL CHECK_BUFFERS('DGEMM')
    ZC=CMPLX(0.125D0,-0.25D0,KIND=8)
    CALL CPPAW_CUBLAS_ACC_ZGEMM_NN_COPY(N,N,N,ZA,ZB,ZC,USED)
    IF(.NOT.USED) STOP 1
    IF(.NOT.ALL(IEEE_IS_FINITE(REAL(ZC))).OR. &
   &   .NOT.ALL(IEEE_IS_FINITE(AIMAG(ZC)))) STOP 1
    ERROR=MAXVAL(ABS(ZC-ZREFERENCE))/MAX(1.D0,MAXVAL(ABS(ZREFERENCE)))
    WRITE(*,'(A,I0,A,ES16.8)') 'ZGEMM repetition ',REPEAT,' relative error ',ERROR
    IF(ERROR.GT.5.D-12) STOP 1
    CALL CHECK_BUFFERS('ZGEMM')
  END DO
  WRITE(*,'(A)') 'cuBLAS persistent workspace test passed'
CONTAINS
  SUBROUTINE CHECK_BUFFERS(NAME)
    CHARACTER(*),INTENT(IN) :: NAME
    IF(FP64_EMULATION_ENABLED.AND.FP64_WORKSPACE_MB.GT.0) THEN
      IF(.NOT.C_ASSOCIATED(FP64_WORKSPACE_PTR,WORKSPACE)) STOP 1
    ELSE
      IF(C_ASSOCIATED(FP64_WORKSPACE_PTR)) STOP 1
    END IF
    IF(FP64_EMULATION_ENABLED.AND.FP64_TELEMETRY_ENABLED) THEN
      IF(.NOT.C_ASSOCIATED(FP64_BIT_COUNT_PTR,COUNTER)) STOP 1
      ISTAT=CPPAW_CUDA_MEMCPY_C(C_LOC(BITS),FP64_BIT_COUNT_PTR,C_SIZEOF(BITS),2_C_INT)
      WRITE(*,'(A,A,I0)') NAME,' mantissa counter ',BITS
      IF(ISTAT.NE.0.OR.BITS.LT.-2) STOP 1
      IF(EXPECTED.EQ.'used'.AND.BITS.LT.0) STOP 1
      IF(EXPECTED.EQ.'fallback'.AND.BITS.NE.-1) STOP 1
      ! Poisoning detects a stale counter if the next operation fails to reset it.
      BITS=-3_C_INT
      ISTAT=CPPAW_CUDA_MEMCPY_C(FP64_BIT_COUNT_PTR,C_LOC(BITS),C_SIZEOF(BITS),1_C_INT)
      IF(ISTAT.NE.0) STOP 1
    ELSE
      IF(C_ASSOCIATED(FP64_BIT_COUNT_PTR)) STOP 1
      IF(EXPECTED.NE.'any') STOP 1
    END IF
  END SUBROUTINE CHECK_BUFFERS
#ELSE
  IMPLICIT NONE
  WRITE(*,'(A)') 'SKIP: cuBLAS FP64 emulation was not enabled at build time'
#ENDIF
END PROGRAM CUBLAS_WORKSPACE_TEST
