PROGRAM PROJECTOR_STRAIN_TEST
  USE, INTRINSIC :: IEEE_ARITHMETIC, ONLY: IEEE_IS_FINITE
  IMPLICIT NONE
  INTEGER,PARAMETER :: NG=7,NL=5,LM=25
  REAL(8),PARAMETER :: H=1.D-3
  INTEGER :: LOX(NL),I,J,IG,LN,INDEX,IJ
  REAL(8) :: G(3,NG),G2(NG),Y(NG,LM),SY(NG,LM,6),GIJ(6,NG)
  REAL(8) :: YM(NG,LM),YP(NG,LM),YMHALF(NG,LM),YPHALF(NG,LM),BARE(NG,NL),DBARE(NG,NL)
  REAL(8) :: FORCE(3),STRESS(3,3),EM,EP,EMHALF,EPHALF,ERROR,MAXANGULAR,MAXPROJECTOR,ALPHA
  COMPLEX(8) :: PHASE(NG),ADJOINT(NG,LM)
  CALL MPE$INIT
  LOX=[0,1,2,3,4]
  G=RESHAPE([0.7D0,0.D0,0.D0, 0.D0,-1.3D0,0.D0, 0.D0,0.D0,1.1D0, &
     0.8D0,-0.8D0,0.2D0, 0.9D0,0.9D0,-0.3D0, &
     1.2D0,-0.7D0,0.4D0, -0.3D0,0.6D0,1.4D0],[3,NG])
  G2=SUM(G**2,DIM=1)
  DO IG=1,NG
    CALL GETYLM(LM,G(:,IG),Y(IG,:))
    PHASE(IG)=CMPLX(COS(REAL(IG,8)),SIN(REAL(IG,8)),8)
  END DO
  CALL WAVES_STRAINEDYLM(NG,LM,G,Y,SY)
  DO LN=1,NL
    ALPHA=0.2D0+0.1D0*REAL(LN,8)
    BARE(:,LN)=EXP(-ALPHA*G2)
    DBARE(:,LN)=-2.D0*ALPHA*G2*BARE(:,LN)
  END DO
  DO INDEX=1,LM
    DO IG=1,NG
      ADJOINT(IG,INDEX)=CMPLX(SIN(REAL(2*IG+INDEX,8)), &
                             COS(REAL(IG-3*INDEX,8)),8)/REAL(1+INDEX,8)
    END DO
  END DO
  IJ=0
  DO I=1,3
    DO J=I,3
      IJ=IJ+1
      GIJ(IJ,:)=G(I,:)*G(J,:)/G2
    END DO
  END DO
  CALL WAVES_PROFORCE(NL,LM,LOX,NG,1.D0,G,GIJ,BARE,DBARE,LM,Y,SY, &
                     PHASE,ADJOINT,FORCE,.TRUE.,STRESS)
  MAXANGULAR=0.D0
  MAXPROJECTOR=0.D0
  IJ=0
  DO I=1,3
    DO J=I,3
      IJ=IJ+1
      CALL EVALUATE(-H,I,J,YM,EM)
      CALL EVALUATE(H,I,J,YP,EP)
      CALL EVALUATE(-0.5D0*H,I,J,YMHALF,EMHALF)
      CALL EVALUATE(0.5D0*H,I,J,YPHALF,EPHALF)
      ! Fourth-order differences avoid tiny polar angles in the Legendre reference.
      ERROR=MAXVAL(ABS((8.D0*(YPHALF-YMHALF)-(YP-YM))/(6.D0*H)+SY(:,:,IJ)))
      IF(.NOT.IEEE_IS_FINITE(ERROR)) STOP 1
      WRITE(*,'(A,2I3,ES16.7)') 'ANGULAR STRAIN FD ',I,J,ERROR
      MAXANGULAR=MAX(MAXANGULAR,ERROR)
      ERROR=ABS((8.D0*(EPHALF-EMHALF)-(EP-EM))/(6.D0*H)-STRESS(I,J))
      IF(.NOT.IEEE_IS_FINITE(ERROR)) STOP 1
      WRITE(*,'(A,2I3,ES16.7)') 'PROJECTOR STRAIN FD ',I,J,ERROR
      MAXPROJECTOR=MAX(MAXPROJECTOR,ERROR)
    END DO
  END DO
  WRITE(*,'(A,2ES16.7)') 'MAX ANGULAR/PROJECTOR STRAIN ERROR ',MAXANGULAR,MAXPROJECTOR
  IF(MAXANGULAR.GT.2.D-8.OR.MAXPROJECTOR.GT.2.D-8) STOP 2
CONTAINS
  SUBROUTINE EVALUATE(S,A,B,HARMONICS,ENERGY)
    REAL(8),INTENT(IN) :: S
    INTEGER,INTENT(IN) :: A,B
    REAL(8),INTENT(OUT) :: HARMONICS(NG,LM),ENERGY
    REAL(8) :: GP(3,NG),DET,RADIAL,G2P(NG)
    COMPLEX(8),PARAMETER :: CI=(0.D0,1.D0)
    COMPLEX(8) :: P
    INTEGER :: N,K,ELL,M0,LM0
    GP=G
    IF(A.EQ.B) THEN
      DET=1.D0+S
      GP(A,:)=G(A,:)/DET
    ELSE
      DET=1.D0-0.25D0*S*S
      GP(A,:)=(G(A,:)-0.5D0*S*G(B,:))/DET
      GP(B,:)=(G(B,:)-0.5D0*S*G(A,:))/DET
    END IF
    G2P=SUM(GP**2,DIM=1)
    DO N=1,NG
      CALL GETYLM(LM,GP(:,N),HARMONICS(N,:))
    END DO
    ENERGY=0.D0
    LM0=0
    DO K=1,NL
      ELL=LOX(K)
      DO M0=1,2*ELL+1
        LM0=LM0+1
        DO N=1,NG
          ! Cell-normalized orbitals leave one inverse square-root volume factor.
          RADIAL=EXP(-(0.2D0+0.1D0*REAL(K,8))*G2P(N))/SQRT(DET)
          P=(-CI)**ELL*PHASE(N)*RADIAL*HARMONICS(N,LM0)
          ENERGY=ENERGY+2.D0*REAL(CONJG(ADJOINT(N,LM0))*P,8)
        END DO
      END DO
    END DO
  END SUBROUTINE EVALUATE
END PROGRAM PROJECTOR_STRAIN_TEST
