#!/bin/ksh
F90PP=${PAWDIR}/F90PP/f90pp
OBJDIR=${PAWDIR}/Objects/dbg
MODDIR=${OBJDIR}
LFLAGS="-g -lessl -bmaxdata:0x70000000 -bloadmap:loadmap -I${OBJDIR}"
# compile flags for debugging
FFLAGS="-c -g -C -qsource -I${OBJDIR} -qmoddir=${OBJDIR} -qhalt=e -bloadmap:loadmap -qlanglvl=90STD -qextchk -qflttrap=zerodivide:overflow:enable -qsigtrap"
#============================================
#xlf90 -c -I${MODDIR} -qmoddir=${MODDIR} -qhalt=e -omytest.o mytest.f 
$F90PP <paw_diffgl.f >paw_diffgl_d.f 
 xlf90 ${FFLAGS} -opaw_diffgl.o paw_diffgl_d.f
$F90PP <paw_atom.f  >paw_atom_d.f  
xlf90 ${FFLAGS} -opaw_atom.o paw_atom_d.f
echo linking...
xlf90 -L${OBJDIR} -lpaw -lessl -bloadmap:loadmap  -opaw_atom paw_atom.o paw_diffgl.o 
exit


