#!/bin/ksh
F90PP=${PAWDIR}/F90PP/f90pp
OBJDIR=${PAWDIR}/Objects/dbg
MODDIR=${OBJDIR}
COMPILE="f90 -c -g -Rs -L${OBJDIR}  -I${OBJDIR} -p${OBJDIR}"
LINK="f95 -I${OBJDIR} -L${OBJDIR}"
LLIBS="-lblas -llapack -lU77 -lpaw -llapack -lblas -LU77"
F90PP="${F90PP} -archabs -DCPPVARIABLE_DEC"
#===========================================
#${COMPILE} -c -I${MODDIR} -qmoddir=${MODDIR} -qhalt=e -omytest.o mytest.f 
$F90PP paw_diffgl.f >paw_diffgl_d.f90 
${COMPILE} ${FFLAGS} -opaw_diffgl.o paw_diffgl_d.f90
$F90PP paw_atom.f  >paw_atom_d.f90
${COMPILE} ${FFLAGS} -opaw_atom.o paw_atom_d.f90
echo linking...
${LINK} -v ${LLIBS} -o${PAWDIR}/X/paw_atom.x paw_atom.o paw_diffgl.o ${LLIBS}
exit












