!*******************************************************************************
!**  CARTESIAN SOLID-HARMONIC PRIMITIVES FOR THE SKALA PAW ATOM GRIDS         **
!*******************************************************************************
MODULE PAW_SKALA_PRIMITIVES_MODULE
#IF DEFINED(CPPVAR_OPENACC)
  USE OPENACC, ONLY: ACC_GET_NUM_DEVICES,ACC_DEVICE_NVIDIA
#ENDIF
  IMPLICIT NONE
  PRIVATE

  TYPE, PUBLIC :: PAW_SKALA_SOLID_BASIS
    INTEGER(4) :: LMAX=-1
    INTEGER(4) :: NPOLY=0
    INTEGER(4) :: LMX=0
    INTEGER(4),ALLOCATABLE :: POWER(:,:) !(3,NPOLY)
    REAL(8),ALLOCATABLE :: COEFF(:,:)    !(NPOLY,LMX)
  END TYPE PAW_SKALA_SOLID_BASIS

  TYPE, PUBLIC :: PAW_SKALA_SOURCE
    INTEGER(4) :: NR=0,LNX=0,LMNX=0,NDIMD=0
    REAL(8) :: RCUT=0.D0
    INTEGER(4),ALLOCATABLE :: LOX(:)
    REAL(8),ALLOCATABLE :: R(:),PHI(:,:,:),CORE(:,:)
    COMPLEX(8),ALLOCATABLE :: DM(:,:,:),DH(:,:,:)
    TYPE(PAW_SKALA_SOLID_BASIS) :: BASIS
  END TYPE PAW_SKALA_SOURCE

  TYPE, PUBLIC :: PAW_SKALA_SOURCE_CACHE
    PRIVATE
    LOGICAL :: READY=.FALSE.,GEOMETRY=.FALSE.
    INTEGER :: LAST=0
    INTEGER(8) :: BYTES=0_8
    TYPE(PAW_SKALA_SOURCE) :: SETUP
    REAL(8) :: CELL(3,3)=0.D0,AINV(3,3)=0.D0,CENTER(3)=0.D0
    REAL(8),ALLOCATABLE :: POINT(:,:),IMAGE(:,:),WAVE(:,:,:,:)
    REAL(8),ALLOCATABLE :: CORE(:,:),COREJAC(:,:,:)
    INTEGER,ALLOCATABLE :: FIRST(:)
  END TYPE PAW_SKALA_SOURCE_CACHE

  PUBLIC :: PAW_SKALA_SOLID_BASIS_INIT
  PUBLIC :: PAW_SKALA_SOLID_BASIS_EVALUATE
  PUBLIC :: PAW_SKALA_ONECENTER_GRID_SIZE
  PUBLIC :: PAW_SKALA_ONECENTER_CHECK_EXACTNESS
  PUBLIC :: PAW_SKALA_ONECENTER_PRIMITIVES
  PUBLIC :: PAW_SKALA_ONECENTER_REFERENCE
  PUBLIC :: PAW_SKALA_ONECENTER_POINTS
  PUBLIC :: PAW_SKALA_ONECENTER_ADJOINT_POINTS
  PUBLIC :: PAW_SKALA_PRIMITIVES_TEST
  PUBLIC :: PAW_SKALA_RADIAL_SAMPLE
  PUBLIC :: PAW_SKALA_SOURCE_POINT
  PUBLIC :: PAW_SKALA_SOURCE_IMAGES
  PUBLIC :: PAW_SKALA_SOURCE_CACHE_PREPARE,PAW_SKALA_SOURCE_CACHE_BYTES
  PUBLIC :: PAW_SKALA_SOURCE_CACHE_LIMIT
  PUBLIC :: PAW_SKALA_SOURCE_BACK_BATCH

CONTAINS

  SUBROUTINE PAW_SKALA_SOURCE_BACK_BATCH(CACHE,S,BAR,GEOMETRY,STRESS,DX,MOMENT,CONTRACTION,COVERED)
    ! Only complete cached rows are offloaded. Remaining rows use SOURCE_IMAGES.
    TYPE(PAW_SKALA_SOURCE_CACHE),INTENT(IN) :: CACHE
    TYPE(PAW_SKALA_SOURCE),INTENT(INOUT) :: S
    REAL(8),INTENT(IN) :: BAR(:,:,:)
    LOGICAL,INTENT(IN) :: GEOMETRY,STRESS
    REAL(8),INTENT(OUT) :: DX(3),MOMENT(3,3),CONTRACTION
    INTEGER,INTENT(OUT) :: COVERED
#IF DEFINED(CPPVAR_OPENACC)
    INTEGER,PARAMETER :: TILE=128
    LOGICAL,SAVE :: INITIALIZED=.FALSE.,ENABLED=.FALSE.
    INTEGER(8),SAVE :: LIMIT=256_8*1048576_8
    INTEGER,SAVE :: MINROWS=4096
    CHARACTER(128) :: TEXT
    INTEGER :: STATUS,IOS,IP,NE,NC,N,D
    INTEGER(8) :: FIXED,ENTRY,PAYLOAD,MB
    REAL(8) :: DM(S%LMNX,S%LMNX,S%NDIMD),DH(S%LMNX,S%LMNX,S%NDIMD)
#ENDIF
    COVERED=0
    DX=0.D0
    MOMENT=0.D0
    CONTRACTION=0.D0
#IF DEFINED(CPPVAR_OPENACC)
    IF(.NOT.INITIALIZED) THEN
      INITIALIZED=.TRUE.
      CALL GET_ENVIRONMENT_VARIABLE('CPPAW_SKALA_SOURCE_BACK_ACC',TEXT,STATUS=STATUS)
      IF(STATUS.EQ.0) ENABLED=TRIM(ADJUSTL(TEXT)).EQ.'1'
      CALL GET_ENVIRONMENT_VARIABLE('CPPAW_SKALA_SOURCE_BACK_ACC_MIN_ROWS',TEXT,STATUS=STATUS)
      IF(STATUS.EQ.0) THEN
        READ(TEXT,*,IOSTAT=IOS) MINROWS
        IF(IOS.NE.0) MINROWS=4096
        MINROWS=MAX(1,MINROWS)
      END IF
      CALL GET_ENVIRONMENT_VARIABLE('CPPAW_SKALA_SOURCE_BACK_ACC_MB',TEXT,STATUS=STATUS)
      IF(STATUS.EQ.0) THEN
        MB=-1_8
        IOS=1
        IF(LEN_TRIM(TEXT).GT.0.AND.VERIFY(TRIM(ADJUSTL(TEXT)),'0123456789').EQ.0) &
 &        READ(TEXT,*,IOSTAT=IOS) MB
        IF(IOS.NE.0.OR.MB.LT.0_8.OR.MB.GT.HUGE(MB)/1048576_8) THEN
          CALL ERROR$MSG('CPPAW_SKALA_SOURCE_BACK_ACC_MB MUST BE A NONNEGATIVE INTEGER')
          CALL ERROR$STOP('PAW_SKALA_SOURCE_BACK_BATCH')
        END IF
        LIMIT=MB*1048576_8
      END IF
    END IF
    IF(.NOT.ENABLED.OR..NOT.CACHE%READY) RETURN
    IF(GEOMETRY.AND..NOT.CACHE%GEOMETRY) RETURN
    IF(STRESS.AND..NOT.GEOMETRY) RETURN
    IF(SIZE(BAR,1).NE.5.OR.SIZE(BAR,2).NE.2.OR.SIZE(BAR,3).NE.SIZE(CACHE%POINT,1)) RETURN
    IF(ACC_GET_NUM_DEVICES(ACC_DEVICE_NVIDIA).LE.0) RETURN
    N=S%LMNX
    NC=SIZE(CACHE%WAVE,1)
    ! Includes geometry, adjoints, density matrix, output matrix and tile scratch.
    FIXED=8_8*((2_8+TILE)*N*N*S%NDIMD+13_8*TILE)+4_8
    ENTRY=8_8*(INT(NC,8)*N*2_8+18_8)
    DO IP=1,CACHE%LAST
      NE=CACHE%FIRST(IP+1)-1
      PAYLOAD=FIXED+ENTRY*NE+84_8*IP
      IF(PAYLOAD.GT.LIMIT) EXIT
      COVERED=IP
    END DO
    IF(COVERED.LT.MINROWS) THEN
      COVERED=0
      RETURN
    END IF
    NE=CACHE%FIRST(COVERED+1)-1
    IF(NE.EQ.0) THEN
      COVERED=0
      RETURN
    END IF
    DO D=1,S%NDIMD
      DM(:,:,D)=0.5D0*REAL(S%DM(:,:,D)+TRANSPOSE(S%DM(:,:,D)),KIND=8)
    END DO
    CALL SOURCE_BACK_DEVICE(N,NC,S%NDIMD,COVERED,NE,TILE &
 &       ,CACHE%FIRST(1:COVERED+1),CACHE%WAVE(:,:,:,1:NE),CACHE%COREJAC(:,:,1:NE) &
 &       ,CACHE%IMAGE(:,1:NE),DM,BAR(:,:,1:COVERED),GEOMETRY,STRESS &
 &       ,DH,DX,MOMENT,CONTRACTION)
    S%DH(:,:,1:S%NDIMD)=S%DH(:,:,1:S%NDIMD)+DH
#ENDIF
  END SUBROUTINE PAW_SKALA_SOURCE_BACK_BATCH

#IF DEFINED(CPPVAR_OPENACC)
  SUBROUTINE SOURCE_BACK_DEVICE(N,NC,ND,NP,NE,NT,FIRST,WAVE,COREJAC,IMAGE,DM,BAR &
 &                              ,GEOMETRY,STRESS,DH,DX,MOMENT,CONTRACTION)
    INTEGER,INTENT(IN) :: N,NC,ND,NP,NE,NT,FIRST(NP+1)
    REAL(8),INTENT(IN) :: WAVE(NC,N,2,NE),COREJAC(5,3,NE),IMAGE(3,NE)
    REAL(8),INTENT(IN) :: DM(N,N,ND),BAR(5,2,NP)
    LOGICAL,INTENT(IN) :: GEOMETRY,STRESS
    REAL(8),INTENT(OUT) :: DH(N,N,ND),DX(3),MOMENT(3,3),CONTRACTION
    REAL(8) :: ROWDH(N,N,ND,NT),ROWDX(3,NT),ROWMOM(3,3,NT),ROWCON(NT)
    REAL(8) :: KB(5),DC,DG(3),BC,BG(3),DP(3),KERNEL,SGN,C,G(3),V
    INTEGER :: START,COUNT,IT,IP,E,Q,D,I,J,K,L
    DH=0.D0
    DX=0.D0
    MOMENT=0.D0
    CONTRACTION=0.D0
!$ACC DATA COPYIN(FIRST,WAVE,COREJAC,IMAGE,DM,BAR) &
!$ACC& CREATE(ROWDH,ROWDX,ROWMOM,ROWCON)
    DO START=1,NP,NT
      COUNT=MIN(NT,NP-START+1)
!$ACC PARALLEL LOOP GANG VECTOR &
!$ACC& PRESENT(FIRST,WAVE,COREJAC,IMAGE,DM,BAR,ROWDH,ROWDX,ROWMOM,ROWCON) &
!$ACC& PRIVATE(IP,E,Q,D,I,J,K,L,KB,DC,DG,BC,BG,DP,KERNEL,SGN,C,G,V)
      DO IT=1,COUNT
        IP=START+IT-1
        ROWDH(:,:,:,IT)=0.D0
        ROWDX(:,IT)=0.D0
        ROWMOM(:,:,IT)=0.D0
        ROWCON(IT)=0.D0
        DO E=FIRST(IP),FIRST(IP+1)-1
          DP=0.D0
          DO D=1,ND
            SGN=MERGE(1.D0,-1.D0,D.EQ.1)
            KB=0.5D0*(BAR(:,1,IP)+SGN*BAR(:,2,IP))
            IF(GEOMETRY.AND.D.EQ.1) THEN
              DO K=1,3
                DP(K)=SUM(KB*COREJAC(:,K,E))
              END DO
            END IF
            DO Q=1,2
              SGN=MERGE(1.D0,-1.D0,Q.EQ.1)
              DO I=1,N
                C=WAVE(1,I,Q,E)
                G=WAVE(2:4,I,Q,E)
                DC=0.D0
                DG=0.D0
                DO J=1,N
                  V=SGN*DM(I,J,D)
                  DC=DC+V*WAVE(1,J,Q,E)
                  DG=DG+V*WAVE(2:4,J,Q,E)
                END DO
                ROWCON(IT)=ROWCON(IT)+KB(1)*C*DC+2.D0*SUM(KB(2:4)*G)*DC &
 &                                      +0.5D0*KB(5)*SUM(G*DG)
                IF(GEOMETRY) THEN
                  BC=2.D0*(KB(1)*DC+SUM(KB(2:4)*DG))
                  BG=2.D0*KB(2:4)*DC+KB(5)*DG
                  DO K=1,3
                    DP(K)=DP(K)+BC*G(K)
                    DO L=1,3
                      DP(K)=DP(K)+BG(L)*WAVE(4+L+3*(K-1),I,Q,E)
                    END DO
                  END DO
                END IF
                DO J=I,N
                  KERNEL=KB(1)*C*WAVE(1,J,Q,E) &
 &                      +SUM(KB(2:4)*(G*WAVE(1,J,Q,E)+C*WAVE(2:4,J,Q,E))) &
 &                      +0.5D0*KB(5)*SUM(G*WAVE(2:4,J,Q,E))
                  ROWDH(I,J,D,IT)=ROWDH(I,J,D,IT)+SGN*KERNEL
                  IF(I.NE.J) ROWDH(J,I,D,IT)=ROWDH(J,I,D,IT)+SGN*KERNEL
                END DO
              END DO
            END DO
          END DO
          ROWDX(:,IT)=ROWDX(:,IT)+DP
          IF(STRESS) THEN
            DO K=1,3
              ROWMOM(:,K,IT)=ROWMOM(:,K,IT)+DP*IMAGE(K,E)
            END DO
          END IF
        END DO
      END DO
!$ACC UPDATE SELF(ROWDH(:,:,:,1:COUNT),ROWDX(:,1:COUNT),ROWMOM(:,:,1:COUNT),ROWCON(1:COUNT))
      ! Preserve row order and pre-existing host matrix contents without atomics.
      DO IT=1,COUNT
        DH=DH+ROWDH(:,:,:,IT)
        DX=DX+ROWDX(:,IT)
        MOMENT=MOMENT+ROWMOM(:,:,IT)
        CONTRACTION=CONTRACTION+ROWCON(IT)
      END DO
    END DO
!$ACC END DATA
  END SUBROUTINE SOURCE_BACK_DEVICE
#ENDIF

  FUNCTION PAW_SKALA_SOURCE_CACHE_LIMIT() RESULT(BYTES)
    INTEGER(8) :: BYTES
    INTEGER(8),SAVE :: LIMIT=-1_8
    CHARACTER(128) :: VALUE
    INTEGER :: STATUS,IOS
    IF(LIMIT.LT.0_8) THEN
      LIMIT=256_8
      CALL GET_ENVIRONMENT_VARIABLE('CPPAW_SKALA_SOURCE_CACHE_MB',VALUE,STATUS=STATUS)
      IF(STATUS.NE.1) THEN
        VALUE=ADJUSTL(VALUE)
        IOS=1
        IF(STATUS.EQ.0.AND.LEN_TRIM(VALUE).GT.0) THEN
          IF(VERIFY(TRIM(VALUE),'0123456789').EQ.0) READ(VALUE,*,IOSTAT=IOS) LIMIT
        END IF
        IF(IOS.NE.0.OR.LIMIT.LT.0_8.OR.LIMIT.GT.HUGE(LIMIT)/1048576_8) THEN
          CALL ERROR$MSG('CPPAW_SKALA_SOURCE_CACHE_MB MUST BE A NONNEGATIVE INTEGER')
          CALL ERROR$STOP('PAW_SKALA_SOURCE_CACHE_LIMIT')
        END IF
      END IF
      LIMIT=LIMIT*1048576_8
    END IF
    BYTES=LIMIT
  END FUNCTION PAW_SKALA_SOURCE_CACHE_LIMIT

  FUNCTION PAW_SKALA_SOURCE_CACHE_BYTES(CACHE) RESULT(BYTES)
    TYPE(PAW_SKALA_SOURCE_CACHE),INTENT(IN) :: CACHE
    INTEGER(8) :: BYTES
    BYTES=CACHE%BYTES
  END FUNCTION PAW_SKALA_SOURCE_CACHE_BYTES

  SUBROUTINE SOURCE_CACHE_CLEAR(CACHE)
    TYPE(PAW_SKALA_SOURCE_CACHE),INTENT(OUT) :: CACHE
  END SUBROUTINE SOURCE_CACHE_CLEAR

  LOGICAL FUNCTION SOURCE_CACHE_MATCH(CACHE,S,CELL,AINV,CENTER,X,GEOMETRY)
    TYPE(PAW_SKALA_SOURCE_CACHE),INTENT(IN) :: CACHE
    TYPE(PAW_SKALA_SOURCE),INTENT(IN) :: S
    REAL(8),INTENT(IN) :: CELL(3,3),AINV(3,3),CENTER(3),X(:,:)
    LOGICAL,INTENT(IN) :: GEOMETRY
    SOURCE_CACHE_MATCH=.FALSE.
    IF(.NOT.CACHE%READY) RETURN
    IF(CACHE%GEOMETRY.NEQV.GEOMETRY) RETURN
    IF(SIZE(CACHE%POINT,1).NE.SIZE(X,1)) RETURN
    IF(CACHE%SETUP%NR.NE.S%NR.OR.CACHE%SETUP%LNX.NE.S%LNX &
 &    .OR.CACHE%SETUP%LMNX.NE.S%LMNX.OR.CACHE%SETUP%RCUT.NE.S%RCUT) RETURN
    IF(CACHE%SETUP%BASIS%LMAX.NE.S%BASIS%LMAX &
 &    .OR.CACHE%SETUP%BASIS%NPOLY.NE.S%BASIS%NPOLY &
 &    .OR.CACHE%SETUP%BASIS%LMX.NE.S%BASIS%LMX) RETURN
    IF(ANY(CACHE%CELL.NE.CELL).OR.ANY(CACHE%AINV.NE.AINV) &
 &    .OR.ANY(CACHE%CENTER.NE.CENTER).OR.ANY(CACHE%POINT.NE.X)) RETURN
    ! Only immutable setup data belong to the key, never DM or DH.
    IF(ANY(CACHE%SETUP%LOX.NE.S%LOX).OR.ANY(CACHE%SETUP%R.NE.S%R) &
 &    .OR.ANY(CACHE%SETUP%PHI.NE.S%PHI).OR.ANY(CACHE%SETUP%CORE.NE.S%CORE)) RETURN
    IF(ANY(CACHE%SETUP%BASIS%POWER.NE.S%BASIS%POWER) &
 &    .OR.ANY(CACHE%SETUP%BASIS%COEFF.NE.S%BASIS%COEFF)) RETURN
    SOURCE_CACHE_MATCH=.TRUE.
  END FUNCTION SOURCE_CACHE_MATCH

  SUBROUTINE SOURCE_IMAGE_BOUNDS(S,AINV,CENTER,POINT,LO,HI)
    TYPE(PAW_SKALA_SOURCE),INTENT(IN) :: S
    REAL(8),INTENT(IN) :: AINV(3,3),CENTER(3),POINT(3)
    INTEGER,INTENT(OUT) :: LO(3),HI(3)
    REAL(8) :: F(3),REACH(3)
    INTEGER :: K
    F=MATMUL(AINV,POINT-CENTER)
    DO K=1,3
      REACH(K)=S%RCUT*SQRT(SUM(AINV(K,:)**2))
    END DO
    LO=CEILING(F-REACH)
    HI=FLOOR(F+REACH)
  END SUBROUTINE SOURCE_IMAGE_BOUNDS

  SUBROUTINE PAW_SKALA_SOURCE_CACHE_PREPARE(CACHE,S,CELL,AINV,CENTER,X,GEOMETRY,LIMIT,REUSED)
    ! Call once before each atom block. Images remain in the uncached sum order.
    TYPE(PAW_SKALA_SOURCE_CACHE),INTENT(INOUT) :: CACHE
    TYPE(PAW_SKALA_SOURCE),INTENT(IN) :: S
    REAL(8),INTENT(IN) :: CELL(3,3),AINV(3,3),CENTER(3),X(:,:)
    LOGICAL,INTENT(IN) :: GEOMETRY
    INTEGER(8),INTENT(IN) :: LIMIT
    LOGICAL,INTENT(OUT),OPTIONAL :: REUSED
    INTEGER(8) :: KEYBYTES,ENTRYBYTES,MAXENTRY
    INTEGER :: NP,NC,NE,IP,LO(3),HI(3),N1,N2,N3,IOS,PASS,LAST
    REAL(8) :: IMAGE(3),REL(3)
    IF(PRESENT(REUSED)) REUSED=.FALSE.
    NP=SIZE(X,1)
    IF(CACHE%BYTES.LE.LIMIT) THEN
      IF(SOURCE_CACHE_MATCH(CACHE,S,CELL,AINV,CENTER,X,GEOMETRY)) THEN
        IF(PRESENT(REUSED)) REUSED=.TRUE.
        RETURN
      END IF
    END IF
    CALL SOURCE_CACHE_CLEAR(CACHE)
    NC=MERGE(13,4,GEOMETRY)
    ! Account for all allocated array payloads, including exact setup keys.
    KEYBYTES=(SIZE(S%R,KIND=8)+SIZE(S%PHI,KIND=8)+SIZE(S%CORE,KIND=8) &
 &           +SIZE(S%BASIS%COEFF,KIND=8)+3_8*NP)*(STORAGE_SIZE(0.D0)/8) &
 &          +(SIZE(S%LOX,KIND=8)+SIZE(S%BASIS%POWER,KIND=8)+INT(NP,8)+1_8) &
 &           *(STORAGE_SIZE(0)/8)
    ENTRYBYTES=(2_8*NC*S%LMNX+23_8)*(STORAGE_SIZE(0.D0)/8)
    IF(NP.LE.0.OR.LIMIT.LT.KEYBYTES) RETURN
    MAXENTRY=MIN(INT(HUGE(NE),8)-1_8,(LIMIT-KEYBYTES)/ENTRYBYTES)
    ALLOCATE(CACHE%FIRST(NP+1),STAT=IOS)
    IF(IOS.NE.0) THEN
      CALL SOURCE_CACHE_CLEAR(CACHE)
      RETURN
    END IF
    LAST=NP
    DO PASS=1,2
      NE=0
      POINT_LOOP: DO IP=1,LAST
        CACHE%FIRST(IP)=NE+1
        CALL SOURCE_IMAGE_BOUNDS(S,AINV,CENTER,X(IP,:),LO,HI)
        DO N3=LO(3),HI(3)
          DO N2=LO(2),HI(2)
            DO N1=LO(1),HI(1)
              IMAGE=CENTER+MATMUL(CELL,REAL((/N1,N2,N3/),KIND=8))
              REL=X(IP,:)-IMAGE
              IF(SUM(REL**2).GE.S%RCUT**2) CYCLE
              IF(INT(NE,8).GE.MAXENTRY) THEN
                ! Keep only complete rows. Later rows follow the direct path.
                LAST=IP-1
                NE=CACHE%FIRST(IP)-1
                EXIT POINT_LOOP
              END IF
              NE=NE+1
              IF(PASS.EQ.1) CYCLE
              CACHE%IMAGE(:,NE)=IMAGE
              CALL SOURCE_GEOMETRY(S,REL,GEOMETRY,CACHE%WAVE(:,:,:,NE) &
 &                                 ,CACHE%CORE(:,NE),CACHE%COREJAC(:,:,NE))
            END DO
          END DO
        END DO
      END DO POINT_LOOP
      IF(LAST.EQ.0) THEN
        CALL SOURCE_CACHE_CLEAR(CACHE)
        RETURN
      END IF
      CACHE%FIRST(LAST+1:NP+1)=NE+1
      IF(PASS.EQ.2) EXIT
      ALLOCATE(CACHE%POINT(NP,3),CACHE%IMAGE(3,NE),CACHE%WAVE(NC,S%LMNX,2,NE) &
 &            ,CACHE%CORE(5,NE),CACHE%COREJAC(5,3,NE) &
 &            ,CACHE%SETUP%R(S%NR),CACHE%SETUP%PHI(S%NR,S%LNX,2) &
 &            ,CACHE%SETUP%CORE(S%NR,2),CACHE%SETUP%LOX(S%LNX) &
 &            ,CACHE%SETUP%BASIS%POWER(3,S%BASIS%NPOLY) &
 &            ,CACHE%SETUP%BASIS%COEFF(S%BASIS%NPOLY,S%BASIS%LMX),STAT=IOS)
      IF(IOS.NE.0) THEN
        CALL SOURCE_CACHE_CLEAR(CACHE)
        RETURN
      END IF
    END DO
    CACHE%SETUP%NR=S%NR
    CACHE%SETUP%LNX=S%LNX
    CACHE%SETUP%LMNX=S%LMNX
    CACHE%SETUP%RCUT=S%RCUT
    CACHE%SETUP%LOX=S%LOX
    CACHE%SETUP%R=S%R
    CACHE%SETUP%PHI=S%PHI
    CACHE%SETUP%CORE=S%CORE
    CACHE%SETUP%BASIS%LMAX=S%BASIS%LMAX
    CACHE%SETUP%BASIS%NPOLY=S%BASIS%NPOLY
    CACHE%SETUP%BASIS%LMX=S%BASIS%LMX
    CACHE%SETUP%BASIS%POWER=S%BASIS%POWER
    CACHE%SETUP%BASIS%COEFF=S%BASIS%COEFF
    CACHE%CELL=CELL
    CACHE%AINV=AINV
    CACHE%CENTER=CENTER
    CACHE%POINT=X
    CACHE%GEOMETRY=GEOMETRY
    CACHE%LAST=LAST
    CACHE%BYTES=KEYBYTES+INT(NE,8)*ENTRYBYTES
    CACHE%READY=.TRUE.
  END SUBROUTINE PAW_SKALA_SOURCE_CACHE_PREPARE

  SUBROUTINE SOURCE_CACHE_EVALUATE(CACHE,IP,S,VALUE,BAR,DX,MOMENT,DMCONTRACTION)
    TYPE(PAW_SKALA_SOURCE_CACHE),INTENT(IN) :: CACHE
    INTEGER,INTENT(IN) :: IP
    TYPE(PAW_SKALA_SOURCE),INTENT(INOUT) :: S
    REAL(8),INTENT(OUT) :: VALUE(5,2)
    REAL(8),INTENT(IN),OPTIONAL :: BAR(5,2)
    REAL(8),INTENT(OUT),OPTIONAL :: DX(3),MOMENT(3,3),DMCONTRACTION
    REAL(8) :: V(5,2),D(3),CONTRACTION
    INTEGER :: I,K
    VALUE=0.D0
    IF(PRESENT(DX)) DX=0.D0
    IF(PRESENT(MOMENT)) MOMENT=0.D0
    IF(PRESENT(DMCONTRACTION)) DMCONTRACTION=0.D0
    DO I=CACHE%FIRST(IP),CACHE%FIRST(IP+1)-1
      IF(PRESENT(BAR).AND.(PRESENT(DX).OR.PRESENT(MOMENT))) THEN
        CALL SOURCE_CONTRACT(S,CACHE%WAVE(:,:,:,I),CACHE%CORE(:,I) &
 &                          ,CACHE%COREJAC(:,:,I),V,BAR,D,CONTRACTION)
        IF(PRESENT(DX)) DX=DX+D
        IF(PRESENT(MOMENT)) THEN
          DO K=1,3
            MOMENT(:,K)=MOMENT(:,K)+D*CACHE%IMAGE(K,I)
          END DO
        END IF
      ELSE
        CALL SOURCE_CONTRACT(S,CACHE%WAVE(:,:,:,I),CACHE%CORE(:,I) &
 &                          ,CACHE%COREJAC(:,:,I),V,BAR,DMCONTRACTION=CONTRACTION)
      END IF
      IF(PRESENT(DMCONTRACTION)) DMCONTRACTION=DMCONTRACTION+CONTRACTION
      VALUE=VALUE+V
    END DO
  END SUBROUTINE SOURCE_CACHE_EVALUATE

  SUBROUTINE PAW_SKALA_SOLID_BASIS_INIT(BASIS,LMAX)
    TYPE(PAW_SKALA_SOLID_BASIS),INTENT(INOUT) :: BASIS
    INTEGER(4),INTENT(IN) :: LMAX
    INTEGER(4) :: I,J,K,N,IND

    IF(LMAX.LT.0) THEN
      CALL ERROR$MSG('LMAX MUST NOT BE NEGATIVE')
      CALL ERROR$I4VAL('LMAX',LMAX)
      CALL ERROR$STOP('PAW_SKALA_SOLID_BASIS_INIT')
    END IF
    IF(ALLOCATED(BASIS%POWER)) DEALLOCATE(BASIS%POWER)
    IF(ALLOCATED(BASIS%COEFF)) DEALLOCATE(BASIS%COEFF)
    BASIS%LMAX=LMAX
    BASIS%NPOLY=(LMAX+1)*(LMAX+2)*(LMAX+3)/6
    BASIS%LMX=(LMAX+1)**2
    ALLOCATE(BASIS%POWER(3,BASIS%NPOLY))
    ALLOCATE(BASIS%COEFF(BASIS%NPOLY,BASIS%LMX))
    IND=0
    DO N=0,LMAX
      DO I=0,N
        DO J=0,N-I
          K=N-I-J
          IND=IND+1
          BASIS%POWER(:,IND)=(/I,J,K/)
        END DO
      END DO
    END DO
    CALL SPHERICAL$YLMPOLYNOMIALS(LMAX,BASIS%NPOLY,BASIS%LMX &
   &                             ,BASIS%COEFF)
  END SUBROUTINE PAW_SKALA_SOLID_BASIS_INIT

  SUBROUTINE PAW_SKALA_SOLID_BASIS_EVALUATE(BASIS,R,SOLID,GRAD,HESS)
    TYPE(PAW_SKALA_SOLID_BASIS),INTENT(IN) :: BASIS
    REAL(8),INTENT(IN) :: R(3)
    REAL(8),INTENT(OUT) :: SOLID(BASIS%LMX)
    REAL(8),INTENT(OUT) :: GRAD(3,BASIS%LMX)
    REAL(8),INTENT(OUT),OPTIONAL :: HESS(3,3,BASIS%LMX)
    INTEGER(4) :: I,J,K,IND,LM,A,B,P(3)
    REAL(8) :: C,TERM

    IF(.NOT.ALLOCATED(BASIS%COEFF)) THEN
      CALL ERROR$MSG('SOLID-HARMONIC BASIS HAS NOT BEEN INITIALIZED')
      CALL ERROR$STOP('PAW_SKALA_SOLID_BASIS_EVALUATE')
    END IF
    SOLID(:)=0.D0
    GRAD(:,:)=0.D0
    IF(PRESENT(HESS)) HESS=0.D0
    DO LM=1,BASIS%LMX
      DO IND=1,BASIS%NPOLY
        C=BASIS%COEFF(IND,LM)
        IF(C.EQ.0.D0) CYCLE
        I=BASIS%POWER(1,IND)
        J=BASIS%POWER(2,IND)
        K=BASIS%POWER(3,IND)
        TERM=C*R(1)**I*R(2)**J*R(3)**K
        SOLID(LM)=SOLID(LM)+TERM
        IF(I.GT.0) GRAD(1,LM)=GRAD(1,LM) &
       &                    +C*REAL(I,KIND=8)*R(1)**(I-1)*R(2)**J*R(3)**K
        IF(J.GT.0) GRAD(2,LM)=GRAD(2,LM) &
       &                    +C*REAL(J,KIND=8)*R(1)**I*R(2)**(J-1)*R(3)**K
        IF(K.GT.0) GRAD(3,LM)=GRAD(3,LM) &
       &                    +C*REAL(K,KIND=8)*R(1)**I*R(2)**J*R(3)**(K-1)
        IF(PRESENT(HESS)) THEN
          DO A=1,3
            DO B=1,3
              P=(/I,J,K/)
              TERM=C*P(A)
              P(A)=P(A)-1
              TERM=TERM*P(B)
              P(B)=P(B)-1
              IF(ANY(P.LT.0)) CYCLE
              HESS(A,B,LM)=HESS(A,B,LM)+TERM*PRODUCT(R**P)
            END DO
          END DO
        END IF
      END DO
    END DO
  END SUBROUTINE PAW_SKALA_SOLID_BASIS_EVALUATE

  SUBROUTINE PAW_SKALA_RADIAL_SAMPLE(R,F,X,V,DV,DDV)
    ! One polynomial defines values and both derivatives of the discrete map.
    REAL(8),INTENT(IN) :: R(:),F(:),X
    REAL(8),INTENT(OUT) :: V
    REAL(8),INTENT(OUT),OPTIONAL :: DV,DDV
    INTEGER :: LO,HI,MID,FIRST,I,J,N
    REAL(8) :: SCALE,T,Z(6),L,DL,DDL,DEN
    LOGICAL :: DERIV
    N=SIZE(R)
    IF(N.LT.6.OR.SIZE(F).NE.N) THEN
      CALL ERROR$MSG('SKALA RADIAL INTERPOLATION NEEDS SIX MATCHING NODES')
      CALL ERROR$STOP('PAW_SKALA_RADIAL_SAMPLE')
    END IF
    LO=1
    HI=N
    DO WHILE(HI-LO.GT.1)
      MID=(HI+LO)/2
      IF(R(MID).GT.X) THEN
        HI=MID
      ELSE
        LO=MID
      END IF
    END DO
    FIRST=MAX(1,MIN(N-5,LO-2))
    SCALE=R(FIRST+5)-R(FIRST)
    Z=(R(FIRST:FIRST+5)-R(FIRST))/SCALE
    T=(X-R(FIRST))/SCALE
    DERIV=PRESENT(DV).OR.PRESENT(DDV)
    V=0.D0
    IF(PRESENT(DV)) DV=0.D0
    IF(PRESENT(DDV)) DDV=0.D0
    DO I=1,6
      L=1.D0
      DL=0.D0
      DDL=0.D0
      DEN=1.D0
      DO J=1,6
        IF(I.EQ.J) CYCLE
        IF(PRESENT(DDV)) DDL=DDL*(T-Z(J))+2.D0*DL
        IF(DERIV) DL=DL*(T-Z(J))+L
        L=L*(T-Z(J))
        DEN=DEN*(Z(I)-Z(J))
      END DO
      V=V+F(FIRST+I-1)*L/DEN
      IF(PRESENT(DV)) DV=DV+F(FIRST+I-1)*DL/DEN/SCALE
      IF(PRESENT(DDV)) DDV=DDV+F(FIRST+I-1)*DDL/DEN/SCALE**2
    END DO
  END SUBROUTINE PAW_SKALA_RADIAL_SAMPLE

  SUBROUTINE PAW_SKALA_SOURCE_POINT(S,X,VALUE,BAR,DX,DMCONTRACTION)
    ! All five fields and their adjoints use the same interpolated orbitals.
    TYPE(PAW_SKALA_SOURCE),INTENT(INOUT) :: S
    REAL(8),INTENT(IN) :: X(3)
    REAL(8),INTENT(OUT) :: VALUE(5,2)
    REAL(8),INTENT(IN),OPTIONAL :: BAR(5,2)
    REAL(8),INTENT(OUT),OPTIONAL :: DX(3)
    REAL(8),INTENT(OUT),OPTIONAL :: DMCONTRACTION
    REAL(8) :: WAVE(13,S%LMNX,2),CORE(5),COREJAC(5,3)
    VALUE=0.D0
    IF(PRESENT(DMCONTRACTION)) DMCONTRACTION=0.D0
    IF(PRESENT(DX)) DX=0.D0
    IF(SQRT(SUM(X**2)).GE.S%RCUT) RETURN
    CALL SOURCE_GEOMETRY(S,X,PRESENT(BAR).AND.PRESENT(DX),WAVE,CORE,COREJAC)
    CALL SOURCE_CONTRACT(S,WAVE,CORE,COREJAC,VALUE,BAR,DX,DMCONTRACTION)
  END SUBROUTINE PAW_SKALA_SOURCE_POINT

  SUBROUTINE SOURCE_GEOMETRY(S,X,GEOMETRY,WAVE,CORE,COREJAC)
    TYPE(PAW_SKALA_SOURCE),INTENT(IN) :: S
    REAL(8),INTENT(IN) :: X(3)
    LOGICAL,INTENT(IN) :: GEOMETRY
    REAL(8),INTENT(OUT) :: WAVE(:,:,:),CORE(5),COREJAC(5,3)
    REAL(8),PARAMETER :: Y00=1.D0/SQRT(16.D0*ATAN(1.D0))
    REAL(8) :: R,U(3),F,DF,DDF,A,B,EYE(3,3),H(3,3)
    REAL(8) :: Y(S%BASIS%LMX),GY(3,S%BASIS%LMX),HY(3,3,S%BASIS%LMX)
    INTEGER :: Q,LN,L,IM,LM,LMN,K,ID,JD
    WAVE=0.D0
    CORE=0.D0
    COREJAC=0.D0
    R=SQRT(SUM(X**2))
    IF(R.GE.S%RCUT) RETURN
    ! Radial quadrature never contains a nucleus. Coincident foreign rows
    ! have measure zero but need a deterministic finite limiting direction.
    R=MAX(R,1.D-12)
    U=X/R
    IF(SUM(U**2).LT.0.5D0) U=(/1.D0,0.D0,0.D0/)
    EYE=0.D0
    DO K=1,3
      EYE(K,K)=1.D0
    END DO
    IF(GEOMETRY) THEN
      CALL PAW_SKALA_SOLID_BASIS_EVALUATE(S%BASIS,U,Y,GY,HY)
    ELSE
      CALL PAW_SKALA_SOLID_BASIS_EVALUATE(S%BASIS,U,Y,GY)
    END IF
    DO Q=1,2
      LMN=0
      DO LN=1,S%LNX
        L=S%LOX(LN)
        IF(GEOMETRY) THEN
          CALL PAW_SKALA_RADIAL_SAMPLE(S%R,S%PHI(:,LN,Q),R,F,DF,DDF)
          B=DDF-(2*L+1)*DF/R+L*(L+2)*F/R**2
        ELSE
          CALL PAW_SKALA_RADIAL_SAMPLE(S%R,S%PHI(:,LN,Q),R,F,DF)
        END IF
        A=(DF-L*F/R)/R
        DO IM=1,2*L+1
          LMN=LMN+1
          LM=L*L+IM
          WAVE(1,LMN,Q)=F*Y(LM)
          WAVE(2:4,LMN,Q)=A*R*Y(LM)*U+F/R*GY(:,LM)
          IF(GEOMETRY) THEN
            DO JD=1,3
              DO ID=1,3
                H(ID,JD)=B*Y(LM)*U(ID)*U(JD) &
 &                +A*(Y(LM)*EYE(ID,JD)+U(ID)*GY(JD,LM)+GY(ID,LM)*U(JD)) &
 &                +F/R**2*HY(ID,JD,LM)
              END DO
            END DO
            WAVE(5:13,LMN,Q)=RESHAPE(H,(/9/))
          END IF
        END DO
      END DO
    END DO
    ! CORE(:,1) is AE minus pseudo core density, CORE(:,2) the complete
    ! frozen-core positive tau. The smooth tau contains valence only.
    IF(GEOMETRY) THEN
      CALL PAW_SKALA_RADIAL_SAMPLE(S%R,S%CORE(:,1),R,F,DF,DDF)
    ELSE
      CALL PAW_SKALA_RADIAL_SAMPLE(S%R,S%CORE(:,1),R,F,DF)
    END IF
    CORE(1)=Y00*F
    CORE(2:4)=Y00*DF*U
    IF(GEOMETRY) THEN
      COREJAC(1,:)=Y00*DF*U
      DO K=1,3
        COREJAC(2:4,K)=Y00*((DDF-DF/R)*U*U(K)+DF/R*EYE(:,K))
      END DO
      CALL PAW_SKALA_RADIAL_SAMPLE(S%R,S%CORE(:,2),R,F,DF)
      COREJAC(5,:)=Y00*DF*U
    ELSE
      CALL PAW_SKALA_RADIAL_SAMPLE(S%R,S%CORE(:,2),R,F)
    END IF
    CORE(5)=Y00*F
  END SUBROUTINE SOURCE_GEOMETRY

  SUBROUTINE SOURCE_CONTRACT(S,WAVE,CORE,COREJAC,VALUE,BAR,DX,DMCONTRACTION)
    TYPE(PAW_SKALA_SOURCE),INTENT(INOUT) :: S
    REAL(8),INTENT(IN) :: WAVE(:,:,:),CORE(5),COREJAC(5,3)
    REAL(8),INTENT(OUT) :: VALUE(5,2)
    REAL(8),INTENT(IN),OPTIONAL :: BAR(5,2)
    REAL(8),INTENT(OUT),OPTIONAL :: DX(3),DMCONTRACTION
    REAL(8) :: C(S%LMNX),G(3,S%LMNX),H(3,3,S%LMNX)
    REAL(8) :: FIELD(5,S%NDIMD),KB(5,S%NDIMD),KERNEL(5)
    REAL(8) :: DC(S%LMNX),DG(3,S%LMNX)
    REAL(8) :: BC(S%LMNX),BG(3,S%LMNX)
    REAL(8) :: SGN,SPIN,DM,ADJOINT
    INTEGER :: Q,I,J,D,K
    LOGICAL :: BACK,GEOMETRY
    BACK=PRESENT(BAR)
    GEOMETRY=BACK.AND.PRESENT(DX)
    KB=0.D0
    IF(BACK) THEN
      KB(:,1)=0.5D0*(BAR(:,1)+BAR(:,2))
      IF(S%NDIMD.EQ.2) KB(:,2)=0.5D0*(BAR(:,1)-BAR(:,2))
    END IF
    IF(PRESENT(DX)) DX=0.D0
    FIELD=0.D0
    DO Q=1,2
      SGN=MERGE(1.D0,-1.D0,Q.EQ.1)
      C=WAVE(1,:,Q)
      G=WAVE(2:4,:,Q)
      IF(GEOMETRY) H=RESHAPE(WAVE(5:13,:,Q),SHAPE(H))
      DO D=1,S%NDIMD
        DC=0.D0
        DG=0.D0
        ! Only the real symmetric part contributes to these quadratic fields.
        ! Contract it once, so Hessian work is linear in the partial-wave count.
        DO J=1,S%LMNX
          DO I=1,S%LMNX
            DM=0.5D0*SGN*REAL(S%DM(I,J,D)+S%DM(J,I,D),KIND=8)
            DC(I)=DC(I)+DM*C(J)
            DG(:,I)=DG(:,I)+DM*G(:,J)
          END DO
        END DO
        FIELD(1,D)=FIELD(1,D)+DOT_PRODUCT(C,DC)
        FIELD(2:4,D)=FIELD(2:4,D)+2.D0*MATMUL(G,DC)
        FIELD(5,D)=FIELD(5,D)+0.5D0*SUM(G*DG)
        IF(GEOMETRY) THEN
          ! Pull the model adjoints back to partial-wave values/gradients first.
          ! Only their scalar contraction with spatial derivatives is needed.
          BC=2.D0*(KB(1,D)*DC+MATMUL(TRANSPOSE(DG),KB(2:4,D)))
          DO I=1,S%LMNX
            BG(:,I)=2.D0*KB(2:4,D)*DC(I)+KB(5,D)*DG(:,I)
          END DO
          DO K=1,3
            DX(K)=DX(K)+DOT_PRODUCT(BC,G(K,:))+SUM(BG*H(:,K,:))
          END DO
        END IF
      END DO
      IF(BACK) THEN
        DO J=1,S%LMNX
          ! The real primitive kernel is symmetric, even for complex DM/DH.
          ! Preserve both pre-existing DH entries, which need not be symmetric.
          DO I=1,J
            KERNEL(1)=C(I)*C(J)
            KERNEL(2:4)=G(:,I)*C(J)+C(I)*G(:,J)
            KERNEL(5)=0.5D0*SUM(G(:,I)*G(:,J))
            DO D=1,S%NDIMD
              ADJOINT=SGN*SUM(KB(:,D)*KERNEL)
              S%DH(I,J,D)=S%DH(I,J,D)+ADJOINT
              IF(I.NE.J) S%DH(J,I,D)=S%DH(J,I,D)+ADJOINT
            END DO
          END DO
        END DO
      END IF
    END DO
    IF(PRESENT(DMCONTRACTION)) DMCONTRACTION=SUM(KB*FIELD)
    FIELD(:,1)=FIELD(:,1)+CORE
    IF(GEOMETRY) THEN
      DO K=1,3
        DX(K)=DX(K)+SUM(KB(:,1)*COREJAC(:,K))
      END DO
    END IF
    DO D=1,2
      VALUE(:,D)=0.5D0*FIELD(:,1)
      IF(S%NDIMD.EQ.2) THEN
        SPIN=MERGE(1.D0,-1.D0,D.EQ.1)
        VALUE(:,D)=VALUE(:,D)+0.5D0*SPIN*FIELD(:,2)
      END IF
    END DO
  END SUBROUTINE SOURCE_CONTRACT

  SUBROUTINE PAW_SKALA_SOURCE_IMAGES(S,CELL,AINV,CENTER,POINT,VALUE &
 &                                   ,BAR,DX,MOMENT,DMCONTRACTION,CACHE,IP,HIT)
    TYPE(PAW_SKALA_SOURCE),INTENT(INOUT) :: S
    REAL(8),INTENT(IN) :: CELL(3,3),AINV(3,3),CENTER(3),POINT(3)
    REAL(8),INTENT(OUT) :: VALUE(5,2)
    REAL(8),INTENT(IN),OPTIONAL :: BAR(5,2)
    REAL(8),INTENT(OUT),OPTIONAL :: DX(3),MOMENT(3,3)
    REAL(8),INTENT(OUT),OPTIONAL :: DMCONTRACTION
    TYPE(PAW_SKALA_SOURCE_CACHE),INTENT(IN),OPTIONAL :: CACHE
    INTEGER,INTENT(IN),OPTIONAL :: IP
    LOGICAL,INTENT(OUT),OPTIONAL :: HIT
    REAL(8) :: IMAGE(3),REL(3),V(5,2),D(3),CONTRACTION
    INTEGER :: LO(3),HI(3),N1,N2,N3,K
    IF(PRESENT(HIT)) HIT=.FALSE.
    IF(PRESENT(CACHE).AND.PRESENT(IP)) THEN
      IF(CACHE%READY) THEN
        IF(IP.GE.1.AND.IP.LE.CACHE%LAST) THEN
          IF(ALL(CACHE%POINT(IP,:).EQ.POINT).AND.ALL(CACHE%CELL.EQ.CELL) &
 &           .AND.ALL(CACHE%AINV.EQ.AINV).AND.ALL(CACHE%CENTER.EQ.CENTER) &
 &           .AND.(CACHE%GEOMETRY.OR..NOT.(PRESENT(BAR).AND.(PRESENT(DX).OR.PRESENT(MOMENT))))) THEN
            CALL SOURCE_CACHE_EVALUATE(CACHE,IP,S,VALUE,BAR,DX,MOMENT,DMCONTRACTION)
            IF(PRESENT(HIT)) HIT=.TRUE.
            RETURN
          END IF
        END IF
      END IF
    END IF
    VALUE=0.D0
    IF(PRESENT(DMCONTRACTION)) DMCONTRACTION=0.D0
    IF(PRESENT(DX)) DX=0.D0
    IF(PRESENT(MOMENT)) MOMENT=0.D0
    CALL SOURCE_IMAGE_BOUNDS(S,AINV,CENTER,POINT,LO,HI)
    DO N3=LO(3),HI(3)
      DO N2=LO(2),HI(2)
        DO N1=LO(1),HI(1)
          IMAGE=CENTER+MATMUL(CELL,REAL((/N1,N2,N3/),KIND=8))
          REL=POINT-IMAGE
          IF(SUM(REL**2).GE.S%RCUT**2) CYCLE
          IF(PRESENT(BAR)) THEN
            IF(PRESENT(DX).OR.PRESENT(MOMENT)) THEN
              CALL PAW_SKALA_SOURCE_POINT(S,REL,V,BAR,D,CONTRACTION)
              IF(PRESENT(DX)) DX=DX+D
              IF(PRESENT(MOMENT)) THEN
                DO K=1,3
                  MOMENT(:,K)=MOMENT(:,K)+D*IMAGE(K)
                END DO
              END IF
            ELSE
              CALL PAW_SKALA_SOURCE_POINT(S,REL,V,BAR,DMCONTRACTION=CONTRACTION)
            END IF
            IF(PRESENT(DMCONTRACTION)) DMCONTRACTION=DMCONTRACTION+CONTRACTION
          ELSE
            CALL PAW_SKALA_SOURCE_POINT(S,REL,V)
          END IF
          VALUE=VALUE+V
        END DO
      END DO
    END DO
  END SUBROUTINE PAW_SKALA_SOURCE_IMAGES

  PURE INTEGER FUNCTION PAW_SKALA_ONECENTER_CHECK_EXACTNESS(REQUEST,LOX) RESULT(EXACTNESS)
    INTEGER,INTENT(IN) :: REQUEST,LOX(:)
    ! Density has degree <= 2*lmax; Cartesian gradient products <= 2*lmax+2.
    ! This cap is only for linear one-center checks, never the model quadrature.
    EXACTNESS=MIN(REQUEST,2*MAXVAL(LOX)+2)
  END FUNCTION PAW_SKALA_ONECENTER_CHECK_EXACTNESS

  SUBROUTINE PAW_SKALA_ONECENTER_GRID_SIZE(GID,NR,RCUT,LEBEDEV_L &
 &                                         ,NRUSE,NANG,NPOINT)
    USE PAW_LEBEDEV_MODULE, ONLY: PAW_LEBEDEV_SIZE
    IMPLICIT NONE
    INTEGER(4),INTENT(IN) :: GID,NR,LEBEDEV_L
    REAL(8),INTENT(IN) :: RCUT
    INTEGER(4),INTENT(OUT) :: NRUSE,NANG,NPOINT
    REAL(8) :: R(NR)
    INTEGER(4) :: IR

    IF(RCUT.LE.0.D0) THEN
      CALL ERROR$MSG('ONE-CENTER GRID CUTOFF MUST BE POSITIVE')
      CALL ERROR$R8VAL('RCUT',RCUT)
      CALL ERROR$STOP('PAW_SKALA_ONECENTER_GRID_SIZE')
    END IF
    CALL RADIAL$R(GID,NR,R)
    NRUSE=NR
    DO IR=1,NR
      IF(R(IR).GE.RCUT) THEN
        NRUSE=IR
        EXIT
      END IF
    END DO
    CALL PAW_LEBEDEV_SIZE(LEBEDEV_L,NANG)
    NPOINT=NRUSE*NANG
  END SUBROUTINE PAW_SKALA_ONECENTER_GRID_SIZE

  SUBROUTINE PAW_SKALA_ONECENTER_PRIMITIVES(GID,NR,LNX,LOX,LMNX,NDIMD &
 &                                           ,DENMAT,AEPHI,PSPHI &
 &                                           ,AECORE,PSCORE,RCUT,LEBEDEV_L &
 &                                           ,NPOINT,RELCOORD,WEIGHT &
 &                                           ,AERHO,AEGRAD,AETau &
 &                                           ,PSRHO,PSGRAD,PSTAU)
    USE PAW_LEBEDEV_MODULE, ONLY: PAW_LEBEDEV_GET
    IMPLICIT NONE
    INTEGER(4),INTENT(IN) :: GID,NR,LNX,LOX(LNX),LMNX,NDIMD
    INTEGER(4),INTENT(IN) :: LEBEDEV_L,NPOINT
    COMPLEX(8),INTENT(IN) :: DENMAT(LMNX,LMNX,NDIMD)
    REAL(8),INTENT(IN) :: AEPHI(NR,LNX),PSPHI(NR,LNX)
    REAL(8),INTENT(IN) :: AECORE(NR),PSCORE(NR),RCUT
    REAL(8),INTENT(OUT) :: RELCOORD(NPOINT,3),WEIGHT(NPOINT)
    REAL(8),INTENT(OUT) :: AERHO(NPOINT,2),AEGRAD(NPOINT,3,2)
    REAL(8),INTENT(OUT) :: AETAU(NPOINT,2)
    REAL(8),INTENT(OUT) :: PSRHO(NPOINT,2),PSGRAD(NPOINT,3,2)
    REAL(8),INTENT(OUT) :: PSTAU(NPOINT,2)
    TYPE(PAW_SKALA_SOLID_BASIS) :: BASIS
    REAL(8),PARAMETER :: PI=4.D0*ATAN(1.D0)
    REAL(8),PARAMETER :: Y00=1.D0/SQRT(4.D0*PI)
    REAL(8),ALLOCATABLE :: DRAEPHI(:,:),DRPSPHI(:,:)
    REAL(8),ALLOCATABLE :: DRAECORE(:),DRPSCORE(:)
    REAL(8),ALLOCATABLE :: DIRECTION(:,:),ANGWEIGHT(:),RADWEIGHT(:)
    REAL(8),ALLOCATABLE :: DELTA(:),INTEGRAL(:)
    REAL(8),ALLOCATABLE :: YLM(:),GRADYLM(:,:)
    REAL(8),ALLOCATABLE :: AECHI(:),PSCHI(:)
    REAL(8),ALLOCATABLE :: GAECHI(:,:),GPSCHI(:,:)
    REAL(8),ALLOCATABLE :: RHOAE(:),RHOPS(:),TAUAE(:),TAUPS(:)
    REAL(8),ALLOCATABLE :: GRADAE(:,:),GRADPS(:,:)
    REAL(8) :: R(NR),DREAL,FACTOR
    INTEGER(4) :: NRUSE,NANG,NPOINT1,LMAX,LMX
    INTEGER(4) :: IR,IA,IP,LN,L,IM,LM,LMN,I,J,IDIM,ICART

    IF(NDIMD.NE.1.AND.NDIMD.NE.2) THEN
      CALL ERROR$MSG('SKALA CURRENTLY SUPPORTS ONLY COLLINEAR DENSITIES')
      CALL ERROR$I4VAL('NDIMD',NDIMD)
      CALL ERROR$STOP('PAW_SKALA_ONECENTER_PRIMITIVES')
    END IF
    IF(SUM(2*LOX+1).NE.LMNX) THEN
      CALL ERROR$MSG('PARTIAL-WAVE BASIS SIZE IS INCONSISTENT')
      CALL ERROR$I4VAL('LMNX',LMNX)
      CALL ERROR$I4VAL('EXPECTED',SUM(2*LOX+1))
      CALL ERROR$STOP('PAW_SKALA_ONECENTER_PRIMITIVES')
    END IF
    CALL PAW_SKALA_ONECENTER_GRID_SIZE(GID,NR,RCUT,LEBEDEV_L &
 &                                    ,NRUSE,NANG,NPOINT1)
    IF(NPOINT.NE.NPOINT1) THEN
      CALL ERROR$MSG('ONE-CENTER GRID SIZE IS INCONSISTENT')
      CALL ERROR$I4VAL('NPOINT',NPOINT)
      CALL ERROR$I4VAL('EXPECTED',NPOINT1)
      CALL ERROR$STOP('PAW_SKALA_ONECENTER_PRIMITIVES')
    END IF

    CALL RADIAL$R(GID,NR,R)
    LMAX=MAXVAL(LOX)
    LMX=(LMAX+1)**2
    CALL PAW_SKALA_SOLID_BASIS_INIT(BASIS,LMAX)
    ALLOCATE(DIRECTION(3,NANG),ANGWEIGHT(NANG),RADWEIGHT(NRUSE))
    CALL PAW_LEBEDEV_GET(LEBEDEV_L,NANG,DIRECTION,ANGWEIGHT)
    ALLOCATE(DELTA(NR),INTEGRAL(NR))
    DO IR=1,NRUSE
      DELTA(:)=0.D0
      DELTA(IR)=1.D0
      CALL RADIAL$INTEGRATE(GID,NR,DELTA,INTEGRAL)
      RADWEIGHT(IR)=INTEGRAL(NRUSE)
    END DO
    DEALLOCATE(DELTA,INTEGRAL)

    ALLOCATE(DRAEPHI(NR,LNX),DRPSPHI(NR,LNX))
    DO LN=1,LNX
      CALL RADIAL$DERIVE(GID,NR,AEPHI(:,LN),DRAEPHI(:,LN))
      CALL RADIAL$DERIVE(GID,NR,PSPHI(:,LN),DRPSPHI(:,LN))
    END DO
    ALLOCATE(DRAECORE(NR),DRPSCORE(NR))
    CALL RADIAL$DERIVE(GID,NR,AECORE,DRAECORE)
    CALL RADIAL$DERIVE(GID,NR,PSCORE,DRPSCORE)

    ALLOCATE(YLM(LMX),GRADYLM(3,LMX))
    ALLOCATE(AECHI(LMNX),PSCHI(LMNX))
    ALLOCATE(GAECHI(3,LMNX),GPSCHI(3,LMNX))
    ALLOCATE(RHOAE(NDIMD),RHOPS(NDIMD),TAUAE(NDIMD),TAUPS(NDIMD))
    ALLOCATE(GRADAE(3,NDIMD),GRADPS(3,NDIMD))
    IP=0
    DO IR=1,NRUSE
      DO IA=1,NANG
        IP=IP+1
        RELCOORD(IP,:)=R(IR)*DIRECTION(:,IA)
        WEIGHT(IP)=4.D0*PI*RADWEIGHT(IR)*R(IR)**2*ANGWEIGHT(IA)
        CALL PAW_SKALA_SOLID_BASIS_EVALUATE(BASIS,DIRECTION(:,IA) &
 &                                          ,YLM,GRADYLM)
        LMN=0
        DO LN=1,LNX
          L=LOX(LN)
          DO IM=1,2*L+1
            LMN=LMN+1
            LM=L**2+IM
            AECHI(LMN)=AEPHI(IR,LN)*YLM(LM)
            PSCHI(LMN)=PSPHI(IR,LN)*YLM(LM)
            DO ICART=1,3
              GAECHI(ICART,LMN)=(DRAEPHI(IR,LN) &
 &                     -REAL(L,KIND=8)*AEPHI(IR,LN)/R(IR))*YLM(LM) &
 &                     *DIRECTION(ICART,IA) &
 &                     +AEPHI(IR,LN)/R(IR)*GRADYLM(ICART,LM)
              GPSCHI(ICART,LMN)=(DRPSPHI(IR,LN) &
 &                     -REAL(L,KIND=8)*PSPHI(IR,LN)/R(IR))*YLM(LM) &
 &                     *DIRECTION(ICART,IA) &
 &                     +PSPHI(IR,LN)/R(IR)*GRADYLM(ICART,LM)
            END DO
          END DO
        END DO

        RHOAE(:)=0.D0
        RHOPS(:)=0.D0
        GRADAE(:,:)=0.D0
        GRADPS(:,:)=0.D0
        TAUAE(:)=0.D0
        TAUPS(:)=0.D0
        DO IDIM=1,NDIMD
          DO J=1,LMNX
            DO I=1,LMNX
              DREAL=REAL(DENMAT(I,J,IDIM),KIND=8)
              RHOAE(IDIM)=RHOAE(IDIM)+DREAL*AECHI(I)*AECHI(J)
              RHOPS(IDIM)=RHOPS(IDIM)+DREAL*PSCHI(I)*PSCHI(J)
              GRADAE(:,IDIM)=GRADAE(:,IDIM)+DREAL &
 &                  *(GAECHI(:,I)*AECHI(J)+AECHI(I)*GAECHI(:,J))
              GRADPS(:,IDIM)=GRADPS(:,IDIM)+DREAL &
 &                  *(GPSCHI(:,I)*PSCHI(J)+PSCHI(I)*GPSCHI(:,J))
              TAUAE(IDIM)=TAUAE(IDIM)+0.5D0*DREAL &
 &                                         *DOT_PRODUCT(GAECHI(:,I),GAECHI(:,J))
              TAUPS(IDIM)=TAUPS(IDIM)+0.5D0*DREAL &
 &                                         *DOT_PRODUCT(GPSCHI(:,I),GPSCHI(:,J))
            END DO
          END DO
        END DO
        RHOAE(1)=RHOAE(1)+AECORE(IR)*Y00
        RHOPS(1)=RHOPS(1)+PSCORE(IR)*Y00
        GRADAE(:,1)=GRADAE(:,1)+DRAECORE(IR)*Y00*DIRECTION(:,IA)
        GRADPS(:,1)=GRADPS(:,1)+DRPSCORE(IR)*Y00*DIRECTION(:,IA)

        IF(NDIMD.EQ.1) THEN
          AERHO(IP,1)=0.5D0*RHOAE(1)
          AERHO(IP,2)=AERHO(IP,1)
          PSRHO(IP,1)=0.5D0*RHOPS(1)
          PSRHO(IP,2)=PSRHO(IP,1)
          AEGRAD(IP,:,1)=0.5D0*GRADAE(:,1)
          AEGRAD(IP,:,2)=AEGRAD(IP,:,1)
          PSGRAD(IP,:,1)=0.5D0*GRADPS(:,1)
          PSGRAD(IP,:,2)=PSGRAD(IP,:,1)
          AETAU(IP,1)=0.5D0*TAUAE(1)
          AETAU(IP,2)=AETAU(IP,1)
          PSTAU(IP,1)=0.5D0*TAUPS(1)
          PSTAU(IP,2)=PSTAU(IP,1)
        ELSE
          DO IDIM=1,2
            FACTOR=MERGE(1.D0,-1.D0,IDIM.EQ.1)
            AERHO(IP,IDIM)=0.5D0*(RHOAE(1)+FACTOR*RHOAE(2))
            PSRHO(IP,IDIM)=0.5D0*(RHOPS(1)+FACTOR*RHOPS(2))
            AEGRAD(IP,:,IDIM)=0.5D0*(GRADAE(:,1)+FACTOR*GRADAE(:,2))
            PSGRAD(IP,:,IDIM)=0.5D0*(GRADPS(:,1)+FACTOR*GRADPS(:,2))
            AETAU(IP,IDIM)=0.5D0*(TAUAE(1)+FACTOR*TAUAE(2))
            PSTAU(IP,IDIM)=0.5D0*(TAUPS(1)+FACTOR*TAUPS(2))
          END DO
        END IF
      END DO
    END DO

    DEALLOCATE(DIRECTION,ANGWEIGHT,RADWEIGHT,DRAEPHI,DRPSPHI)
    DEALLOCATE(DRAECORE,DRPSCORE,YLM,GRADYLM,AECHI,PSCHI)
    DEALLOCATE(GAECHI,GPSCHI,RHOAE,RHOPS,TAUAE,TAUPS,GRADAE,GRADPS)
  END SUBROUTINE PAW_SKALA_ONECENTER_PRIMITIVES

  SUBROUTINE PAW_SKALA_ONECENTER_POINTS(GID,NR,LNX,LOX,LMNX,NDIMD &
 &                                      ,DENMAT,AEPHI,PSPHI,AECORE,PSCORE &
 &                                      ,RCUT,NPOINT,RELCOORD &
 &                                      ,AERHO,AEGRAD,AETAU &
 &                                      ,PSRHO,PSGRAD,PSTAU)
    IMPLICIT NONE
    INTEGER(4),INTENT(IN) :: GID,NR,LNX,LOX(LNX),LMNX,NDIMD,NPOINT
    COMPLEX(8),INTENT(IN) :: DENMAT(LMNX,LMNX,NDIMD)
    REAL(8),INTENT(IN) :: AEPHI(NR,LNX),PSPHI(NR,LNX)
    REAL(8),INTENT(IN) :: AECORE(NR),PSCORE(NR),RCUT
    REAL(8),INTENT(IN) :: RELCOORD(NPOINT,3)
    REAL(8),INTENT(OUT) :: AERHO(NPOINT,2),AEGRAD(NPOINT,3,2)
    REAL(8),INTENT(OUT) :: AETAU(NPOINT,2)
    REAL(8),INTENT(OUT) :: PSRHO(NPOINT,2),PSGRAD(NPOINT,3,2)
    REAL(8),INTENT(OUT) :: PSTAU(NPOINT,2)
    TYPE(PAW_SKALA_SOLID_BASIS) :: BASIS
    REAL(8),PARAMETER :: PI=4.D0*ATAN(1.D0)
    REAL(8),PARAMETER :: Y00=1.D0/SQRT(4.D0*PI)
    REAL(8),ALLOCATABLE :: DRAEPHI(:,:),DRPSPHI(:,:)
    REAL(8),ALLOCATABLE :: DRAECORE(:),DRPSCORE(:)
    REAL(8),ALLOCATABLE :: YLM(:),GRADYLM(:,:)
    REAL(8),ALLOCATABLE :: AECHI(:),PSCHI(:)
    REAL(8),ALLOCATABLE :: GAECHI(:,:),GPSCHI(:,:)
    REAL(8),ALLOCATABLE :: RHOAE(:),RHOPS(:),TAUAE(:),TAUPS(:)
    REAL(8),ALLOCATABLE :: GRADAE(:,:),GRADPS(:,:)
    REAL(8) :: RGRID(NR),DIRECTION(3),RADIUS,RSAMPLE,DREAL,FACTOR
    REAL(8) :: AEPHIVAL(LNX),PSPHIVAL(LNX)
    REAL(8) :: DRAEPHIVAL(LNX),DRPSPHIVAL(LNX)
    REAL(8) :: AECOREVAL,PSCOREVAL,DRAECOREVAL,DRPSCOREVAL
    INTEGER(4) :: LMAX,LMX,IP,LN,L,IM,LM,LMN,I,J,IDIM,ICART

    IF(NDIMD.NE.1.AND.NDIMD.NE.2) THEN
      CALL ERROR$MSG('SKALA CURRENTLY SUPPORTS ONLY COLLINEAR DENSITIES')
      CALL ERROR$I4VAL('NDIMD',NDIMD)
      CALL ERROR$STOP('PAW_SKALA_ONECENTER_POINTS')
    END IF
    IF(SUM(2*LOX+1).NE.LMNX) THEN
      CALL ERROR$MSG('PARTIAL-WAVE BASIS SIZE IS INCONSISTENT')
      CALL ERROR$I4VAL('LMNX',LMNX)
      CALL ERROR$I4VAL('EXPECTED',SUM(2*LOX+1))
      CALL ERROR$STOP('PAW_SKALA_ONECENTER_POINTS')
    END IF
    IF(RCUT.LE.0.D0) THEN
      CALL ERROR$MSG('ONE-CENTER CUTOFF MUST BE POSITIVE')
      CALL ERROR$R8VAL('RCUT',RCUT)
      CALL ERROR$STOP('PAW_SKALA_ONECENTER_POINTS')
    END IF

    CALL RADIAL$R(GID,NR,RGRID)
    LMAX=MAXVAL(LOX)
    LMX=(LMAX+1)**2
    CALL PAW_SKALA_SOLID_BASIS_INIT(BASIS,LMAX)
    ALLOCATE(DRAEPHI(NR,LNX),DRPSPHI(NR,LNX))
    DO LN=1,LNX
      CALL RADIAL$DERIVE(GID,NR,AEPHI(:,LN),DRAEPHI(:,LN))
      CALL RADIAL$DERIVE(GID,NR,PSPHI(:,LN),DRPSPHI(:,LN))
    END DO
    ALLOCATE(DRAECORE(NR),DRPSCORE(NR))
    CALL RADIAL$DERIVE(GID,NR,AECORE,DRAECORE)
    CALL RADIAL$DERIVE(GID,NR,PSCORE,DRPSCORE)
    ALLOCATE(YLM(LMX),GRADYLM(3,LMX))
    ALLOCATE(AECHI(LMNX),PSCHI(LMNX))
    ALLOCATE(GAECHI(3,LMNX),GPSCHI(3,LMNX))
    ALLOCATE(RHOAE(NDIMD),RHOPS(NDIMD),TAUAE(NDIMD),TAUPS(NDIMD))
    ALLOCATE(GRADAE(3,NDIMD),GRADPS(3,NDIMD))

    AERHO=0.D0
    PSRHO=0.D0
    AEGRAD=0.D0
    PSGRAD=0.D0
    AETAU=0.D0
    PSTAU=0.D0
    DO IP=1,NPOINT
      RADIUS=SQRT(DOT_PRODUCT(RELCOORD(IP,:),RELCOORD(IP,:)))
      IF(RADIUS.GT.RCUT) CYCLE
      RSAMPLE=MAX(RADIUS,RGRID(1),1.D-12)
      IF(RADIUS.GT.1.D-14) THEN
        DIRECTION=RELCOORD(IP,:)/RADIUS
      ELSE
        DIRECTION=(/1.D0,0.D0,0.D0/)
      END IF
      DO LN=1,LNX
        CALL RADIAL$VALUE(GID,NR,AEPHI(:,LN),RSAMPLE,AEPHIVAL(LN))
        CALL RADIAL$VALUE(GID,NR,PSPHI(:,LN),RSAMPLE,PSPHIVAL(LN))
        CALL RADIAL$VALUE(GID,NR,DRAEPHI(:,LN),RSAMPLE,DRAEPHIVAL(LN))
        CALL RADIAL$VALUE(GID,NR,DRPSPHI(:,LN),RSAMPLE,DRPSPHIVAL(LN))
      END DO
      CALL RADIAL$VALUE(GID,NR,AECORE,RSAMPLE,AECOREVAL)
      CALL RADIAL$VALUE(GID,NR,PSCORE,RSAMPLE,PSCOREVAL)
      CALL RADIAL$VALUE(GID,NR,DRAECORE,RSAMPLE,DRAECOREVAL)
      CALL RADIAL$VALUE(GID,NR,DRPSCORE,RSAMPLE,DRPSCOREVAL)
      CALL PAW_SKALA_SOLID_BASIS_EVALUATE(BASIS,DIRECTION,YLM,GRADYLM)

      LMN=0
      DO LN=1,LNX
        L=LOX(LN)
        DO IM=1,2*L+1
          LMN=LMN+1
          LM=L**2+IM
          AECHI(LMN)=AEPHIVAL(LN)*YLM(LM)
          PSCHI(LMN)=PSPHIVAL(LN)*YLM(LM)
          DO ICART=1,3
            GAECHI(ICART,LMN)=(DRAEPHIVAL(LN) &
 &                   -REAL(L,KIND=8)*AEPHIVAL(LN)/RSAMPLE)*YLM(LM) &
 &                   *DIRECTION(ICART) &
 &                   +AEPHIVAL(LN)/RSAMPLE*GRADYLM(ICART,LM)
            GPSCHI(ICART,LMN)=(DRPSPHIVAL(LN) &
 &                   -REAL(L,KIND=8)*PSPHIVAL(LN)/RSAMPLE)*YLM(LM) &
 &                   *DIRECTION(ICART) &
 &                   +PSPHIVAL(LN)/RSAMPLE*GRADYLM(ICART,LM)
          END DO
        END DO
      END DO

      RHOAE=0.D0
      RHOPS=0.D0
      GRADAE=0.D0
      GRADPS=0.D0
      TAUAE=0.D0
      TAUPS=0.D0
      DO IDIM=1,NDIMD
        DO J=1,LMNX
          DO I=1,LMNX
            DREAL=REAL(DENMAT(I,J,IDIM),KIND=8)
            RHOAE(IDIM)=RHOAE(IDIM)+DREAL*AECHI(I)*AECHI(J)
            RHOPS(IDIM)=RHOPS(IDIM)+DREAL*PSCHI(I)*PSCHI(J)
            GRADAE(:,IDIM)=GRADAE(:,IDIM)+DREAL &
 &              *(GAECHI(:,I)*AECHI(J)+AECHI(I)*GAECHI(:,J))
            GRADPS(:,IDIM)=GRADPS(:,IDIM)+DREAL &
 &              *(GPSCHI(:,I)*PSCHI(J)+PSCHI(I)*GPSCHI(:,J))
            TAUAE(IDIM)=TAUAE(IDIM)+0.5D0*DREAL &
 &                                     *DOT_PRODUCT(GAECHI(:,I),GAECHI(:,J))
            TAUPS(IDIM)=TAUPS(IDIM)+0.5D0*DREAL &
 &                                     *DOT_PRODUCT(GPSCHI(:,I),GPSCHI(:,J))
          END DO
        END DO
      END DO
      RHOAE(1)=RHOAE(1)+AECOREVAL*Y00
      RHOPS(1)=RHOPS(1)+PSCOREVAL*Y00
      GRADAE(:,1)=GRADAE(:,1)+DRAECOREVAL*Y00*DIRECTION
      GRADPS(:,1)=GRADPS(:,1)+DRPSCOREVAL*Y00*DIRECTION

      IF(NDIMD.EQ.1) THEN
        AERHO(IP,1)=0.5D0*RHOAE(1)
        AERHO(IP,2)=AERHO(IP,1)
        PSRHO(IP,1)=0.5D0*RHOPS(1)
        PSRHO(IP,2)=PSRHO(IP,1)
        AEGRAD(IP,:,1)=0.5D0*GRADAE(:,1)
        AEGRAD(IP,:,2)=AEGRAD(IP,:,1)
        PSGRAD(IP,:,1)=0.5D0*GRADPS(:,1)
        PSGRAD(IP,:,2)=PSGRAD(IP,:,1)
        AETAU(IP,1)=0.5D0*TAUAE(1)
        AETAU(IP,2)=AETAU(IP,1)
        PSTAU(IP,1)=0.5D0*TAUPS(1)
        PSTAU(IP,2)=PSTAU(IP,1)
      ELSE
        DO IDIM=1,2
          FACTOR=MERGE(1.D0,-1.D0,IDIM.EQ.1)
          AERHO(IP,IDIM)=0.5D0*(RHOAE(1)+FACTOR*RHOAE(2))
          PSRHO(IP,IDIM)=0.5D0*(RHOPS(1)+FACTOR*RHOPS(2))
          AEGRAD(IP,:,IDIM)=0.5D0*(GRADAE(:,1)+FACTOR*GRADAE(:,2))
          PSGRAD(IP,:,IDIM)=0.5D0*(GRADPS(:,1)+FACTOR*GRADPS(:,2))
          AETAU(IP,IDIM)=0.5D0*(TAUAE(1)+FACTOR*TAUAE(2))
          PSTAU(IP,IDIM)=0.5D0*(TAUPS(1)+FACTOR*TAUPS(2))
        END DO
      END IF
    END DO

    DEALLOCATE(DRAEPHI,DRPSPHI,DRAECORE,DRPSCORE,YLM,GRADYLM)
    DEALLOCATE(AECHI,PSCHI,GAECHI,GPSCHI,RHOAE,RHOPS,TAUAE,TAUPS)
    DEALLOCATE(GRADAE,GRADPS)
  END SUBROUTINE PAW_SKALA_ONECENTER_POINTS

  SUBROUTINE PAW_SKALA_ONECENTER_ADJOINT_POINTS(GID,NR,LNX,LOX,LMNX &
 &                                              ,NDIMD,AEPHI,PSPHI,RCUT &
 &                                              ,NPOINT,RELCOORD &
 &                                              ,VRHO,VGRAD,VTAU,DHDM)
    IMPLICIT NONE
    INTEGER(4),INTENT(IN) :: GID,NR,LNX,LOX(LNX),LMNX,NDIMD,NPOINT
    REAL(8),INTENT(IN) :: AEPHI(NR,LNX),PSPHI(NR,LNX),RCUT
    REAL(8),INTENT(IN) :: RELCOORD(NPOINT,3)
    REAL(8),INTENT(IN) :: VRHO(NPOINT,2),VGRAD(NPOINT,3,2)
    REAL(8),INTENT(IN) :: VTAU(NPOINT,2)
    COMPLEX(8),INTENT(OUT) :: DHDM(LMNX,LMNX,NDIMD)
    TYPE(PAW_SKALA_SOLID_BASIS) :: BASIS
    REAL(8),ALLOCATABLE :: DRAEPHI(:,:),DRPSPHI(:,:)
    REAL(8),ALLOCATABLE :: YLM(:),GRADYLM(:,:)
    REAL(8),ALLOCATABLE :: AECHI(:),PSCHI(:)
    REAL(8),ALLOCATABLE :: GAECHI(:,:),GPSCHI(:,:)
    REAL(8) :: RGRID(NR),DIRECTION(3),RADIUS,RSAMPLE
    REAL(8) :: AEPHIVAL(LNX),PSPHIVAL(LNX)
    REAL(8) :: DRAEPHIVAL(LNX),DRPSPHIVAL(LNX)
    REAL(8) :: VRHOC(2),VTAUC(2),VGRADC(3,2),FACTOR,VALUE
    INTEGER(4) :: LMAX,LMX,IP,LN,L,IM,LM,LMN,I,J,IDIM,ICART

    IF(NDIMD.NE.1.AND.NDIMD.NE.2) THEN
      CALL ERROR$MSG('SKALA CURRENTLY SUPPORTS ONLY COLLINEAR DENSITIES')
      CALL ERROR$I4VAL('NDIMD',NDIMD)
      CALL ERROR$STOP('PAW_SKALA_ONECENTER_ADJOINT_POINTS')
    END IF
    IF(SUM(2*LOX+1).NE.LMNX) THEN
      CALL ERROR$MSG('PARTIAL-WAVE BASIS SIZE IS INCONSISTENT')
      CALL ERROR$I4VAL('LMNX',LMNX)
      CALL ERROR$I4VAL('EXPECTED',SUM(2*LOX+1))
      CALL ERROR$STOP('PAW_SKALA_ONECENTER_ADJOINT_POINTS')
    END IF

    CALL RADIAL$R(GID,NR,RGRID)
    LMAX=MAXVAL(LOX)
    LMX=(LMAX+1)**2
    CALL PAW_SKALA_SOLID_BASIS_INIT(BASIS,LMAX)
    ALLOCATE(DRAEPHI(NR,LNX),DRPSPHI(NR,LNX))
    DO LN=1,LNX
      CALL RADIAL$DERIVE(GID,NR,AEPHI(:,LN),DRAEPHI(:,LN))
      CALL RADIAL$DERIVE(GID,NR,PSPHI(:,LN),DRPSPHI(:,LN))
    END DO
    ALLOCATE(YLM(LMX),GRADYLM(3,LMX))
    ALLOCATE(AECHI(LMNX),PSCHI(LMNX))
    ALLOCATE(GAECHI(3,LMNX),GPSCHI(3,LMNX))

    DHDM=CMPLX(0.D0,0.D0,KIND=8)
    DO IP=1,NPOINT
      RADIUS=SQRT(DOT_PRODUCT(RELCOORD(IP,:),RELCOORD(IP,:)))
      IF(RADIUS.GT.RCUT) CYCLE
      RSAMPLE=MAX(RADIUS,RGRID(1),1.D-12)
      IF(RADIUS.GT.1.D-14) THEN
        DIRECTION=RELCOORD(IP,:)/RADIUS
      ELSE
        DIRECTION=(/1.D0,0.D0,0.D0/)
      END IF
      DO LN=1,LNX
        CALL RADIAL$VALUE(GID,NR,AEPHI(:,LN),RSAMPLE,AEPHIVAL(LN))
        CALL RADIAL$VALUE(GID,NR,PSPHI(:,LN),RSAMPLE,PSPHIVAL(LN))
        CALL RADIAL$VALUE(GID,NR,DRAEPHI(:,LN),RSAMPLE,DRAEPHIVAL(LN))
        CALL RADIAL$VALUE(GID,NR,DRPSPHI(:,LN),RSAMPLE,DRPSPHIVAL(LN))
      END DO
      CALL PAW_SKALA_SOLID_BASIS_EVALUATE(BASIS,DIRECTION,YLM,GRADYLM)
      LMN=0
      DO LN=1,LNX
        L=LOX(LN)
        DO IM=1,2*L+1
          LMN=LMN+1
          LM=L**2+IM
          AECHI(LMN)=AEPHIVAL(LN)*YLM(LM)
          PSCHI(LMN)=PSPHIVAL(LN)*YLM(LM)
          DO ICART=1,3
            GAECHI(ICART,LMN)=(DRAEPHIVAL(LN) &
 &                   -REAL(L,KIND=8)*AEPHIVAL(LN)/RSAMPLE)*YLM(LM) &
 &                   *DIRECTION(ICART) &
 &                   +AEPHIVAL(LN)/RSAMPLE*GRADYLM(ICART,LM)
            GPSCHI(ICART,LMN)=(DRPSPHIVAL(LN) &
 &                   -REAL(L,KIND=8)*PSPHIVAL(LN)/RSAMPLE)*YLM(LM) &
 &                   *DIRECTION(ICART) &
 &                   +PSPHIVAL(LN)/RSAMPLE*GRADYLM(ICART,LM)
          END DO
        END DO
      END DO

      VRHOC(1)=0.5D0*(VRHO(IP,1)+VRHO(IP,2))
      VTAUC(1)=0.5D0*(VTAU(IP,1)+VTAU(IP,2))
      VGRADC(:,1)=0.5D0*(VGRAD(IP,:,1)+VGRAD(IP,:,2))
      IF(NDIMD.EQ.2) THEN
        VRHOC(2)=0.5D0*(VRHO(IP,1)-VRHO(IP,2))
        VTAUC(2)=0.5D0*(VTAU(IP,1)-VTAU(IP,2))
        VGRADC(:,2)=0.5D0*(VGRAD(IP,:,1)-VGRAD(IP,:,2))
      END IF
      DO IDIM=1,NDIMD
        DO J=1,LMNX
          DO I=1,LMNX
            VALUE=VRHOC(IDIM)*(AECHI(I)*AECHI(J)-PSCHI(I)*PSCHI(J))
            VALUE=VALUE+0.5D0*VTAUC(IDIM) &
 &                       *(DOT_PRODUCT(GAECHI(:,I),GAECHI(:,J)) &
 &                         -DOT_PRODUCT(GPSCHI(:,I),GPSCHI(:,J)))
            DO ICART=1,3
              FACTOR=GAECHI(ICART,I)*AECHI(J) &
 &                  +AECHI(I)*GAECHI(ICART,J) &
 &                  -GPSCHI(ICART,I)*PSCHI(J) &
 &                  -PSCHI(I)*GPSCHI(ICART,J)
              VALUE=VALUE+VGRADC(ICART,IDIM)*FACTOR
            END DO
            DHDM(I,J,IDIM)=DHDM(I,J,IDIM)+CMPLX(VALUE,0.D0,KIND=8)
          END DO
        END DO
      END DO
    END DO

    DEALLOCATE(DRAEPHI,DRPSPHI,YLM,GRADYLM,AECHI,PSCHI,GAECHI,GPSCHI)
  END SUBROUTINE PAW_SKALA_ONECENTER_ADJOINT_POINTS

  SUBROUTINE PAW_SKALA_ONECENTER_REFERENCE(GID,NR,NRUSE,LNX,LOX,LMNX &
 &                                         ,DENMAT,PHI,CORE,TCORE &
 &                                         ,RHOINT,TAUINT,RADIALTAU,SURFACE)
    IMPLICIT NONE
    INTEGER(4),INTENT(IN) :: GID,NR,NRUSE,LNX,LOX(LNX),LMNX
    COMPLEX(8),INTENT(IN) :: DENMAT(LMNX,LMNX)
    REAL(8),INTENT(IN) :: PHI(NR,LNX),CORE(NR)
    LOGICAL(4),INTENT(IN) :: TCORE
    REAL(8),INTENT(OUT) :: RHOINT,TAUINT
    REAL(8),INTENT(OUT),OPTIONAL :: RADIALTAU(NR),SURFACE(NR)
    REAL(8),PARAMETER :: PI=4.D0*ATAN(1.D0)
    REAL(8) :: R(NR),DRPHI(NR,LNX),WORK(NR),INTEGRAL(NR),DREAL
    INTEGER(4) :: LNOF(LMNX),LOF(LMNX),IMOF(LMNX)
    INTEGER(4) :: LN,L,IM,LMN,I,J

    CALL RADIAL$R(GID,NR,R)
    LMN=0
    DO LN=1,LNX
      L=LOX(LN)
      CALL RADIAL$DERIVE(GID,NR,PHI(:,LN),DRPHI(:,LN))
      DO IM=1,2*L+1
        LMN=LMN+1
        LNOF(LMN)=LN
        LOF(LMN)=L
        IMOF(LMN)=IM
      END DO
    END DO

    WORK(:)=0.D0
    DO J=1,LMNX
      DO I=1,LMNX
        IF(LOF(I).NE.LOF(J).OR.IMOF(I).NE.IMOF(J)) CYCLE
        DREAL=REAL(DENMAT(I,J),KIND=8)
        WORK=WORK+DREAL*PHI(:,LNOF(I))*PHI(:,LNOF(J))*R**2
      END DO
    END DO
    IF(TCORE) WORK=WORK+SQRT(4.D0*PI)*CORE*R**2
    CALL RADIAL$INTEGRATE(GID,NR,WORK,INTEGRAL)
    RHOINT=INTEGRAL(NRUSE)

    WORK(:)=0.D0
    DO J=1,LMNX
      DO I=1,LMNX
        IF(LOF(I).NE.LOF(J).OR.IMOF(I).NE.IMOF(J)) CYCLE
        L=LOF(I)
        DREAL=REAL(DENMAT(I,J),KIND=8)
        WORK=WORK+0.5D0*DREAL*(DRPHI(:,LNOF(I))*DRPHI(:,LNOF(J))*R**2 &
 &                            +REAL(L*(L+1),KIND=8) &
 &                              *PHI(:,LNOF(I))*PHI(:,LNOF(J)))
      END DO
    END DO
    CALL RADIAL$INTEGRATE(GID,NR,WORK,INTEGRAL)
    TAUINT=INTEGRAL(NRUSE)
    IF(PRESENT(RADIALTAU)) RADIALTAU=WORK
    IF(PRESENT(SURFACE)) THEN
      ! Surface term in <phi|-laplacian/2|phi> = integral(tau) - surface.
      SURFACE=0.D0
      DO J=1,LMNX
        DO I=1,LMNX
          IF(LOF(I).NE.LOF(J).OR.IMOF(I).NE.IMOF(J)) CYCLE
          SURFACE=SURFACE+0.5D0*REAL(DENMAT(I,J),KIND=8)*R**2 &
 &                         *PHI(:,LNOF(I))*DRPHI(:,LNOF(J))
        END DO
      END DO
    END IF
  END SUBROUTINE PAW_SKALA_ONECENTER_REFERENCE

  SUBROUTINE PAW_SKALA_PRIMITIVES_TEST(MAXERROR)
    USE PAW_LEBEDEV_MODULE, ONLY: PAW_LEBEDEV_TEST
    IMPLICIT NONE
    REAL(8),INTENT(OUT) :: MAXERROR
    TYPE(PAW_SKALA_SOLID_BASIS) :: BASIS
    INTEGER(4),PARAMETER :: LMAX=4
    INTEGER(4),PARAMETER :: LMX=(LMAX+1)**2
    REAL(8),PARAMETER :: EPS=1.D-6
    REAL(8) :: R(3),RP(3),RM(3),YLM(LMX),YLMP(LMX),YLMM(LMX)
    REAL(8) :: SOLID(LMX),GRAD(3,LMX),REFERENCE,NUMERICAL
    REAL(8) :: RNORM,ERR
    INTEGER(4) :: IDIM,L,LM

    CALL PAW_LEBEDEV_TEST(MAXERROR)
    CALL PAW_SKALA_SOLID_BASIS_INIT(BASIS,LMAX)
    R=(/0.31D0,-0.47D0,0.825D0/)
    CALL PAW_SKALA_SOLID_BASIS_EVALUATE(BASIS,R,SOLID,GRAD)
    CALL SPHERICAL$YLM(LMX,R,YLM)
    RNORM=SQRT(SUM(R**2))
    DO LM=1,LMX
      L=INT(SQRT(REAL(LM-1,KIND=8)))
      REFERENCE=RNORM**L*YLM(LM)
      MAXERROR=MAX(MAXERROR,ABS(SOLID(LM)-REFERENCE))
      DO IDIM=1,3
        RP=R
        RM=R
        RP(IDIM)=RP(IDIM)+EPS
        RM(IDIM)=RM(IDIM)-EPS
        CALL SPHERICAL$YLM(LMX,RP,YLMP)
        CALL SPHERICAL$YLM(LMX,RM,YLMM)
        NUMERICAL=(SQRT(SUM(RP**2))**L*YLMP(LM) &
       &          -SQRT(SUM(RM**2))**L*YLMM(LM))/(2.D0*EPS)
        ERR=ABS(GRAD(IDIM,LM)-NUMERICAL)
        MAXERROR=MAX(MAXERROR,ERR)
      END DO
    END DO
    CALL PAW_SKALA_ONECENTER_TEST(MAXERROR)
    CALL ONECENTER_CHECK_QUADRATURE_TEST(MAXERROR)
    CALL SOURCE_CONTRACT_TEST(MAXERROR)
  END SUBROUTINE PAW_SKALA_PRIMITIVES_TEST

  SUBROUTINE ONECENTER_CHECK_QUADRATURE_TEST(MAXERROR)
    REAL(8),INTENT(INOUT) :: MAXERROR
    INTEGER,PARAMETER :: NR=64
    INTEGER :: GID,LMAX,LNX,N,L,I,J,Q,NRUSE,NANG,NP,EXACTNESS,SPIN
    INTEGER,ALLOCATABLE :: LOX(:)
    REAL(8) :: R(NR),AECORE(NR),PSCORE(NR),VALUE(4,2,2),E,REF,TAUREF,SGN
    REAL(8),ALLOCATABLE :: AE(:,:),PS(:,:),X(:,:),W(:)
    REAL(8),ALLOCATABLE :: AR(:,:),PR(:,:),AG(:,:,:),PG(:,:,:),AT(:,:),PT(:,:)
    COMPLEX(8),ALLOCATABLE :: DM(:,:,:)
    CALL RADIAL$NEW('SHLOG',GID)
    CALL RADIAL$SETR8(GID,'R1',0.03D0)
    CALL RADIAL$SETR8(GID,'DEX',0.12D0)
    CALL RADIAL$SETI4(GID,'NR',NR)
    CALL RADIAL$R(GID,NR,R)
    AECORE=0.04D0*EXP(-2.D0*R**2)
    PSCORE=0.03D0*EXP(-1.6D0*R**2)
    E=0.D0
    DO LMAX=0,4
      LNX=LMAX+1
      N=LNX**2
      ALLOCATE(LOX(LNX),AE(NR,LNX),PS(NR,LNX),DM(N,N,2))
      DO L=0,LMAX
        LOX(L+1)=L
        AE(:,L+1)=(R/3.D0)**L*EXP(-R)
        PS(:,L+1)=(R/3.D0)**L*EXP(-1.1D0*R)
      END DO
      DO I=1,N
        DO J=1,N
          DM(I,J,1)=CMPLX(0.01D0*COS(REAL(I+J,8))/REAL(I+J,8) &
 &                       ,0.001D0*SIN(REAL(I-J,8)),KIND=8)
          IF(I.EQ.J) DM(I,J,1)=DM(I,J,1)+1.D0/REAL(I+1,8)
          DM(I,J,2)=0.1D0*DM(I,J,1)
        END DO
      END DO
      IF(PAW_SKALA_ONECENTER_CHECK_EXACTNESS(1,LOX).NE.1) THEN
        CALL ERROR$MSG('ONE-CENTER CHECK MUST PRESERVE AN UNDERRESOLVED REQUEST')
        CALL ERROR$STOP('ONECENTER_CHECK_QUADRATURE_TEST')
      END IF
      DO Q=1,2
        EXACTNESS=65
        IF(Q.EQ.1) EXACTNESS=PAW_SKALA_ONECENTER_CHECK_EXACTNESS(EXACTNESS,LOX)
        CALL PAW_SKALA_ONECENTER_GRID_SIZE(GID,NR,3.5D0,EXACTNESS,NRUSE,NANG,NP)
        ALLOCATE(X(NP,3),W(NP),AR(NP,2),PR(NP,2),AG(NP,3,2),PG(NP,3,2),AT(NP,2),PT(NP,2))
        CALL PAW_SKALA_ONECENTER_PRIMITIVES(GID,NR,LNX,LOX,N,2,DM,AE,PS,AECORE,PSCORE &
 &                                        ,3.5D0,EXACTNESS,NP,X,W,AR,AG,AT,PR,PG,PT)
        DO SPIN=1,2
          SGN=MERGE(1.D0,-1.D0,SPIN.EQ.1)
          VALUE(1,SPIN,Q)=SUM(W*(AR(:,1)+SGN*AR(:,2)))
          VALUE(2,SPIN,Q)=SUM(W*(PR(:,1)+SGN*PR(:,2)))
          VALUE(3,SPIN,Q)=SUM(W*(AT(:,1)+SGN*AT(:,2)))
          VALUE(4,SPIN,Q)=SUM(W*(PT(:,1)+SGN*PT(:,2)))
          CALL PAW_SKALA_ONECENTER_REFERENCE(GID,NR,NRUSE,LNX,LOX,N,DM(:,:,SPIN),AE,AECORE &
 &                                          ,SPIN.EQ.1,REF,TAUREF)
          E=MAX(E,ABS(VALUE(1,SPIN,Q)-REF),ABS(VALUE(3,SPIN,Q)-TAUREF))
          CALL PAW_SKALA_ONECENTER_REFERENCE(GID,NR,NRUSE,LNX,LOX,N,DM(:,:,SPIN),PS,PSCORE &
 &                                          ,SPIN.EQ.1,REF,TAUREF)
          E=MAX(E,ABS(VALUE(2,SPIN,Q)-REF),ABS(VALUE(4,SPIN,Q)-TAUREF))
        END DO
        DEALLOCATE(X,W,AR,PR,AG,PG,AT,PT)
      END DO
      E=MAX(E,MAXVAL(ABS(VALUE(:,:,1)-VALUE(:,:,2))))
      DEALLOCATE(LOX,AE,PS,DM)
    END DO
    WRITE(*,'(A,ES24.14)') 'ONE-CENTER CAPPED QUADRATURE ERROR ',E
    IF(.NOT.(E.LE.1.D-11)) THEN
      CALL ERROR$MSG('CAPPED ONE-CENTER CHECK DISAGREES WITH FULL RULE OR RADIAL REFERENCE')
      CALL ERROR$STOP('ONECENTER_CHECK_QUADRATURE_TEST')
    END IF
    MAXERROR=MAX(MAXERROR,E)
  END SUBROUTINE ONECENTER_CHECK_QUADRATURE_TEST

  SUBROUTINE SOURCE_CONTRACT_TEST(MAXERROR)
    REAL(8),INTENT(INOUT) :: MAXERROR
    TYPE(PAW_SKALA_SOURCE) :: S
    REAL(8),ALLOCATABLE :: WAVE(:,:,:),C(:),G(:,:),H(:,:,:)
    COMPLEX(8),ALLOCATABLE :: DH(:,:,:),INITIAL(:,:,:)
    REAL(8) :: CORE(5),COREJAC(5,3),BAR(5,2),KB(5,2),FIELD(5,2)
    REAL(8) :: VALUE(5,2),REFERENCE(5,2),DX(3),DR(3),CONTRACTION,CR
    REAL(8) :: KERNEL(5),JAC(5,3),SGN,DM,E
    INTEGER :: N,NSPIN,MODE,Q,I,J,D,K
    E=0.D0
    DO N=1,11,5
      S%LMNX=N
      ALLOCATE(WAVE(13,N,2),C(N),G(3,N),H(3,3,N))
      ALLOCATE(S%DM(N,N,2),S%DH(N,N,2),DH(N,N,2),INITIAL(N,N,2))
      DO D=1,2
        DO I=1,5
          CORE(I)=SIN(REAL(I,KIND=8))*0.1D0
          BAR(I,D)=COS(REAL(I+2*D,KIND=8))
          DO K=1,3
            COREJAC(I,K)=COS(REAL(I+K,KIND=8))*0.1D0
          END DO
        END DO
        DO J=1,N
          DO I=1,13
            WAVE(I,J,D)=SIN(REAL(I+3*J+2*D,KIND=8))*0.1D0
          END DO
          DO I=1,N
            ! Deliberately nonsymmetric and complex to test the exact contraction.
            S%DM(I,J,D)=CMPLX(SIN(REAL(I+2*J+D,KIND=8)),0.03D0*(I-J),KIND=8)
            INITIAL(I,J,D)=CMPLX(0.01D0*(I+2*J),0.02D0*(I-J),KIND=8)
          END DO
        END DO
      END DO
      DO NSPIN=1,2
        S%NDIMD=NSPIN
        KB(:,1)=0.5D0*(BAR(:,1)+BAR(:,2))
        KB(:,2)=0.5D0*(BAR(:,1)-BAR(:,2))
        FIELD=0.D0
        DR=0.D0
        DH=INITIAL
        DO Q=1,2
          SGN=MERGE(1.D0,-1.D0,Q.EQ.1)
          C=WAVE(1,:,Q)
          G=WAVE(2:4,:,Q)
          H=RESHAPE(WAVE(5:13,:,Q),SHAPE(H))
          DO J=1,N
            DO I=1,N
              KERNEL(1)=C(I)*C(J)
              KERNEL(2:4)=G(:,I)*C(J)+C(I)*G(:,J)
              KERNEL(5)=0.5D0*SUM(G(:,I)*G(:,J))
              JAC(1,:)=KERNEL(2:4)
              DO K=1,3
                JAC(2:4,K)=H(:,K,I)*C(J)+G(:,I)*G(K,J) &
 &                         +G(K,I)*G(:,J)+C(I)*H(:,K,J)
                JAC(5,K)=0.5D0*SUM(H(:,K,I)*G(:,J)+G(:,I)*H(:,K,J))
              END DO
              DO D=1,NSPIN
                DM=SGN*REAL(S%DM(I,J,D),KIND=8)
                FIELD(:,D)=FIELD(:,D)+DM*KERNEL
                DH(I,J,D)=DH(I,J,D)+SGN*SUM(KB(:,D)*KERNEL)
                DO K=1,3
                  DR(K)=DR(K)+DM*SUM(KB(:,D)*JAC(:,K))
                END DO
              END DO
            END DO
          END DO
        END DO
        CR=SUM(KB(:,1:NSPIN)*FIELD(:,1:NSPIN))
        FIELD(:,1)=FIELD(:,1)+CORE
        DO K=1,3
          DR(K)=DR(K)+SUM(KB(:,1)*COREJAC(:,K))
        END DO
        REFERENCE(:,1)=0.5D0*FIELD(:,1)
        REFERENCE(:,2)=REFERENCE(:,1)
        IF(NSPIN.EQ.2) THEN
          REFERENCE(:,1)=REFERENCE(:,1)+0.5D0*FIELD(:,2)
          REFERENCE(:,2)=REFERENCE(:,2)-0.5D0*FIELD(:,2)
        END IF
        DO MODE=1,3
          S%DH=INITIAL
          IF(MODE.EQ.1) THEN
            CALL SOURCE_CONTRACT(S,WAVE,CORE,COREJAC,VALUE,DX=DX)
            E=MAX(E,MAXVAL(ABS(DX)),MAXVAL(ABS(S%DH-INITIAL)))
          ELSE IF(MODE.EQ.2) THEN
            CALL SOURCE_CONTRACT(S,WAVE(1:4,:,:),CORE,COREJAC,VALUE,BAR &
 &                              ,DMCONTRACTION=CONTRACTION)
            E=MAX(E,ABS(CONTRACTION-CR),MAXVAL(ABS(S%DH-DH)))
          ELSE
            CALL SOURCE_CONTRACT(S,WAVE,CORE,COREJAC,VALUE,BAR,DX,CONTRACTION)
            E=MAX(E,ABS(CONTRACTION-CR),MAXVAL(ABS(DX-DR)),MAXVAL(ABS(S%DH-DH)))
          END IF
          E=MAX(E,MAXVAL(ABS(VALUE-REFERENCE)))
        END DO
      END DO
      DEALLOCATE(WAVE,C,G,H,S%DM,S%DH,DH,INITIAL)
    END DO
    WRITE(*,'(A,ES24.14)') 'SOURCE FACTORIZED CONTRACTION ERROR ',E
    IF(.NOT.(E.LE.1.D-12)) THEN
      CALL ERROR$MSG('FACTORIZED SOURCE CONTRACTION DISAGREES WITH DIRECT PAIR SUM')
      CALL ERROR$STOP('SOURCE_CONTRACT_TEST')
    END IF
    MAXERROR=MAX(MAXERROR,E)
  END SUBROUTINE SOURCE_CONTRACT_TEST

  SUBROUTINE PAW_SKALA_ONECENTER_TEST(MAXERROR)
    IMPLICIT NONE
    REAL(8),INTENT(INOUT) :: MAXERROR
    INTEGER(4),PARAMETER :: NR=160,LNX=2,LMNX=4,NDIMD=2,LEBEDEV_L=17
    INTEGER(4),PARAMETER :: NTEST=23
    INTEGER(4),PARAMETER :: LOX(LNX)=(/0,1/)
    INTEGER(4) :: GID,NRUSE,NANG,NPOINT,IP,ICART
    REAL(8),PARAMETER :: RCUT=4.D0,EPSDM=1.D-6
    REAL(8) :: R(NR),AEPHI(NR,LNX),PSPHI(NR,LNX)
    REAL(8) :: AECORE(NR),PSCORE(NR)
    COMPLEX(8) :: DENMAT(LMNX,LMNX,NDIMD)
    COMPLEX(8) :: DENMATP(LMNX,LMNX,NDIMD)
    COMPLEX(8) :: DENMATM(LMNX,LMNX,NDIMD)
    COMPLEX(8) :: DHDM(LMNX,LMNX,NDIMD)
    REAL(8) :: DMDIR(LMNX,LMNX,NDIMD)
    REAL(8),ALLOCATABLE :: RELCOORD(:,:),WEIGHT(:)
    REAL(8),ALLOCATABLE :: AERHO(:,:),PSRHO(:,:),AETAU(:,:),PSTAU(:,:)
    REAL(8),ALLOCATABLE :: AEGRAD(:,:,:),PSGRAD(:,:,:)
    REAL(8),ALLOCATABLE :: AERHO1(:,:),PSRHO1(:,:),AETAU1(:,:),PSTAU1(:,:)
    REAL(8),ALLOCATABLE :: AEGRAD1(:,:,:),PSGRAD1(:,:,:)
    REAL(8) :: TESTCOORD(NTEST,3),VRHO(NTEST,2),VTAU(NTEST,2)
    REAL(8) :: VGRAD(NTEST,3,2),TRHOAE(NTEST,2),TRHOPS(NTEST,2)
    REAL(8) :: TTAUAE(NTEST,2),TTAUPS(NTEST,2)
    REAL(8) :: TGRADAE(NTEST,3,2),TGRADPS(NTEST,3,2)
    REAL(8) :: RHOREF,TAUREF,VAL,FPLUS,FMINUS,DERIVFD,DERIVADJ
    REAL(8) :: RADTAU(NR),SURFACE(NR),TAUINT(NR),DRAE(NR,LNX),SURFREF(NR)

    CALL RADIAL$NEW('SHLOG',GID)
    CALL RADIAL$SETR8(GID,'R1',0.01D0)
    CALL RADIAL$SETR8(GID,'DEX',0.04D0)
    CALL RADIAL$SETI4(GID,'NR',NR)
    CALL RADIAL$R(GID,NR,R)
    AEPHI(:,1)=EXP(-R)
    AEPHI(:,2)=R*EXP(-0.7D0*R)
    PSPHI(:,1)=EXP(-1.1D0*R)
    PSPHI(:,2)=R*EXP(-0.8D0*R)
    AECORE=0.4D0*EXP(-2.D0*R**2)
    PSCORE=0.3D0*EXP(-1.6D0*R**2)
    DENMAT(:,:,:)=CMPLX(0.D0,0.D0,KIND=8)
    DENMAT(1,1,1)=CMPLX(1.3D0,0.D0,KIND=8)
    DENMAT(2,2,1)=CMPLX(0.4D0,0.D0,KIND=8)
    DENMAT(3,3,1)=CMPLX(0.6D0,0.D0,KIND=8)
    DENMAT(4,4,1)=CMPLX(0.5D0,0.D0,KIND=8)
    DENMAT(1,3,1)=CMPLX(0.12D0,0.03D0,KIND=8)
    DENMAT(3,1,1)=CONJG(DENMAT(1,3,1))
    DENMAT(1,1,2)=CMPLX(0.2D0,0.D0,KIND=8)
    DENMAT(2,2,2)=CMPLX(-0.1D0,0.D0,KIND=8)
    DENMAT(3,3,2)=CMPLX(0.08D0,0.D0,KIND=8)
    DENMAT(4,4,2)=CMPLX(-0.05D0,0.D0,KIND=8)

    CALL PAW_SKALA_ONECENTER_GRID_SIZE(GID,NR,RCUT,LEBEDEV_L &
 &                                    ,NRUSE,NANG,NPOINT)
    ALLOCATE(RELCOORD(NPOINT,3),WEIGHT(NPOINT))
    ALLOCATE(AERHO(NPOINT,2),PSRHO(NPOINT,2))
    ALLOCATE(AEGRAD(NPOINT,3,2),PSGRAD(NPOINT,3,2))
    ALLOCATE(AETAU(NPOINT,2),PSTAU(NPOINT,2))
    CALL PAW_SKALA_ONECENTER_PRIMITIVES(GID,NR,LNX,LOX,LMNX,NDIMD &
 &                                     ,DENMAT,AEPHI,PSPHI,AECORE,PSCORE &
 &                                     ,RCUT,LEBEDEV_L,NPOINT &
 &                                     ,RELCOORD,WEIGHT,AERHO,AEGRAD,AETAU &
 &                                     ,PSRHO,PSGRAD,PSTAU)

    CALL PAW_SKALA_ONECENTER_REFERENCE(GID,NR,NRUSE,LNX,LOX,LMNX &
 &                                    ,DENMAT(:,:,1),AEPHI,AECORE,.TRUE. &
 &                                    ,RHOREF,TAUREF,RADTAU,SURFACE)
    VAL=SUM(WEIGHT*(AERHO(:,1)+AERHO(:,2)))
    MAXERROR=MAX(MAXERROR,ABS(VAL-RHOREF))
    VAL=SUM(WEIGHT*(AETAU(:,1)+AETAU(:,2)))
    MAXERROR=MAX(MAXERROR,ABS(VAL-TAUREF))
    CALL RADIAL$INTEGRATE(GID,NR,RADTAU,TAUINT)
    MAXERROR=MAX(MAXERROR,ABS(TAUINT(NRUSE)-TAUREF))
    CALL RADIAL$DERIVE(GID,NR,AEPHI(:,1),DRAE(:,1))
    CALL RADIAL$DERIVE(GID,NR,AEPHI(:,2),DRAE(:,2))
    SURFREF=0.5D0*R**2*(1.3D0*AEPHI(:,1)*DRAE(:,1) &
 &                         +1.5D0*AEPHI(:,2)*DRAE(:,2))
    MAXERROR=MAX(MAXERROR,MAXVAL(ABS(SURFACE-SURFREF)))
    CALL PAW_SKALA_ONECENTER_REFERENCE(GID,NR,NRUSE,LNX,LOX,LMNX &
 &                                    ,DENMAT(:,:,2),AEPHI,AECORE,.FALSE. &
 &                                    ,RHOREF,TAUREF)
    VAL=SUM(WEIGHT*(AERHO(:,1)-AERHO(:,2)))
    MAXERROR=MAX(MAXERROR,ABS(VAL-RHOREF))
    VAL=SUM(WEIGHT*(AETAU(:,1)-AETAU(:,2)))
    MAXERROR=MAX(MAXERROR,ABS(VAL-TAUREF))

    CALL PAW_SKALA_ONECENTER_REFERENCE(GID,NR,NRUSE,LNX,LOX,LMNX &
 &                                    ,DENMAT(:,:,1),PSPHI,PSCORE,.TRUE. &
 &                                    ,RHOREF,TAUREF)
    VAL=SUM(WEIGHT*(PSRHO(:,1)+PSRHO(:,2)))
    MAXERROR=MAX(MAXERROR,ABS(VAL-RHOREF))
    VAL=SUM(WEIGHT*(PSTAU(:,1)+PSTAU(:,2)))
    MAXERROR=MAX(MAXERROR,ABS(VAL-TAUREF))
    CALL PAW_SKALA_ONECENTER_REFERENCE(GID,NR,NRUSE,LNX,LOX,LMNX &
 &                                    ,DENMAT(:,:,2),PSPHI,PSCORE,.FALSE. &
 &                                    ,RHOREF,TAUREF)
    VAL=SUM(WEIGHT*(PSRHO(:,1)-PSRHO(:,2)))
    MAXERROR=MAX(MAXERROR,ABS(VAL-RHOREF))
    VAL=SUM(WEIGHT*(PSTAU(:,1)-PSTAU(:,2)))
    MAXERROR=MAX(MAXERROR,ABS(VAL-TAUREF))

    ALLOCATE(AERHO1(NPOINT,2),PSRHO1(NPOINT,2))
    ALLOCATE(AEGRAD1(NPOINT,3,2),PSGRAD1(NPOINT,3,2))
    ALLOCATE(AETAU1(NPOINT,2),PSTAU1(NPOINT,2))
    CALL PAW_SKALA_ONECENTER_POINTS(GID,NR,LNX,LOX,LMNX,NDIMD &
 &                                  ,DENMAT,AEPHI,PSPHI,AECORE,PSCORE &
 &                                  ,R(NRUSE),NPOINT,RELCOORD &
 &                                  ,AERHO1,AEGRAD1,AETAU1 &
 &                                  ,PSRHO1,PSGRAD1,PSTAU1)
    MAXERROR=MAX(MAXERROR,MAXVAL(ABS(AERHO1-AERHO)))
    MAXERROR=MAX(MAXERROR,MAXVAL(ABS(PSRHO1-PSRHO)))
    MAXERROR=MAX(MAXERROR,MAXVAL(ABS(AEGRAD1-AEGRAD)))
    MAXERROR=MAX(MAXERROR,MAXVAL(ABS(PSGRAD1-PSGRAD)))
    MAXERROR=MAX(MAXERROR,MAXVAL(ABS(AETAU1-AETAU)))
    MAXERROR=MAX(MAXERROR,MAXVAL(ABS(PSTAU1-PSTAU)))
    DEALLOCATE(AERHO1,PSRHO1,AEGRAD1,PSGRAD1,AETAU1,PSTAU1)

    DO IP=1,NTEST
      TESTCOORD(IP,:)=RELCOORD(1+(IP-1)*(NPOINT-1)/(NTEST-1),:)
      VRHO(IP,1)=0.17D0+0.013D0*REAL(IP,KIND=8)
      VRHO(IP,2)=-0.11D0+0.007D0*REAL(IP,KIND=8)
      VTAU(IP,1)=-0.08D0+0.009D0*REAL(IP,KIND=8)
      VTAU(IP,2)=0.12D0-0.004D0*REAL(IP,KIND=8)
      DO ICART=1,3
        VGRAD(IP,ICART,1)=0.03D0*REAL(ICART,KIND=8) &
 &                              +0.002D0*REAL(IP,KIND=8)
        VGRAD(IP,ICART,2)=-0.02D0*REAL(ICART,KIND=8) &
 &                              +0.001D0*REAL(IP,KIND=8)
      END DO
    END DO
    DMDIR=0.D0
    DMDIR(1,1,1)=0.31D0
    DMDIR(2,2,1)=-0.19D0
    DMDIR(1,3,1)=0.14D0
    DMDIR(3,1,1)=DMDIR(1,3,1)
    DMDIR(4,4,2)=0.23D0
    DMDIR(2,4,2)=-0.09D0
    DMDIR(4,2,2)=DMDIR(2,4,2)
    DENMATP=DENMAT+CMPLX(EPSDM*DMDIR,0.D0,KIND=8)
    DENMATM=DENMAT-CMPLX(EPSDM*DMDIR,0.D0,KIND=8)
    CALL PAW_SKALA_ONECENTER_POINTS(GID,NR,LNX,LOX,LMNX,NDIMD &
 &                                  ,DENMATP,AEPHI,PSPHI,AECORE,PSCORE &
 &                                  ,RCUT,NTEST,TESTCOORD &
 &                                  ,TRHOAE,TGRADAE,TTAUAE &
 &                                  ,TRHOPS,TGRADPS,TTAUPS)
    FPLUS=SUM(VRHO*(TRHOAE-TRHOPS)) &
 &       +SUM(VGRAD*(TGRADAE-TGRADPS)) &
 &       +SUM(VTAU*(TTAUAE-TTAUPS))
    CALL PAW_SKALA_ONECENTER_POINTS(GID,NR,LNX,LOX,LMNX,NDIMD &
 &                                  ,DENMATM,AEPHI,PSPHI,AECORE,PSCORE &
 &                                  ,RCUT,NTEST,TESTCOORD &
 &                                  ,TRHOAE,TGRADAE,TTAUAE &
 &                                  ,TRHOPS,TGRADPS,TTAUPS)
    FMINUS=SUM(VRHO*(TRHOAE-TRHOPS)) &
 &        +SUM(VGRAD*(TGRADAE-TGRADPS)) &
 &        +SUM(VTAU*(TTAUAE-TTAUPS))
    CALL PAW_SKALA_ONECENTER_ADJOINT_POINTS(GID,NR,LNX,LOX,LMNX &
 &                                          ,NDIMD,AEPHI,PSPHI,RCUT &
 &                                          ,NTEST,TESTCOORD &
 &                                          ,VRHO,VGRAD,VTAU,DHDM)
    DERIVFD=(FPLUS-FMINUS)/(2.D0*EPSDM)
    DERIVADJ=SUM(DMDIR*REAL(DHDM,KIND=8))
    MAXERROR=MAX(MAXERROR,ABS(DERIVFD-DERIVADJ))

    DEALLOCATE(RELCOORD,WEIGHT,AERHO,PSRHO,AEGRAD,PSGRAD,AETAU,PSTAU)
  END SUBROUTINE PAW_SKALA_ONECENTER_TEST

END MODULE PAW_SKALA_PRIMITIVES_MODULE
