! SPDX-License-Identifier: GPL-3.0-or-later

      MODULE PAW_SKALA_MODULE
#IF DEFINED(CPPVAR_SKALA_FTORCH)
      USE PAW_SKALA_BRIDGE, ONLY: PAW_SKALA_MODEL, PAW_SKALA_LOAD &
     &                           ,PAW_SKALA_EVALUATE, PAW_SKALA_RELEASE &
     &                           ,PAW_SKALA_CUDA_AVAILABLE
#ENDIF
      IMPLICIT NONE
#IF DEFINED(CPPVAR_SKALA_FTORCH)
      TYPE(PAW_SKALA_MODEL),SAVE :: MODEL
#ENDIF
      LOGICAL(4),SAVE :: TINITIALIZED=.FALSE.
      LOGICAL(4),SAVE :: TON=.FALSE.
      CHARACTER(2048),SAVE :: CONFIG_MODELFILE=' '
      CHARACTER(16),SAVE :: CONFIG_DEVICE='AUTO'
      INTEGER(4),SAVE :: CONFIG_DEVICEINDEX=-1
      LOGICAL(4),ALLOCATABLE,SAVE :: TONECENTERREPORTED(:)
      LOGICAL(4),SAVE :: TSMOOTHREPORTED=.FALSE.
      LOGICAL(4),SAVE :: TSMOOTHREADY=.FALSE.
      INTEGER(4),SAVE :: SMOOTH_NR1=0,SMOOTH_NR2=0,SMOOTH_NR3=0
      INTEGER(4),SAVE :: SMOOTH_NDIMD=0
      REAL(8),SAVE :: SMOOTH_RBAS(3,3)=0.D0
      REAL(8),ALLOCATABLE,SAVE :: SMOOTH_RHO(:,:,:,:)
      REAL(8),ALLOCATABLE,SAVE :: SMOOTH_GRHO(:,:,:,:,:)
      REAL(8),ALLOCATABLE,SAVE :: SMOOTH_TAU(:,:,:,:)
      REAL(8),SAVE :: FORWARD_ENERGY=0.D0
      REAL(8),SAVE :: FORWARD_ELECTRONS=0.D0
      REAL(8),SAVE :: FORWARD_TAU=0.D0
      REAL(8),SAVE :: FORWARD_SMOOTH_ELECTRONS=0.D0
      REAL(8),SAVE :: FORWARD_CORRECTION_ELECTRONS=0.D0
      REAL(8),SAVE :: FORWARD_SMOOTH_TAU=0.D0
      REAL(8),SAVE :: FORWARD_CORRECTION_TAU=0.D0
      INTEGER(4),SAVE :: FORWARD_NPOINT=0
      LOGICAL(4),SAVE :: TFORWARDREPORTED=.FALSE.
      END MODULE PAW_SKALA_MODULE

!     ..................................................................
      SUBROUTINE SKALA$SETL4(ID,VAL)
      USE PAW_SKALA_MODULE
      IMPLICIT NONE
      CHARACTER(*),INTENT(IN) :: ID
      LOGICAL(4),INTENT(IN)   :: VAL
      IF(ID.EQ.'ON') THEN
        TON=VAL
      ELSE
        CALL ERROR$MSG('ID NOT RECOGNIZED')
        CALL ERROR$CHVAL('ID',ID)
        CALL ERROR$STOP('SKALA$SETL4')
      END IF
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$GETL4(ID,VAL)
      USE PAW_SKALA_MODULE
      IMPLICIT NONE
      CHARACTER(*),INTENT(IN) :: ID
      LOGICAL(4),INTENT(OUT)  :: VAL
      IF(ID.EQ.'ON') THEN
        VAL=TON
      ELSE
        CALL ERROR$MSG('ID NOT RECOGNIZED')
        CALL ERROR$CHVAL('ID',ID)
        CALL ERROR$STOP('SKALA$GETL4')
      END IF
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$SETCH(ID,VAL)
      USE PAW_SKALA_MODULE
      IMPLICIT NONE
      CHARACTER(*),INTENT(IN) :: ID
      CHARACTER(*),INTENT(IN) :: VAL
      IF(ID.EQ.'MODEL') THEN
        CONFIG_MODELFILE=TRIM(VAL)
      ELSE IF(ID.EQ.'DEVICE') THEN
        CONFIG_DEVICE=TRIM(VAL)
      ELSE
        CALL ERROR$MSG('ID NOT RECOGNIZED')
        CALL ERROR$CHVAL('ID',ID)
        CALL ERROR$STOP('SKALA$SETCH')
      END IF
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$SETI4(ID,VAL)
      USE PAW_SKALA_MODULE
      IMPLICIT NONE
      CHARACTER(*),INTENT(IN) :: ID
      INTEGER(4),INTENT(IN)   :: VAL
      IF(ID.EQ.'DEVICEINDEX') THEN
        CONFIG_DEVICEINDEX=VAL
      ELSE
        CALL ERROR$MSG('ID NOT RECOGNIZED')
        CALL ERROR$CHVAL('ID',ID)
        CALL ERROR$STOP('SKALA$SETI4')
      END IF
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$REPORT(NFIL)
      USE PAW_SKALA_MODULE
      IMPLICIT NONE
      INTEGER(4),INTENT(IN) :: NFIL
      IF(.NOT.TON) RETURN
      WRITE(NFIL,FMT='(/"SKALA 1.1 PAW INTEGRATION"/25("="))')
      WRITE(NFIL,FMT='("STATUS",T30,A)')'COMPLETE PAW ATOM-BLOCK VALIDATION'
      WRITE(NFIL,FMT='("MODEL FILE",T30,A)')TRIM(CONFIG_MODELFILE)
      WRITE(NFIL,FMT='("DEVICE",T30,A)')TRIM(CONFIG_DEVICE)
      WRITE(NFIL,FMT='("DEVICE INDEX",T30,I8)')CONFIG_DEVICEINDEX
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$AVAILABLE(TAVAILABLE)
      IMPLICIT NONE
      LOGICAL(4),INTENT(OUT) :: TAVAILABLE
#IF DEFINED(CPPVAR_SKALA_FTORCH)
      TAVAILABLE=.TRUE.
#ELSE
      TAVAILABLE=.FALSE.
#ENDIF
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$INITIALIZE(MODELFILE,DEVICE,DEVICEINDEX)
      USE PAW_SKALA_MODULE
      IMPLICIT NONE
      CHARACTER(*),INTENT(IN) :: MODELFILE
      CHARACTER(*),INTENT(IN) :: DEVICE
      INTEGER(4)  ,INTENT(IN) :: DEVICEINDEX
#IF DEFINED(CPPVAR_SKALA_FTORCH)
      INTEGER(4)              :: STATUS
      CHARACTER(2048)         :: MESSAGE
      CHARACTER(16)           :: DEVICE1

      IF(TINITIALIZED) CALL PAW_SKALA_RELEASE(MODEL)
      DEVICE1=DEVICE
      IF(TRIM(DEVICE1).EQ.'AUTO'.OR.TRIM(DEVICE1).EQ.'auto') THEN
        IF(PAW_SKALA_CUDA_AVAILABLE()) THEN
          DEVICE1='CUDA'
        ELSE
          DEVICE1='CPU'
        END IF
      END IF
      CALL PAW_SKALA_LOAD(MODEL,MODELFILE,DEVICE1,DEVICEINDEX,STATUS,MESSAGE)
      IF(STATUS.NE.0) THEN
        CALL ERROR$MSG('FAILED TO INITIALIZE SKALA 1.1')
        CALL ERROR$CHVAL('DETAIL',TRIM(MESSAGE))
        CALL ERROR$STOP('SKALA$INITIALIZE')
      END IF
      TINITIALIZED=.TRUE.
#ELSE
      CALL ERROR$MSG('CP-PAW WAS BUILT WITHOUT THE SKALA/FTORCH BRIDGE')
      CALL ERROR$STOP('SKALA$INITIALIZE')
#ENDIF
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$ENSUREINITIALIZED
      USE PAW_SKALA_MODULE
      IMPLICIT NONE
      IF(TINITIALIZED) RETURN
      IF(.NOT.TON) THEN
        CALL ERROR$MSG('SKALA FUNCTIONAL IS NOT ENABLED')
        CALL ERROR$STOP('SKALA$ENSUREINITIALIZED')
      END IF
      IF(LEN_TRIM(CONFIG_MODELFILE).EQ.0) THEN
        CALL ERROR$MSG('SKALA MODEL FILE HAS NOT BEEN SPECIFIED')
        CALL ERROR$STOP('SKALA$ENSUREINITIALIZED')
      END IF
      CALL SKALA$INITIALIZE(TRIM(CONFIG_MODELFILE),TRIM(CONFIG_DEVICE) &
     &                     ,CONFIG_DEVICEINDEX)
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$FINALIZE
      USE PAW_SKALA_MODULE
      IMPLICIT NONE
#IF DEFINED(CPPVAR_SKALA_FTORCH)
      IF(TINITIALIZED) CALL PAW_SKALA_RELEASE(MODEL)
#ENDIF
      TINITIALIZED=.FALSE.
      TSMOOTHREPORTED=.FALSE.
      TSMOOTHREADY=.FALSE.
      TFORWARDREPORTED=.FALSE.
      IF(ALLOCATED(TONECENTERREPORTED)) DEALLOCATE(TONECENTERREPORTED)
      IF(ALLOCATED(SMOOTH_RHO)) DEALLOCATE(SMOOTH_RHO)
      IF(ALLOCATED(SMOOTH_GRHO)) DEALLOCATE(SMOOTH_GRHO)
      IF(ALLOCATED(SMOOTH_TAU)) DEALLOCATE(SMOOTH_TAU)
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$FORWARDBEGIN
      USE PAW_SKALA_MODULE
      IMPLICIT NONE
      FORWARD_ENERGY=0.D0
      FORWARD_ELECTRONS=0.D0
      FORWARD_TAU=0.D0
      FORWARD_SMOOTH_ELECTRONS=0.D0
      FORWARD_CORRECTION_ELECTRONS=0.D0
      FORWARD_SMOOTH_TAU=0.D0
      FORWARD_CORRECTION_TAU=0.D0
      FORWARD_NPOINT=0
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$ATOMFORWARD(IAT,GID,NR,LNX,LOX,LMNX,NDIMD &
     &                            ,DENMAT,AEPHI,PSPHI,AECORE,PSCORE,RCUT)
      USE PAW_SKALA_MODULE
      USE PAW_SKALA_GRID_MODULE, ONLY: PAW_SKALA_SMOOTH_PARTITION &
     &                                ,PAW_SKALA_NEAREST_IMAGE &
     &                                ,PAW_SKALA_PARTITION_TAPER &
     &                                ,PAW_SKALA_LOCAL_GRID_SIZE &
     &                                ,PAW_SKALA_LOCAL_GRID &
     &                                ,PAW_SKALA_GRID_INTERPOLATE
      USE PAW_SKALA_PRIMITIVES_MODULE, ONLY: PAW_SKALA_ONECENTER_POINTS
      IMPLICIT NONE
      INTEGER(4),INTENT(IN) :: IAT,GID,NR,LNX,LOX(LNX),LMNX,NDIMD
      COMPLEX(8),INTENT(IN) :: DENMAT(LMNX,LMNX,NDIMD)
      REAL(8),INTENT(IN) :: AEPHI(NR,LNX),PSPHI(NR,LNX)
      REAL(8),INTENT(IN) :: AECORE(NR),PSCORE(NR),RCUT
      REAL(8),PARAMETER :: PARTITION_EPS=1.D-12
      INTEGER(4),PARAMETER :: LOCAL_NRADIAL=100,LOCAL_LEBEDEV_L=17
      INTEGER(4) :: NAT,NPOINT,NLOCAL,NANG,I1,I2,I3,IP,IDIM,ICART,ILOC
      INTEGER(8) :: ATOMICGRIDSIZES(1)
      REAL(8) :: MODELATOM(1,3),POINT(3),IMAGE(3),RELATIVE(3),DISTANCE
      REAL(8) :: CELLVOL,DVOL,FACTOR,ENERGY
      REAL(8) :: RHOCOMP(2),TAUCOMP(2),GRADCOMP(3,2)
      REAL(8),ALLOCATABLE :: ATOMCOORD(:,:),ATOMCOORD3(:,:),PARTITION(:)
      REAL(8),ALLOCATABLE :: LOCALCOORD(:,:),LOCALWEIGHT(:)
      REAL(8),ALLOCATABLE :: RELCOORD(:,:),GRIDCOORDS(:,:),GRIDWEIGHTS(:)
      REAL(8),ALLOCATABLE :: ATOMICGRIDWEIGHTS(:)
      REAL(8),ALLOCATABLE :: DENSITY(:,:),GRAD(:,:,:),KIN(:,:)
      REAL(8),ALLOCATABLE :: AERHO(:,:),PSRHO(:,:),AETAU(:,:),PSTAU(:,:)
      REAL(8),ALLOCATABLE :: AEGRAD(:,:,:),PSGRAD(:,:,:)
      REAL(8),ALLOCATABLE :: DDENSITY(:,:),DGRAD(:,:,:),DKIN(:,:)
      REAL(8),ALLOCATABLE :: DGRIDCOORDS(:,:),DGRIDWEIGHTS(:)
      REAL(8),ALLOCATABLE :: DATOMCOORDS(:,:),DATOMICGRIDWEIGHTS(:)

      IF(.NOT.TON) RETURN
      IF(.NOT.TSMOOTHREADY) THEN
        CALL ERROR$MSG('SKALA SMOOTH FIELDS ARE NOT AVAILABLE')
        CALL ERROR$STOP('SKALA$ATOMFORWARD')
      END IF
      IF(NDIMD.NE.SMOOTH_NDIMD) THEN
        CALL ERROR$MSG('SKALA SMOOTH AND ONE-CENTER SPINS DIFFER')
        CALL ERROR$I4VAL('SMOOTH NDIMD',SMOOTH_NDIMD)
        CALL ERROR$I4VAL('ONE-CENTER NDIMD',NDIMD)
        CALL ERROR$STOP('SKALA$ATOMFORWARD')
      END IF
      CALL ATOMLIST$NATOM(NAT)
      IF(IAT.LT.1.OR.IAT.GT.NAT) THEN
        CALL ERROR$MSG('INVALID ATOM INDEX FOR SKALA FORWARD EVALUATION')
        CALL ERROR$I4VAL('IAT',IAT)
        CALL ERROR$STOP('SKALA$ATOMFORWARD')
      END IF
      ALLOCATE(ATOMCOORD(NAT,3),ATOMCOORD3(3,NAT),PARTITION(NAT))
      CALL ATOMLIST$GETR8A('R(0)',0,3*NAT,ATOMCOORD3)
      ATOMCOORD=TRANSPOSE(ATOMCOORD3)

      CELLVOL=ABS(SMOOTH_RBAS(1,1)*(SMOOTH_RBAS(2,2)*SMOOTH_RBAS(3,3) &
     &                              -SMOOTH_RBAS(2,3)*SMOOTH_RBAS(3,2)) &
     &           -SMOOTH_RBAS(1,2)*(SMOOTH_RBAS(2,1)*SMOOTH_RBAS(3,3) &
     &                              -SMOOTH_RBAS(2,3)*SMOOTH_RBAS(3,1)) &
     &           +SMOOTH_RBAS(1,3)*(SMOOTH_RBAS(2,1)*SMOOTH_RBAS(3,2) &
     &                              -SMOOTH_RBAS(2,2)*SMOOTH_RBAS(3,1)))
      DVOL=CELLVOL/REAL(SMOOTH_NR1*SMOOTH_NR2*SMOOTH_NR3,KIND=8)
      CALL PAW_SKALA_LOCAL_GRID_SIZE(LOCAL_NRADIAL,LOCAL_LEBEDEV_L &
     &                              ,NANG,NLOCAL)
      ALLOCATE(LOCALCOORD(NLOCAL,3),LOCALWEIGHT(NLOCAL))
      CALL PAW_SKALA_LOCAL_GRID(LOCAL_NRADIAL,RCUT,LOCAL_LEBEDEV_L &
     &                          ,NLOCAL,LOCALCOORD,LOCALWEIGHT)
      NPOINT=0
      DO I3=1,SMOOTH_NR3
        DO I2=1,SMOOTH_NR2
          DO I1=1,SMOOTH_NR1
            POINT=MATMUL(SMOOTH_RBAS &
     &                  ,(/REAL(I1-1,KIND=8)/REAL(SMOOTH_NR1,KIND=8) &
     &                    ,REAL(I2-1,KIND=8)/REAL(SMOOTH_NR2,KIND=8) &
     &                    ,REAL(I3-1,KIND=8)/REAL(SMOOTH_NR3,KIND=8)/))
            CALL PAW_SKALA_NEAREST_IMAGE(POINT,ATOMCOORD(IAT,:) &
     &                                   ,SMOOTH_RBAS,IMAGE,DISTANCE)
            IF(DISTANCE.LE.RCUT) CYCLE
            CALL PAW_SKALA_SMOOTH_PARTITION(POINT,NAT,ATOMCOORD &
     &                                      ,SMOOTH_RBAS,PARTITION)
            IF(PARTITION(IAT).GT.PARTITION_EPS) NPOINT=NPOINT+1
          END DO
        END DO
      END DO
      DO ILOC=1,NLOCAL
        POINT=ATOMCOORD(IAT,:)+LOCALCOORD(ILOC,:)
        CALL PAW_SKALA_SMOOTH_PARTITION(POINT,NAT,ATOMCOORD &
     &                                  ,SMOOTH_RBAS,PARTITION)
        IF(PARTITION(IAT).GT.PARTITION_EPS) NPOINT=NPOINT+1
      END DO
      IF(NPOINT.EQ.0) THEN
        CALL ERROR$MSG('SKALA ATOM BLOCK HAS NO GRID POINTS')
        CALL ERROR$I4VAL('IAT',IAT)
        CALL ERROR$STOP('SKALA$ATOMFORWARD')
      END IF

      ALLOCATE(RELCOORD(NPOINT,3),GRIDCOORDS(NPOINT,3))
      ALLOCATE(GRIDWEIGHTS(NPOINT),ATOMICGRIDWEIGHTS(NPOINT))
      ALLOCATE(DENSITY(NPOINT,2),GRAD(NPOINT,3,2),KIN(NPOINT,2))
      IP=0
      DO I3=1,SMOOTH_NR3
        DO I2=1,SMOOTH_NR2
          DO I1=1,SMOOTH_NR1
            POINT=MATMUL(SMOOTH_RBAS &
     &                  ,(/REAL(I1-1,KIND=8)/REAL(SMOOTH_NR1,KIND=8) &
     &                    ,REAL(I2-1,KIND=8)/REAL(SMOOTH_NR2,KIND=8) &
     &                    ,REAL(I3-1,KIND=8)/REAL(SMOOTH_NR3,KIND=8)/))
            CALL PAW_SKALA_SMOOTH_PARTITION(POINT,NAT,ATOMCOORD &
     &                                      ,SMOOTH_RBAS,PARTITION)
            CALL PAW_SKALA_NEAREST_IMAGE(POINT,ATOMCOORD(IAT,:) &
     &                                   ,SMOOTH_RBAS,IMAGE,DISTANCE)
            IF(DISTANCE.LE.RCUT) CYCLE
            IF(PARTITION(IAT).LE.PARTITION_EPS) CYCLE
            IP=IP+1
            RELATIVE=POINT-IMAGE
            RELCOORD(IP,:)=RELATIVE
            GRIDCOORDS(IP,:)=ATOMCOORD(IAT,:)+RELATIVE
            GRIDWEIGHTS(IP)=DVOL*PARTITION(IAT)
            ATOMICGRIDWEIGHTS(IP)=DVOL &
     &          *PAW_SKALA_PARTITION_TAPER(PARTITION(IAT))
            IF(NDIMD.EQ.1) THEN
              DENSITY(IP,:)=0.5D0*SMOOTH_RHO(I1,I2,I3,1)
              KIN(IP,:)=0.5D0*SMOOTH_TAU(I1,I2,I3,1)
              DO ICART=1,3
                GRAD(IP,ICART,:)=0.5D0*SMOOTH_GRHO(I1,I2,I3,ICART,1)
              END DO
            ELSE
              DO IDIM=1,2
                FACTOR=MERGE(1.D0,-1.D0,IDIM.EQ.1)
                DENSITY(IP,IDIM)=0.5D0*(SMOOTH_RHO(I1,I2,I3,1) &
     &                                      +FACTOR*SMOOTH_RHO(I1,I2,I3,2))
                KIN(IP,IDIM)=0.5D0*(SMOOTH_TAU(I1,I2,I3,1) &
     &                                      +FACTOR*SMOOTH_TAU(I1,I2,I3,2))
                DO ICART=1,3
                  GRAD(IP,ICART,IDIM)=0.5D0 &
     &                         *(SMOOTH_GRHO(I1,I2,I3,ICART,1) &
     &                    +FACTOR*SMOOTH_GRHO(I1,I2,I3,ICART,2))
                END DO
              END DO
            END IF
          END DO
        END DO
      END DO

      DO ILOC=1,NLOCAL
        RELATIVE=LOCALCOORD(ILOC,:)
        POINT=ATOMCOORD(IAT,:)+RELATIVE
        CALL PAW_SKALA_SMOOTH_PARTITION(POINT,NAT,ATOMCOORD &
     &                                  ,SMOOTH_RBAS,PARTITION)
        IF(PARTITION(IAT).LE.PARTITION_EPS) CYCLE
        IP=IP+1
        RELCOORD(IP,:)=RELATIVE
        GRIDCOORDS(IP,:)=POINT
        GRIDWEIGHTS(IP)=LOCALWEIGHT(ILOC)*PARTITION(IAT)
        ATOMICGRIDWEIGHTS(IP)=LOCALWEIGHT(ILOC) &
     &        *PAW_SKALA_PARTITION_TAPER(PARTITION(IAT))
        RHOCOMP=0.D0
        TAUCOMP=0.D0
        GRADCOMP=0.D0
        DO IDIM=1,NDIMD
          CALL PAW_SKALA_GRID_INTERPOLATE(SMOOTH_NR1,SMOOTH_NR2,SMOOTH_NR3 &
     &                                   ,SMOOTH_RBAS,SMOOTH_RHO(:,:,:,IDIM) &
     &                                   ,POINT,RHOCOMP(IDIM))
          CALL PAW_SKALA_GRID_INTERPOLATE(SMOOTH_NR1,SMOOTH_NR2,SMOOTH_NR3 &
     &                                   ,SMOOTH_RBAS,SMOOTH_TAU(:,:,:,IDIM) &
     &                                   ,POINT,TAUCOMP(IDIM))
          DO ICART=1,3
            CALL PAW_SKALA_GRID_INTERPOLATE &
     &           (SMOOTH_NR1,SMOOTH_NR2,SMOOTH_NR3,SMOOTH_RBAS &
     &           ,SMOOTH_GRHO(:,:,:,ICART,IDIM),POINT,GRADCOMP(ICART,IDIM))
          END DO
        END DO
        IF(NDIMD.EQ.1) THEN
          DENSITY(IP,:)=0.5D0*RHOCOMP(1)
          KIN(IP,:)=0.5D0*TAUCOMP(1)
          DO ICART=1,3
            GRAD(IP,ICART,:)=0.5D0*GRADCOMP(ICART,1)
          END DO
        ELSE
          DO IDIM=1,2
            FACTOR=MERGE(1.D0,-1.D0,IDIM.EQ.1)
            DENSITY(IP,IDIM)=0.5D0*(RHOCOMP(1)+FACTOR*RHOCOMP(2))
            KIN(IP,IDIM)=0.5D0*(TAUCOMP(1)+FACTOR*TAUCOMP(2))
            DO ICART=1,3
              GRAD(IP,ICART,IDIM)=0.5D0 &
     &                            *(GRADCOMP(ICART,1) &
     &                              +FACTOR*GRADCOMP(ICART,2))
            END DO
          END DO
        END IF
      END DO
      IF(IP.NE.NPOINT) THEN
        CALL ERROR$MSG('SKALA HYBRID GRID COUNT CHANGED WHILE BUILDING')
        CALL ERROR$I4VAL('COUNTED',NPOINT)
        CALL ERROR$I4VAL('BUILT',IP)
        CALL ERROR$STOP('SKALA$ATOMFORWARD')
      END IF

      ALLOCATE(AERHO(NPOINT,2),PSRHO(NPOINT,2))
      ALLOCATE(AEGRAD(NPOINT,3,2),PSGRAD(NPOINT,3,2))
      ALLOCATE(AETAU(NPOINT,2),PSTAU(NPOINT,2))
      CALL PAW_SKALA_ONECENTER_POINTS(GID,NR,LNX,LOX,LMNX,NDIMD &
     &                                ,DENMAT,AEPHI,PSPHI,AECORE,PSCORE &
     &                                ,RCUT,NPOINT,RELCOORD &
     &                                ,AERHO,AEGRAD,AETAU &
     &                                ,PSRHO,PSGRAD,PSTAU)
      FORWARD_SMOOTH_ELECTRONS=FORWARD_SMOOTH_ELECTRONS &
     &                 +SUM(GRIDWEIGHTS*SUM(DENSITY,DIM=2))
      FORWARD_CORRECTION_ELECTRONS=FORWARD_CORRECTION_ELECTRONS &
     &                 +SUM(GRIDWEIGHTS*SUM(AERHO-PSRHO,DIM=2))
      FORWARD_SMOOTH_TAU=FORWARD_SMOOTH_TAU &
     &                 +SUM(GRIDWEIGHTS*SUM(KIN,DIM=2))
      FORWARD_CORRECTION_TAU=FORWARD_CORRECTION_TAU &
     &                 +SUM(GRIDWEIGHTS*SUM(AETAU-PSTAU,DIM=2))
      DENSITY=DENSITY+AERHO-PSRHO
      GRAD=GRAD+AEGRAD-PSGRAD
      KIN=KIN+AETAU-PSTAU

      ALLOCATE(DDENSITY(NPOINT,2),DGRAD(NPOINT,3,2),DKIN(NPOINT,2))
      ALLOCATE(DGRIDCOORDS(NPOINT,3),DGRIDWEIGHTS(NPOINT))
      ALLOCATE(DATOMCOORDS(1,3),DATOMICGRIDWEIGHTS(NPOINT))
      MODELATOM(1,:)=ATOMCOORD(IAT,:)
      ATOMICGRIDSIZES(1)=INT(NPOINT,KIND=8)
      CALL SKALA$EVALUATE(NPOINT,1,DENSITY,GRAD,KIN &
     &                   ,GRIDCOORDS,GRIDWEIGHTS,MODELATOM &
     &                   ,ATOMICGRIDWEIGHTS,ATOMICGRIDSIZES,ENERGY &
     &                   ,DDENSITY,DGRAD,DKIN,DGRIDCOORDS &
     &                   ,DGRIDWEIGHTS,DATOMCOORDS,DATOMICGRIDWEIGHTS)
      IF(ENERGY.NE.ENERGY.OR.ABS(ENERGY).GT.0.5D0*HUGE(ENERGY)) THEN
        CALL ERROR$MSG('SKALA FORWARD ENERGY IS NOT FINITE')
        CALL ERROR$I4VAL('IAT',IAT)
        CALL ERROR$STOP('SKALA$ATOMFORWARD')
      END IF
      FORWARD_ENERGY=FORWARD_ENERGY+ENERGY
      FORWARD_ELECTRONS=FORWARD_ELECTRONS &
     &                 +SUM(GRIDWEIGHTS*SUM(DENSITY,DIM=2))
      FORWARD_TAU=FORWARD_TAU+SUM(GRIDWEIGHTS*SUM(KIN,DIM=2))
      FORWARD_NPOINT=FORWARD_NPOINT+NPOINT

      DEALLOCATE(ATOMCOORD,ATOMCOORD3,PARTITION,RELCOORD,GRIDCOORDS)
      DEALLOCATE(LOCALCOORD,LOCALWEIGHT,GRIDWEIGHTS)
      DEALLOCATE(ATOMICGRIDWEIGHTS,DENSITY,GRAD,KIN)
      DEALLOCATE(AERHO,PSRHO,AEGRAD,PSGRAD,AETAU,PSTAU)
      DEALLOCATE(DDENSITY,DGRAD,DKIN,DGRIDCOORDS,DGRIDWEIGHTS)
      DEALLOCATE(DATOMCOORDS,DATOMICGRIDWEIGHTS)
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$FORWARDEND
      USE PAW_SKALA_MODULE
      USE MPE_MODULE
      IMPLICIT NONE
      INTEGER(4) :: NTASKS,THISTASK,NFIL

      IF(.NOT.TON) RETURN
      CALL MPE$COMBINE('MONOMER','+',FORWARD_ENERGY)
      CALL MPE$COMBINE('MONOMER','+',FORWARD_ELECTRONS)
      CALL MPE$COMBINE('MONOMER','+',FORWARD_TAU)
      CALL MPE$COMBINE('MONOMER','+',FORWARD_SMOOTH_ELECTRONS)
      CALL MPE$COMBINE('MONOMER','+',FORWARD_CORRECTION_ELECTRONS)
      CALL MPE$COMBINE('MONOMER','+',FORWARD_SMOOTH_TAU)
      CALL MPE$COMBINE('MONOMER','+',FORWARD_CORRECTION_TAU)
      CALL MPE$COMBINE('MONOMER','+',FORWARD_NPOINT)
      CALL MPE$QUERY('MONOMER',NTASKS,THISTASK)
      IF(THISTASK.EQ.1.AND..NOT.TFORWARDREPORTED) THEN
        CALL FILEHANDLER$UNIT('PROT',NFIL)
        WRITE(NFIL,FMT='(/"SKALA COMPLETE PAW ATOM BLOCKS"/30("="))')
        WRITE(NFIL,FMT='("HYBRID-GRID ROWS",T34,I12)')FORWARD_NPOINT
        WRITE(NFIL,FMT='("SMOOTH ELECTRONS",T34,ES24.14)') &
     &       FORWARD_SMOOTH_ELECTRONS
        WRITE(NFIL,FMT='("AE-PS ELECTRONS",T34,ES24.14)') &
     &       FORWARD_CORRECTION_ELECTRONS
        WRITE(NFIL,FMT='("COMPOSITE ELECTRONS",T34,ES24.14)')FORWARD_ELECTRONS
        WRITE(NFIL,FMT='("SMOOTH POSITIVE TAU",T34,ES24.14)')FORWARD_SMOOTH_TAU
        WRITE(NFIL,FMT='("AE-PS POSITIVE TAU",T34,ES24.14)') &
     &       FORWARD_CORRECTION_TAU
        WRITE(NFIL,FMT='("COMPOSITE POSITIVE TAU",T34,ES24.14)')FORWARD_TAU
        WRITE(NFIL,FMT='("MODEL XC ENERGY",T34,ES24.14)')FORWARD_ENERGY
      END IF
      TFORWARDREPORTED=.TRUE.
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$SMOOTHSET(NR1START,NR1L,NR1,NR2,NR3,NDIMD &
     &                          ,RHO,GRHO,TAUPOS,RBAS)
      USE PAW_SKALA_MODULE
      USE MPE_MODULE
      IMPLICIT NONE
      INTEGER(4),INTENT(IN) :: NR1START,NR1L,NR1,NR2,NR3,NDIMD
      REAL(8),INTENT(IN) :: RHO(NR1L*NR2*NR3,NDIMD)
      REAL(8),INTENT(IN) :: GRHO(NR1L*NR2*NR3,3,NDIMD)
      REAL(8),INTENT(IN) :: TAUPOS(NR1L*NR2*NR3,NDIMD)
      REAL(8),INTENT(IN) :: RBAS(3,3)
      INTEGER(4) :: IDIM,ICART,IEND

      IF(.NOT.TON) RETURN
      IF(NDIMD.NE.1.AND.NDIMD.NE.2) THEN
        CALL ERROR$MSG('SKALA SMOOTH CACHE REQUIRES COLLINEAR SPIN')
        CALL ERROR$I4VAL('NDIMD',NDIMD)
        CALL ERROR$STOP('SKALA$SMOOTHSET')
      END IF
      IEND=NR1START+NR1L-1
      IF(NR1START.LT.1.OR.IEND.GT.NR1) THEN
        CALL ERROR$MSG('INVALID LOCAL SKALA GRID SLAB')
        CALL ERROR$I4VAL('NR1START',NR1START)
        CALL ERROR$I4VAL('NR1L',NR1L)
        CALL ERROR$I4VAL('NR1',NR1)
        CALL ERROR$STOP('SKALA$SMOOTHSET')
      END IF
      IF(ALLOCATED(SMOOTH_RHO)) DEALLOCATE(SMOOTH_RHO)
      IF(ALLOCATED(SMOOTH_GRHO)) DEALLOCATE(SMOOTH_GRHO)
      IF(ALLOCATED(SMOOTH_TAU)) DEALLOCATE(SMOOTH_TAU)
      ALLOCATE(SMOOTH_RHO(NR1,NR2,NR3,NDIMD))
      ALLOCATE(SMOOTH_GRHO(NR1,NR2,NR3,3,NDIMD))
      ALLOCATE(SMOOTH_TAU(NR1,NR2,NR3,NDIMD))
      SMOOTH_RHO=0.D0
      SMOOTH_GRHO=0.D0
      SMOOTH_TAU=0.D0
      DO IDIM=1,NDIMD
        SMOOTH_RHO(NR1START:IEND,:,:,IDIM)= &
     &      RESHAPE(RHO(:,IDIM),(/NR1L,NR2,NR3/))
        SMOOTH_TAU(NR1START:IEND,:,:,IDIM)= &
     &      RESHAPE(TAUPOS(:,IDIM),(/NR1L,NR2,NR3/))
        DO ICART=1,3
          SMOOTH_GRHO(NR1START:IEND,:,:,ICART,IDIM)= &
     &        RESHAPE(GRHO(:,ICART,IDIM),(/NR1L,NR2,NR3/))
        END DO
      END DO
      CALL MPE$COMBINE('MONOMER','+',SMOOTH_RHO)
      CALL MPE$COMBINE('MONOMER','+',SMOOTH_GRHO)
      CALL MPE$COMBINE('MONOMER','+',SMOOTH_TAU)
      SMOOTH_NR1=NR1
      SMOOTH_NR2=NR2
      SMOOTH_NR3=NR3
      SMOOTH_NDIMD=NDIMD
      SMOOTH_RBAS=RBAS
      TSMOOTHREADY=.TRUE.
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$SMOOTHVALIDATE(NRL,NDIMD,RHO,GRHO,TAUPOS &
     &                               ,NGRIDGLOBAL,CELLVOL)
      USE PAW_SKALA_MODULE
      USE MPE_MODULE
      IMPLICIT NONE
      INTEGER(4),INTENT(IN) :: NRL,NDIMD,NGRIDGLOBAL
      REAL(8),INTENT(IN) :: RHO(NRL,NDIMD)
      REAL(8),INTENT(IN) :: GRHO(NRL,3,NDIMD)
      REAL(8),INTENT(IN) :: TAUPOS(NRL,NDIMD)
      REAL(8),INTENT(IN) :: CELLVOL
      REAL(8) :: RWEIGHT,RHOINT,SPININT,TAUINT,GRADNORM
      INTEGER(4) :: NTASKS,THISTASK,NFIL

      IF(.NOT.TON.OR.TSMOOTHREPORTED) RETURN
      IF(NDIMD.NE.1.AND.NDIMD.NE.2) THEN
        CALL ERROR$MSG('SKALA SMOOTH PRIMITIVES REQUIRE COLLINEAR SPIN')
        CALL ERROR$I4VAL('NDIMD',NDIMD)
        CALL ERROR$STOP('SKALA$SMOOTHVALIDATE')
      END IF
      RWEIGHT=CELLVOL/REAL(NGRIDGLOBAL,KIND=8)
      RHOINT=SUM(RHO(:,1))*RWEIGHT
      TAUINT=SUM(TAUPOS(:,1))*RWEIGHT
      GRADNORM=SUM(GRHO(:,:,1)**2)*RWEIGHT
      SPININT=0.D0
      IF(NDIMD.EQ.2) SPININT=SUM(RHO(:,2))*RWEIGHT
      CALL MPE$COMBINE('MONOMER','+',RHOINT)
      CALL MPE$COMBINE('MONOMER','+',TAUINT)
      CALL MPE$COMBINE('MONOMER','+',GRADNORM)
      CALL MPE$COMBINE('MONOMER','+',SPININT)
      CALL MPE$QUERY('MONOMER',NTASKS,THISTASK)
      IF(THISTASK.EQ.1) THEN
        CALL FILEHANDLER$UNIT('PROT',NFIL)
        WRITE(NFIL,FMT='(/"SKALA SMOOTH PRIMITIVES"/23("="))')
        WRITE(NFIL,FMT='("GRID POINTS",T34,I12)')NGRIDGLOBAL
        WRITE(NFIL,FMT='("SMOOTH ELECTRONS WITH CORE",T34,ES24.14)')RHOINT
        IF(NDIMD.EQ.2) THEN
          WRITE(NFIL,FMT='("SMOOTH SPIN",T34,ES24.14)')SPININT
        END IF
        WRITE(NFIL,FMT='("POSITIVE TAU",T34,ES24.14)')TAUINT
        WRITE(NFIL,FMT='("DENSITY GRADIENT L2",T34,ES24.14)')SQRT(GRADNORM)
      END IF
      TSMOOTHREPORTED=.TRUE.
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$ONECENTERVALIDATE(IAT,GID,NR,LNX,LOX,LMNX,LMRX &
     &                                  ,NDIMD,DENMAT,AEPHI,PSPHI &
     &                                  ,AECORE,PSCORE,AERHOL,PSRHOL &
     &                                  ,RCUT,EKINNL)
      USE PAW_SKALA_MODULE
      USE PAW_SKALA_PRIMITIVES_MODULE, ONLY: &
     &     PAW_SKALA_ONECENTER_GRID_SIZE,PAW_SKALA_ONECENTER_PRIMITIVES
      IMPLICIT NONE
      INTEGER(4),INTENT(IN) :: IAT,GID,NR,LNX,LOX(LNX),LMNX,LMRX,NDIMD
      COMPLEX(8),INTENT(IN) :: DENMAT(LMNX,LMNX,NDIMD)
      REAL(8),INTENT(IN) :: AEPHI(NR,LNX),PSPHI(NR,LNX)
      REAL(8),INTENT(IN) :: AECORE(NR),PSCORE(NR)
      REAL(8),INTENT(IN) :: AERHOL(NR,LMRX,NDIMD),PSRHOL(NR,LMRX,NDIMD)
      REAL(8),INTENT(IN) :: RCUT,EKINNL
      INTEGER(4),PARAMETER :: LEBEDEV_L=17
      REAL(8),PARAMETER :: PI=4.D0*ATAN(1.D0)
      LOGICAL(4),ALLOCATABLE :: TREPORTED1(:)
      REAL(8),ALLOCATABLE :: RELCOORD(:,:),WEIGHT(:)
      REAL(8),ALLOCATABLE :: AERHO(:,:),PSRHO(:,:),AETAU(:,:),PSTAU(:,:)
      REAL(8),ALLOCATABLE :: AEGRAD(:,:,:),PSGRAD(:,:,:)
      REAL(8) :: R(NR),WORK(NR),INTEGRAL(NR)
      REAL(8) :: AECOUNT,PSCOUNT,AECOUNTREF,PSCOUNTREF,TAUDIFF
      INTEGER(4) :: NRUSE,NANG,NPOINT,NFIL

      IF(.NOT.TON) RETURN
      IF(IAT.LE.0) RETURN
      IF(.NOT.ALLOCATED(TONECENTERREPORTED)) THEN
        ALLOCATE(TONECENTERREPORTED(IAT))
        TONECENTERREPORTED(:)=.FALSE.
      ELSE IF(SIZE(TONECENTERREPORTED).LT.IAT) THEN
        ALLOCATE(TREPORTED1(IAT))
        TREPORTED1(:)=.FALSE.
        TREPORTED1(1:SIZE(TONECENTERREPORTED))=TONECENTERREPORTED
        CALL MOVE_ALLOC(TREPORTED1,TONECENTERREPORTED)
      END IF
      IF(TONECENTERREPORTED(IAT)) RETURN

      CALL PAW_SKALA_ONECENTER_GRID_SIZE(GID,NR,RCUT,LEBEDEV_L &
     &                                  ,NRUSE,NANG,NPOINT)
      ALLOCATE(RELCOORD(NPOINT,3),WEIGHT(NPOINT))
      ALLOCATE(AERHO(NPOINT,2),PSRHO(NPOINT,2))
      ALLOCATE(AEGRAD(NPOINT,3,2),PSGRAD(NPOINT,3,2))
      ALLOCATE(AETAU(NPOINT,2),PSTAU(NPOINT,2))
      CALL PAW_SKALA_ONECENTER_PRIMITIVES(GID,NR,LNX,LOX,LMNX,NDIMD &
     &                                   ,DENMAT,AEPHI,PSPHI,AECORE,PSCORE &
     &                                   ,RCUT,LEBEDEV_L,NPOINT &
     &                                   ,RELCOORD,WEIGHT,AERHO,AEGRAD,AETAU &
     &                                   ,PSRHO,PSGRAD,PSTAU)

      AECOUNT=SUM(WEIGHT*(AERHO(:,1)+AERHO(:,2)))
      PSCOUNT=SUM(WEIGHT*(PSRHO(:,1)+PSRHO(:,2)))
      TAUDIFF=SUM(WEIGHT*(AETAU(:,1)+AETAU(:,2) &
     &                         -PSTAU(:,1)-PSTAU(:,2)))
      CALL RADIAL$R(GID,NR,R)
      WORK(:)=(AERHOL(:,1,1)+AECORE)*R**2
      CALL RADIAL$INTEGRATE(GID,NR,WORK,INTEGRAL)
      AECOUNTREF=SQRT(4.D0*PI)*INTEGRAL(NRUSE)
      WORK(:)=(PSRHOL(:,1,1)+PSCORE)*R**2
      CALL RADIAL$INTEGRATE(GID,NR,WORK,INTEGRAL)
      PSCOUNTREF=SQRT(4.D0*PI)*INTEGRAL(NRUSE)

      CALL FILEHANDLER$UNIT('PROT',NFIL)
      WRITE(NFIL,FMT='(/"SKALA PAW ONE-CENTER PRIMITIVES"/31("="))')
      WRITE(NFIL,FMT='("ATOM INDEX",T34,I10)')IAT
      WRITE(NFIL,FMT='("LEBEDEV EXACTNESS",T34,I10)')LEBEDEV_L
      WRITE(NFIL,FMT='("RADIAL POINTS",T34,I10)')NRUSE
      WRITE(NFIL,FMT='("ANGULAR POINTS",T34,I10)')NANG
      WRITE(NFIL,FMT='("TOTAL POINTS",T34,I10)')NPOINT
      WRITE(NFIL,FMT='("AE ELECTRONS",T34,ES24.14)')AECOUNT
      WRITE(NFIL,FMT='("AE ELECTRON ERROR",T34,ES24.14)')AECOUNT-AECOUNTREF
      WRITE(NFIL,FMT='("PS ELECTRONS",T34,ES24.14)')PSCOUNT
      WRITE(NFIL,FMT='("PS ELECTRON ERROR",T34,ES24.14)')PSCOUNT-PSCOUNTREF
      WRITE(NFIL,FMT='("POSITIVE TAU AE-PS",T34,ES24.14)')TAUDIFF
      WRITE(NFIL,FMT='("ONE-CENTER KINETIC",T34,ES24.14)')EKINNL
      WRITE(NFIL,FMT='("TAU-KINETIC DIFFERENCE",T34,ES24.14)')TAUDIFF-EKINNL
      TONECENTERREPORTED(IAT)=.TRUE.

      DEALLOCATE(RELCOORD,WEIGHT,AERHO,PSRHO,AEGRAD,PSGRAD,AETAU,PSTAU)
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$EVALUATE(NPOINT,NATOM,DENSITY,GRAD,KIN &
     &                         ,GRIDCOORDS,GRIDWEIGHTS,ATOMCOORDS &
     &                         ,ATOMICGRIDWEIGHTS,ATOMICGRIDSIZES,ENERGY &
     &                         ,DDENSITY,DGRAD,DKIN,DGRIDCOORDS &
     &                         ,DGRIDWEIGHTS,DATOMCOORDS,DATOMICGRIDWEIGHTS)
      USE PAW_SKALA_MODULE
      IMPLICIT NONE
      INTEGER(4),INTENT(IN)  :: NPOINT
      INTEGER(4),INTENT(IN)  :: NATOM
      REAL(8)   ,INTENT(IN)  :: DENSITY(NPOINT,2)
      REAL(8)   ,INTENT(IN)  :: GRAD(NPOINT,3,2)
      REAL(8)   ,INTENT(IN)  :: KIN(NPOINT,2)
      REAL(8)   ,INTENT(IN)  :: GRIDCOORDS(NPOINT,3)
      REAL(8)   ,INTENT(IN)  :: GRIDWEIGHTS(NPOINT)
      REAL(8)   ,INTENT(IN)  :: ATOMCOORDS(NATOM,3)
      REAL(8)   ,INTENT(IN)  :: ATOMICGRIDWEIGHTS(NPOINT)
      INTEGER(8),INTENT(IN)  :: ATOMICGRIDSIZES(NATOM)
      REAL(8)   ,INTENT(OUT) :: ENERGY
      REAL(8)   ,INTENT(OUT) :: DDENSITY(NPOINT,2)
      REAL(8)   ,INTENT(OUT) :: DGRAD(NPOINT,3,2)
      REAL(8)   ,INTENT(OUT) :: DKIN(NPOINT,2)
      REAL(8)   ,INTENT(OUT) :: DGRIDCOORDS(NPOINT,3)
      REAL(8)   ,INTENT(OUT) :: DGRIDWEIGHTS(NPOINT)
      REAL(8)   ,INTENT(OUT) :: DATOMCOORDS(NATOM,3)
      REAL(8)   ,INTENT(OUT) :: DATOMICGRIDWEIGHTS(NPOINT)
#IF DEFINED(CPPVAR_SKALA_FTORCH)
      INTEGER(4)             :: STATUS
      CHARACTER(2048)        :: MESSAGE

      IF(.NOT.TINITIALIZED) CALL SKALA$ENSUREINITIALIZED
      CALL PAW_SKALA_EVALUATE(MODEL,DENSITY,GRAD,KIN,GRIDCOORDS,GRIDWEIGHTS &
     &                       ,ATOMCOORDS,ATOMICGRIDWEIGHTS,ATOMICGRIDSIZES &
     &                       ,ENERGY,DDENSITY,DGRAD,DKIN,STATUS,MESSAGE &
     &                       ,DGRIDCOORDS,DGRIDWEIGHTS,DATOMCOORDS &
     &                       ,DATOMICGRIDWEIGHTS)
      IF(STATUS.NE.0) THEN
        CALL ERROR$MSG('SKALA 1.1 EVALUATION FAILED')
        CALL ERROR$CHVAL('DETAIL',TRIM(MESSAGE))
        CALL ERROR$STOP('SKALA$EVALUATE')
      END IF
#ELSE
      CALL ERROR$MSG('CP-PAW WAS BUILT WITHOUT THE SKALA/FTORCH BRIDGE')
      CALL ERROR$STOP('SKALA$EVALUATE')
#ENDIF
      RETURN
      END
