! SPDX-License-Identifier: GPL-3.0-or-later
!**  PERIODIC ATOM PARTITION AND NATIVE-GRID INTERPOLATION FOR SKALA PAW      **

MODULE PAW_SKALA_GRID_MODULE
  IMPLICIT NONE
  PRIVATE
  INTEGER(4),PARAMETER :: INTERP_MIN=-3
  INTEGER(4),PARAMETER :: INTERP_MAX=4
  INTEGER(4),PARAMETER :: INTERP_N=INTERP_MAX-INTERP_MIN+1

  PUBLIC :: PAW_SKALA_SMOOTH_PARTITION
  PUBLIC :: PAW_SKALA_GRID_INTERPOLATE
  PUBLIC :: PAW_SKALA_GRID_INTERPOLATE_GRADIENT
  PUBLIC :: PAW_SKALA_GRID_INTERPOLATION_ADJOINT
  PUBLIC :: PAW_SKALA_GRID_TEST

CONTAINS

  SUBROUTINE PAW_SKALA_INVERSE3(A,AINV)
    IMPLICIT NONE
    REAL(8),INTENT(IN) :: A(3,3)
    REAL(8),INTENT(OUT) :: AINV(3,3)
    REAL(8) :: DET

    DET=A(1,1)*(A(2,2)*A(3,3)-A(2,3)*A(3,2)) &
 &     -A(1,2)*(A(2,1)*A(3,3)-A(2,3)*A(3,1)) &
 &     +A(1,3)*(A(2,1)*A(3,2)-A(2,2)*A(3,1))
    IF(ABS(DET).LE.TINY(DET)) THEN
      CALL ERROR$MSG('SINGULAR CELL IN SKALA GRID OPERATION')
      CALL ERROR$STOP('PAW_SKALA_INVERSE3')
    END IF
    AINV(1,1)=(A(2,2)*A(3,3)-A(2,3)*A(3,2))/DET
    AINV(1,2)=(A(1,3)*A(3,2)-A(1,2)*A(3,3))/DET
    AINV(1,3)=(A(1,2)*A(2,3)-A(1,3)*A(2,2))/DET
    AINV(2,1)=(A(2,3)*A(3,1)-A(2,1)*A(3,3))/DET
    AINV(2,2)=(A(1,1)*A(3,3)-A(1,3)*A(3,1))/DET
    AINV(2,3)=(A(1,3)*A(2,1)-A(1,1)*A(2,3))/DET
    AINV(3,1)=(A(2,1)*A(3,2)-A(2,2)*A(3,1))/DET
    AINV(3,2)=(A(1,2)*A(3,1)-A(1,1)*A(3,2))/DET
    AINV(3,3)=(A(1,1)*A(2,2)-A(1,2)*A(2,1))/DET
  END SUBROUTINE PAW_SKALA_INVERSE3

  SUBROUTINE PAW_SKALA_LAGRANGE_WEIGHTS(FRACTION,WEIGHT,DWEIGHT)
    IMPLICIT NONE
    REAL(8),INTENT(IN) :: FRACTION
    REAL(8),INTENT(OUT) :: WEIGHT(INTERP_N)
    REAL(8),INTENT(OUT),OPTIONAL :: DWEIGHT(INTERP_N)
    REAL(8) :: NODE(INTERP_N),NUMERATOR,DENOMINATOR,DERIVATIVE
    INTEGER(4) :: I,J,K

    DO I=1,INTERP_N
      NODE(I)=REAL(INTERP_MIN+I-1,KIND=8)
    END DO
    DO I=1,INTERP_N
      NUMERATOR=1.D0
      DENOMINATOR=1.D0
      DO J=1,INTERP_N
        IF(J.EQ.I) CYCLE
        NUMERATOR=NUMERATOR*(FRACTION-NODE(J))
        DENOMINATOR=DENOMINATOR*(NODE(I)-NODE(J))
      END DO
      WEIGHT(I)=NUMERATOR/DENOMINATOR
      IF(PRESENT(DWEIGHT)) THEN
        DERIVATIVE=0.D0
        DO K=1,INTERP_N
          IF(K.EQ.I) CYCLE
          NUMERATOR=1.D0
          DO J=1,INTERP_N
            IF(J.EQ.I.OR.J.EQ.K) CYCLE
            NUMERATOR=NUMERATOR*(FRACTION-NODE(J))
          END DO
          DERIVATIVE=DERIVATIVE+NUMERATOR/DENOMINATOR
        END DO
        DWEIGHT(I)=DERIVATIVE
      END IF
    END DO
  END SUBROUTINE PAW_SKALA_LAGRANGE_WEIGHTS

  SUBROUTINE PAW_SKALA_INTERPOLATION_DATA(NR1,NR2,NR3,RBAS,POINT &
 &                                        ,BASE,WEIGHT,DWEIGHT,AINV)
    IMPLICIT NONE
    INTEGER(4),INTENT(IN) :: NR1,NR2,NR3
    REAL(8),INTENT(IN) :: RBAS(3,3),POINT(3)
    INTEGER(4),INTENT(OUT) :: BASE(3)
    REAL(8),INTENT(OUT) :: WEIGHT(INTERP_N,3),AINV(3,3)
    REAL(8),INTENT(OUT),OPTIONAL :: DWEIGHT(INTERP_N,3)
    REAL(8) :: RELATIVE(3),FRACTION
    INTEGER(4) :: IDIR,NGRID(3)

    NGRID=(/NR1,NR2,NR3/)
    CALL PAW_SKALA_INVERSE3(RBAS,AINV)
    RELATIVE=MATMUL(AINV,POINT)*REAL(NGRID,KIND=8)
    DO IDIR=1,3
      RELATIVE(IDIR)=MODULO(RELATIVE(IDIR),REAL(NGRID(IDIR),KIND=8))
      BASE(IDIR)=FLOOR(RELATIVE(IDIR))
      FRACTION=RELATIVE(IDIR)-REAL(BASE(IDIR),KIND=8)
      IF(PRESENT(DWEIGHT)) THEN
        CALL PAW_SKALA_LAGRANGE_WEIGHTS(FRACTION,WEIGHT(:,IDIR) &
 &                                      ,DWEIGHT(:,IDIR))
      ELSE
        CALL PAW_SKALA_LAGRANGE_WEIGHTS(FRACTION,WEIGHT(:,IDIR))
      END IF
    END DO
  END SUBROUTINE PAW_SKALA_INTERPOLATION_DATA

  SUBROUTINE PAW_SKALA_GRID_INTERPOLATE(NR1,NR2,NR3,RBAS,FIELD,POINT,VALUE)
    IMPLICIT NONE
    INTEGER(4),INTENT(IN) :: NR1,NR2,NR3
    REAL(8),INTENT(IN) :: RBAS(3,3),FIELD(NR1,NR2,NR3),POINT(3)
    REAL(8),INTENT(OUT) :: VALUE
    INTEGER(4) :: BASE(3),I1,I2,I3,J1,J2,J3
    REAL(8) :: WEIGHT(INTERP_N,3),AINV(3,3),COEFFICIENT

    CALL PAW_SKALA_INTERPOLATION_DATA(NR1,NR2,NR3,RBAS,POINT &
 &                                    ,BASE,WEIGHT,AINV=AINV)
    VALUE=0.D0
    DO I3=INTERP_MIN,INTERP_MAX
      J3=MODULO(BASE(3)+I3,NR3)+1
      DO I2=INTERP_MIN,INTERP_MAX
        J2=MODULO(BASE(2)+I2,NR2)+1
        DO I1=INTERP_MIN,INTERP_MAX
          J1=MODULO(BASE(1)+I1,NR1)+1
          COEFFICIENT=WEIGHT(I1-INTERP_MIN+1,1) &
 &                   *WEIGHT(I2-INTERP_MIN+1,2) &
 &                   *WEIGHT(I3-INTERP_MIN+1,3)
          VALUE=VALUE+COEFFICIENT*FIELD(J1,J2,J3)
        END DO
      END DO
    END DO
  END SUBROUTINE PAW_SKALA_GRID_INTERPOLATE

  SUBROUTINE PAW_SKALA_GRID_INTERPOLATE_GRADIENT(NR1,NR2,NR3,RBAS &
 &                                               ,FIELD,POINT,GRADIENT)
    IMPLICIT NONE
    INTEGER(4),INTENT(IN) :: NR1,NR2,NR3
    REAL(8),INTENT(IN) :: RBAS(3,3),FIELD(NR1,NR2,NR3),POINT(3)
    REAL(8),INTENT(OUT) :: GRADIENT(3)
    INTEGER(4) :: BASE(3),I1,I2,I3,J1,J2,J3,IDIR,JDIR,INDEX(3),NGRID(3)
    REAL(8) :: WEIGHT(INTERP_N,3),DWEIGHT(INTERP_N,3),AINV(3,3)
    REAL(8) :: COEFFICIENT,GRADREL(3)

    CALL PAW_SKALA_INTERPOLATION_DATA(NR1,NR2,NR3,RBAS,POINT &
 &                                    ,BASE,WEIGHT,DWEIGHT,AINV)
    NGRID=(/NR1,NR2,NR3/)
    GRADREL=0.D0
    DO I3=INTERP_MIN,INTERP_MAX
      J3=MODULO(BASE(3)+I3,NR3)+1
      DO I2=INTERP_MIN,INTERP_MAX
        J2=MODULO(BASE(2)+I2,NR2)+1
        DO I1=INTERP_MIN,INTERP_MAX
          J1=MODULO(BASE(1)+I1,NR1)+1
          INDEX=(/I1-INTERP_MIN+1,I2-INTERP_MIN+1,I3-INTERP_MIN+1/)
          DO IDIR=1,3
            COEFFICIENT=1.D0
            DO JDIR=1,3
              IF(JDIR.EQ.IDIR) THEN
                COEFFICIENT=COEFFICIENT*DWEIGHT(INDEX(JDIR),JDIR)
              ELSE
                COEFFICIENT=COEFFICIENT*WEIGHT(INDEX(JDIR),JDIR)
              END IF
            END DO
            GRADREL(IDIR)=GRADREL(IDIR)+COEFFICIENT*FIELD(J1,J2,J3)
          END DO
        END DO
      END DO
    END DO
    GRADIENT=MATMUL(TRANSPOSE(AINV),REAL(NGRID,KIND=8)*GRADREL)
  END SUBROUTINE PAW_SKALA_GRID_INTERPOLATE_GRADIENT

  SUBROUTINE PAW_SKALA_GRID_INTERPOLATION_ADJOINT(NR1,NR2,NR3,RBAS &
 &                                                ,FIELD,POINT,VALUE)
    IMPLICIT NONE
    INTEGER(4),INTENT(IN) :: NR1,NR2,NR3
    REAL(8),INTENT(IN) :: RBAS(3,3),POINT(3),VALUE
    REAL(8),INTENT(INOUT) :: FIELD(NR1,NR2,NR3)
    INTEGER(4) :: BASE(3),I1,I2,I3,J1,J2,J3
    REAL(8) :: WEIGHT(INTERP_N,3),AINV(3,3),COEFFICIENT

    CALL PAW_SKALA_INTERPOLATION_DATA(NR1,NR2,NR3,RBAS,POINT &
 &                                    ,BASE,WEIGHT,AINV=AINV)
    DO I3=INTERP_MIN,INTERP_MAX
      J3=MODULO(BASE(3)+I3,NR3)+1
      DO I2=INTERP_MIN,INTERP_MAX
        J2=MODULO(BASE(2)+I2,NR2)+1
        DO I1=INTERP_MIN,INTERP_MAX
          J1=MODULO(BASE(1)+I1,NR1)+1
          COEFFICIENT=WEIGHT(I1-INTERP_MIN+1,1) &
 &                   *WEIGHT(I2-INTERP_MIN+1,2) &
 &                   *WEIGHT(I3-INTERP_MIN+1,3)
          FIELD(J1,J2,J3)=FIELD(J1,J2,J3)+COEFFICIENT*VALUE
        END DO
      END DO
    END DO
  END SUBROUTINE PAW_SKALA_GRID_INTERPOLATION_ADJOINT

  PURE REAL(8) FUNCTION PAW_SKALA_BECKE_SHAPE(MU)
    IMPLICIT NONE
    REAL(8),INTENT(IN) :: MU
    INTEGER(4) :: I
    PAW_SKALA_BECKE_SHAPE=MU
    DO I=1,3
      PAW_SKALA_BECKE_SHAPE=0.5D0*PAW_SKALA_BECKE_SHAPE &
 &                         *(3.D0-PAW_SKALA_BECKE_SHAPE**2)
    END DO
  END FUNCTION PAW_SKALA_BECKE_SHAPE

  SUBROUTINE PAW_SKALA_NEAREST_IMAGE(POINT,ATOM,RBAS,IMAGE,DISTANCE)
    IMPLICIT NONE
    REAL(8),INTENT(IN) :: POINT(3),ATOM(3),RBAS(3,3)
    REAL(8),INTENT(OUT) :: IMAGE(3),DISTANCE
    REAL(8) :: AINV(3,3),DR(3),TRIAL(3),BEST2,R2
    INTEGER(4) :: CENTER(3),SHIFT(3),I1,I2,I3

    CALL PAW_SKALA_INVERSE3(RBAS,AINV)
    DR=ATOM-POINT
    CENTER=NINT(MATMUL(AINV,DR))
    BEST2=HUGE(BEST2)
    DO I3=-1,1
      DO I2=-1,1
        DO I1=-1,1
          SHIFT=CENTER+(/I1,I2,I3/)
          TRIAL=DR-MATMUL(RBAS,REAL(SHIFT,KIND=8))
          R2=DOT_PRODUCT(TRIAL,TRIAL)
          IF(R2.LT.BEST2) THEN
            BEST2=R2
            IMAGE=POINT+TRIAL
          END IF
        END DO
      END DO
    END DO
    DISTANCE=SQRT(BEST2)
  END SUBROUTINE PAW_SKALA_NEAREST_IMAGE

  SUBROUTINE PAW_SKALA_SMOOTH_PARTITION(POINT,NAT,ATOMCOORD,RBAS,WEIGHT)
    IMPLICIT NONE
    INTEGER(4),INTENT(IN) :: NAT
    REAL(8),INTENT(IN) :: POINT(3),ATOMCOORD(NAT,3),RBAS(3,3)
    REAL(8),INTENT(OUT) :: WEIGHT(NAT)
    REAL(8) :: IMAGE(NAT,3),DISTANCE(NAT),PAIR(3),RAB,MU,SWITCH,TOTAL
    INTEGER(4) :: I,J,IMIN

    DO I=1,NAT
      CALL PAW_SKALA_NEAREST_IMAGE(POINT,ATOMCOORD(I,:),RBAS &
 &                                 ,IMAGE(I,:),DISTANCE(I))
    END DO
    WEIGHT=1.D0
    DO I=1,NAT-1
      DO J=I+1,NAT
        PAIR=IMAGE(I,:)-IMAGE(J,:)
        RAB=SQRT(DOT_PRODUCT(PAIR,PAIR))
        IF(RAB.LE.1.D-14) CYCLE
        MU=(DISTANCE(I)-DISTANCE(J))/RAB
        MU=MAX(-1.D0,MIN(1.D0,MU))
        SWITCH=0.5D0*(1.D0-PAW_SKALA_BECKE_SHAPE(MU))
        WEIGHT(I)=WEIGHT(I)*SWITCH
        WEIGHT(J)=WEIGHT(J)*(1.D0-SWITCH)
      END DO
    END DO
    TOTAL=SUM(WEIGHT)
    IF(TOTAL.GT.0.D0) THEN
      WEIGHT=WEIGHT/TOTAL
    ELSE
      IMIN=MINLOC(DISTANCE,DIM=1)
      WEIGHT=0.D0
      WEIGHT(IMIN)=1.D0
    END IF
  END SUBROUTINE PAW_SKALA_SMOOTH_PARTITION

  SUBROUTINE PAW_SKALA_GRID_TEST(MAXERROR)
    IMPLICIT NONE
    REAL(8),INTENT(OUT) :: MAXERROR
    INTEGER(4),PARAMETER :: NR1=12,NR2=11,NR3=10,NAT=2
    REAL(8) :: RBAS(3,3),FIELD(NR1,NR2,NR3),ADJOINT(NR1,NR2,NR3)
    REAL(8) :: POINT(3),POINT2(3),ATOMCOORD(NAT,3),WEIGHT(NAT),WEIGHT2(NAT)
    REAL(8) :: VALUE,VALUE1,LHS,RHS,GRAD(3),GRADFD(3),STEP
    INTEGER(4) :: I1,I2,I3,IDIR

    RBAS=RESHAPE((/8.D0,0.D0,0.D0,1.2D0,7.D0,0.D0 &
 &                ,0.4D0,0.8D0,6.D0/),(/3,3/))
    DO I3=1,NR3
      DO I2=1,NR2
        DO I1=1,NR1
          FIELD(I1,I2,I3)=SIN(0.31D0*REAL(I1,KIND=8)) &
 &                       +COS(0.27D0*REAL(I2,KIND=8)) &
 &                       +0.03D0*REAL(I3**2,KIND=8)
        END DO
      END DO
    END DO
    POINT=MATMUL(RBAS,(/3.D0/NR1,4.D0/NR2,2.D0/NR3/))
    CALL PAW_SKALA_GRID_INTERPOLATE(NR1,NR2,NR3,RBAS,FIELD,POINT,VALUE)
    MAXERROR=ABS(VALUE-FIELD(4,5,3))

    POINT=MATMUL(RBAS,(/0.237D0,0.419D0,0.713D0/))
    VALUE1=-0.371D0
    CALL PAW_SKALA_GRID_INTERPOLATE(NR1,NR2,NR3,RBAS,FIELD,POINT,VALUE)
    ADJOINT=0.D0
    CALL PAW_SKALA_GRID_INTERPOLATION_ADJOINT(NR1,NR2,NR3,RBAS &
 &                                            ,ADJOINT,POINT,VALUE1)
    LHS=VALUE*VALUE1
    RHS=SUM(FIELD*ADJOINT)
    MAXERROR=MAX(MAXERROR,ABS(LHS-RHS))

    CALL PAW_SKALA_GRID_INTERPOLATE_GRADIENT(NR1,NR2,NR3,RBAS &
 &                                            ,FIELD,POINT,GRAD)
    STEP=1.D-5
    DO IDIR=1,3
      POINT2=POINT
      POINT2(IDIR)=POINT2(IDIR)+STEP
      CALL PAW_SKALA_GRID_INTERPOLATE(NR1,NR2,NR3,RBAS,FIELD,POINT2,LHS)
      POINT2(IDIR)=POINT(IDIR)-STEP
      CALL PAW_SKALA_GRID_INTERPOLATE(NR1,NR2,NR3,RBAS,FIELD,POINT2,RHS)
      GRADFD(IDIR)=(LHS-RHS)/(2.D0*STEP)
    END DO
    MAXERROR=MAX(MAXERROR,MAXVAL(ABS(GRAD-GRADFD)))

    ATOMCOORD(1,:)=MATMUL(RBAS,(/0.1D0,0.2D0,0.3D0/))
    ATOMCOORD(2,:)=MATMUL(RBAS,(/0.6D0,0.2D0,0.3D0/))
    POINT=0.5D0*(ATOMCOORD(1,:)+ATOMCOORD(2,:))
    CALL PAW_SKALA_SMOOTH_PARTITION(POINT,NAT,ATOMCOORD,RBAS,WEIGHT)
    POINT2=POINT+RBAS(:,1)
    CALL PAW_SKALA_SMOOTH_PARTITION(POINT2,NAT,ATOMCOORD,RBAS,WEIGHT2)
    MAXERROR=MAX(MAXERROR,ABS(SUM(WEIGHT)-1.D0))
    MAXERROR=MAX(MAXERROR,MAXVAL(ABS(WEIGHT-WEIGHT2)))
    MAXERROR=MAX(MAXERROR,ABS(WEIGHT(1)-0.5D0),ABS(WEIGHT(2)-0.5D0))
  END SUBROUTINE PAW_SKALA_GRID_TEST

END MODULE PAW_SKALA_GRID_MODULE
