! SPDX-License-Identifier: GPL-3.0-or-later

      MODULE PAW_SKALA_MODULE
#IF DEFINED(CPPVAR_SKALA_FTORCH)
      USE PAW_SKALA_BRIDGE, ONLY: PAW_SKALA_MODEL, PAW_SKALA_LOAD &
     &                           ,PAW_SKALA_EVALUATE, PAW_SKALA_RELEASE &
     &                           ,PAW_SKALA_CUDA_AVAILABLE
#ENDIF
      IMPLICIT NONE
#IF DEFINED(CPPVAR_SKALA_FTORCH)
      TYPE(PAW_SKALA_MODEL),SAVE :: MODEL
#ENDIF
      LOGICAL(4),SAVE :: TINITIALIZED=.FALSE.
      LOGICAL(4),SAVE :: TON=.FALSE.
      LOGICAL(4),SAVE :: CONFIG_APPLY=.FALSE.
      LOGICAL(4),SAVE :: CONFIG_APPLYSMOOTH=.TRUE.
      LOGICAL(4),SAVE :: CONFIG_APPLYTAU=.TRUE.
      LOGICAL(4),SAVE :: CONFIG_APPLYONECENTER=.TRUE.
      LOGICAL(4),SAVE :: CONFIG_INTERPOLATEPARTITION=.FALSE.
      LOGICAL(4),SAVE :: CONFIG_CHECK=.FALSE.
      LOGICAL(4),SAVE :: CONFIG_NEEDFORCE=.FALSE.
      LOGICAL(4),SAVE :: CONFIG_NEEDSTRESS=.FALSE.
      CHARACTER(2048),SAVE :: CONFIG_MODELFILE=' '
      CHARACTER(16),SAVE :: CONFIG_DEVICE='AUTO'
      INTEGER(4),SAVE :: CONFIG_DEVICEINDEX=-1
      INTEGER(4),PARAMETER :: LOCAL_NRADIAL=100,LOCAL_LEBEDEV_L=17
      LOGICAL(4),ALLOCATABLE,SAVE :: TONECENTERREPORTED(:)
      LOGICAL(4),SAVE :: TONECENTERCHECKED=.FALSE.
      LOGICAL(4),SAVE :: TSMOOTHREPORTED=.FALSE.
      LOGICAL(4),SAVE :: TSMOOTHREADY=.FALSE.
      INTEGER(4),SAVE :: SMOOTH_NR1=0,SMOOTH_NR2=0,SMOOTH_NR3=0
      INTEGER(4),SAVE :: SMOOTH_NDIMD=0
      REAL(8),SAVE :: SMOOTH_RBAS(3,3)=0.D0
      REAL(8),SAVE :: SMOOTH_DVOL=0.D0
      REAL(8),ALLOCATABLE,SAVE :: SMOOTH_RHO(:,:,:,:)
      REAL(8),ALLOCATABLE,SAVE :: SMOOTH_GRHO(:,:,:,:,:)
      REAL(8),ALLOCATABLE,SAVE :: SMOOTH_TAU(:,:,:,:)
      REAL(8),ALLOCATABLE,SAVE :: SMOOTH_ADJ_RHO(:,:,:,:)
      REAL(8),ALLOCATABLE,SAVE :: SMOOTH_ADJ_GRHO(:,:,:,:,:)
      REAL(8),ALLOCATABLE,SAVE :: SMOOTH_ADJ_TAU(:,:,:,:)
      REAL(8),ALLOCATABLE,SAVE :: SMOOTH_PARTITION(:,:,:,:)
      REAL(8),ALLOCATABLE,SAVE :: SMOOTH_PARTITION_SENSITIVITY(:,:,:,:)
      INTEGER(4),SAVE :: SMOOTH_PARTITION_NCLASS=0
      INTEGER(4),ALLOCATABLE,SAVE :: SMOOTH_ATOM_CLASS(:)
      LOGICAL(4),ALLOCATABLE,SAVE :: LOCAL_PARTITION_READY(:)
      REAL(8),ALLOCATABLE,SAVE :: LOCAL_PARTITION_RCUT(:)
      REAL(8),ALLOCATABLE,SAVE :: LOCAL_PARTITION_CACHE(:,:)
      REAL(8),SAVE :: FORWARD_ENERGY=0.D0
      REAL(8),SAVE :: FORWARD_ELECTRONS=0.D0
      REAL(8),SAVE :: FORWARD_TAU=0.D0
      REAL(8),SAVE :: FORWARD_SMOOTH_ELECTRONS=0.D0
      REAL(8),SAVE :: FORWARD_CORRECTION_ELECTRONS=0.D0
      REAL(8),SAVE :: FORWARD_SMOOTH_TAU=0.D0
      REAL(8),SAVE :: FORWARD_CORRECTION_TAU=0.D0
      REAL(8),SAVE :: FORWARD_ONECENTER_ADJOINT_NORM2=0.D0
      REAL(8),SAVE :: FORWARD_ONECENTER_CONTRACTION=0.D0
      REAL(8),ALLOCATABLE,SAVE :: FORWARD_ATOM_ENERGY(:)
      INTEGER(4),ALLOCATABLE,SAVE :: FORWARD_ATOM_NPOINT(:)
      REAL(8),ALLOCATABLE,SAVE :: FORWARD_DERIV(:,:)
      REAL(8),ALLOCATABLE,SAVE :: FORWARD_DERIV_MODEL_ATOM(:,:)
      REAL(8),ALLOCATABLE,SAVE :: FORWARD_DERIV_LOCAL_GRID(:,:)
      REAL(8),ALLOCATABLE,SAVE :: FORWARD_DERIV_LOCAL_PRIMITIVE(:,:)
      REAL(8),ALLOCATABLE,SAVE :: FORWARD_DERIV_LOCAL_PARTITION(:,:)
      REAL(8),ALLOCATABLE,SAVE :: FORWARD_DERIV_SMOOTH_PARTITION(:,:)
      REAL(8),ALLOCATABLE,SAVE :: FORWARD_DERIV_RADIAL_BLEND(:,:)
      INTEGER(4),SAVE :: FORWARD_NPOINT=0
      LOGICAL(4),SAVE :: TFORWARDREPORTED=.FALSE.
      LOGICAL(4),SAVE :: TOPERATORREPORTED=.FALSE.
      LOGICAL(4),SAVE :: TTAUCONTRACTIONREADY=.FALSE.
      REAL(8),SAVE :: SMOOTH_TAU_CONTRACTION=0.D0
      LOGICAL(4),SAVE :: TSCALARCONTRACTIONREADY=.FALSE.
      REAL(8),SAVE :: SMOOTH_SCALAR_CONTRACTION=0.D0
      LOGICAL(4),SAVE :: TONECENTERCONTRACTIONREADY=.FALSE.
      REAL(8),SAVE :: ONECENTER_CONTRACTION=0.D0
      END MODULE PAW_SKALA_MODULE

!     ..................................................................
      SUBROUTINE SKALA$SETL4(ID,VAL)
      USE PAW_SKALA_MODULE
      IMPLICIT NONE
      CHARACTER(*),INTENT(IN) :: ID
      LOGICAL(4),INTENT(IN)   :: VAL
      IF(ID.EQ.'ON') THEN
        TON=VAL
      ELSE IF(ID.EQ.'APPLY') THEN
        CONFIG_APPLY=VAL
      ELSE IF(ID.EQ.'APPLYSMOOTH') THEN
        CONFIG_APPLYSMOOTH=VAL
      ELSE IF(ID.EQ.'APPLYTAU') THEN
        CONFIG_APPLYTAU=VAL
      ELSE IF(ID.EQ.'APPLYONECENTER') THEN
        CONFIG_APPLYONECENTER=VAL
      ELSE IF(ID.EQ.'INTERPOLATEPARTITION') THEN
        CONFIG_INTERPOLATEPARTITION=VAL
      ELSE IF(ID.EQ.'CHECK') THEN
        CONFIG_CHECK=VAL
      ELSE IF(ID.EQ.'NEEDFORCE') THEN
        CONFIG_NEEDFORCE=VAL
      ELSE IF(ID.EQ.'NEEDSTRESS') THEN
        CONFIG_NEEDSTRESS=VAL
      ELSE
        CALL ERROR$MSG('ID NOT RECOGNIZED')
        CALL ERROR$CHVAL('ID',ID)
        CALL ERROR$STOP('SKALA$SETL4')
      END IF
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$GETL4(ID,VAL)
      USE PAW_SKALA_MODULE
      IMPLICIT NONE
      CHARACTER(*),INTENT(IN) :: ID
      LOGICAL(4),INTENT(OUT)  :: VAL
      IF(ID.EQ.'ON') THEN
        VAL=TON
      ELSE IF(ID.EQ.'APPLY') THEN
        VAL=CONFIG_APPLY
      ELSE IF(ID.EQ.'APPLYSMOOTH') THEN
        VAL=CONFIG_APPLYSMOOTH
      ELSE IF(ID.EQ.'APPLYTAU') THEN
        VAL=CONFIG_APPLYTAU
      ELSE IF(ID.EQ.'APPLYONECENTER') THEN
        VAL=CONFIG_APPLYONECENTER
      ELSE IF(ID.EQ.'INTERPOLATEPARTITION') THEN
        VAL=CONFIG_INTERPOLATEPARTITION
      ELSE IF(ID.EQ.'CHECK') THEN
        VAL=CONFIG_CHECK
      ELSE IF(ID.EQ.'NEEDFORCE') THEN
        VAL=CONFIG_NEEDFORCE
      ELSE IF(ID.EQ.'NEEDSTRESS') THEN
        VAL=CONFIG_NEEDSTRESS
      ELSE
        CALL ERROR$MSG('ID NOT RECOGNIZED')
        CALL ERROR$CHVAL('ID',ID)
        CALL ERROR$STOP('SKALA$GETL4')
      END IF
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$SETCH(ID,VAL)
      USE PAW_SKALA_MODULE
      IMPLICIT NONE
      CHARACTER(*),INTENT(IN) :: ID
      CHARACTER(*),INTENT(IN) :: VAL
      IF(ID.EQ.'MODEL') THEN
        CONFIG_MODELFILE=TRIM(VAL)
      ELSE IF(ID.EQ.'DEVICE') THEN
        CONFIG_DEVICE=TRIM(VAL)
      ELSE
        CALL ERROR$MSG('ID NOT RECOGNIZED')
        CALL ERROR$CHVAL('ID',ID)
        CALL ERROR$STOP('SKALA$SETCH')
      END IF
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$SETI4(ID,VAL)
      USE PAW_SKALA_MODULE
      IMPLICIT NONE
      CHARACTER(*),INTENT(IN) :: ID
      INTEGER(4),INTENT(IN)   :: VAL
      IF(ID.EQ.'DEVICEINDEX') THEN
        CONFIG_DEVICEINDEX=VAL
      ELSE
        CALL ERROR$MSG('ID NOT RECOGNIZED')
        CALL ERROR$CHVAL('ID',ID)
        CALL ERROR$STOP('SKALA$SETI4')
      END IF
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$REPORT(NFIL)
      USE PAW_SKALA_MODULE
      IMPLICIT NONE
      INTEGER(4),INTENT(IN) :: NFIL
      IF(.NOT.TON) RETURN
      WRITE(NFIL,FMT='(/"SKALA 1.1 PAW INTEGRATION"/25("="))')
      WRITE(NFIL,FMT='("STATUS",T30,A)')'COMPLETE PAW ATOM-BLOCK VALIDATION'
      WRITE(NFIL,FMT='("MODEL FILE",T30,A)')TRIM(CONFIG_MODELFILE)
      WRITE(NFIL,FMT='("DEVICE",T30,A)')TRIM(CONFIG_DEVICE)
      WRITE(NFIL,FMT='("DEVICE INDEX",T30,I8)')CONFIG_DEVICEINDEX
      WRITE(NFIL,FMT='("APPLY TO HAMILTONIAN",T30,L8)')CONFIG_APPLY
      WRITE(NFIL,FMT='("INTERPOLATE PARTITION",T30,L8)') &
     &     CONFIG_INTERPOLATEPARTITION
      WRITE(NFIL,FMT='("CHECK MODEL ADJOINTS",T30,L8)')CONFIG_CHECK
      IF(CONFIG_APPLY) THEN
        WRITE(NFIL,FMT='("APPLY SMOOTH OPERATOR",T30,L8)')CONFIG_APPLYSMOOTH
        WRITE(NFIL,FMT='("APPLY TAU OPERATOR",T30,L8)')CONFIG_APPLYTAU
        WRITE(NFIL,FMT='("APPLY ONE-CENTER OPERATOR",T30,L8)') &
     &       CONFIG_APPLYONECENTER
        WRITE(NFIL,FMT='("ANALYTIC ATOMIC FORCES",T30,A)')'AVAILABLE'
        WRITE(NFIL,FMT='("STRESS",T30,A)')'NOT YET AVAILABLE'
      END IF
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$AVAILABLE(TAVAILABLE)
      IMPLICIT NONE
      LOGICAL(4),INTENT(OUT) :: TAVAILABLE
#IF DEFINED(CPPVAR_SKALA_FTORCH)
      TAVAILABLE=.TRUE.
#ELSE
      TAVAILABLE=.FALSE.
#ENDIF
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$INITIALIZE(MODELFILE,DEVICE,DEVICEINDEX)
      USE PAW_SKALA_MODULE
      IMPLICIT NONE
      CHARACTER(*),INTENT(IN) :: MODELFILE
      CHARACTER(*),INTENT(IN) :: DEVICE
      INTEGER(4)  ,INTENT(IN) :: DEVICEINDEX
#IF DEFINED(CPPVAR_SKALA_FTORCH)
      INTEGER(4)              :: STATUS
      CHARACTER(2048)         :: MESSAGE
      CHARACTER(16)           :: DEVICE1

      IF(TINITIALIZED) CALL PAW_SKALA_RELEASE(MODEL)
      DEVICE1=DEVICE
      IF(TRIM(DEVICE1).EQ.'AUTO'.OR.TRIM(DEVICE1).EQ.'auto') THEN
        IF(PAW_SKALA_CUDA_AVAILABLE()) THEN
          DEVICE1='CUDA'
        ELSE
          DEVICE1='CPU'
        END IF
      END IF
      CALL PAW_SKALA_LOAD(MODEL,MODELFILE,DEVICE1,DEVICEINDEX,STATUS,MESSAGE)
      IF(STATUS.NE.0) THEN
        CALL ERROR$MSG('FAILED TO INITIALIZE SKALA 1.1')
        CALL ERROR$CHVAL('DETAIL',TRIM(MESSAGE))
        CALL ERROR$STOP('SKALA$INITIALIZE')
      END IF
      TINITIALIZED=.TRUE.
#ELSE
      CALL ERROR$MSG('CP-PAW WAS BUILT WITHOUT THE SKALA/FTORCH BRIDGE')
      CALL ERROR$STOP('SKALA$INITIALIZE')
#ENDIF
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$ENSUREINITIALIZED
      USE PAW_SKALA_MODULE
      IMPLICIT NONE
      IF(TINITIALIZED) RETURN
      IF(.NOT.TON) THEN
        CALL ERROR$MSG('SKALA FUNCTIONAL IS NOT ENABLED')
        CALL ERROR$STOP('SKALA$ENSUREINITIALIZED')
      END IF
      IF(LEN_TRIM(CONFIG_MODELFILE).EQ.0) THEN
        CALL ERROR$MSG('SKALA MODEL FILE HAS NOT BEEN SPECIFIED')
        CALL ERROR$STOP('SKALA$ENSUREINITIALIZED')
      END IF
      CALL SKALA$INITIALIZE(TRIM(CONFIG_MODELFILE),TRIM(CONFIG_DEVICE) &
     &                     ,CONFIG_DEVICEINDEX)
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$FINALIZE
      USE PAW_SKALA_MODULE
      IMPLICIT NONE
#IF DEFINED(CPPVAR_SKALA_FTORCH)
      IF(TINITIALIZED) CALL PAW_SKALA_RELEASE(MODEL)
#ENDIF
      TINITIALIZED=.FALSE.
      TSMOOTHREPORTED=.FALSE.
      TSMOOTHREADY=.FALSE.
      TFORWARDREPORTED=.FALSE.
      TOPERATORREPORTED=.FALSE.
      TTAUCONTRACTIONREADY=.FALSE.
      SMOOTH_TAU_CONTRACTION=0.D0
      TSCALARCONTRACTIONREADY=.FALSE.
      SMOOTH_SCALAR_CONTRACTION=0.D0
      TONECENTERCONTRACTIONREADY=.FALSE.
      ONECENTER_CONTRACTION=0.D0
      IF(ALLOCATED(TONECENTERREPORTED)) DEALLOCATE(TONECENTERREPORTED)
      IF(ALLOCATED(SMOOTH_RHO)) DEALLOCATE(SMOOTH_RHO)
      IF(ALLOCATED(SMOOTH_GRHO)) DEALLOCATE(SMOOTH_GRHO)
      IF(ALLOCATED(SMOOTH_TAU)) DEALLOCATE(SMOOTH_TAU)
      IF(ALLOCATED(SMOOTH_PARTITION)) DEALLOCATE(SMOOTH_PARTITION)
      IF(ALLOCATED(SMOOTH_PARTITION_SENSITIVITY)) &
     &  DEALLOCATE(SMOOTH_PARTITION_SENSITIVITY)
      IF(ALLOCATED(SMOOTH_ATOM_CLASS)) DEALLOCATE(SMOOTH_ATOM_CLASS)
      IF(ALLOCATED(LOCAL_PARTITION_READY)) DEALLOCATE(LOCAL_PARTITION_READY)
      IF(ALLOCATED(LOCAL_PARTITION_RCUT)) DEALLOCATE(LOCAL_PARTITION_RCUT)
      IF(ALLOCATED(LOCAL_PARTITION_CACHE)) DEALLOCATE(LOCAL_PARTITION_CACHE)
      IF(ALLOCATED(SMOOTH_ADJ_RHO)) DEALLOCATE(SMOOTH_ADJ_RHO)
      IF(ALLOCATED(SMOOTH_ADJ_GRHO)) DEALLOCATE(SMOOTH_ADJ_GRHO)
      IF(ALLOCATED(SMOOTH_ADJ_TAU)) DEALLOCATE(SMOOTH_ADJ_TAU)
      IF(ALLOCATED(FORWARD_ATOM_ENERGY)) DEALLOCATE(FORWARD_ATOM_ENERGY)
      IF(ALLOCATED(FORWARD_ATOM_NPOINT)) DEALLOCATE(FORWARD_ATOM_NPOINT)
      IF(ALLOCATED(FORWARD_DERIV)) DEALLOCATE(FORWARD_DERIV)
      IF(ALLOCATED(FORWARD_DERIV_MODEL_ATOM)) &
     &  DEALLOCATE(FORWARD_DERIV_MODEL_ATOM)
      IF(ALLOCATED(FORWARD_DERIV_LOCAL_GRID)) &
     &  DEALLOCATE(FORWARD_DERIV_LOCAL_GRID)
      IF(ALLOCATED(FORWARD_DERIV_LOCAL_PRIMITIVE)) &
     &  DEALLOCATE(FORWARD_DERIV_LOCAL_PRIMITIVE)
      IF(ALLOCATED(FORWARD_DERIV_LOCAL_PARTITION)) &
     &  DEALLOCATE(FORWARD_DERIV_LOCAL_PARTITION)
      IF(ALLOCATED(FORWARD_DERIV_SMOOTH_PARTITION)) &
     &  DEALLOCATE(FORWARD_DERIV_SMOOTH_PARTITION)
      IF(ALLOCATED(FORWARD_DERIV_RADIAL_BLEND)) &
     &  DEALLOCATE(FORWARD_DERIV_RADIAL_BLEND)
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$FORWARDBEGIN
      USE PAW_SKALA_MODULE
      IMPLICIT NONE
      INTEGER(4) :: NAT
      IF(.NOT.TON) RETURN
      IF(.NOT.TSMOOTHREADY) THEN
        CALL ERROR$MSG('SKALA SMOOTH FIELDS ARE NOT AVAILABLE')
        CALL ERROR$STOP('SKALA$FORWARDBEGIN')
      END IF
      FORWARD_ENERGY=0.D0
      FORWARD_ELECTRONS=0.D0
      FORWARD_TAU=0.D0
      FORWARD_SMOOTH_ELECTRONS=0.D0
      FORWARD_CORRECTION_ELECTRONS=0.D0
      FORWARD_SMOOTH_TAU=0.D0
      FORWARD_CORRECTION_TAU=0.D0
      FORWARD_ONECENTER_ADJOINT_NORM2=0.D0
      FORWARD_ONECENTER_CONTRACTION=0.D0
      FORWARD_NPOINT=0
      CALL ATOMLIST$NATOM(NAT)
      IF(ALLOCATED(FORWARD_ATOM_ENERGY)) DEALLOCATE(FORWARD_ATOM_ENERGY)
      IF(ALLOCATED(FORWARD_ATOM_NPOINT)) DEALLOCATE(FORWARD_ATOM_NPOINT)
      ALLOCATE(FORWARD_ATOM_ENERGY(NAT),FORWARD_ATOM_NPOINT(NAT))
      FORWARD_ATOM_ENERGY=0.D0
      FORWARD_ATOM_NPOINT=0
      IF(ALLOCATED(SMOOTH_ADJ_RHO)) DEALLOCATE(SMOOTH_ADJ_RHO)
      IF(ALLOCATED(SMOOTH_ADJ_GRHO)) DEALLOCATE(SMOOTH_ADJ_GRHO)
      IF(ALLOCATED(SMOOTH_ADJ_TAU)) DEALLOCATE(SMOOTH_ADJ_TAU)
      ALLOCATE(SMOOTH_ADJ_RHO(SMOOTH_NR1,SMOOTH_NR2,SMOOTH_NR3 &
     &                       ,SMOOTH_NDIMD))
      ALLOCATE(SMOOTH_ADJ_GRHO(SMOOTH_NR1,SMOOTH_NR2,SMOOTH_NR3,3 &
     &                        ,SMOOTH_NDIMD))
      ALLOCATE(SMOOTH_ADJ_TAU(SMOOTH_NR1,SMOOTH_NR2,SMOOTH_NR3 &
     &                       ,SMOOTH_NDIMD))
      SMOOTH_ADJ_RHO=0.D0
      SMOOTH_ADJ_GRHO=0.D0
      SMOOTH_ADJ_TAU=0.D0
      IF(ALLOCATED(FORWARD_DERIV)) DEALLOCATE(FORWARD_DERIV)
      IF(ALLOCATED(FORWARD_DERIV_MODEL_ATOM)) &
     &  DEALLOCATE(FORWARD_DERIV_MODEL_ATOM)
      IF(ALLOCATED(FORWARD_DERIV_LOCAL_GRID)) &
     &  DEALLOCATE(FORWARD_DERIV_LOCAL_GRID)
      IF(ALLOCATED(FORWARD_DERIV_LOCAL_PRIMITIVE)) &
     &  DEALLOCATE(FORWARD_DERIV_LOCAL_PRIMITIVE)
      IF(ALLOCATED(FORWARD_DERIV_LOCAL_PARTITION)) &
     &  DEALLOCATE(FORWARD_DERIV_LOCAL_PARTITION)
      IF(ALLOCATED(FORWARD_DERIV_SMOOTH_PARTITION)) &
     &  DEALLOCATE(FORWARD_DERIV_SMOOTH_PARTITION)
      IF(ALLOCATED(FORWARD_DERIV_RADIAL_BLEND)) &
     &  DEALLOCATE(FORWARD_DERIV_RADIAL_BLEND)
      IF(ALLOCATED(SMOOTH_PARTITION_SENSITIVITY)) &
     &  DEALLOCATE(SMOOTH_PARTITION_SENSITIVITY)
      IF(CONFIG_APPLY.AND.CONFIG_NEEDFORCE) THEN
        ALLOCATE(FORWARD_DERIV(3,NAT))
        ALLOCATE(FORWARD_DERIV_MODEL_ATOM(3,NAT))
        ALLOCATE(FORWARD_DERIV_LOCAL_GRID(3,NAT))
        ALLOCATE(FORWARD_DERIV_LOCAL_PRIMITIVE(3,NAT))
        ALLOCATE(FORWARD_DERIV_LOCAL_PARTITION(3,NAT))
        ALLOCATE(FORWARD_DERIV_SMOOTH_PARTITION(3,NAT))
        ALLOCATE(FORWARD_DERIV_RADIAL_BLEND(3,NAT))
        ALLOCATE(SMOOTH_PARTITION_SENSITIVITY &
     &          (SMOOTH_NR1,SMOOTH_NR2,SMOOTH_NR3,NAT))
        FORWARD_DERIV=0.D0
        FORWARD_DERIV_MODEL_ATOM=0.D0
        FORWARD_DERIV_LOCAL_GRID=0.D0
        FORWARD_DERIV_LOCAL_PRIMITIVE=0.D0
        FORWARD_DERIV_LOCAL_PARTITION=0.D0
        FORWARD_DERIV_SMOOTH_PARTITION=0.D0
        FORWARD_DERIV_RADIAL_BLEND=0.D0
        SMOOTH_PARTITION_SENSITIVITY=0.D0
      END IF
      TTAUCONTRACTIONREADY=.FALSE.
      SMOOTH_TAU_CONTRACTION=0.D0
      TSCALARCONTRACTIONREADY=.FALSE.
      SMOOTH_SCALAR_CONTRACTION=0.D0
      TONECENTERCONTRACTIONREADY=.FALSE.
      ONECENTER_CONTRACTION=0.D0
      CALL SKALA_BUILDPARTITIONCACHE
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA_BUILDPARTITIONCACHE
      USE PAW_SKALA_MODULE
      USE PAW_SKALA_GRID_MODULE, ONLY: PAW_SKALA_SMOOTH_PARTITION &
     &                                ,PAW_SKALA_INVERSE3 &
     &                                ,PAW_SKALA_LOCAL_GRID_SIZE
      USE MPE_MODULE
      IMPLICIT NONE
      INTEGER(4) :: NAT,I1,I2,I3,NTASKS,THISTASK
      INTEGER(4) :: I,J,K,L,NANG,NLOCAL
      REAL(8),PARAMETER :: CLASS_TOL=1.D-10
      REAL(8) :: POINT(3),AINV(3,3),SHIFT(3),DELTA(3)
      LOGICAL(4) :: TEQUIVALENT,TFOUND
      REAL(8),ALLOCATABLE :: ATOMCOORD(:,:),ATOMCOORD3(:,:),PARTITION(:)
      REAL(8),ALLOCATABLE :: FRACTIONAL(:,:)
#IF DEFINED(CPPVAR_ACCEL_PROFILE)
      REAL(8) :: ACCEL_T0,ACCEL_T1
#ENDIF

#IF DEFINED(CPPVAR_ACCEL_PROFILE)
      CALL ACCELPROFILE$NOW(ACCEL_T0)
#ENDIF
      CALL TIMING$CLOCKON('SKALA:PARTITION')
      CALL ATOMLIST$NATOM(NAT)
      ALLOCATE(ATOMCOORD(NAT,3),ATOMCOORD3(3,NAT),PARTITION(NAT))
      CALL ATOMLIST$GETR8A('R(0)',0,3*NAT,ATOMCOORD3)
      ATOMCOORD=TRANSPOSE(ATOMCOORD3)
      CALL PAW_SKALA_INVERSE3(SMOOTH_RBAS,AINV)
      ALLOCATE(FRACTIONAL(NAT,3))
      DO I=1,NAT
        FRACTIONAL(I,:)=MODULO(MATMUL(AINV,ATOMCOORD(I,:)),1.D0)
      END DO
      IF(ALLOCATED(SMOOTH_ATOM_CLASS)) DEALLOCATE(SMOOTH_ATOM_CLASS)
      ALLOCATE(SMOOTH_ATOM_CLASS(NAT))
      SMOOTH_ATOM_CLASS=0
      SMOOTH_PARTITION_NCLASS=0
      DO I=1,NAT
        DO J=1,I-1
          SHIFT=FRACTIONAL(I,:)-FRACTIONAL(J,:)
          TEQUIVALENT=.TRUE.
          DO K=1,NAT
            TFOUND=.FALSE.
            DO L=1,NAT
              DELTA=FRACTIONAL(K,:)+SHIFT-FRACTIONAL(L,:)
              DELTA=DELTA-ANINT(DELTA)
              IF(MAXVAL(ABS(DELTA)).LE.CLASS_TOL) THEN
                TFOUND=.TRUE.
                EXIT
              END IF
            END DO
            IF(.NOT.TFOUND) THEN
              TEQUIVALENT=.FALSE.
              EXIT
            END IF
          END DO
          IF(TEQUIVALENT) THEN
            SMOOTH_ATOM_CLASS(I)=SMOOTH_ATOM_CLASS(J)
            EXIT
          END IF
        END DO
        IF(SMOOTH_ATOM_CLASS(I).EQ.0) THEN
          SMOOTH_PARTITION_NCLASS=SMOOTH_PARTITION_NCLASS+1
          SMOOTH_ATOM_CLASS(I)=SMOOTH_PARTITION_NCLASS
        END IF
      END DO
      CALL PAW_SKALA_LOCAL_GRID_SIZE(LOCAL_NRADIAL,LOCAL_LEBEDEV_L &
     &                              ,NANG,NLOCAL)
      IF(ALLOCATED(LOCAL_PARTITION_READY)) DEALLOCATE(LOCAL_PARTITION_READY)
      IF(ALLOCATED(LOCAL_PARTITION_RCUT)) DEALLOCATE(LOCAL_PARTITION_RCUT)
      IF(ALLOCATED(LOCAL_PARTITION_CACHE)) DEALLOCATE(LOCAL_PARTITION_CACHE)
      ALLOCATE(LOCAL_PARTITION_READY(NAT),LOCAL_PARTITION_RCUT(NAT))
      ALLOCATE(LOCAL_PARTITION_CACHE(NLOCAL,NAT))
      LOCAL_PARTITION_READY=.FALSE.
      LOCAL_PARTITION_RCUT=0.D0
      IF(ALLOCATED(SMOOTH_PARTITION)) DEALLOCATE(SMOOTH_PARTITION)
      ALLOCATE(SMOOTH_PARTITION(SMOOTH_NR1,SMOOTH_NR2,SMOOTH_NR3,NAT))
      SMOOTH_PARTITION=0.D0
      CALL MPE$QUERY('MONOMER',NTASKS,THISTASK)
      IF(THISTASK.EQ.1) THEN
        DO I3=1,SMOOTH_NR3
          DO I2=1,SMOOTH_NR2
            DO I1=1,SMOOTH_NR1
              POINT=MATMUL(SMOOTH_RBAS &
     &              ,(/REAL(I1-1,KIND=8)/REAL(SMOOTH_NR1,KIND=8) &
     &                ,REAL(I2-1,KIND=8)/REAL(SMOOTH_NR2,KIND=8) &
     &                ,REAL(I3-1,KIND=8)/REAL(SMOOTH_NR3,KIND=8)/))
              CALL PAW_SKALA_SMOOTH_PARTITION(POINT,NAT,ATOMCOORD &
     &                                        ,SMOOTH_RBAS,PARTITION)
              SMOOTH_PARTITION(I1,I2,I3,:)=PARTITION
            END DO
          END DO
        END DO
      END IF
      CALL MPE$BROADCAST('MONOMER',1,SMOOTH_PARTITION)
      DEALLOCATE(ATOMCOORD,ATOMCOORD3,PARTITION,FRACTIONAL)
      CALL TIMING$CLOCKOFF('SKALA:PARTITION')
#IF DEFINED(CPPVAR_ACCEL_PROFILE)
      CALL ACCELPROFILE$NOW(ACCEL_T1)
      CALL ACCELPROFILE$ADD('SKALA_PARTITION' &
     &    ,INT(SMOOTH_NR1*SMOOTH_NR2*SMOOTH_NR3,KIND=8),INT(NAT,KIND=8) &
     &    ,0_8,0_8,0.D0,0.D0,ACCEL_T1-ACCEL_T0)
#ENDIF
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$ATOMFORWARD(IAT,GID,NR,LNX,LOX,LMNX,NDIMD &
     &                            ,DENMAT,AEPHI,PSPHI,AECORE,PSCORE,RCUT &
     &                            ,DHSKALA)
      USE PAW_SKALA_MODULE
      USE PAW_SKALA_GRID_MODULE, ONLY: PAW_SKALA_SMOOTH_PARTITION &
     &                                ,PAW_SKALA_SMOOTH_PARTITION_DERIVATIVES &
     &                                ,PAW_SKALA_NEAREST_IMAGE &
     &                                ,PAW_SKALA_INVERSE3 &
     &                                ,PAW_SKALA_PARTITION_TAPER &
     &                                ,PAW_SKALA_PARTITION_TAPER_DERIVATIVE &
     &                                ,PAW_SKALA_RADIAL_BLEND &
     &                                ,PAW_SKALA_RADIAL_BLEND_DERIVATIVE &
     &                                ,PAW_SKALA_LOCAL_GRID_SIZE &
     &                                ,PAW_SKALA_LOCAL_GRID &
     &                                ,PAW_SKALA_GRID_INTERPOLATE &
     &                                ,PAW_SKALA_GRID_INTERPOLATE_PRIMITIVES &
     &                                ,PAW_SKALA_GRID_PRIMITIVES_ADJOINT
      USE PAW_SKALA_PRIMITIVES_MODULE, ONLY: PAW_SKALA_ONECENTER_POINTS &
     &                                      ,PAW_SKALA_ONECENTER_ADJOINT_POINTS
      IMPLICIT NONE
      INTEGER(4),INTENT(IN) :: IAT,GID,NR,LNX,LOX(LNX),LMNX,NDIMD
      COMPLEX(8),INTENT(IN) :: DENMAT(LMNX,LMNX,NDIMD)
      REAL(8),INTENT(IN) :: AEPHI(NR,LNX),PSPHI(NR,LNX)
      REAL(8),INTENT(IN) :: AECORE(NR),PSCORE(NR),RCUT
      COMPLEX(8),INTENT(OUT) :: DHSKALA(LMNX,LMNX,NDIMD)
      REAL(8),PARAMETER :: PARTITION_EPS=1.D-12
      INTEGER(4) :: NAT,NPOINT,NLOCAL,NANG,I1,I2,I3,IP,IDIM,ICART,ILOC
      INTEGER(4) :: NGRID,NSMOOTH,ISMOOTH,IWORK,J,ISOURCE
      INTEGER(8) :: ATOMICGRIDSIZES(1)
      REAL(8) :: MODELATOM(1,3),POINT(3),IMAGE(3),RELATIVE(3),DISTANCE
      REAL(8) :: CELLVOL,DVOL,FACTOR,ENERGY
      REAL(8) :: CELL_INVERSE(3,3)
      REAL(8) :: PARTWEIGHT,BLEND,SMOOTHSCALE,BLENDDERIV
      REAL(8) :: RHOCOMP(2),TAUCOMP(2),GRADCOMP(3,2)
      REAL(8) :: DRHOCOMP(3,2),DTAUCOMP(3,2),DGRADCOMP(3,3,2)
      REAL(8) :: ADJRHO(2),ADJTAU(2),ADJGRAD(3,2)
      REAL(8) :: MOVINGDERIV(3),PRIMITIVEDERIV(3),WEIGHTSENSITIVITY
      REAL(8) :: BLENDSENSITIVITY
      REAL(8),ALLOCATABLE :: ATOMCOORD(:,:),ATOMCOORD3(:,:),PARTITION(:)
      REAL(8),ALLOCATABLE :: DPARTITION_DATOM(:,:,:)
      REAL(8),ALLOCATABLE :: DPARTITION_DPOINT(:,:)
      REAL(8),ALLOCATABLE :: LOCALCOORD(:,:),LOCALWEIGHT(:)
      REAL(8),ALLOCATABLE :: LOCALPARTWEIGHT(:)
      INTEGER(4),ALLOCATABLE :: SMOOTHINDEX(:)
      REAL(8),ALLOCATABLE :: SMOOTHREL(:,:)
      REAL(8),ALLOCATABLE :: RELCOORD(:,:),GRIDCOORDS(:,:),GRIDWEIGHTS(:)
      REAL(8),ALLOCATABLE :: ATOMICGRIDWEIGHTS(:)
      REAL(8),ALLOCATABLE :: DENSITY(:,:),GRAD(:,:,:),KIN(:,:)
      REAL(8),ALLOCATABLE :: AERHO(:,:),PSRHO(:,:),AETAU(:,:),PSTAU(:,:)
      REAL(8),ALLOCATABLE :: AEGRAD(:,:,:),PSGRAD(:,:,:)
      REAL(8),ALLOCATABLE :: DDENSITY(:,:),DGRAD(:,:,:),DKIN(:,:)
      REAL(8),ALLOCATABLE :: DGRIDCOORDS(:,:),DGRIDWEIGHTS(:)
      REAL(8),ALLOCATABLE :: DATOMCOORDS(:,:),DATOMICGRIDWEIGHTS(:)
#IF DEFINED(CPPVAR_ACCEL_PROFILE)
      REAL(8) :: ACCEL_T0,ACCEL_T1
#ENDIF

      DHSKALA=CMPLX(0.D0,0.D0,KIND=8)
      IF(.NOT.TON) RETURN
      IF(.NOT.TSMOOTHREADY) THEN
        CALL ERROR$MSG('SKALA SMOOTH FIELDS ARE NOT AVAILABLE')
        CALL ERROR$STOP('SKALA$ATOMFORWARD')
      END IF
      IF(NDIMD.NE.SMOOTH_NDIMD) THEN
        CALL ERROR$MSG('SKALA SMOOTH AND ONE-CENTER SPINS DIFFER')
        CALL ERROR$I4VAL('SMOOTH NDIMD',SMOOTH_NDIMD)
        CALL ERROR$I4VAL('ONE-CENTER NDIMD',NDIMD)
        CALL ERROR$STOP('SKALA$ATOMFORWARD')
      END IF
      IF(.NOT.ALLOCATED(SMOOTH_PARTITION)) THEN
        CALL ERROR$MSG('SKALA SMOOTH PARTITION CACHE IS NOT AVAILABLE')
        CALL ERROR$STOP('SKALA$ATOMFORWARD')
      END IF
      IF(ALLOCATED(FORWARD_DERIV).AND.CONFIG_INTERPOLATEPARTITION) THEN
        CALL ERROR$MSG('SKALA FORCES REQUIRE THE EXACT PARTITION')
        CALL ERROR$MSG('SET INTERPOLATEPARTITION=F FOR FORCE CALCULATIONS')
        CALL ERROR$STOP('SKALA$ATOMFORWARD')
      END IF
#IF DEFINED(CPPVAR_ACCEL_PROFILE)
      CALL ACCELPROFILE$NOW(ACCEL_T0)
#ENDIF
      CALL TIMING$CLOCKON('SKALA:ATOMGRID')
      CALL ATOMLIST$NATOM(NAT)
      IF(IAT.LT.1.OR.IAT.GT.NAT) THEN
        CALL ERROR$MSG('INVALID ATOM INDEX FOR SKALA FORWARD EVALUATION')
        CALL ERROR$I4VAL('IAT',IAT)
        CALL ERROR$STOP('SKALA$ATOMFORWARD')
      END IF
      ALLOCATE(ATOMCOORD(NAT,3),ATOMCOORD3(3,NAT))
      IF(.NOT.CONFIG_INTERPOLATEPARTITION) ALLOCATE(PARTITION(NAT))
      IF(ALLOCATED(FORWARD_DERIV)) THEN
        ALLOCATE(DPARTITION_DATOM(3,NAT,NAT))
        ALLOCATE(DPARTITION_DPOINT(3,NAT))
      END IF
      CALL ATOMLIST$GETR8A('R(0)',0,3*NAT,ATOMCOORD3)
      ATOMCOORD=TRANSPOSE(ATOMCOORD3)

      CELLVOL=ABS(SMOOTH_RBAS(1,1)*(SMOOTH_RBAS(2,2)*SMOOTH_RBAS(3,3) &
     &                              -SMOOTH_RBAS(2,3)*SMOOTH_RBAS(3,2)) &
     &           -SMOOTH_RBAS(1,2)*(SMOOTH_RBAS(2,1)*SMOOTH_RBAS(3,3) &
     &                              -SMOOTH_RBAS(2,3)*SMOOTH_RBAS(3,1)) &
     &           +SMOOTH_RBAS(1,3)*(SMOOTH_RBAS(2,1)*SMOOTH_RBAS(3,2) &
     &                              -SMOOTH_RBAS(2,2)*SMOOTH_RBAS(3,1)))
      DVOL=CELLVOL/REAL(SMOOTH_NR1*SMOOTH_NR2*SMOOTH_NR3,KIND=8)
      CALL PAW_SKALA_INVERSE3(SMOOTH_RBAS,CELL_INVERSE)
      CALL PAW_SKALA_LOCAL_GRID_SIZE(LOCAL_NRADIAL,LOCAL_LEBEDEV_L &
     &                              ,NANG,NLOCAL)
      ALLOCATE(LOCALCOORD(NLOCAL,3),LOCALWEIGHT(NLOCAL))
      ALLOCATE(LOCALPARTWEIGHT(NLOCAL))
      CALL PAW_SKALA_LOCAL_GRID(LOCAL_NRADIAL,RCUT,LOCAL_LEBEDEV_L &
     &                          ,NLOCAL,LOCALCOORD,LOCALWEIGHT)
      ISOURCE=0
      IF(.NOT.CONFIG_INTERPOLATEPARTITION) THEN
        DO J=1,NAT
          IF(.NOT.LOCAL_PARTITION_READY(J)) CYCLE
          IF(SMOOTH_ATOM_CLASS(J).NE.SMOOTH_ATOM_CLASS(IAT)) CYCLE
          IF(ABS(LOCAL_PARTITION_RCUT(J)-RCUT) &
     &       .GT.1.D-12*MAX(1.D0,ABS(RCUT))) CYCLE
          ISOURCE=J
          EXIT
        END DO
      END IF
      IF(ISOURCE.GT.0) THEN
        LOCALPARTWEIGHT=LOCAL_PARTITION_CACHE(:,ISOURCE)
      ELSE
        DO ILOC=1,NLOCAL
          POINT=ATOMCOORD(IAT,:)+LOCALCOORD(ILOC,:)
          IF(CONFIG_INTERPOLATEPARTITION) THEN
          CALL PAW_SKALA_GRID_INTERPOLATE &
     &         (SMOOTH_NR1,SMOOTH_NR2,SMOOTH_NR3,SMOOTH_RBAS &
     &         ,SMOOTH_PARTITION(:,:,:,IAT),POINT &
     &         ,LOCALPARTWEIGHT(ILOC))
          LOCALPARTWEIGHT(ILOC)=MAX(0.D0,MIN(1.D0 &
     &                                    ,LOCALPARTWEIGHT(ILOC)))
          ELSE
            CALL PAW_SKALA_SMOOTH_PARTITION(POINT,NAT,ATOMCOORD &
     &                                    ,SMOOTH_RBAS,PARTITION)
            LOCALPARTWEIGHT(ILOC)=PARTITION(IAT)
          END IF
        END DO
      END IF
      IF(.NOT.CONFIG_INTERPOLATEPARTITION) THEN
        LOCAL_PARTITION_CACHE(:,IAT)=LOCALPARTWEIGHT
        LOCAL_PARTITION_RCUT(IAT)=RCUT
        LOCAL_PARTITION_READY(IAT)=.TRUE.
      END IF
      NGRID=SMOOTH_NR1*SMOOTH_NR2*SMOOTH_NR3
      ALLOCATE(SMOOTHINDEX(NGRID),SMOOTHREL(NGRID,3))
      NSMOOTH=0
      DO I3=1,SMOOTH_NR3
        DO I2=1,SMOOTH_NR2
          DO I1=1,SMOOTH_NR1
            POINT=MATMUL(SMOOTH_RBAS &
     &                  ,(/REAL(I1-1,KIND=8)/REAL(SMOOTH_NR1,KIND=8) &
     &                    ,REAL(I2-1,KIND=8)/REAL(SMOOTH_NR2,KIND=8) &
     &                    ,REAL(I3-1,KIND=8)/REAL(SMOOTH_NR3,KIND=8)/))
            PARTWEIGHT=SMOOTH_PARTITION(I1,I2,I3,IAT)
            IF(PARTWEIGHT.LE.PARTITION_EPS) CYCLE
            CALL PAW_SKALA_NEAREST_IMAGE(POINT,ATOMCOORD(IAT,:) &
     &                                   ,SMOOTH_RBAS,IMAGE,DISTANCE &
     &                                   ,CELL_INVERSE)
            SMOOTHSCALE=1.D0-PAW_SKALA_RADIAL_BLEND(DISTANCE,RCUT)
            IF(SMOOTHSCALE.LE.PARTITION_EPS) CYCLE
            NSMOOTH=NSMOOTH+1
            SMOOTHINDEX(NSMOOTH)=I1+SMOOTH_NR1 &
     &                   *((I2-1)+SMOOTH_NR2*(I3-1))
            SMOOTHREL(NSMOOTH,:)=POINT-IMAGE
          END DO
        END DO
      END DO
      NPOINT=NSMOOTH
      DO ILOC=1,NLOCAL
        DISTANCE=SQRT(SUM(LOCALCOORD(ILOC,:)**2))
        BLEND=PAW_SKALA_RADIAL_BLEND(DISTANCE,RCUT)
        IF(LOCALPARTWEIGHT(ILOC).GT.PARTITION_EPS.AND.BLEND.GT.0.D0) &
     &    NPOINT=NPOINT+1
      END DO
      IF(NPOINT.EQ.0) THEN
        CALL ERROR$MSG('SKALA ATOM BLOCK HAS NO GRID POINTS')
        CALL ERROR$I4VAL('IAT',IAT)
        CALL ERROR$STOP('SKALA$ATOMFORWARD')
      END IF

      ALLOCATE(RELCOORD(NPOINT,3),GRIDCOORDS(NPOINT,3))
      ALLOCATE(GRIDWEIGHTS(NPOINT),ATOMICGRIDWEIGHTS(NPOINT))
      ALLOCATE(DENSITY(NPOINT,2),GRAD(NPOINT,3,2),KIN(NPOINT,2))
      IP=0
      DO ISMOOTH=1,NSMOOTH
            IWORK=SMOOTHINDEX(ISMOOTH)-1
            I1=MOD(IWORK,SMOOTH_NR1)+1
            IWORK=IWORK/SMOOTH_NR1
            I2=MOD(IWORK,SMOOTH_NR2)+1
            I3=IWORK/SMOOTH_NR2+1
            POINT=MATMUL(SMOOTH_RBAS &
     &            ,(/REAL(I1-1,KIND=8)/REAL(SMOOTH_NR1,KIND=8) &
     &              ,REAL(I2-1,KIND=8)/REAL(SMOOTH_NR2,KIND=8) &
     &              ,REAL(I3-1,KIND=8)/REAL(SMOOTH_NR3,KIND=8)/))
            IP=IP+1
            RELATIVE=SMOOTHREL(ISMOOTH,:)
            RELCOORD(IP,:)=RELATIVE
            GRIDCOORDS(IP,:)=POINT
            PARTWEIGHT=SMOOTH_PARTITION(I1,I2,I3,IAT)
            DISTANCE=SQRT(SUM(RELATIVE**2))
            SMOOTHSCALE=1.D0-PAW_SKALA_RADIAL_BLEND(DISTANCE,RCUT)
            GRIDWEIGHTS(IP)=DVOL*PARTWEIGHT*SMOOTHSCALE
            ATOMICGRIDWEIGHTS(IP)=DVOL &
     &          *PAW_SKALA_PARTITION_TAPER(PARTWEIGHT)*SMOOTHSCALE
            IF(NDIMD.EQ.1) THEN
              DENSITY(IP,:)=0.5D0*SMOOTH_RHO(I1,I2,I3,1)
              KIN(IP,:)=0.5D0*SMOOTH_TAU(I1,I2,I3,1)
              DO ICART=1,3
                GRAD(IP,ICART,:)=0.5D0*SMOOTH_GRHO(I1,I2,I3,ICART,1)
              END DO
            ELSE
              DO IDIM=1,2
                FACTOR=MERGE(1.D0,-1.D0,IDIM.EQ.1)
                DENSITY(IP,IDIM)=0.5D0*(SMOOTH_RHO(I1,I2,I3,1) &
     &                                      +FACTOR*SMOOTH_RHO(I1,I2,I3,2))
                KIN(IP,IDIM)=0.5D0*(SMOOTH_TAU(I1,I2,I3,1) &
     &                                      +FACTOR*SMOOTH_TAU(I1,I2,I3,2))
                DO ICART=1,3
                  GRAD(IP,ICART,IDIM)=0.5D0 &
     &                         *(SMOOTH_GRHO(I1,I2,I3,ICART,1) &
     &                    +FACTOR*SMOOTH_GRHO(I1,I2,I3,ICART,2))
                END DO
              END DO
            END IF
      END DO

      DO ILOC=1,NLOCAL
        RELATIVE=LOCALCOORD(ILOC,:)
        POINT=ATOMCOORD(IAT,:)+RELATIVE
        PARTWEIGHT=LOCALPARTWEIGHT(ILOC)
        DISTANCE=SQRT(SUM(RELATIVE**2))
        BLEND=PAW_SKALA_RADIAL_BLEND(DISTANCE,RCUT)
        IF(PARTWEIGHT.LE.PARTITION_EPS.OR.BLEND.LE.0.D0) CYCLE
        IP=IP+1
        RELCOORD(IP,:)=RELATIVE
        GRIDCOORDS(IP,:)=POINT
        GRIDWEIGHTS(IP)=LOCALWEIGHT(ILOC)*PARTWEIGHT*BLEND
        ATOMICGRIDWEIGHTS(IP)=LOCALWEIGHT(ILOC) &
     &        *PAW_SKALA_PARTITION_TAPER(PARTWEIGHT)*BLEND
        CALL PAW_SKALA_GRID_INTERPOLATE_PRIMITIVES &
     &       (SMOOTH_NR1,SMOOTH_NR2,SMOOTH_NR3,SMOOTH_RBAS,NDIMD &
     &       ,SMOOTH_RHO,SMOOTH_GRHO,SMOOTH_TAU,POINT &
     &       ,RHOCOMP(1:NDIMD),GRADCOMP(:,1:NDIMD),TAUCOMP(1:NDIMD))
        IF(NDIMD.EQ.1) THEN
          DENSITY(IP,:)=0.5D0*RHOCOMP(1)
          KIN(IP,:)=0.5D0*TAUCOMP(1)
          DO ICART=1,3
            GRAD(IP,ICART,:)=0.5D0*GRADCOMP(ICART,1)
          END DO
        ELSE
          DO IDIM=1,2
            FACTOR=MERGE(1.D0,-1.D0,IDIM.EQ.1)
            DENSITY(IP,IDIM)=0.5D0*(RHOCOMP(1)+FACTOR*RHOCOMP(2))
            KIN(IP,IDIM)=0.5D0*(TAUCOMP(1)+FACTOR*TAUCOMP(2))
            DO ICART=1,3
              GRAD(IP,ICART,IDIM)=0.5D0 &
     &                            *(GRADCOMP(ICART,1) &
     &                              +FACTOR*GRADCOMP(ICART,2))
            END DO
          END DO
        END IF
      END DO
      IF(IP.NE.NPOINT) THEN
        CALL ERROR$MSG('SKALA HYBRID GRID COUNT CHANGED WHILE BUILDING')
        CALL ERROR$I4VAL('COUNTED',NPOINT)
        CALL ERROR$I4VAL('BUILT',IP)
        CALL ERROR$STOP('SKALA$ATOMFORWARD')
      END IF
      CALL TIMING$CLOCKOFF('SKALA:ATOMGRID')
#IF DEFINED(CPPVAR_ACCEL_PROFILE)
      CALL ACCELPROFILE$NOW(ACCEL_T1)
      CALL ACCELPROFILE$ADD('SKALA_ATOM_GRID' &
     &    ,INT(NPOINT,KIND=8),INT(NLOCAL,KIND=8),INT(NAT,KIND=8) &
     &    ,INT(IAT,KIND=8),0.D0,0.D0,ACCEL_T1-ACCEL_T0)
      CALL ACCELPROFILE$NOW(ACCEL_T0)
#ENDIF

      CALL TIMING$CLOCKON('SKALA:1CENTER')
      ALLOCATE(AERHO(NPOINT,2),PSRHO(NPOINT,2))
      ALLOCATE(AEGRAD(NPOINT,3,2),PSGRAD(NPOINT,3,2))
      ALLOCATE(AETAU(NPOINT,2),PSTAU(NPOINT,2))
      CALL PAW_SKALA_ONECENTER_POINTS(GID,NR,LNX,LOX,LMNX,NDIMD &
     &                                ,DENMAT,AEPHI,PSPHI,AECORE,PSCORE &
     &                                ,RCUT,NPOINT,RELCOORD &
     &                                ,AERHO,AEGRAD,AETAU &
     &                                ,PSRHO,PSGRAD,PSTAU)
      IF(NSMOOTH.GT.0) THEN
        AERHO(1:NSMOOTH,:)=0.D0
        PSRHO(1:NSMOOTH,:)=0.D0
        AEGRAD(1:NSMOOTH,:,:)=0.D0
        PSGRAD(1:NSMOOTH,:,:)=0.D0
        AETAU(1:NSMOOTH,:)=0.D0
        PSTAU(1:NSMOOTH,:)=0.D0
      END IF
      FORWARD_SMOOTH_ELECTRONS=FORWARD_SMOOTH_ELECTRONS &
     &                 +SUM(GRIDWEIGHTS*SUM(DENSITY,DIM=2))
      FORWARD_CORRECTION_ELECTRONS=FORWARD_CORRECTION_ELECTRONS &
     &                 +SUM(GRIDWEIGHTS*SUM(AERHO-PSRHO,DIM=2))
      FORWARD_SMOOTH_TAU=FORWARD_SMOOTH_TAU &
     &                 +SUM(GRIDWEIGHTS*SUM(KIN,DIM=2))
      FORWARD_CORRECTION_TAU=FORWARD_CORRECTION_TAU &
     &                 +SUM(GRIDWEIGHTS*SUM(AETAU-PSTAU,DIM=2))
      DENSITY=DENSITY+AERHO-PSRHO
      GRAD=GRAD+AEGRAD-PSGRAD
      KIN=KIN+AETAU-PSTAU
      CALL TIMING$CLOCKOFF('SKALA:1CENTER')
#IF DEFINED(CPPVAR_ACCEL_PROFILE)
      CALL ACCELPROFILE$NOW(ACCEL_T1)
      CALL ACCELPROFILE$ADD('SKALA_ONECENTER' &
     &    ,INT(NPOINT,KIND=8),INT(LMNX,KIND=8),INT(NR,KIND=8) &
     &    ,INT(IAT,KIND=8),0.D0,0.D0,ACCEL_T1-ACCEL_T0)
#ENDIF

      ALLOCATE(DDENSITY(NPOINT,2),DGRAD(NPOINT,3,2),DKIN(NPOINT,2))
      ALLOCATE(DGRIDCOORDS(NPOINT,3),DGRIDWEIGHTS(NPOINT))
      ALLOCATE(DATOMCOORDS(1,3),DATOMICGRIDWEIGHTS(NPOINT))
      MODELATOM(1,:)=ATOMCOORD(IAT,:)
      ATOMICGRIDSIZES(1)=INT(NPOINT,KIND=8)
#IF DEFINED(CPPVAR_ACCEL_PROFILE)
      CALL ACCELPROFILE$NOW(ACCEL_T0)
#ENDIF
      CALL TIMING$CLOCKON('SKALA:MODEL')
      CALL SKALA$EVALUATE(NPOINT,1,DENSITY,GRAD,KIN &
     &                   ,GRIDCOORDS,GRIDWEIGHTS,MODELATOM &
     &                   ,ATOMICGRIDWEIGHTS,ATOMICGRIDSIZES,ENERGY &
     &                   ,DDENSITY,DGRAD,DKIN,DGRIDCOORDS &
     &                   ,DGRIDWEIGHTS,DATOMCOORDS,DATOMICGRIDWEIGHTS)
      CALL TIMING$CLOCKOFF('SKALA:MODEL')
#IF DEFINED(CPPVAR_ACCEL_PROFILE)
      CALL ACCELPROFILE$NOW(ACCEL_T1)
      CALL ACCELPROFILE$ADD('SKALA_MODEL' &
     &    ,INT(NPOINT,KIND=8),INT(IAT,KIND=8),0_8,0_8 &
     &    ,0.D0,0.D0,ACCEL_T1-ACCEL_T0)
#ENDIF
      IF(ENERGY.NE.ENERGY.OR.ABS(ENERGY).GT.0.5D0*HUGE(ENERGY)) THEN
        CALL ERROR$MSG('SKALA FORWARD ENERGY IS NOT FINITE')
        CALL ERROR$I4VAL('IAT',IAT)
        CALL ERROR$STOP('SKALA$ATOMFORWARD')
      END IF
      IF(ANY(DDENSITY.NE.DDENSITY).OR.ANY(DGRAD.NE.DGRAD) &
     &   .OR.ANY(DKIN.NE.DKIN).OR.ANY(DGRIDCOORDS.NE.DGRIDCOORDS) &
     &   .OR.ANY(DGRIDWEIGHTS.NE.DGRIDWEIGHTS) &
     &   .OR.ANY(DATOMCOORDS.NE.DATOMCOORDS) &
     &   .OR.ANY(DATOMICGRIDWEIGHTS.NE.DATOMICGRIDWEIGHTS)) THEN
        CALL ERROR$MSG('SKALA PRIMITIVE ADJOINTS ARE NOT FINITE')
        CALL ERROR$I4VAL('IAT',IAT)
        CALL ERROR$STOP('SKALA$ATOMFORWARD')
      END IF
      IF(ALLOCATED(FORWARD_DERIV)) THEN
        FORWARD_DERIV(:,IAT)=FORWARD_DERIV(:,IAT)+DATOMCOORDS(1,:)
        FORWARD_DERIV_MODEL_ATOM(:,IAT)= &
     &      FORWARD_DERIV_MODEL_ATOM(:,IAT)+DATOMCOORDS(1,:)
      END IF
#IF DEFINED(CPPVAR_ACCEL_PROFILE)
      CALL ACCELPROFILE$NOW(ACCEL_T0)
#ENDIF
      CALL TIMING$CLOCKON('SKALA:1CADJOINT')
      CALL PAW_SKALA_ONECENTER_ADJOINT_POINTS(GID,NR,LNX,LOX,LMNX &
     &                                        ,NDIMD,AEPHI,PSPHI,RCUT &
     &                                        ,NPOINT-NSMOOTH &
     &                                        ,RELCOORD(NSMOOTH+1:NPOINT,:) &
     &                                        ,DDENSITY(NSMOOTH+1:NPOINT,:) &
     &                                        ,DGRAD(NSMOOTH+1:NPOINT,:,:) &
     &                                        ,DKIN(NSMOOTH+1:NPOINT,:) &
     &                                        ,DHSKALA)
      CALL TIMING$CLOCKOFF('SKALA:1CADJOINT')
#IF DEFINED(CPPVAR_ACCEL_PROFILE)
      CALL ACCELPROFILE$NOW(ACCEL_T1)
      CALL ACCELPROFILE$ADD('SKALA_ONECENTER_ADJOINT' &
     &    ,INT(NPOINT,KIND=8),INT(LMNX,KIND=8),INT(NR,KIND=8) &
     &    ,INT(IAT,KIND=8),0.D0,0.D0,ACCEL_T1-ACCEL_T0)
#ENDIF
      IF(CONFIG_CHECK.AND..NOT.TONECENTERCHECKED) THEN
        CALL SKALA_ONECENTER_MODELCHECK(GID,NR,LNX,LOX,LMNX,NDIMD &
     &       ,DENMAT,AEPHI,PSPHI,RCUT,NPOINT,NSMOOTH,RELCOORD &
     &       ,DENSITY,GRAD,KIN &
     &       ,GRIDCOORDS,GRIDWEIGHTS,MODELATOM,ATOMICGRIDWEIGHTS &
     &       ,ATOMICGRIDSIZES,DDENSITY,DGRAD,DKIN,DHSKALA)
        TONECENTERCHECKED=.TRUE.
      END IF
      FORWARD_ONECENTER_ADJOINT_NORM2=FORWARD_ONECENTER_ADJOINT_NORM2 &
     &                               +SUM(ABS(DHSKALA)**2)
      FORWARD_ONECENTER_CONTRACTION=FORWARD_ONECENTER_CONTRACTION &
     &       +REAL(SUM(CONJG(DENMAT)*DHSKALA),KIND=8)

#IF DEFINED(CPPVAR_ACCEL_PROFILE)
      CALL ACCELPROFILE$NOW(ACCEL_T0)
#ENDIF
      CALL TIMING$CLOCKON('SKALA:GRIDBACK')
      IP=0
      DO ISMOOTH=1,NSMOOTH
            IWORK=SMOOTHINDEX(ISMOOTH)-1
            I1=MOD(IWORK,SMOOTH_NR1)+1
            IWORK=IWORK/SMOOTH_NR1
            I2=MOD(IWORK,SMOOTH_NR2)+1
            I3=IWORK/SMOOTH_NR2+1
            IP=IP+1
            IF(ALLOCATED(FORWARD_DERIV)) THEN
              RELATIVE=SMOOTHREL(ISMOOTH,:)
              DISTANCE=SQRT(SUM(RELATIVE**2))
              SMOOTHSCALE=1.D0-PAW_SKALA_RADIAL_BLEND(DISTANCE,RCUT)
              PARTWEIGHT=SMOOTH_PARTITION(I1,I2,I3,IAT)
              WEIGHTSENSITIVITY=DVOL*SMOOTHSCALE*(DGRIDWEIGHTS(IP) &
     &            +DATOMICGRIDWEIGHTS(IP) &
     &             *PAW_SKALA_PARTITION_TAPER_DERIVATIVE(PARTWEIGHT))
              SMOOTH_PARTITION_SENSITIVITY(I1,I2,I3,IAT)= &
     &          SMOOTH_PARTITION_SENSITIVITY(I1,I2,I3,IAT) &
     &          +WEIGHTSENSITIVITY
              BLENDSENSITIVITY=DVOL*(DGRIDWEIGHTS(IP)*PARTWEIGHT &
     &          +DATOMICGRIDWEIGHTS(IP) &
     &           *PAW_SKALA_PARTITION_TAPER(PARTWEIGHT))
              BLENDDERIV=PAW_SKALA_RADIAL_BLEND_DERIVATIVE &
     &                   (DISTANCE,RCUT)
              IF(DISTANCE.GT.0.D0.AND.BLENDDERIV.NE.0.D0) THEN
                MOVINGDERIV=BLENDSENSITIVITY*BLENDDERIV &
     &                     *RELATIVE/DISTANCE
                FORWARD_DERIV(:,IAT)=FORWARD_DERIV(:,IAT)+MOVINGDERIV
                FORWARD_DERIV_RADIAL_BLEND(:,IAT)= &
     &            FORWARD_DERIV_RADIAL_BLEND(:,IAT)+MOVINGDERIV
              END IF
            END IF
            DO IDIM=1,NDIMD
              FACTOR=MERGE(1.D0,-1.D0,IDIM.EQ.1)
              SMOOTH_ADJ_RHO(I1,I2,I3,IDIM)= &
     &          SMOOTH_ADJ_RHO(I1,I2,I3,IDIM) &
     &          +0.5D0*(DDENSITY(IP,1)+FACTOR*DDENSITY(IP,2))
              SMOOTH_ADJ_TAU(I1,I2,I3,IDIM)= &
     &          SMOOTH_ADJ_TAU(I1,I2,I3,IDIM) &
     &          +0.5D0*(DKIN(IP,1)+FACTOR*DKIN(IP,2))
              DO ICART=1,3
                SMOOTH_ADJ_GRHO(I1,I2,I3,ICART,IDIM)= &
     &            SMOOTH_ADJ_GRHO(I1,I2,I3,ICART,IDIM) &
     &            +0.5D0*(DGRAD(IP,ICART,1) &
     &                    +FACTOR*DGRAD(IP,ICART,2))
              END DO
            END DO
      END DO
      DO ILOC=1,NLOCAL
        POINT=ATOMCOORD(IAT,:)+LOCALCOORD(ILOC,:)
        DISTANCE=SQRT(SUM(LOCALCOORD(ILOC,:)**2))
        BLEND=PAW_SKALA_RADIAL_BLEND(DISTANCE,RCUT)
        IF(LOCALPARTWEIGHT(ILOC).LE.PARTITION_EPS.OR.BLEND.LE.0.D0) CYCLE
        IP=IP+1
        IF(ALLOCATED(FORWARD_DERIV)) THEN
          CALL PAW_SKALA_GRID_INTERPOLATE_PRIMITIVES &
     &         (SMOOTH_NR1,SMOOTH_NR2,SMOOTH_NR3,SMOOTH_RBAS,NDIMD &
     &         ,SMOOTH_RHO,SMOOTH_GRHO,SMOOTH_TAU,POINT &
     &         ,RHOCOMP(1:NDIMD),GRADCOMP(:,1:NDIMD),TAUCOMP(1:NDIMD) &
     &         ,DRHOCOMP(:,1:NDIMD),DGRADCOMP(:,:,1:NDIMD) &
     &         ,DTAUCOMP(:,1:NDIMD))
        END IF
        DO IDIM=1,NDIMD
          FACTOR=MERGE(1.D0,-1.D0,IDIM.EQ.1)
          ADJRHO(IDIM)=0.5D0*(DDENSITY(IP,1)+FACTOR*DDENSITY(IP,2))
          ADJTAU(IDIM)=0.5D0*(DKIN(IP,1)+FACTOR*DKIN(IP,2))
          DO ICART=1,3
            ADJGRAD(ICART,IDIM)=0.5D0*(DGRAD(IP,ICART,1) &
     &                                     +FACTOR*DGRAD(IP,ICART,2))
          END DO
        END DO
        IF(ALLOCATED(FORWARD_DERIV)) THEN
          MOVINGDERIV=DGRIDCOORDS(IP,:)
          PRIMITIVEDERIV=0.D0
          DO IDIM=1,NDIMD
            PRIMITIVEDERIV=PRIMITIVEDERIV &
     &                  +ADJRHO(IDIM)*DRHOCOMP(:,IDIM) &
     &                  +ADJTAU(IDIM)*DTAUCOMP(:,IDIM)
            DO ICART=1,3
              PRIMITIVEDERIV=PRIMITIVEDERIV &
     &                   +ADJGRAD(ICART,IDIM)*DGRADCOMP(ICART,:,IDIM)
            END DO
          END DO
          MOVINGDERIV=MOVINGDERIV+PRIMITIVEDERIV
          FORWARD_DERIV(:,IAT)=FORWARD_DERIV(:,IAT)+MOVINGDERIV
          FORWARD_DERIV_LOCAL_GRID(:,IAT)= &
     &        FORWARD_DERIV_LOCAL_GRID(:,IAT)+DGRIDCOORDS(IP,:)
          FORWARD_DERIV_LOCAL_PRIMITIVE(:,IAT)= &
     &        FORWARD_DERIV_LOCAL_PRIMITIVE(:,IAT)+PRIMITIVEDERIV
          CALL PAW_SKALA_SMOOTH_PARTITION_DERIVATIVES &
     &         (POINT,NAT,ATOMCOORD,SMOOTH_RBAS,PARTITION &
     &         ,DPARTITION_DATOM,DPARTITION_DPOINT)
          PARTWEIGHT=PARTITION(IAT)
          WEIGHTSENSITIVITY=LOCALWEIGHT(ILOC)*BLEND*(DGRIDWEIGHTS(IP) &
     &        +DATOMICGRIDWEIGHTS(IP) &
     &         *PAW_SKALA_PARTITION_TAPER_DERIVATIVE(PARTWEIGHT))
          DO J=1,NAT
            FORWARD_DERIV(:,J)=FORWARD_DERIV(:,J) &
     &            +WEIGHTSENSITIVITY*DPARTITION_DATOM(:,J,IAT)
            FORWARD_DERIV_LOCAL_PARTITION(:,J)= &
     &          FORWARD_DERIV_LOCAL_PARTITION(:,J) &
     &          +WEIGHTSENSITIVITY*DPARTITION_DATOM(:,J,IAT)
          END DO
          FORWARD_DERIV(:,IAT)=FORWARD_DERIV(:,IAT) &
     &            +WEIGHTSENSITIVITY*DPARTITION_DPOINT(:,IAT)
          FORWARD_DERIV_LOCAL_PARTITION(:,IAT)= &
     &        FORWARD_DERIV_LOCAL_PARTITION(:,IAT) &
     &        +WEIGHTSENSITIVITY*DPARTITION_DPOINT(:,IAT)
        END IF
        CALL PAW_SKALA_GRID_PRIMITIVES_ADJOINT &
     &       (SMOOTH_NR1,SMOOTH_NR2,SMOOTH_NR3,SMOOTH_RBAS,NDIMD &
     &       ,SMOOTH_ADJ_RHO,SMOOTH_ADJ_GRHO,SMOOTH_ADJ_TAU,POINT &
     &       ,ADJRHO(1:NDIMD),ADJGRAD(:,1:NDIMD),ADJTAU(1:NDIMD))
      END DO
      IF(IP.NE.NPOINT) THEN
        CALL ERROR$MSG('SKALA ADJOINT GRID COUNT CHANGED')
        CALL ERROR$I4VAL('COUNTED',NPOINT)
        CALL ERROR$I4VAL('MAPPED',IP)
        CALL ERROR$STOP('SKALA$ATOMFORWARD')
      END IF
      CALL TIMING$CLOCKOFF('SKALA:GRIDBACK')
#IF DEFINED(CPPVAR_ACCEL_PROFILE)
      CALL ACCELPROFILE$NOW(ACCEL_T1)
      CALL ACCELPROFILE$ADD('SKALA_GRID_BACK' &
     &    ,INT(NPOINT,KIND=8),INT(NLOCAL,KIND=8),INT(NAT,KIND=8) &
     &    ,INT(IAT,KIND=8),0.D0,0.D0,ACCEL_T1-ACCEL_T0)
#ENDIF
      FORWARD_ENERGY=FORWARD_ENERGY+ENERGY
      FORWARD_ATOM_ENERGY(IAT)=FORWARD_ATOM_ENERGY(IAT)+ENERGY
      FORWARD_ATOM_NPOINT(IAT)=FORWARD_ATOM_NPOINT(IAT)+NPOINT
      FORWARD_ELECTRONS=FORWARD_ELECTRONS &
     &                 +SUM(GRIDWEIGHTS*SUM(DENSITY,DIM=2))
      FORWARD_TAU=FORWARD_TAU+SUM(GRIDWEIGHTS*SUM(KIN,DIM=2))
      FORWARD_NPOINT=FORWARD_NPOINT+NPOINT

      DEALLOCATE(ATOMCOORD,ATOMCOORD3,RELCOORD,GRIDCOORDS)
      IF(ALLOCATED(PARTITION)) DEALLOCATE(PARTITION)
      IF(ALLOCATED(DPARTITION_DATOM)) DEALLOCATE(DPARTITION_DATOM)
      IF(ALLOCATED(DPARTITION_DPOINT)) DEALLOCATE(DPARTITION_DPOINT)
      DEALLOCATE(LOCALCOORD,LOCALWEIGHT,LOCALPARTWEIGHT,GRIDWEIGHTS)
      DEALLOCATE(SMOOTHINDEX,SMOOTHREL)
      DEALLOCATE(ATOMICGRIDWEIGHTS,DENSITY,GRAD,KIN)
      DEALLOCATE(AERHO,PSRHO,AEGRAD,PSGRAD,AETAU,PSTAU)
      DEALLOCATE(DDENSITY,DGRAD,DKIN,DGRIDCOORDS,DGRIDWEIGHTS)
      DEALLOCATE(DATOMCOORDS,DATOMICGRIDWEIGHTS)
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA_ONECENTER_MODELCHECK(GID,NR,LNX,LOX,LMNX,NDIMD &
     &       ,DENMAT,AEPHI,PSPHI,RCUT,NPOINT,NSMOOTH,RELCOORD &
     &       ,DENSITY,GRAD,KIN &
     &       ,GRIDCOORDS,GRIDWEIGHTS,ATOMCOORDS,ATOMICGRIDWEIGHTS &
     &       ,ATOMICGRIDSIZES,DDENSITY,DGRAD,DKIN,DHDM)
      USE PAW_SKALA_PRIMITIVES_MODULE, ONLY: PAW_SKALA_ONECENTER_POINTS
      IMPLICIT NONE
      REAL(8),PARAMETER :: EPSLIST(3)=(/1.D-2,3.D-3,1.D-3/)
      INTEGER(4),INTENT(IN) :: GID,NR,LNX,LOX(LNX),LMNX,NDIMD,NPOINT
      INTEGER(4),INTENT(IN) :: NSMOOTH
      COMPLEX(8),INTENT(IN) :: DENMAT(LMNX,LMNX,NDIMD)
      COMPLEX(8),INTENT(IN) :: DHDM(LMNX,LMNX,NDIMD)
      REAL(8),INTENT(IN) :: AEPHI(NR,LNX),PSPHI(NR,LNX),RCUT
      REAL(8),INTENT(IN) :: RELCOORD(NPOINT,3),DENSITY(NPOINT,2)
      REAL(8),INTENT(IN) :: GRAD(NPOINT,3,2),KIN(NPOINT,2)
      REAL(8),INTENT(IN) :: GRIDCOORDS(NPOINT,3),GRIDWEIGHTS(NPOINT)
      REAL(8),INTENT(IN) :: ATOMCOORDS(1,3),ATOMICGRIDWEIGHTS(NPOINT)
      INTEGER(8),INTENT(IN) :: ATOMICGRIDSIZES(1)
      REAL(8),INTENT(IN) :: DDENSITY(NPOINT,2),DGRAD(NPOINT,3,2)
      REAL(8),INTENT(IN) :: DKIN(NPOINT,2)
      COMPLEX(8),ALLOCATABLE :: DENMATR(:,:,:)
      REAL(8),ALLOCATABLE :: ZEROCORE(:),AERHO(:,:),PSRHO(:,:)
      REAL(8),ALLOCATABLE :: AEGRAD(:,:,:),PSGRAD(:,:,:)
      REAL(8),ALLOCATABLE :: AETAU(:,:),PSTAU(:,:)
      REAL(8),ALLOCATABLE :: DENSITY1(:,:),GRAD1(:,:,:),KIN1(:,:)
      REAL(8),ALLOCATABLE :: DDUMMY(:,:),GDUMMY(:,:,:),TDUMMY(:,:)
      REAL(8),ALLOCATABLE :: XCDUMMY(:,:),XWDUMMY(:),ACDUMMY(:,:)
      REAL(8),ALLOCATABLE :: AWDUMMY(:)
      REAL(8),ALLOCATABLE :: HMAT(:,:),EIG(:),EIGVEC(:,:)
      REAL(8) :: EPLUS,EMINUS,FD,PRIMITIVE,MATRIX,ERROR,EPS
      INTEGER(4) :: NFIL,IDIM,ISTEP

      ALLOCATE(DENMATR(LMNX,LMNX,NDIMD),ZEROCORE(NR))
      ALLOCATE(AERHO(NPOINT,2),PSRHO(NPOINT,2))
      ALLOCATE(AEGRAD(NPOINT,3,2),PSGRAD(NPOINT,3,2))
      ALLOCATE(AETAU(NPOINT,2),PSTAU(NPOINT,2))
      DENMATR=CMPLX(REAL(DENMAT,KIND=8),0.D0,KIND=8)
      ZEROCORE=0.D0
      CALL PAW_SKALA_ONECENTER_POINTS(GID,NR,LNX,LOX,LMNX,NDIMD &
     &       ,DENMATR,AEPHI,PSPHI,ZEROCORE,ZEROCORE,RCUT,NPOINT &
     &       ,RELCOORD,AERHO,AEGRAD,AETAU,PSRHO,PSGRAD,PSTAU)
      IF(NSMOOTH.GT.0) THEN
        AERHO(1:NSMOOTH,:)=0.D0
        PSRHO(1:NSMOOTH,:)=0.D0
        AEGRAD(1:NSMOOTH,:,:)=0.D0
        PSGRAD(1:NSMOOTH,:,:)=0.D0
        AETAU(1:NSMOOTH,:)=0.D0
        PSTAU(1:NSMOOTH,:)=0.D0
      END IF
      ALLOCATE(DENSITY1(NPOINT,2),GRAD1(NPOINT,3,2),KIN1(NPOINT,2))
      ALLOCATE(DDUMMY(NPOINT,2),GDUMMY(NPOINT,3,2),TDUMMY(NPOINT,2))
      ALLOCATE(XCDUMMY(NPOINT,3),XWDUMMY(NPOINT),ACDUMMY(1,3))
      ALLOCATE(AWDUMMY(NPOINT))
      PRIMITIVE=SUM(DDENSITY*(AERHO-PSRHO)) &
     &         +SUM(DGRAD*(AEGRAD-PSGRAD))+SUM(DKIN*(AETAU-PSTAU))
      MATRIX=REAL(SUM(CONJG(DENMATR)*DHDM),KIND=8)
      ERROR=ABS(PRIMITIVE-MATRIX)
      CALL FILEHANDLER$UNIT('PROT',NFIL)
      WRITE(NFIL,FMT='(/"SKALA ONE-CENTER MODEL CHECK"/28("="))')
      WRITE(NFIL,FMT='("PRIMITIVE ADJOINT CONTRACTION",T36,ES24.14)')PRIMITIVE
      WRITE(NFIL,FMT='("DENSITY-MATRIX CONTRACTION",T36,ES24.14)')MATRIX
      WRITE(NFIL,FMT='("ONE-CENTER MATRIX DIFFERENCE",T36,ES24.14)') &
     &     MATRIX-PRIMITIVE
      DO ISTEP=1,SIZE(EPSLIST)
        EPS=EPSLIST(ISTEP)
        DENSITY1=DENSITY+EPS*(AERHO-PSRHO)
        GRAD1=GRAD+EPS*(AEGRAD-PSGRAD)
        KIN1=KIN+EPS*(AETAU-PSTAU)
        CALL SKALA$EVALUATE(NPOINT,1,DENSITY1,GRAD1,KIN1 &
     &         ,GRIDCOORDS,GRIDWEIGHTS,ATOMCOORDS,ATOMICGRIDWEIGHTS &
     &         ,ATOMICGRIDSIZES,EPLUS,DDUMMY,GDUMMY,TDUMMY,XCDUMMY &
     &         ,XWDUMMY,ACDUMMY,AWDUMMY)
        DENSITY1=DENSITY-EPS*(AERHO-PSRHO)
        GRAD1=GRAD-EPS*(AEGRAD-PSGRAD)
        KIN1=KIN-EPS*(AETAU-PSTAU)
        CALL SKALA$EVALUATE(NPOINT,1,DENSITY1,GRAD1,KIN1 &
     &         ,GRIDCOORDS,GRIDWEIGHTS,ATOMCOORDS,ATOMICGRIDWEIGHTS &
     &         ,ATOMICGRIDSIZES,EMINUS,DDUMMY,GDUMMY,TDUMMY,XCDUMMY &
     &         ,XWDUMMY,ACDUMMY,AWDUMMY)
        FD=(EPLUS-EMINUS)/(2.D0*EPS)
        ERROR=MAX(ERROR,ABS(FD-PRIMITIVE))
        WRITE(NFIL,FMT='("FD STEP AND DERIVATIVE",T31,ES12.4,ES24.14)') &
     &       EPS,FD
        WRITE(NFIL,FMT='("FD-ADJOINT DIFFERENCE",T36,ES24.14)') &
     &       FD-PRIMITIVE
      END DO
      WRITE(NFIL,FMT='("MAXIMUM DIFFERENCE",T36,ES24.14)')ERROR
      ALLOCATE(HMAT(LMNX,LMNX),EIG(LMNX),EIGVEC(LMNX,LMNX))
      DO IDIM=1,NDIMD
        HMAT=REAL(DHDM(:,:,IDIM),KIND=8)
        CALL LIB$DIAGR8(LMNX,HMAT,EIG,EIGVEC)
        WRITE(NFIL,FMT='("ONE-CENTER CHANNEL",T36,I8)')IDIM
        WRITE(NFIL,FMT='("MATRIX MAX ABS",T36,ES24.14)')MAXVAL(ABS(HMAT))
        WRITE(NFIL,FMT='("EIGENVALUE MIN",T36,ES24.14)')MINVAL(EIG)
        WRITE(NFIL,FMT='("EIGENVALUE MAX",T36,ES24.14)')MAXVAL(EIG)
      END DO
      DEALLOCATE(HMAT,EIG,EIGVEC)
      DEALLOCATE(DENMATR,ZEROCORE,AERHO,PSRHO,AEGRAD,PSGRAD,AETAU,PSTAU)
      DEALLOCATE(DENSITY1,GRAD1,KIN1,DDUMMY,GDUMMY,TDUMMY)
      DEALLOCATE(XCDUMMY,XWDUMMY,ACDUMMY,AWDUMMY)
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$FORWARDEND
      USE PAW_SKALA_MODULE
      USE PAW_SKALA_GRID_MODULE, ONLY: &
     &     PAW_SKALA_SMOOTH_PARTITION_DERIVATIVES
      USE MPE_MODULE
      IMPLICIT NONE
      INTEGER(4) :: NTASKS,THISTASK,NFIL,NAT,I1,I2,I3,I,J
      REAL(8) :: RHONORM,GRADNORM,TAUNORM,POINT(3),NETFORCE(3)
      REAL(8),ALLOCATABLE :: ATOMCOORD(:,:),ATOMCOORD3(:,:)
      REAL(8),ALLOCATABLE :: PARTITION(:),DPARTITION_DATOM(:,:,:)
      REAL(8),ALLOCATABLE :: DPARTITION_DPOINT(:,:),FORCE(:,:)

      IF(.NOT.TON) RETURN
      CALL MPE$COMBINE('MONOMER','+',FORWARD_ENERGY)
      CALL MPE$COMBINE('MONOMER','+',FORWARD_ELECTRONS)
      CALL MPE$COMBINE('MONOMER','+',FORWARD_TAU)
      CALL MPE$COMBINE('MONOMER','+',FORWARD_SMOOTH_ELECTRONS)
      CALL MPE$COMBINE('MONOMER','+',FORWARD_CORRECTION_ELECTRONS)
      CALL MPE$COMBINE('MONOMER','+',FORWARD_SMOOTH_TAU)
      CALL MPE$COMBINE('MONOMER','+',FORWARD_CORRECTION_TAU)
      CALL MPE$COMBINE('MONOMER','+',FORWARD_ONECENTER_ADJOINT_NORM2)
      CALL MPE$COMBINE('MONOMER','+',FORWARD_ONECENTER_CONTRACTION)
      CALL MPE$COMBINE('MONOMER','+',FORWARD_NPOINT)
      CALL MPE$COMBINE('MONOMER','+',FORWARD_ATOM_ENERGY)
      CALL MPE$COMBINE('MONOMER','+',FORWARD_ATOM_NPOINT)
      CALL MPE$COMBINE('MONOMER','+',SMOOTH_ADJ_RHO)
      CALL MPE$COMBINE('MONOMER','+',SMOOTH_ADJ_GRHO)
      CALL MPE$COMBINE('MONOMER','+',SMOOTH_ADJ_TAU)
      CALL MPE$QUERY('MONOMER',NTASKS,THISTASK)
      ONECENTER_CONTRACTION=FORWARD_ONECENTER_CONTRACTION
      TONECENTERCONTRACTIONREADY=.TRUE.
      IF(ALLOCATED(FORWARD_DERIV)) THEN
        CALL MPE$COMBINE('MONOMER','+',FORWARD_DERIV)
        CALL MPE$COMBINE('MONOMER','+',FORWARD_DERIV_MODEL_ATOM)
        CALL MPE$COMBINE('MONOMER','+',FORWARD_DERIV_LOCAL_GRID)
        CALL MPE$COMBINE('MONOMER','+',FORWARD_DERIV_LOCAL_PRIMITIVE)
        CALL MPE$COMBINE('MONOMER','+',FORWARD_DERIV_LOCAL_PARTITION)
        CALL MPE$COMBINE('MONOMER','+',FORWARD_DERIV_SMOOTH_PARTITION)
        CALL MPE$COMBINE('MONOMER','+',FORWARD_DERIV_RADIAL_BLEND)
        CALL MPE$COMBINE('MONOMER','+',SMOOTH_PARTITION_SENSITIVITY)
        NAT=SIZE(FORWARD_DERIV,2)
        IF(THISTASK.EQ.1) THEN
          ALLOCATE(ATOMCOORD(NAT,3),ATOMCOORD3(3,NAT),PARTITION(NAT))
          ALLOCATE(DPARTITION_DATOM(3,NAT,NAT))
          ALLOCATE(DPARTITION_DPOINT(3,NAT))
          CALL ATOMLIST$GETR8A('R(0)',0,3*NAT,ATOMCOORD3)
          ATOMCOORD=TRANSPOSE(ATOMCOORD3)
          DO I3=1,SMOOTH_NR3
            DO I2=1,SMOOTH_NR2
              DO I1=1,SMOOTH_NR1
                IF(MAXVAL(ABS(SMOOTH_PARTITION_SENSITIVITY(I1,I2,I3,:))) &
     &             .EQ.0.D0) CYCLE
                POINT=MATMUL(SMOOTH_RBAS &
     &              ,(/REAL(I1-1,KIND=8)/REAL(SMOOTH_NR1,KIND=8) &
     &                ,REAL(I2-1,KIND=8)/REAL(SMOOTH_NR2,KIND=8) &
     &                ,REAL(I3-1,KIND=8)/REAL(SMOOTH_NR3,KIND=8)/))
                CALL PAW_SKALA_SMOOTH_PARTITION_DERIVATIVES &
     &               (POINT,NAT,ATOMCOORD,SMOOTH_RBAS,PARTITION &
     &               ,DPARTITION_DATOM,DPARTITION_DPOINT)
                DO I=1,NAT
                  DO J=1,NAT
                    FORWARD_DERIV(:,J)=FORWARD_DERIV(:,J) &
     &                +SMOOTH_PARTITION_SENSITIVITY(I1,I2,I3,I) &
     &                 *DPARTITION_DATOM(:,J,I)
                    FORWARD_DERIV_SMOOTH_PARTITION(:,J)= &
     &                FORWARD_DERIV_SMOOTH_PARTITION(:,J) &
     &                +SMOOTH_PARTITION_SENSITIVITY(I1,I2,I3,I) &
     &                 *DPARTITION_DATOM(:,J,I)
                  END DO
                END DO
              END DO
            END DO
          END DO
          DEALLOCATE(ATOMCOORD,ATOMCOORD3,PARTITION)
          DEALLOCATE(DPARTITION_DATOM,DPARTITION_DPOINT)
        END IF
        CALL MPE$BROADCAST('MONOMER',1,FORWARD_DERIV)
        ALLOCATE(FORCE(3,NAT))
        CALL ATOMLIST$GETR8A('FORCE',0,3*NAT,FORCE)
        FORCE=FORCE-FORWARD_DERIV
        CALL ATOMLIST$SETR8A('FORCE',0,3*NAT,FORCE)
        DEALLOCATE(FORCE)
      END IF
      IF(SMOOTH_DVOL.LE.0.D0) THEN
        CALL ERROR$MSG('SKALA SMOOTH GRID VOLUME IS INVALID')
        CALL ERROR$STOP('SKALA$FORWARDEND')
      END IF
      SMOOTH_ADJ_RHO=SMOOTH_ADJ_RHO/SMOOTH_DVOL
      SMOOTH_ADJ_GRHO=SMOOTH_ADJ_GRHO/SMOOTH_DVOL
      SMOOTH_ADJ_TAU=SMOOTH_ADJ_TAU/SMOOTH_DVOL
      RHONORM=SQRT(SUM(SMOOTH_ADJ_RHO**2))
      GRADNORM=SQRT(SUM(SMOOTH_ADJ_GRHO**2))
      TAUNORM=SQRT(SUM(SMOOTH_ADJ_TAU**2))
      IF(CONFIG_APPLY) THEN
        CALL ENERGYLIST$ADD('TOTAL ENERGY',FORWARD_ENERGY)
        CALL ENERGYLIST$ADD('AE  EXCHANGE-CORRELATION',FORWARD_ENERGY)
        CALL ENERGYLIST$ADD('PS  EXCHANGE-CORRELATION',FORWARD_ENERGY)
      END IF
      IF(THISTASK.EQ.1.AND..NOT.TFORWARDREPORTED) THEN
        CALL FILEHANDLER$UNIT('PROT',NFIL)
        WRITE(NFIL,FMT='(/"SKALA COMPLETE PAW ATOM BLOCKS"/30("="))')
        WRITE(NFIL,FMT='("HYBRID-GRID ROWS",T34,I12)')FORWARD_NPOINT
        WRITE(NFIL,FMT='("PARTITION TRANSLATION CLASSES",T34,I12)') &
     &       SMOOTH_PARTITION_NCLASS
        WRITE(NFIL,FMT='("SMOOTH ELECTRONS",T34,ES24.14)') &
     &       FORWARD_SMOOTH_ELECTRONS
        WRITE(NFIL,FMT='("AE-PS ELECTRONS",T34,ES24.14)') &
     &       FORWARD_CORRECTION_ELECTRONS
        WRITE(NFIL,FMT='("COMPOSITE ELECTRONS",T34,ES24.14)')FORWARD_ELECTRONS
        WRITE(NFIL,FMT='("SMOOTH POSITIVE TAU",T34,ES24.14)')FORWARD_SMOOTH_TAU
        WRITE(NFIL,FMT='("AE-PS POSITIVE TAU",T34,ES24.14)') &
     &       FORWARD_CORRECTION_TAU
        WRITE(NFIL,FMT='("COMPOSITE POSITIVE TAU",T34,ES24.14)')FORWARD_TAU
        WRITE(NFIL,FMT='("MODEL XC ENERGY",T34,ES24.14)')FORWARD_ENERGY
        IF(CONFIG_CHECK) THEN
          DO I=1,SIZE(FORWARD_ATOM_ENERGY)
            WRITE(NFIL,FMT='("ATOM BLOCK",I6," ROWS",I10 &
     &                    ," ENERGY",ES24.14)') &
     &           I,FORWARD_ATOM_NPOINT(I),FORWARD_ATOM_ENERGY(I)
          END DO
        END IF
        WRITE(NFIL,FMT='("SMOOTH GRID DVOL",T34,ES24.14)')SMOOTH_DVOL
        WRITE(NFIL,FMT='("SMOOTH RHO ADJOINT L2",T34,ES24.14)')RHONORM
        WRITE(NFIL,FMT='("SMOOTH GRAD ADJOINT L2",T34,ES24.14)')GRADNORM
        WRITE(NFIL,FMT='("SMOOTH TAU ADJOINT L2",T34,ES24.14)')TAUNORM
        WRITE(NFIL,FMT='("ONE-CENTER ADJOINT L2",T34,ES24.14)') &
     &       SQRT(FORWARD_ONECENTER_ADJOINT_NORM2)
        IF(ALLOCATED(FORWARD_DERIV)) THEN
          NETFORCE=-SUM(FORWARD_DERIV,DIM=2)
          WRITE(NFIL,FMT='("SKALA FORCE L2",T34,ES24.14)') &
     &         SQRT(SUM(FORWARD_DERIV**2))
          WRITE(NFIL,FMT='("SKALA NET FORCE",T34,3ES16.7)')NETFORCE
          IF(CONFIG_CHECK) THEN
            DO I=1,SIZE(FORWARD_DERIV,2)
              WRITE(NFIL,FMT='("SKALA FORCE ATOM",I6,3ES24.14)') &
     &             I,-FORWARD_DERIV(:,I)
              WRITE(NFIL,FMT='("MODEL COORD FORCE ATOM",I6,3ES24.14)') &
     &             I,-FORWARD_DERIV_MODEL_ATOM(:,I)
              WRITE(NFIL,FMT='("LOCAL GRID FORCE ATOM",I6,3ES24.14)') &
     &             I,-FORWARD_DERIV_LOCAL_GRID(:,I)
              WRITE(NFIL,FMT='("LOCAL PRIMITIVE FORCE ATOM",I6 &
     &                    ,3ES24.14)') &
     &             I,-FORWARD_DERIV_LOCAL_PRIMITIVE(:,I)
              WRITE(NFIL,FMT='("LOCAL PARTITION FORCE ATOM",I6 &
     &                    ,3ES24.14)') &
     &             I,-FORWARD_DERIV_LOCAL_PARTITION(:,I)
              WRITE(NFIL,FMT='("SMOOTH PARTITION FORCE ATOM",I6 &
     &                    ,3ES24.14)') &
     &             I,-FORWARD_DERIV_SMOOTH_PARTITION(:,I)
              WRITE(NFIL,FMT='("RADIAL BLEND FORCE ATOM",I6,3ES24.14)') &
     &             I,-FORWARD_DERIV_RADIAL_BLEND(:,I)
            END DO
          END IF
          WRITE(NFIL,FMT='("MODEL ATOM FORCE L2",T34,ES24.14)') &
     &         SQRT(SUM(FORWARD_DERIV_MODEL_ATOM**2))
          NETFORCE=-SUM(FORWARD_DERIV_MODEL_ATOM,DIM=2)
          WRITE(NFIL,FMT='("MODEL ATOM NET FORCE",T34,3ES16.7)')NETFORCE
          WRITE(NFIL,FMT='("LOCAL GRID FORCE L2",T34,ES24.14)') &
     &         SQRT(SUM(FORWARD_DERIV_LOCAL_GRID**2))
          NETFORCE=-SUM(FORWARD_DERIV_LOCAL_GRID,DIM=2)
          WRITE(NFIL,FMT='("LOCAL GRID NET FORCE",T34,3ES16.7)')NETFORCE
          WRITE(NFIL,FMT='("LOCAL PRIMITIVE FORCE L2",T34,ES24.14)') &
     &         SQRT(SUM(FORWARD_DERIV_LOCAL_PRIMITIVE**2))
          NETFORCE=-SUM(FORWARD_DERIV_LOCAL_PRIMITIVE,DIM=2)
          WRITE(NFIL,FMT='("LOCAL PRIMITIVE NET FORCE",T34,3ES16.7)')NETFORCE
          WRITE(NFIL,FMT='("LOCAL PARTITION FORCE L2",T34,ES24.14)') &
     &         SQRT(SUM(FORWARD_DERIV_LOCAL_PARTITION**2))
          NETFORCE=-SUM(FORWARD_DERIV_LOCAL_PARTITION,DIM=2)
          WRITE(NFIL,FMT='("LOCAL PARTITION NET FORCE",T34,3ES16.7)')NETFORCE
          WRITE(NFIL,FMT='("SMOOTH PARTITION FORCE L2",T34,ES24.14)') &
     &         SQRT(SUM(FORWARD_DERIV_SMOOTH_PARTITION**2))
          NETFORCE=-SUM(FORWARD_DERIV_SMOOTH_PARTITION,DIM=2)
          WRITE(NFIL,FMT='("SMOOTH PARTITION NET FORCE",T34,3ES16.7)') &
     &         NETFORCE
          WRITE(NFIL,FMT='("RADIAL BLEND FORCE L2",T34,ES24.14)') &
     &         SQRT(SUM(FORWARD_DERIV_RADIAL_BLEND**2))
          NETFORCE=-SUM(FORWARD_DERIV_RADIAL_BLEND,DIM=2)
          WRITE(NFIL,FMT='("RADIAL BLEND NET FORCE",T34,3ES16.7)') &
     &         NETFORCE
        END IF
      END IF
      TFORWARDREPORTED=.TRUE.
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$TOTALFORCEREPORT(NAT,FORCE)
      USE PAW_SKALA_MODULE
      USE MPE_MODULE
      IMPLICIT NONE
      INTEGER(4),INTENT(IN) :: NAT
      REAL(8),INTENT(IN) :: FORCE(3,NAT)
      INTEGER(4) :: NTASKS,THISTASK,NFIL,IAT
      REAL(8) :: ETOT

      IF(.NOT.TON.OR..NOT.CONFIG_NEEDFORCE) RETURN
      IF(.NOT.CONFIG_APPLY.AND..NOT.CONFIG_CHECK) RETURN
      CALL MPE$QUERY('MONOMER',NTASKS,THISTASK)
      IF(THISTASK.NE.1) RETURN
      CALL FILEHANDLER$UNIT('PROT',NFIL)
      CALL ENERGYLIST$GET('TOTAL ENERGY',ETOT)
      WRITE(NFIL,FMT='(/"SKALA TOTAL FORCE DIAGNOSTIC"/28("="))')
      WRITE(NFIL,FMT='("TOTAL ENERGY",T20,ES24.14)')ETOT
      DO IAT=1,NAT
        WRITE(NFIL,FMT='("ATOM",I6,3ES24.14)')IAT,FORCE(:,IAT)
      END DO
      WRITE(NFIL,FMT='("NET FORCE",T12,3ES24.14)')SUM(FORCE,DIM=2)
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$SMOOTHADJOINTGET(NR1START,NR1L,NR1,NR2,NR3 &
     &                                  ,NDIMD,VRHO,VGRAD,VTAU)
      USE PAW_SKALA_MODULE
      IMPLICIT NONE
      INTEGER(4),INTENT(IN) :: NR1START,NR1L,NR1,NR2,NR3,NDIMD
      REAL(8),INTENT(OUT) :: VRHO(NR1L*NR2*NR3,NDIMD)
      REAL(8),INTENT(OUT) :: VGRAD(NR1L*NR2*NR3,3,NDIMD)
      REAL(8),INTENT(OUT) :: VTAU(NR1L*NR2*NR3,NDIMD)
      INTEGER(4) :: IEND,IDIM,ICART

      IF(.NOT.ALLOCATED(SMOOTH_ADJ_RHO) &
     &   .OR..NOT.ALLOCATED(SMOOTH_ADJ_GRHO) &
     &   .OR..NOT.ALLOCATED(SMOOTH_ADJ_TAU)) THEN
        CALL ERROR$MSG('SKALA SMOOTH ADJOINTS ARE NOT AVAILABLE')
        CALL ERROR$STOP('SKALA$SMOOTHADJOINTGET')
      END IF
      IEND=NR1START+NR1L-1
      IF(NR1.NE.SMOOTH_NR1.OR.NR2.NE.SMOOTH_NR2 &
     &   .OR.NR3.NE.SMOOTH_NR3.OR.NDIMD.NE.SMOOTH_NDIMD &
     &   .OR.NR1START.LT.1.OR.IEND.GT.NR1) THEN
        CALL ERROR$MSG('SKALA SMOOTH ADJOINT GRID IS INCONSISTENT')
        CALL ERROR$I4VAL('NR1',NR1)
        CALL ERROR$I4VAL('CACHED NR1',SMOOTH_NR1)
        CALL ERROR$I4VAL('NR1START',NR1START)
        CALL ERROR$I4VAL('NR1L',NR1L)
        CALL ERROR$STOP('SKALA$SMOOTHADJOINTGET')
      END IF
      DO IDIM=1,NDIMD
        VRHO(:,IDIM)=RESHAPE(SMOOTH_ADJ_RHO(NR1START:IEND,:,:,IDIM) &
     &                      ,(/NR1L*NR2*NR3/))
        VTAU(:,IDIM)=RESHAPE(SMOOTH_ADJ_TAU(NR1START:IEND,:,:,IDIM) &
     &                      ,(/NR1L*NR2*NR3/))
        DO ICART=1,3
          VGRAD(:,ICART,IDIM)=RESHAPE &
     &       (SMOOTH_ADJ_GRHO(NR1START:IEND,:,:,ICART,IDIM) &
     &       ,(/NR1L*NR2*NR3/))
        END DO
      END DO
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$SMOOTHFIELDSGET(NR1START,NR1L,NR1,NR2,NR3 &
     &                                 ,NDIMD,RHO,GRHO,TAU,DVOL)
      USE PAW_SKALA_MODULE
      IMPLICIT NONE
      INTEGER(4),INTENT(IN) :: NR1START,NR1L,NR1,NR2,NR3,NDIMD
      REAL(8),INTENT(OUT) :: RHO(NR1L*NR2*NR3,NDIMD)
      REAL(8),INTENT(OUT) :: GRHO(NR1L*NR2*NR3,3,NDIMD)
      REAL(8),INTENT(OUT) :: TAU(NR1L*NR2*NR3,NDIMD),DVOL
      INTEGER(4) :: IEND,IDIM,ICART

      IF(.NOT.TSMOOTHREADY) THEN
        CALL ERROR$MSG('SKALA SMOOTH FIELDS ARE NOT AVAILABLE')
        CALL ERROR$STOP('SKALA$SMOOTHFIELDSGET')
      END IF
      IEND=NR1START+NR1L-1
      IF(NR1.NE.SMOOTH_NR1.OR.NR2.NE.SMOOTH_NR2 &
     &   .OR.NR3.NE.SMOOTH_NR3.OR.NDIMD.NE.SMOOTH_NDIMD &
     &   .OR.NR1START.LT.1.OR.IEND.GT.NR1) THEN
        CALL ERROR$MSG('SKALA SMOOTH FIELD GRID IS INCONSISTENT')
        CALL ERROR$STOP('SKALA$SMOOTHFIELDSGET')
      END IF
      DO IDIM=1,NDIMD
        RHO(:,IDIM)=RESHAPE(SMOOTH_RHO(NR1START:IEND,:,:,IDIM) &
     &                     ,(/NR1L*NR2*NR3/))
        TAU(:,IDIM)=RESHAPE(SMOOTH_TAU(NR1START:IEND,:,:,IDIM) &
     &                     ,(/NR1L*NR2*NR3/))
        DO ICART=1,3
          GRHO(:,ICART,IDIM)=RESHAPE &
     &       (SMOOTH_GRHO(NR1START:IEND,:,:,ICART,IDIM) &
     &       ,(/NR1L*NR2*NR3/))
        END DO
      END DO
      DVOL=SMOOTH_DVOL
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$SMOOTHSCALARCONTRACTION(VAL)
      USE PAW_SKALA_MODULE
      USE MPE_MODULE
      IMPLICIT NONE
      REAL(8),INTENT(IN) :: VAL

      SMOOTH_SCALAR_CONTRACTION=VAL
      CALL MPE$COMBINE('MONOMER','+',SMOOTH_SCALAR_CONTRACTION)
      TSCALARCONTRACTIONREADY=.TRUE.
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$SMOOTHOPERATORCHECK(LEFT,RIGHT,TAUCONTR)
      USE PAW_SKALA_MODULE
      USE MPE_MODULE
      IMPLICIT NONE
      REAL(8),INTENT(IN) :: LEFT,RIGHT,TAUCONTR
      REAL(8) :: LEFT1,RIGHT1,TAUCONTR1
      INTEGER(4) :: NTASKS,THISTASK,NFIL

      LEFT1=LEFT
      RIGHT1=RIGHT
      TAUCONTR1=TAUCONTR
      CALL MPE$COMBINE('MONOMER','+',LEFT1)
      CALL MPE$COMBINE('MONOMER','+',RIGHT1)
      CALL MPE$COMBINE('MONOMER','+',TAUCONTR1)
      SMOOTH_TAU_CONTRACTION=TAUCONTR1
      TTAUCONTRACTIONREADY=.TRUE.
      CALL MPE$QUERY('MONOMER',NTASKS,THISTASK)
      IF(THISTASK.EQ.1) THEN
        CALL FILEHANDLER$UNIT('PROT',NFIL)
        WRITE(NFIL,FMT='("SMOOTH OPERATOR CONTRACTION",T34,ES24.14)')LEFT1
        WRITE(NFIL,FMT='("PRIMITIVE GRAD CONTRACTION",T34,ES24.14)')RIGHT1
        WRITE(NFIL,FMT='("GRAD ADJOINT DIFFERENCE",T34,ES24.14)')LEFT1-RIGHT1
        WRITE(NFIL,FMT='("TAU ADJOINT CONTRACTION",T34,ES24.14)')TAUCONTR1
      END IF
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$TAUOPERATORCHECK(EXPECTATION)
      USE PAW_SKALA_MODULE
      USE MPE_MODULE
      IMPLICIT NONE
      REAL(8),INTENT(IN) :: EXPECTATION
      REAL(8) :: EXPECTATION1,TOTAL
      INTEGER(4) :: NTASKS,THISTASK,NFIL

      IF(.NOT.TTAUCONTRACTIONREADY) THEN
        CALL ERROR$MSG('SKALA TAU CONTRACTION IS NOT AVAILABLE')
        CALL ERROR$STOP('SKALA$TAUOPERATORCHECK')
      END IF
      IF(.NOT.TSCALARCONTRACTIONREADY) THEN
        CALL ERROR$MSG('SKALA SCALAR CONTRACTION IS NOT AVAILABLE')
        CALL ERROR$STOP('SKALA$TAUOPERATORCHECK')
      END IF
      IF(.NOT.TONECENTERCONTRACTIONREADY) THEN
        CALL ERROR$MSG('SKALA ONE-CENTER CONTRACTION IS NOT AVAILABLE')
        CALL ERROR$STOP('SKALA$TAUOPERATORCHECK')
      END IF
      EXPECTATION1=EXPECTATION
      CALL MPE$COMBINE('MONOMER','+',EXPECTATION1)
      CALL MPE$QUERY('MONOMER',NTASKS,THISTASK)
      IF(THISTASK.EQ.1) THEN
        CALL FILEHANDLER$UNIT('PROT',NFIL)
        WRITE(NFIL,FMT='("TAU OPERATOR EXPECTATION",T34,ES24.14)')EXPECTATION1
        WRITE(NFIL,FMT='("TAU OPERATOR DIFFERENCE",T34,ES24.14)') &
     &       EXPECTATION1-SMOOTH_TAU_CONTRACTION
        WRITE(NFIL,FMT='("SMOOTH SCALAR VALENCE CONTRACTION",T42,ES24.14)') &
     &       SMOOTH_SCALAR_CONTRACTION
        WRITE(NFIL,FMT='("ONE-CENTER VALENCE CONTRACTION",T42,ES24.14)') &
     &       ONECENTER_CONTRACTION
        TOTAL=SMOOTH_SCALAR_CONTRACTION+EXPECTATION1+ONECENTER_CONTRACTION
        WRITE(NFIL,FMT='("FULL ELECTRONIC OPERATOR CONTRACTION",T42,ES24.14)') &
     &       TOTAL
      END IF
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$SMOOTHOPERATORREPORT(POTNORM2,TAUNORM2)
      USE PAW_SKALA_MODULE
      USE MPE_MODULE
      IMPLICIT NONE
      REAL(8),INTENT(IN) :: POTNORM2,TAUNORM2
      REAL(8) :: POTNORM21,TAUNORM21
      INTEGER(4) :: NTASKS,THISTASK,NFIL

      IF(TOPERATORREPORTED) RETURN
      POTNORM21=POTNORM2
      TAUNORM21=TAUNORM2
      CALL MPE$COMBINE('MONOMER','+',POTNORM21)
      CALL MPE$COMBINE('MONOMER','+',TAUNORM21)
      CALL MPE$QUERY('MONOMER',NTASKS,THISTASK)
      IF(THISTASK.EQ.1) THEN
        CALL FILEHANDLER$UNIT('PROT',NFIL)
        WRITE(NFIL,FMT='("SMOOTH SCALAR OPERATOR L2",T34,ES24.14)') &
     &       SQRT(POTNORM21)
        WRITE(NFIL,FMT='("SMOOTH TAU OPERATOR L2",T34,ES24.14)') &
     &       SQRT(TAUNORM21)
      END IF
      TOPERATORREPORTED=.TRUE.
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$SMOOTHSET(NR1START,NR1L,NR1,NR2,NR3,NDIMD &
     &                          ,RHO,GRHO,TAUPOS,RBAS)
      USE PAW_SKALA_MODULE
      USE MPE_MODULE
      IMPLICIT NONE
      INTEGER(4),INTENT(IN) :: NR1START,NR1L,NR1,NR2,NR3,NDIMD
      REAL(8),INTENT(IN) :: RHO(NR1L*NR2*NR3,NDIMD)
      REAL(8),INTENT(IN) :: GRHO(NR1L*NR2*NR3,3,NDIMD)
      REAL(8),INTENT(IN) :: TAUPOS(NR1L*NR2*NR3,NDIMD)
      REAL(8),INTENT(IN) :: RBAS(3,3)
      INTEGER(4) :: IDIM,ICART,IEND

      IF(.NOT.TON) RETURN
      IF(NDIMD.NE.1.AND.NDIMD.NE.2) THEN
        CALL ERROR$MSG('SKALA SMOOTH CACHE REQUIRES COLLINEAR SPIN')
        CALL ERROR$I4VAL('NDIMD',NDIMD)
        CALL ERROR$STOP('SKALA$SMOOTHSET')
      END IF
      IEND=NR1START+NR1L-1
      IF(NR1START.LT.1.OR.IEND.GT.NR1) THEN
        CALL ERROR$MSG('INVALID LOCAL SKALA GRID SLAB')
        CALL ERROR$I4VAL('NR1START',NR1START)
        CALL ERROR$I4VAL('NR1L',NR1L)
        CALL ERROR$I4VAL('NR1',NR1)
        CALL ERROR$STOP('SKALA$SMOOTHSET')
      END IF
      IF(ALLOCATED(SMOOTH_RHO)) DEALLOCATE(SMOOTH_RHO)
      IF(ALLOCATED(SMOOTH_GRHO)) DEALLOCATE(SMOOTH_GRHO)
      IF(ALLOCATED(SMOOTH_TAU)) DEALLOCATE(SMOOTH_TAU)
      IF(ALLOCATED(SMOOTH_PARTITION)) DEALLOCATE(SMOOTH_PARTITION)
      ALLOCATE(SMOOTH_RHO(NR1,NR2,NR3,NDIMD))
      ALLOCATE(SMOOTH_GRHO(NR1,NR2,NR3,3,NDIMD))
      ALLOCATE(SMOOTH_TAU(NR1,NR2,NR3,NDIMD))
      SMOOTH_RHO=0.D0
      SMOOTH_GRHO=0.D0
      SMOOTH_TAU=0.D0
      DO IDIM=1,NDIMD
        SMOOTH_RHO(NR1START:IEND,:,:,IDIM)= &
     &      RESHAPE(RHO(:,IDIM),(/NR1L,NR2,NR3/))
        SMOOTH_TAU(NR1START:IEND,:,:,IDIM)= &
     &      RESHAPE(TAUPOS(:,IDIM),(/NR1L,NR2,NR3/))
        DO ICART=1,3
          SMOOTH_GRHO(NR1START:IEND,:,:,ICART,IDIM)= &
     &        RESHAPE(GRHO(:,ICART,IDIM),(/NR1L,NR2,NR3/))
        END DO
      END DO
      CALL MPE$COMBINE('MONOMER','+',SMOOTH_RHO)
      CALL MPE$COMBINE('MONOMER','+',SMOOTH_GRHO)
      CALL MPE$COMBINE('MONOMER','+',SMOOTH_TAU)
      SMOOTH_NR1=NR1
      SMOOTH_NR2=NR2
      SMOOTH_NR3=NR3
      SMOOTH_NDIMD=NDIMD
      SMOOTH_RBAS=RBAS
      SMOOTH_DVOL=ABS(RBAS(1,1)*(RBAS(2,2)*RBAS(3,3) &
     &                              -RBAS(2,3)*RBAS(3,2)) &
     &                -RBAS(1,2)*(RBAS(2,1)*RBAS(3,3) &
     &                              -RBAS(2,3)*RBAS(3,1)) &
     &                +RBAS(1,3)*(RBAS(2,1)*RBAS(3,2) &
     &                              -RBAS(2,2)*RBAS(3,1))) &
     &             /(REAL(NR1,KIND=8)*REAL(NR2,KIND=8) &
     &                                *REAL(NR3,KIND=8))
      TSMOOTHREADY=.TRUE.
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$SMOOTHVALIDATE(NRL,NDIMD,RHO,GRHO,TAUPOS &
     &                               ,NGRIDGLOBAL,CELLVOL)
      USE PAW_SKALA_MODULE
      USE MPE_MODULE
      IMPLICIT NONE
      INTEGER(4),INTENT(IN) :: NRL,NDIMD,NGRIDGLOBAL
      REAL(8),INTENT(IN) :: RHO(NRL,NDIMD)
      REAL(8),INTENT(IN) :: GRHO(NRL,3,NDIMD)
      REAL(8),INTENT(IN) :: TAUPOS(NRL,NDIMD)
      REAL(8),INTENT(IN) :: CELLVOL
      REAL(8) :: RWEIGHT,RHOINT,SPININT,TAUINT,GRADNORM
      INTEGER(4) :: NTASKS,THISTASK,NFIL

      IF(.NOT.TON.OR.TSMOOTHREPORTED) RETURN
      IF(NDIMD.NE.1.AND.NDIMD.NE.2) THEN
        CALL ERROR$MSG('SKALA SMOOTH PRIMITIVES REQUIRE COLLINEAR SPIN')
        CALL ERROR$I4VAL('NDIMD',NDIMD)
        CALL ERROR$STOP('SKALA$SMOOTHVALIDATE')
      END IF
      RWEIGHT=CELLVOL/REAL(NGRIDGLOBAL,KIND=8)
      RHOINT=SUM(RHO(:,1))*RWEIGHT
      TAUINT=SUM(TAUPOS(:,1))*RWEIGHT
      GRADNORM=SUM(GRHO(:,:,1)**2)*RWEIGHT
      SPININT=0.D0
      IF(NDIMD.EQ.2) SPININT=SUM(RHO(:,2))*RWEIGHT
      CALL MPE$COMBINE('MONOMER','+',RHOINT)
      CALL MPE$COMBINE('MONOMER','+',TAUINT)
      CALL MPE$COMBINE('MONOMER','+',GRADNORM)
      CALL MPE$COMBINE('MONOMER','+',SPININT)
      CALL MPE$QUERY('MONOMER',NTASKS,THISTASK)
      IF(THISTASK.EQ.1) THEN
        CALL FILEHANDLER$UNIT('PROT',NFIL)
        WRITE(NFIL,FMT='(/"SKALA SMOOTH PRIMITIVES"/23("="))')
        WRITE(NFIL,FMT='("GRID POINTS",T34,I12)')NGRIDGLOBAL
        WRITE(NFIL,FMT='("SMOOTH ELECTRONS WITH CORE",T34,ES24.14)')RHOINT
        IF(NDIMD.EQ.2) THEN
          WRITE(NFIL,FMT='("SMOOTH SPIN",T34,ES24.14)')SPININT
        END IF
        WRITE(NFIL,FMT='("POSITIVE TAU",T34,ES24.14)')TAUINT
        WRITE(NFIL,FMT='("DENSITY GRADIENT L2",T34,ES24.14)')SQRT(GRADNORM)
      END IF
      TSMOOTHREPORTED=.TRUE.
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$ONECENTERVALIDATE(IAT,GID,NR,LNX,LOX,LMNX,LMRX &
     &                                  ,NDIMD,DENMAT,AEPHI,PSPHI &
     &                                  ,AECORE,PSCORE,AERHOL,PSRHOL &
     &                                  ,RCUT,EKINNL)
      USE PAW_SKALA_MODULE
      USE PAW_SKALA_PRIMITIVES_MODULE, ONLY: &
     &     PAW_SKALA_ONECENTER_GRID_SIZE,PAW_SKALA_ONECENTER_PRIMITIVES
      IMPLICIT NONE
      INTEGER(4),INTENT(IN) :: IAT,GID,NR,LNX,LOX(LNX),LMNX,LMRX,NDIMD
      COMPLEX(8),INTENT(IN) :: DENMAT(LMNX,LMNX,NDIMD)
      REAL(8),INTENT(IN) :: AEPHI(NR,LNX),PSPHI(NR,LNX)
      REAL(8),INTENT(IN) :: AECORE(NR),PSCORE(NR)
      REAL(8),INTENT(IN) :: AERHOL(NR,LMRX,NDIMD),PSRHOL(NR,LMRX,NDIMD)
      REAL(8),INTENT(IN) :: RCUT,EKINNL
      INTEGER(4),PARAMETER :: LEBEDEV_L=17
      REAL(8),PARAMETER :: PI=4.D0*ATAN(1.D0)
      LOGICAL(4),ALLOCATABLE :: TREPORTED1(:)
      REAL(8),ALLOCATABLE :: RELCOORD(:,:),WEIGHT(:)
      REAL(8),ALLOCATABLE :: AERHO(:,:),PSRHO(:,:),AETAU(:,:),PSTAU(:,:)
      REAL(8),ALLOCATABLE :: AEGRAD(:,:,:),PSGRAD(:,:,:)
      REAL(8) :: R(NR),WORK(NR),INTEGRAL(NR)
      REAL(8) :: AECOUNT,PSCOUNT,AECOUNTREF,PSCOUNTREF,TAUDIFF
      INTEGER(4) :: NRUSE,NANG,NPOINT,NFIL

      IF(.NOT.TON) RETURN
      IF(IAT.LE.0) RETURN
      IF(.NOT.ALLOCATED(TONECENTERREPORTED)) THEN
        ALLOCATE(TONECENTERREPORTED(IAT))
        TONECENTERREPORTED(:)=.FALSE.
      ELSE IF(SIZE(TONECENTERREPORTED).LT.IAT) THEN
        ALLOCATE(TREPORTED1(IAT))
        TREPORTED1(:)=.FALSE.
        TREPORTED1(1:SIZE(TONECENTERREPORTED))=TONECENTERREPORTED
        CALL MOVE_ALLOC(TREPORTED1,TONECENTERREPORTED)
      END IF
      IF(TONECENTERREPORTED(IAT)) RETURN

      CALL PAW_SKALA_ONECENTER_GRID_SIZE(GID,NR,RCUT,LEBEDEV_L &
     &                                  ,NRUSE,NANG,NPOINT)
      ALLOCATE(RELCOORD(NPOINT,3),WEIGHT(NPOINT))
      ALLOCATE(AERHO(NPOINT,2),PSRHO(NPOINT,2))
      ALLOCATE(AEGRAD(NPOINT,3,2),PSGRAD(NPOINT,3,2))
      ALLOCATE(AETAU(NPOINT,2),PSTAU(NPOINT,2))
      CALL PAW_SKALA_ONECENTER_PRIMITIVES(GID,NR,LNX,LOX,LMNX,NDIMD &
     &                                   ,DENMAT,AEPHI,PSPHI,AECORE,PSCORE &
     &                                   ,RCUT,LEBEDEV_L,NPOINT &
     &                                   ,RELCOORD,WEIGHT,AERHO,AEGRAD,AETAU &
     &                                   ,PSRHO,PSGRAD,PSTAU)

      AECOUNT=SUM(WEIGHT*(AERHO(:,1)+AERHO(:,2)))
      PSCOUNT=SUM(WEIGHT*(PSRHO(:,1)+PSRHO(:,2)))
      TAUDIFF=SUM(WEIGHT*(AETAU(:,1)+AETAU(:,2) &
     &                         -PSTAU(:,1)-PSTAU(:,2)))
      CALL RADIAL$R(GID,NR,R)
      WORK(:)=(AERHOL(:,1,1)+AECORE)*R**2
      CALL RADIAL$INTEGRATE(GID,NR,WORK,INTEGRAL)
      AECOUNTREF=SQRT(4.D0*PI)*INTEGRAL(NRUSE)
      WORK(:)=(PSRHOL(:,1,1)+PSCORE)*R**2
      CALL RADIAL$INTEGRATE(GID,NR,WORK,INTEGRAL)
      PSCOUNTREF=SQRT(4.D0*PI)*INTEGRAL(NRUSE)

      CALL FILEHANDLER$UNIT('PROT',NFIL)
      WRITE(NFIL,FMT='(/"SKALA PAW ONE-CENTER PRIMITIVES"/31("="))')
      WRITE(NFIL,FMT='("ATOM INDEX",T34,I10)')IAT
      WRITE(NFIL,FMT='("LEBEDEV EXACTNESS",T34,I10)')LEBEDEV_L
      WRITE(NFIL,FMT='("RADIAL POINTS",T34,I10)')NRUSE
      WRITE(NFIL,FMT='("ANGULAR POINTS",T34,I10)')NANG
      WRITE(NFIL,FMT='("TOTAL POINTS",T34,I10)')NPOINT
      WRITE(NFIL,FMT='("AE ELECTRONS",T34,ES24.14)')AECOUNT
      WRITE(NFIL,FMT='("AE ELECTRON ERROR",T34,ES24.14)')AECOUNT-AECOUNTREF
      WRITE(NFIL,FMT='("PS ELECTRONS",T34,ES24.14)')PSCOUNT
      WRITE(NFIL,FMT='("PS ELECTRON ERROR",T34,ES24.14)')PSCOUNT-PSCOUNTREF
      WRITE(NFIL,FMT='("POSITIVE TAU AE-PS",T34,ES24.14)')TAUDIFF
      WRITE(NFIL,FMT='("ONE-CENTER KINETIC",T34,ES24.14)')EKINNL
      WRITE(NFIL,FMT='("TAU-KINETIC DIFFERENCE",T34,ES24.14)')TAUDIFF-EKINNL
      TONECENTERREPORTED(IAT)=.TRUE.

      DEALLOCATE(RELCOORD,WEIGHT,AERHO,PSRHO,AEGRAD,PSGRAD,AETAU,PSTAU)
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$EVALUATE(NPOINT,NATOM,DENSITY,GRAD,KIN &
     &                         ,GRIDCOORDS,GRIDWEIGHTS,ATOMCOORDS &
     &                         ,ATOMICGRIDWEIGHTS,ATOMICGRIDSIZES,ENERGY &
     &                         ,DDENSITY,DGRAD,DKIN,DGRIDCOORDS &
     &                         ,DGRIDWEIGHTS,DATOMCOORDS,DATOMICGRIDWEIGHTS)
      USE PAW_SKALA_MODULE
      IMPLICIT NONE
      INTEGER(4),INTENT(IN)  :: NPOINT
      INTEGER(4),INTENT(IN)  :: NATOM
      REAL(8)   ,INTENT(IN)  :: DENSITY(NPOINT,2)
      REAL(8)   ,INTENT(IN)  :: GRAD(NPOINT,3,2)
      REAL(8)   ,INTENT(IN)  :: KIN(NPOINT,2)
      REAL(8)   ,INTENT(IN)  :: GRIDCOORDS(NPOINT,3)
      REAL(8)   ,INTENT(IN)  :: GRIDWEIGHTS(NPOINT)
      REAL(8)   ,INTENT(IN)  :: ATOMCOORDS(NATOM,3)
      REAL(8)   ,INTENT(IN)  :: ATOMICGRIDWEIGHTS(NPOINT)
      INTEGER(8),INTENT(IN)  :: ATOMICGRIDSIZES(NATOM)
      REAL(8)   ,INTENT(OUT) :: ENERGY
      REAL(8)   ,INTENT(OUT) :: DDENSITY(NPOINT,2)
      REAL(8)   ,INTENT(OUT) :: DGRAD(NPOINT,3,2)
      REAL(8)   ,INTENT(OUT) :: DKIN(NPOINT,2)
      REAL(8)   ,INTENT(OUT) :: DGRIDCOORDS(NPOINT,3)
      REAL(8)   ,INTENT(OUT) :: DGRIDWEIGHTS(NPOINT)
      REAL(8)   ,INTENT(OUT) :: DATOMCOORDS(NATOM,3)
      REAL(8)   ,INTENT(OUT) :: DATOMICGRIDWEIGHTS(NPOINT)
#IF DEFINED(CPPVAR_SKALA_FTORCH)
      INTEGER(4)             :: STATUS
      CHARACTER(2048)        :: MESSAGE

      IF(.NOT.TINITIALIZED) CALL SKALA$ENSUREINITIALIZED
      CALL PAW_SKALA_EVALUATE(MODEL,DENSITY,GRAD,KIN,GRIDCOORDS,GRIDWEIGHTS &
     &                       ,ATOMCOORDS,ATOMICGRIDWEIGHTS,ATOMICGRIDSIZES &
     &                       ,ENERGY,DDENSITY,DGRAD,DKIN,STATUS,MESSAGE &
     &                       ,DGRIDCOORDS,DGRIDWEIGHTS,DATOMCOORDS &
     &                       ,DATOMICGRIDWEIGHTS)
      IF(STATUS.NE.0) THEN
        CALL ERROR$MSG('SKALA 1.1 EVALUATION FAILED')
        CALL ERROR$CHVAL('DETAIL',TRIM(MESSAGE))
        CALL ERROR$STOP('SKALA$EVALUATE')
      END IF
#ELSE
      CALL ERROR$MSG('CP-PAW WAS BUILT WITHOUT THE SKALA/FTORCH BRIDGE')
      CALL ERROR$STOP('SKALA$EVALUATE')
#ENDIF
      RETURN
      END
