!*******************************************************************************
!**  CARTESIAN SOLID-HARMONIC PRIMITIVES FOR THE SKALA PAW ATOM GRIDS         **
!*******************************************************************************
MODULE PAW_SKALA_PRIMITIVES_MODULE
  IMPLICIT NONE
  PRIVATE

  TYPE, PUBLIC :: PAW_SKALA_SOLID_BASIS
    INTEGER(4) :: LMAX=-1
    INTEGER(4) :: NPOLY=0
    INTEGER(4) :: LMX=0
    INTEGER(4),ALLOCATABLE :: POWER(:,:) !(3,NPOLY)
    REAL(8),ALLOCATABLE :: COEFF(:,:)    !(NPOLY,LMX)
  END TYPE PAW_SKALA_SOLID_BASIS

  PUBLIC :: PAW_SKALA_SOLID_BASIS_INIT
  PUBLIC :: PAW_SKALA_SOLID_BASIS_EVALUATE
  PUBLIC :: PAW_SKALA_ONECENTER_GRID_SIZE
  PUBLIC :: PAW_SKALA_ONECENTER_PRIMITIVES
  PUBLIC :: PAW_SKALA_ONECENTER_POINTS
  PUBLIC :: PAW_SKALA_PRIMITIVES_TEST

CONTAINS

  SUBROUTINE PAW_SKALA_SOLID_BASIS_INIT(BASIS,LMAX)
    TYPE(PAW_SKALA_SOLID_BASIS),INTENT(INOUT) :: BASIS
    INTEGER(4),INTENT(IN) :: LMAX
    INTEGER(4) :: I,J,K,N,IND

    IF(LMAX.LT.0) THEN
      CALL ERROR$MSG('LMAX MUST NOT BE NEGATIVE')
      CALL ERROR$I4VAL('LMAX',LMAX)
      CALL ERROR$STOP('PAW_SKALA_SOLID_BASIS_INIT')
    END IF
    IF(ALLOCATED(BASIS%POWER)) DEALLOCATE(BASIS%POWER)
    IF(ALLOCATED(BASIS%COEFF)) DEALLOCATE(BASIS%COEFF)
    BASIS%LMAX=LMAX
    BASIS%NPOLY=(LMAX+1)*(LMAX+2)*(LMAX+3)/6
    BASIS%LMX=(LMAX+1)**2
    ALLOCATE(BASIS%POWER(3,BASIS%NPOLY))
    ALLOCATE(BASIS%COEFF(BASIS%NPOLY,BASIS%LMX))
    IND=0
    DO N=0,LMAX
      DO I=0,N
        DO J=0,N-I
          K=N-I-J
          IND=IND+1
          BASIS%POWER(:,IND)=(/I,J,K/)
        END DO
      END DO
    END DO
    CALL SPHERICAL$YLMPOLYNOMIALS(LMAX,BASIS%NPOLY,BASIS%LMX &
   &                             ,BASIS%COEFF)
  END SUBROUTINE PAW_SKALA_SOLID_BASIS_INIT

  SUBROUTINE PAW_SKALA_SOLID_BASIS_EVALUATE(BASIS,R,SOLID,GRAD)
    TYPE(PAW_SKALA_SOLID_BASIS),INTENT(IN) :: BASIS
    REAL(8),INTENT(IN) :: R(3)
    REAL(8),INTENT(OUT) :: SOLID(BASIS%LMX)
    REAL(8),INTENT(OUT) :: GRAD(3,BASIS%LMX)
    INTEGER(4) :: I,J,K,IND,LM
    REAL(8) :: C,TERM

    IF(.NOT.ALLOCATED(BASIS%COEFF)) THEN
      CALL ERROR$MSG('SOLID-HARMONIC BASIS HAS NOT BEEN INITIALIZED')
      CALL ERROR$STOP('PAW_SKALA_SOLID_BASIS_EVALUATE')
    END IF
    SOLID(:)=0.D0
    GRAD(:,:)=0.D0
    DO LM=1,BASIS%LMX
      DO IND=1,BASIS%NPOLY
        C=BASIS%COEFF(IND,LM)
        IF(C.EQ.0.D0) CYCLE
        I=BASIS%POWER(1,IND)
        J=BASIS%POWER(2,IND)
        K=BASIS%POWER(3,IND)
        TERM=C*R(1)**I*R(2)**J*R(3)**K
        SOLID(LM)=SOLID(LM)+TERM
        IF(I.GT.0) GRAD(1,LM)=GRAD(1,LM) &
       &                    +C*REAL(I,KIND=8)*R(1)**(I-1)*R(2)**J*R(3)**K
        IF(J.GT.0) GRAD(2,LM)=GRAD(2,LM) &
       &                    +C*REAL(J,KIND=8)*R(1)**I*R(2)**(J-1)*R(3)**K
        IF(K.GT.0) GRAD(3,LM)=GRAD(3,LM) &
       &                    +C*REAL(K,KIND=8)*R(1)**I*R(2)**J*R(3)**(K-1)
      END DO
    END DO
  END SUBROUTINE PAW_SKALA_SOLID_BASIS_EVALUATE

  SUBROUTINE PAW_SKALA_ONECENTER_GRID_SIZE(GID,NR,RCUT,LEBEDEV_L &
 &                                         ,NRUSE,NANG,NPOINT)
    USE PAW_LEBEDEV_MODULE, ONLY: PAW_LEBEDEV_SIZE
    IMPLICIT NONE
    INTEGER(4),INTENT(IN) :: GID,NR,LEBEDEV_L
    REAL(8),INTENT(IN) :: RCUT
    INTEGER(4),INTENT(OUT) :: NRUSE,NANG,NPOINT
    REAL(8) :: R(NR)
    INTEGER(4) :: IR

    IF(RCUT.LE.0.D0) THEN
      CALL ERROR$MSG('ONE-CENTER GRID CUTOFF MUST BE POSITIVE')
      CALL ERROR$R8VAL('RCUT',RCUT)
      CALL ERROR$STOP('PAW_SKALA_ONECENTER_GRID_SIZE')
    END IF
    CALL RADIAL$R(GID,NR,R)
    NRUSE=NR
    DO IR=1,NR
      IF(R(IR).GE.RCUT) THEN
        NRUSE=IR
        EXIT
      END IF
    END DO
    CALL PAW_LEBEDEV_SIZE(LEBEDEV_L,NANG)
    NPOINT=NRUSE*NANG
  END SUBROUTINE PAW_SKALA_ONECENTER_GRID_SIZE

  SUBROUTINE PAW_SKALA_ONECENTER_PRIMITIVES(GID,NR,LNX,LOX,LMNX,NDIMD &
 &                                           ,DENMAT,AEPHI,PSPHI &
 &                                           ,AECORE,PSCORE,RCUT,LEBEDEV_L &
 &                                           ,NPOINT,RELCOORD,WEIGHT &
 &                                           ,AERHO,AEGRAD,AETau &
 &                                           ,PSRHO,PSGRAD,PSTAU)
    USE PAW_LEBEDEV_MODULE, ONLY: PAW_LEBEDEV_GET
    IMPLICIT NONE
    INTEGER(4),INTENT(IN) :: GID,NR,LNX,LOX(LNX),LMNX,NDIMD
    INTEGER(4),INTENT(IN) :: LEBEDEV_L,NPOINT
    COMPLEX(8),INTENT(IN) :: DENMAT(LMNX,LMNX,NDIMD)
    REAL(8),INTENT(IN) :: AEPHI(NR,LNX),PSPHI(NR,LNX)
    REAL(8),INTENT(IN) :: AECORE(NR),PSCORE(NR),RCUT
    REAL(8),INTENT(OUT) :: RELCOORD(NPOINT,3),WEIGHT(NPOINT)
    REAL(8),INTENT(OUT) :: AERHO(NPOINT,2),AEGRAD(NPOINT,3,2)
    REAL(8),INTENT(OUT) :: AETAU(NPOINT,2)
    REAL(8),INTENT(OUT) :: PSRHO(NPOINT,2),PSGRAD(NPOINT,3,2)
    REAL(8),INTENT(OUT) :: PSTAU(NPOINT,2)
    TYPE(PAW_SKALA_SOLID_BASIS) :: BASIS
    REAL(8),PARAMETER :: PI=4.D0*ATAN(1.D0)
    REAL(8),PARAMETER :: Y00=1.D0/SQRT(4.D0*PI)
    REAL(8),ALLOCATABLE :: DRAEPHI(:,:),DRPSPHI(:,:)
    REAL(8),ALLOCATABLE :: DRAECORE(:),DRPSCORE(:)
    REAL(8),ALLOCATABLE :: DIRECTION(:,:),ANGWEIGHT(:),RADWEIGHT(:)
    REAL(8),ALLOCATABLE :: DELTA(:),INTEGRAL(:)
    REAL(8),ALLOCATABLE :: YLM(:),GRADYLM(:,:)
    REAL(8),ALLOCATABLE :: AECHI(:),PSCHI(:)
    REAL(8),ALLOCATABLE :: GAECHI(:,:),GPSCHI(:,:)
    REAL(8),ALLOCATABLE :: RHOAE(:),RHOPS(:),TAUAE(:),TAUPS(:)
    REAL(8),ALLOCATABLE :: GRADAE(:,:),GRADPS(:,:)
    REAL(8) :: R(NR),DREAL,FACTOR
    INTEGER(4) :: NRUSE,NANG,NPOINT1,LMAX,LMX
    INTEGER(4) :: IR,IA,IP,LN,L,IM,LM,LMN,I,J,IDIM,ICART

    IF(NDIMD.NE.1.AND.NDIMD.NE.2) THEN
      CALL ERROR$MSG('SKALA CURRENTLY SUPPORTS ONLY COLLINEAR DENSITIES')
      CALL ERROR$I4VAL('NDIMD',NDIMD)
      CALL ERROR$STOP('PAW_SKALA_ONECENTER_PRIMITIVES')
    END IF
    IF(SUM(2*LOX+1).NE.LMNX) THEN
      CALL ERROR$MSG('PARTIAL-WAVE BASIS SIZE IS INCONSISTENT')
      CALL ERROR$I4VAL('LMNX',LMNX)
      CALL ERROR$I4VAL('EXPECTED',SUM(2*LOX+1))
      CALL ERROR$STOP('PAW_SKALA_ONECENTER_PRIMITIVES')
    END IF
    CALL PAW_SKALA_ONECENTER_GRID_SIZE(GID,NR,RCUT,LEBEDEV_L &
 &                                    ,NRUSE,NANG,NPOINT1)
    IF(NPOINT.NE.NPOINT1) THEN
      CALL ERROR$MSG('ONE-CENTER GRID SIZE IS INCONSISTENT')
      CALL ERROR$I4VAL('NPOINT',NPOINT)
      CALL ERROR$I4VAL('EXPECTED',NPOINT1)
      CALL ERROR$STOP('PAW_SKALA_ONECENTER_PRIMITIVES')
    END IF

    CALL RADIAL$R(GID,NR,R)
    LMAX=MAXVAL(LOX)
    LMX=(LMAX+1)**2
    CALL PAW_SKALA_SOLID_BASIS_INIT(BASIS,LMAX)
    ALLOCATE(DIRECTION(3,NANG),ANGWEIGHT(NANG),RADWEIGHT(NRUSE))
    CALL PAW_LEBEDEV_GET(LEBEDEV_L,NANG,DIRECTION,ANGWEIGHT)
    ALLOCATE(DELTA(NR),INTEGRAL(NR))
    DO IR=1,NRUSE
      DELTA(:)=0.D0
      DELTA(IR)=1.D0
      CALL RADIAL$INTEGRATE(GID,NR,DELTA,INTEGRAL)
      RADWEIGHT(IR)=INTEGRAL(NRUSE)
    END DO
    DEALLOCATE(DELTA,INTEGRAL)

    ALLOCATE(DRAEPHI(NR,LNX),DRPSPHI(NR,LNX))
    DO LN=1,LNX
      CALL RADIAL$DERIVE(GID,NR,AEPHI(:,LN),DRAEPHI(:,LN))
      CALL RADIAL$DERIVE(GID,NR,PSPHI(:,LN),DRPSPHI(:,LN))
    END DO
    ALLOCATE(DRAECORE(NR),DRPSCORE(NR))
    CALL RADIAL$DERIVE(GID,NR,AECORE,DRAECORE)
    CALL RADIAL$DERIVE(GID,NR,PSCORE,DRPSCORE)

    ALLOCATE(YLM(LMX),GRADYLM(3,LMX))
    ALLOCATE(AECHI(LMNX),PSCHI(LMNX))
    ALLOCATE(GAECHI(3,LMNX),GPSCHI(3,LMNX))
    ALLOCATE(RHOAE(NDIMD),RHOPS(NDIMD),TAUAE(NDIMD),TAUPS(NDIMD))
    ALLOCATE(GRADAE(3,NDIMD),GRADPS(3,NDIMD))
    IP=0
    DO IR=1,NRUSE
      DO IA=1,NANG
        IP=IP+1
        RELCOORD(IP,:)=R(IR)*DIRECTION(:,IA)
        WEIGHT(IP)=4.D0*PI*RADWEIGHT(IR)*R(IR)**2*ANGWEIGHT(IA)
        CALL PAW_SKALA_SOLID_BASIS_EVALUATE(BASIS,DIRECTION(:,IA) &
 &                                          ,YLM,GRADYLM)
        LMN=0
        DO LN=1,LNX
          L=LOX(LN)
          DO IM=1,2*L+1
            LMN=LMN+1
            LM=L**2+IM
            AECHI(LMN)=AEPHI(IR,LN)*YLM(LM)
            PSCHI(LMN)=PSPHI(IR,LN)*YLM(LM)
            DO ICART=1,3
              GAECHI(ICART,LMN)=(DRAEPHI(IR,LN) &
 &                     -REAL(L,KIND=8)*AEPHI(IR,LN)/R(IR))*YLM(LM) &
 &                     *DIRECTION(ICART,IA) &
 &                     +AEPHI(IR,LN)/R(IR)*GRADYLM(ICART,LM)
              GPSCHI(ICART,LMN)=(DRPSPHI(IR,LN) &
 &                     -REAL(L,KIND=8)*PSPHI(IR,LN)/R(IR))*YLM(LM) &
 &                     *DIRECTION(ICART,IA) &
 &                     +PSPHI(IR,LN)/R(IR)*GRADYLM(ICART,LM)
            END DO
          END DO
        END DO

        RHOAE(:)=0.D0
        RHOPS(:)=0.D0
        GRADAE(:,:)=0.D0
        GRADPS(:,:)=0.D0
        TAUAE(:)=0.D0
        TAUPS(:)=0.D0
        DO IDIM=1,NDIMD
          DO J=1,LMNX
            DO I=1,LMNX
              DREAL=REAL(DENMAT(I,J,IDIM),KIND=8)
              RHOAE(IDIM)=RHOAE(IDIM)+DREAL*AECHI(I)*AECHI(J)
              RHOPS(IDIM)=RHOPS(IDIM)+DREAL*PSCHI(I)*PSCHI(J)
              GRADAE(:,IDIM)=GRADAE(:,IDIM)+DREAL &
 &                  *(GAECHI(:,I)*AECHI(J)+AECHI(I)*GAECHI(:,J))
              GRADPS(:,IDIM)=GRADPS(:,IDIM)+DREAL &
 &                  *(GPSCHI(:,I)*PSCHI(J)+PSCHI(I)*GPSCHI(:,J))
              TAUAE(IDIM)=TAUAE(IDIM)+0.5D0*DREAL &
 &                                         *DOT_PRODUCT(GAECHI(:,I),GAECHI(:,J))
              TAUPS(IDIM)=TAUPS(IDIM)+0.5D0*DREAL &
 &                                         *DOT_PRODUCT(GPSCHI(:,I),GPSCHI(:,J))
            END DO
          END DO
        END DO
        RHOAE(1)=RHOAE(1)+AECORE(IR)*Y00
        RHOPS(1)=RHOPS(1)+PSCORE(IR)*Y00
        GRADAE(:,1)=GRADAE(:,1)+DRAECORE(IR)*Y00*DIRECTION(:,IA)
        GRADPS(:,1)=GRADPS(:,1)+DRPSCORE(IR)*Y00*DIRECTION(:,IA)

        IF(NDIMD.EQ.1) THEN
          AERHO(IP,1)=0.5D0*RHOAE(1)
          AERHO(IP,2)=AERHO(IP,1)
          PSRHO(IP,1)=0.5D0*RHOPS(1)
          PSRHO(IP,2)=PSRHO(IP,1)
          AEGRAD(IP,:,1)=0.5D0*GRADAE(:,1)
          AEGRAD(IP,:,2)=AEGRAD(IP,:,1)
          PSGRAD(IP,:,1)=0.5D0*GRADPS(:,1)
          PSGRAD(IP,:,2)=PSGRAD(IP,:,1)
          AETAU(IP,1)=0.5D0*TAUAE(1)
          AETAU(IP,2)=AETAU(IP,1)
          PSTAU(IP,1)=0.5D0*TAUPS(1)
          PSTAU(IP,2)=PSTAU(IP,1)
        ELSE
          DO IDIM=1,2
            FACTOR=MERGE(1.D0,-1.D0,IDIM.EQ.1)
            AERHO(IP,IDIM)=0.5D0*(RHOAE(1)+FACTOR*RHOAE(2))
            PSRHO(IP,IDIM)=0.5D0*(RHOPS(1)+FACTOR*RHOPS(2))
            AEGRAD(IP,:,IDIM)=0.5D0*(GRADAE(:,1)+FACTOR*GRADAE(:,2))
            PSGRAD(IP,:,IDIM)=0.5D0*(GRADPS(:,1)+FACTOR*GRADPS(:,2))
            AETAU(IP,IDIM)=0.5D0*(TAUAE(1)+FACTOR*TAUAE(2))
            PSTAU(IP,IDIM)=0.5D0*(TAUPS(1)+FACTOR*TAUPS(2))
          END DO
        END IF
      END DO
    END DO

    DEALLOCATE(DIRECTION,ANGWEIGHT,RADWEIGHT,DRAEPHI,DRPSPHI)
    DEALLOCATE(DRAECORE,DRPSCORE,YLM,GRADYLM,AECHI,PSCHI)
    DEALLOCATE(GAECHI,GPSCHI,RHOAE,RHOPS,TAUAE,TAUPS,GRADAE,GRADPS)
  END SUBROUTINE PAW_SKALA_ONECENTER_PRIMITIVES

  SUBROUTINE PAW_SKALA_ONECENTER_POINTS(GID,NR,LNX,LOX,LMNX,NDIMD &
 &                                      ,DENMAT,AEPHI,PSPHI,AECORE,PSCORE &
 &                                      ,RCUT,NPOINT,RELCOORD &
 &                                      ,AERHO,AEGRAD,AETAU &
 &                                      ,PSRHO,PSGRAD,PSTAU)
    IMPLICIT NONE
    INTEGER(4),INTENT(IN) :: GID,NR,LNX,LOX(LNX),LMNX,NDIMD,NPOINT
    COMPLEX(8),INTENT(IN) :: DENMAT(LMNX,LMNX,NDIMD)
    REAL(8),INTENT(IN) :: AEPHI(NR,LNX),PSPHI(NR,LNX)
    REAL(8),INTENT(IN) :: AECORE(NR),PSCORE(NR),RCUT
    REAL(8),INTENT(IN) :: RELCOORD(NPOINT,3)
    REAL(8),INTENT(OUT) :: AERHO(NPOINT,2),AEGRAD(NPOINT,3,2)
    REAL(8),INTENT(OUT) :: AETAU(NPOINT,2)
    REAL(8),INTENT(OUT) :: PSRHO(NPOINT,2),PSGRAD(NPOINT,3,2)
    REAL(8),INTENT(OUT) :: PSTAU(NPOINT,2)
    TYPE(PAW_SKALA_SOLID_BASIS) :: BASIS
    REAL(8),PARAMETER :: PI=4.D0*ATAN(1.D0)
    REAL(8),PARAMETER :: Y00=1.D0/SQRT(4.D0*PI)
    REAL(8),ALLOCATABLE :: DRAEPHI(:,:),DRPSPHI(:,:)
    REAL(8),ALLOCATABLE :: DRAECORE(:),DRPSCORE(:)
    REAL(8),ALLOCATABLE :: YLM(:),GRADYLM(:,:)
    REAL(8),ALLOCATABLE :: AECHI(:),PSCHI(:)
    REAL(8),ALLOCATABLE :: GAECHI(:,:),GPSCHI(:,:)
    REAL(8),ALLOCATABLE :: RHOAE(:),RHOPS(:),TAUAE(:),TAUPS(:)
    REAL(8),ALLOCATABLE :: GRADAE(:,:),GRADPS(:,:)
    REAL(8) :: RGRID(NR),DIRECTION(3),RADIUS,RSAMPLE,DREAL,FACTOR
    REAL(8) :: AEPHIVAL(LNX),PSPHIVAL(LNX)
    REAL(8) :: DRAEPHIVAL(LNX),DRPSPHIVAL(LNX)
    REAL(8) :: AECOREVAL,PSCOREVAL,DRAECOREVAL,DRPSCOREVAL
    INTEGER(4) :: LMAX,LMX,IP,LN,L,IM,LM,LMN,I,J,IDIM,ICART

    IF(NDIMD.NE.1.AND.NDIMD.NE.2) THEN
      CALL ERROR$MSG('SKALA CURRENTLY SUPPORTS ONLY COLLINEAR DENSITIES')
      CALL ERROR$I4VAL('NDIMD',NDIMD)
      CALL ERROR$STOP('PAW_SKALA_ONECENTER_POINTS')
    END IF
    IF(SUM(2*LOX+1).NE.LMNX) THEN
      CALL ERROR$MSG('PARTIAL-WAVE BASIS SIZE IS INCONSISTENT')
      CALL ERROR$I4VAL('LMNX',LMNX)
      CALL ERROR$I4VAL('EXPECTED',SUM(2*LOX+1))
      CALL ERROR$STOP('PAW_SKALA_ONECENTER_POINTS')
    END IF
    IF(RCUT.LE.0.D0) THEN
      CALL ERROR$MSG('ONE-CENTER CUTOFF MUST BE POSITIVE')
      CALL ERROR$R8VAL('RCUT',RCUT)
      CALL ERROR$STOP('PAW_SKALA_ONECENTER_POINTS')
    END IF

    CALL RADIAL$R(GID,NR,RGRID)
    LMAX=MAXVAL(LOX)
    LMX=(LMAX+1)**2
    CALL PAW_SKALA_SOLID_BASIS_INIT(BASIS,LMAX)
    ALLOCATE(DRAEPHI(NR,LNX),DRPSPHI(NR,LNX))
    DO LN=1,LNX
      CALL RADIAL$DERIVE(GID,NR,AEPHI(:,LN),DRAEPHI(:,LN))
      CALL RADIAL$DERIVE(GID,NR,PSPHI(:,LN),DRPSPHI(:,LN))
    END DO
    ALLOCATE(DRAECORE(NR),DRPSCORE(NR))
    CALL RADIAL$DERIVE(GID,NR,AECORE,DRAECORE)
    CALL RADIAL$DERIVE(GID,NR,PSCORE,DRPSCORE)
    ALLOCATE(YLM(LMX),GRADYLM(3,LMX))
    ALLOCATE(AECHI(LMNX),PSCHI(LMNX))
    ALLOCATE(GAECHI(3,LMNX),GPSCHI(3,LMNX))
    ALLOCATE(RHOAE(NDIMD),RHOPS(NDIMD),TAUAE(NDIMD),TAUPS(NDIMD))
    ALLOCATE(GRADAE(3,NDIMD),GRADPS(3,NDIMD))

    AERHO=0.D0
    PSRHO=0.D0
    AEGRAD=0.D0
    PSGRAD=0.D0
    AETAU=0.D0
    PSTAU=0.D0
    DO IP=1,NPOINT
      RADIUS=SQRT(DOT_PRODUCT(RELCOORD(IP,:),RELCOORD(IP,:)))
      IF(RADIUS.GT.RCUT) CYCLE
      RSAMPLE=MAX(RADIUS,RGRID(1),1.D-12)
      IF(RADIUS.GT.1.D-14) THEN
        DIRECTION=RELCOORD(IP,:)/RADIUS
      ELSE
        DIRECTION=(/1.D0,0.D0,0.D0/)
      END IF
      DO LN=1,LNX
        CALL RADIAL$VALUE(GID,NR,AEPHI(:,LN),RSAMPLE,AEPHIVAL(LN))
        CALL RADIAL$VALUE(GID,NR,PSPHI(:,LN),RSAMPLE,PSPHIVAL(LN))
        CALL RADIAL$VALUE(GID,NR,DRAEPHI(:,LN),RSAMPLE,DRAEPHIVAL(LN))
        CALL RADIAL$VALUE(GID,NR,DRPSPHI(:,LN),RSAMPLE,DRPSPHIVAL(LN))
      END DO
      CALL RADIAL$VALUE(GID,NR,AECORE,RSAMPLE,AECOREVAL)
      CALL RADIAL$VALUE(GID,NR,PSCORE,RSAMPLE,PSCOREVAL)
      CALL RADIAL$VALUE(GID,NR,DRAECORE,RSAMPLE,DRAECOREVAL)
      CALL RADIAL$VALUE(GID,NR,DRPSCORE,RSAMPLE,DRPSCOREVAL)
      CALL PAW_SKALA_SOLID_BASIS_EVALUATE(BASIS,DIRECTION,YLM,GRADYLM)

      LMN=0
      DO LN=1,LNX
        L=LOX(LN)
        DO IM=1,2*L+1
          LMN=LMN+1
          LM=L**2+IM
          AECHI(LMN)=AEPHIVAL(LN)*YLM(LM)
          PSCHI(LMN)=PSPHIVAL(LN)*YLM(LM)
          DO ICART=1,3
            GAECHI(ICART,LMN)=(DRAEPHIVAL(LN) &
 &                   -REAL(L,KIND=8)*AEPHIVAL(LN)/RSAMPLE)*YLM(LM) &
 &                   *DIRECTION(ICART) &
 &                   +AEPHIVAL(LN)/RSAMPLE*GRADYLM(ICART,LM)
            GPSCHI(ICART,LMN)=(DRPSPHIVAL(LN) &
 &                   -REAL(L,KIND=8)*PSPHIVAL(LN)/RSAMPLE)*YLM(LM) &
 &                   *DIRECTION(ICART) &
 &                   +PSPHIVAL(LN)/RSAMPLE*GRADYLM(ICART,LM)
          END DO
        END DO
      END DO

      RHOAE=0.D0
      RHOPS=0.D0
      GRADAE=0.D0
      GRADPS=0.D0
      TAUAE=0.D0
      TAUPS=0.D0
      DO IDIM=1,NDIMD
        DO J=1,LMNX
          DO I=1,LMNX
            DREAL=REAL(DENMAT(I,J,IDIM),KIND=8)
            RHOAE(IDIM)=RHOAE(IDIM)+DREAL*AECHI(I)*AECHI(J)
            RHOPS(IDIM)=RHOPS(IDIM)+DREAL*PSCHI(I)*PSCHI(J)
            GRADAE(:,IDIM)=GRADAE(:,IDIM)+DREAL &
 &              *(GAECHI(:,I)*AECHI(J)+AECHI(I)*GAECHI(:,J))
            GRADPS(:,IDIM)=GRADPS(:,IDIM)+DREAL &
 &              *(GPSCHI(:,I)*PSCHI(J)+PSCHI(I)*GPSCHI(:,J))
            TAUAE(IDIM)=TAUAE(IDIM)+0.5D0*DREAL &
 &                                     *DOT_PRODUCT(GAECHI(:,I),GAECHI(:,J))
            TAUPS(IDIM)=TAUPS(IDIM)+0.5D0*DREAL &
 &                                     *DOT_PRODUCT(GPSCHI(:,I),GPSCHI(:,J))
          END DO
        END DO
      END DO
      RHOAE(1)=RHOAE(1)+AECOREVAL*Y00
      RHOPS(1)=RHOPS(1)+PSCOREVAL*Y00
      GRADAE(:,1)=GRADAE(:,1)+DRAECOREVAL*Y00*DIRECTION
      GRADPS(:,1)=GRADPS(:,1)+DRPSCOREVAL*Y00*DIRECTION

      IF(NDIMD.EQ.1) THEN
        AERHO(IP,1)=0.5D0*RHOAE(1)
        AERHO(IP,2)=AERHO(IP,1)
        PSRHO(IP,1)=0.5D0*RHOPS(1)
        PSRHO(IP,2)=PSRHO(IP,1)
        AEGRAD(IP,:,1)=0.5D0*GRADAE(:,1)
        AEGRAD(IP,:,2)=AEGRAD(IP,:,1)
        PSGRAD(IP,:,1)=0.5D0*GRADPS(:,1)
        PSGRAD(IP,:,2)=PSGRAD(IP,:,1)
        AETAU(IP,1)=0.5D0*TAUAE(1)
        AETAU(IP,2)=AETAU(IP,1)
        PSTAU(IP,1)=0.5D0*TAUPS(1)
        PSTAU(IP,2)=PSTAU(IP,1)
      ELSE
        DO IDIM=1,2
          FACTOR=MERGE(1.D0,-1.D0,IDIM.EQ.1)
          AERHO(IP,IDIM)=0.5D0*(RHOAE(1)+FACTOR*RHOAE(2))
          PSRHO(IP,IDIM)=0.5D0*(RHOPS(1)+FACTOR*RHOPS(2))
          AEGRAD(IP,:,IDIM)=0.5D0*(GRADAE(:,1)+FACTOR*GRADAE(:,2))
          PSGRAD(IP,:,IDIM)=0.5D0*(GRADPS(:,1)+FACTOR*GRADPS(:,2))
          AETAU(IP,IDIM)=0.5D0*(TAUAE(1)+FACTOR*TAUAE(2))
          PSTAU(IP,IDIM)=0.5D0*(TAUPS(1)+FACTOR*TAUPS(2))
        END DO
      END IF
    END DO

    DEALLOCATE(DRAEPHI,DRPSPHI,DRAECORE,DRPSCORE,YLM,GRADYLM)
    DEALLOCATE(AECHI,PSCHI,GAECHI,GPSCHI,RHOAE,RHOPS,TAUAE,TAUPS)
    DEALLOCATE(GRADAE,GRADPS)
  END SUBROUTINE PAW_SKALA_ONECENTER_POINTS

  SUBROUTINE PAW_SKALA_ONECENTER_REFERENCE(GID,NR,NRUSE,LNX,LOX,LMNX &
 &                                         ,DENMAT,PHI,CORE,TCORE &
 &                                         ,RHOINT,TAUINT)
    IMPLICIT NONE
    INTEGER(4),INTENT(IN) :: GID,NR,NRUSE,LNX,LOX(LNX),LMNX
    COMPLEX(8),INTENT(IN) :: DENMAT(LMNX,LMNX)
    REAL(8),INTENT(IN) :: PHI(NR,LNX),CORE(NR)
    LOGICAL(4),INTENT(IN) :: TCORE
    REAL(8),INTENT(OUT) :: RHOINT,TAUINT
    REAL(8),PARAMETER :: PI=4.D0*ATAN(1.D0)
    REAL(8) :: R(NR),DRPHI(NR,LNX),WORK(NR),INTEGRAL(NR),DREAL
    INTEGER(4) :: LNOF(LMNX),LOF(LMNX),IMOF(LMNX)
    INTEGER(4) :: LN,L,IM,LMN,I,J

    CALL RADIAL$R(GID,NR,R)
    LMN=0
    DO LN=1,LNX
      L=LOX(LN)
      CALL RADIAL$DERIVE(GID,NR,PHI(:,LN),DRPHI(:,LN))
      DO IM=1,2*L+1
        LMN=LMN+1
        LNOF(LMN)=LN
        LOF(LMN)=L
        IMOF(LMN)=IM
      END DO
    END DO

    WORK(:)=0.D0
    DO J=1,LMNX
      DO I=1,LMNX
        IF(LOF(I).NE.LOF(J).OR.IMOF(I).NE.IMOF(J)) CYCLE
        DREAL=REAL(DENMAT(I,J),KIND=8)
        WORK=WORK+DREAL*PHI(:,LNOF(I))*PHI(:,LNOF(J))*R**2
      END DO
    END DO
    IF(TCORE) WORK=WORK+SQRT(4.D0*PI)*CORE*R**2
    CALL RADIAL$INTEGRATE(GID,NR,WORK,INTEGRAL)
    RHOINT=INTEGRAL(NRUSE)

    WORK(:)=0.D0
    DO J=1,LMNX
      DO I=1,LMNX
        IF(LOF(I).NE.LOF(J).OR.IMOF(I).NE.IMOF(J)) CYCLE
        L=LOF(I)
        DREAL=REAL(DENMAT(I,J),KIND=8)
        WORK=WORK+0.5D0*DREAL*(DRPHI(:,LNOF(I))*DRPHI(:,LNOF(J))*R**2 &
 &                            +REAL(L*(L+1),KIND=8) &
 &                              *PHI(:,LNOF(I))*PHI(:,LNOF(J)))
      END DO
    END DO
    CALL RADIAL$INTEGRATE(GID,NR,WORK,INTEGRAL)
    TAUINT=INTEGRAL(NRUSE)
  END SUBROUTINE PAW_SKALA_ONECENTER_REFERENCE

  SUBROUTINE PAW_SKALA_PRIMITIVES_TEST(MAXERROR)
    USE PAW_LEBEDEV_MODULE, ONLY: PAW_LEBEDEV_TEST
    IMPLICIT NONE
    REAL(8),INTENT(OUT) :: MAXERROR
    TYPE(PAW_SKALA_SOLID_BASIS) :: BASIS
    INTEGER(4),PARAMETER :: LMAX=4
    INTEGER(4),PARAMETER :: LMX=(LMAX+1)**2
    REAL(8),PARAMETER :: EPS=1.D-6
    REAL(8) :: R(3),RP(3),RM(3),YLM(LMX),YLMP(LMX),YLMM(LMX)
    REAL(8) :: SOLID(LMX),GRAD(3,LMX),REFERENCE,NUMERICAL
    REAL(8) :: RNORM,ERR
    INTEGER(4) :: IDIM,L,LM

    CALL PAW_LEBEDEV_TEST(MAXERROR)
    CALL PAW_SKALA_SOLID_BASIS_INIT(BASIS,LMAX)
    R=(/0.31D0,-0.47D0,0.825D0/)
    CALL PAW_SKALA_SOLID_BASIS_EVALUATE(BASIS,R,SOLID,GRAD)
    CALL SPHERICAL$YLM(LMX,R,YLM)
    RNORM=SQRT(SUM(R**2))
    DO LM=1,LMX
      L=INT(SQRT(REAL(LM-1,KIND=8)))
      REFERENCE=RNORM**L*YLM(LM)
      MAXERROR=MAX(MAXERROR,ABS(SOLID(LM)-REFERENCE))
      DO IDIM=1,3
        RP=R
        RM=R
        RP(IDIM)=RP(IDIM)+EPS
        RM(IDIM)=RM(IDIM)-EPS
        CALL SPHERICAL$YLM(LMX,RP,YLMP)
        CALL SPHERICAL$YLM(LMX,RM,YLMM)
        NUMERICAL=(SQRT(SUM(RP**2))**L*YLMP(LM) &
       &          -SQRT(SUM(RM**2))**L*YLMM(LM))/(2.D0*EPS)
        ERR=ABS(GRAD(IDIM,LM)-NUMERICAL)
        MAXERROR=MAX(MAXERROR,ERR)
      END DO
    END DO
    CALL PAW_SKALA_ONECENTER_TEST(MAXERROR)
  END SUBROUTINE PAW_SKALA_PRIMITIVES_TEST

  SUBROUTINE PAW_SKALA_ONECENTER_TEST(MAXERROR)
    IMPLICIT NONE
    REAL(8),INTENT(INOUT) :: MAXERROR
    INTEGER(4),PARAMETER :: NR=160,LNX=2,LMNX=4,NDIMD=2,LEBEDEV_L=17
    INTEGER(4),PARAMETER :: LOX(LNX)=(/0,1/)
    INTEGER(4) :: GID,NRUSE,NANG,NPOINT
    REAL(8),PARAMETER :: RCUT=4.D0
    REAL(8) :: R(NR),AEPHI(NR,LNX),PSPHI(NR,LNX)
    REAL(8) :: AECORE(NR),PSCORE(NR)
    COMPLEX(8) :: DENMAT(LMNX,LMNX,NDIMD)
    REAL(8),ALLOCATABLE :: RELCOORD(:,:),WEIGHT(:)
    REAL(8),ALLOCATABLE :: AERHO(:,:),PSRHO(:,:),AETAU(:,:),PSTAU(:,:)
    REAL(8),ALLOCATABLE :: AEGRAD(:,:,:),PSGRAD(:,:,:)
    REAL(8),ALLOCATABLE :: AERHO1(:,:),PSRHO1(:,:),AETAU1(:,:),PSTAU1(:,:)
    REAL(8),ALLOCATABLE :: AEGRAD1(:,:,:),PSGRAD1(:,:,:)
    REAL(8) :: RHOREF,TAUREF,VAL

    CALL RADIAL$NEW('SHLOG',GID)
    CALL RADIAL$SETR8(GID,'R1',0.01D0)
    CALL RADIAL$SETR8(GID,'DEX',0.04D0)
    CALL RADIAL$SETI4(GID,'NR',NR)
    CALL RADIAL$R(GID,NR,R)
    AEPHI(:,1)=EXP(-R)
    AEPHI(:,2)=R*EXP(-0.7D0*R)
    PSPHI(:,1)=EXP(-1.1D0*R)
    PSPHI(:,2)=R*EXP(-0.8D0*R)
    AECORE=0.4D0*EXP(-2.D0*R**2)
    PSCORE=0.3D0*EXP(-1.6D0*R**2)
    DENMAT(:,:,:)=CMPLX(0.D0,0.D0,KIND=8)
    DENMAT(1,1,1)=CMPLX(1.3D0,0.D0,KIND=8)
    DENMAT(2,2,1)=CMPLX(0.4D0,0.D0,KIND=8)
    DENMAT(3,3,1)=CMPLX(0.6D0,0.D0,KIND=8)
    DENMAT(4,4,1)=CMPLX(0.5D0,0.D0,KIND=8)
    DENMAT(1,3,1)=CMPLX(0.12D0,0.03D0,KIND=8)
    DENMAT(3,1,1)=CONJG(DENMAT(1,3,1))
    DENMAT(1,1,2)=CMPLX(0.2D0,0.D0,KIND=8)
    DENMAT(2,2,2)=CMPLX(-0.1D0,0.D0,KIND=8)
    DENMAT(3,3,2)=CMPLX(0.08D0,0.D0,KIND=8)
    DENMAT(4,4,2)=CMPLX(-0.05D0,0.D0,KIND=8)

    CALL PAW_SKALA_ONECENTER_GRID_SIZE(GID,NR,RCUT,LEBEDEV_L &
 &                                    ,NRUSE,NANG,NPOINT)
    ALLOCATE(RELCOORD(NPOINT,3),WEIGHT(NPOINT))
    ALLOCATE(AERHO(NPOINT,2),PSRHO(NPOINT,2))
    ALLOCATE(AEGRAD(NPOINT,3,2),PSGRAD(NPOINT,3,2))
    ALLOCATE(AETAU(NPOINT,2),PSTAU(NPOINT,2))
    CALL PAW_SKALA_ONECENTER_PRIMITIVES(GID,NR,LNX,LOX,LMNX,NDIMD &
 &                                     ,DENMAT,AEPHI,PSPHI,AECORE,PSCORE &
 &                                     ,RCUT,LEBEDEV_L,NPOINT &
 &                                     ,RELCOORD,WEIGHT,AERHO,AEGRAD,AETAU &
 &                                     ,PSRHO,PSGRAD,PSTAU)

    CALL PAW_SKALA_ONECENTER_REFERENCE(GID,NR,NRUSE,LNX,LOX,LMNX &
 &                                    ,DENMAT(:,:,1),AEPHI,AECORE,.TRUE. &
 &                                    ,RHOREF,TAUREF)
    VAL=SUM(WEIGHT*(AERHO(:,1)+AERHO(:,2)))
    MAXERROR=MAX(MAXERROR,ABS(VAL-RHOREF))
    VAL=SUM(WEIGHT*(AETAU(:,1)+AETAU(:,2)))
    MAXERROR=MAX(MAXERROR,ABS(VAL-TAUREF))
    CALL PAW_SKALA_ONECENTER_REFERENCE(GID,NR,NRUSE,LNX,LOX,LMNX &
 &                                    ,DENMAT(:,:,2),AEPHI,AECORE,.FALSE. &
 &                                    ,RHOREF,TAUREF)
    VAL=SUM(WEIGHT*(AERHO(:,1)-AERHO(:,2)))
    MAXERROR=MAX(MAXERROR,ABS(VAL-RHOREF))
    VAL=SUM(WEIGHT*(AETAU(:,1)-AETAU(:,2)))
    MAXERROR=MAX(MAXERROR,ABS(VAL-TAUREF))

    CALL PAW_SKALA_ONECENTER_REFERENCE(GID,NR,NRUSE,LNX,LOX,LMNX &
 &                                    ,DENMAT(:,:,1),PSPHI,PSCORE,.TRUE. &
 &                                    ,RHOREF,TAUREF)
    VAL=SUM(WEIGHT*(PSRHO(:,1)+PSRHO(:,2)))
    MAXERROR=MAX(MAXERROR,ABS(VAL-RHOREF))
    VAL=SUM(WEIGHT*(PSTAU(:,1)+PSTAU(:,2)))
    MAXERROR=MAX(MAXERROR,ABS(VAL-TAUREF))
    CALL PAW_SKALA_ONECENTER_REFERENCE(GID,NR,NRUSE,LNX,LOX,LMNX &
 &                                    ,DENMAT(:,:,2),PSPHI,PSCORE,.FALSE. &
 &                                    ,RHOREF,TAUREF)
    VAL=SUM(WEIGHT*(PSRHO(:,1)-PSRHO(:,2)))
    MAXERROR=MAX(MAXERROR,ABS(VAL-RHOREF))
    VAL=SUM(WEIGHT*(PSTAU(:,1)-PSTAU(:,2)))
    MAXERROR=MAX(MAXERROR,ABS(VAL-TAUREF))

    ALLOCATE(AERHO1(NPOINT,2),PSRHO1(NPOINT,2))
    ALLOCATE(AEGRAD1(NPOINT,3,2),PSGRAD1(NPOINT,3,2))
    ALLOCATE(AETAU1(NPOINT,2),PSTAU1(NPOINT,2))
    CALL PAW_SKALA_ONECENTER_POINTS(GID,NR,LNX,LOX,LMNX,NDIMD &
 &                                  ,DENMAT,AEPHI,PSPHI,AECORE,PSCORE &
 &                                  ,R(NRUSE),NPOINT,RELCOORD &
 &                                  ,AERHO1,AEGRAD1,AETAU1 &
 &                                  ,PSRHO1,PSGRAD1,PSTAU1)
    MAXERROR=MAX(MAXERROR,MAXVAL(ABS(AERHO1-AERHO)))
    MAXERROR=MAX(MAXERROR,MAXVAL(ABS(PSRHO1-PSRHO)))
    MAXERROR=MAX(MAXERROR,MAXVAL(ABS(AEGRAD1-AEGRAD)))
    MAXERROR=MAX(MAXERROR,MAXVAL(ABS(PSGRAD1-PSGRAD)))
    MAXERROR=MAX(MAXERROR,MAXVAL(ABS(AETAU1-AETAU)))
    MAXERROR=MAX(MAXERROR,MAXVAL(ABS(PSTAU1-PSTAU)))
    DEALLOCATE(AERHO1,PSRHO1,AEGRAD1,PSGRAD1,AETAU1,PSTAU1)

    DEALLOCATE(RELCOORD,WEIGHT,AERHO,PSRHO,AEGRAD,PSGRAD,AETAU,PSTAU)
  END SUBROUTINE PAW_SKALA_ONECENTER_TEST

END MODULE PAW_SKALA_PRIMITIVES_MODULE
