! SPDX-License-Identifier: GPL-3.0-or-later
MODULE PAW_SKALA_PARTITION_MODULE
  USE PAW_SKALA_GRID_MODULE, ONLY: PAW_SKALA_INVERSE3
  IMPLICIT NONE
  PRIVATE
  TYPE, PUBLIC :: PAW_SKALA_PERIODIC_LAYOUT
    INTEGER :: NAT=0,NNEIGHBOR=0,SHELL=0
    REAL(8) :: CELL(3,3),AINV(3,3)
    REAL(8),ALLOCATABLE :: ATOM(:,:),OFFSET(:,:,:),INVDIST(:,:)
    REAL(8),ALLOCATABLE :: CUTOFF(:,:),DCUTOFF(:,:,:)
    INTEGER,ALLOCATABLE :: OWNER(:,:),SELF(:)
  END TYPE
  TYPE, PUBLIC :: PAW_SKALA_PARTITION_CACHE
    PRIVATE
    INTEGER :: IAT=0,SHELL=0
    INTEGER(8) :: BYTES=0_8
    LOGICAL :: STRESS=.FALSE.
    REAL(8) :: CELL(3,3)=0.D0
    REAL(8),ALLOCATABLE :: ATOM(:,:),POINT(:,:),DE(:,:,:)
    REAL(8),ALLOCATABLE :: ME(:,:,:),WD(:),DD(:,:,:),MD(:,:,:)
    LOGICAL,ALLOCATABLE :: VALID(:)
  END TYPE
  PUBLIC :: PAW_SKALA_PERIODIC_INIT,PAW_SKALA_PERIODIC_WEIGHT
  PUBLIC :: PAW_SKALA_PARTITION_WINDOW_TEST
  PUBLIC :: PAW_SKALA_PARTITION_CACHE_PREPARE,PAW_SKALA_PARTITION_CACHE_GET
  PUBLIC :: PAW_SKALA_PARTITION_CACHE_PUT,PAW_SKALA_PARTITION_CACHE_BYTES
  PUBLIC :: PAW_SKALA_PARTITION_CACHE_LIMIT
CONTAINS
  FUNCTION PAW_SKALA_PARTITION_CACHE_LIMIT() RESULT(BYTES)
    INTEGER(8) :: BYTES
    INTEGER(8),SAVE :: LIMIT=-1_8
    CHARACTER(128) :: VALUE
    INTEGER :: STATUS,IOS
    IF(LIMIT.LT.0_8) THEN
      LIMIT=256_8
      CALL GET_ENVIRONMENT_VARIABLE('CPPAW_SKALA_PARTITION_CACHE_MB',VALUE,STATUS=STATUS)
      IF(STATUS.NE.1) THEN
        VALUE=ADJUSTL(VALUE)
        IOS=1
        IF(STATUS.EQ.0.AND.LEN_TRIM(VALUE).GT.0) THEN
          IF(VERIFY(TRIM(VALUE),'0123456789').EQ.0) READ(VALUE,*,IOSTAT=IOS) LIMIT
        END IF
        IF(IOS.NE.0.OR.LIMIT.LT.0_8.OR.LIMIT.GT.HUGE(LIMIT)/1048576_8) THEN
          CALL ERROR$MSG('CPPAW_SKALA_PARTITION_CACHE_MB MUST BE A NONNEGATIVE INTEGER')
          CALL ERROR$STOP('PAW_SKALA_PARTITION_CACHE_LIMIT')
        END IF
      END IF
      LIMIT=LIMIT*1048576_8
    END IF
    BYTES=LIMIT
  END FUNCTION

  FUNCTION PAW_SKALA_PARTITION_CACHE_BYTES(CACHE) RESULT(BYTES)
    TYPE(PAW_SKALA_PARTITION_CACHE),INTENT(IN) :: CACHE
    INTEGER(8) :: BYTES
    BYTES=CACHE%BYTES
  END FUNCTION

  SUBROUTINE CACHE_CLEAR(CACHE)
    ! INTENT(OUT) releases all allocatable components, including partial allocations.
    TYPE(PAW_SKALA_PARTITION_CACHE),INTENT(OUT) :: CACHE
  END SUBROUTINE

  SUBROUTINE PAW_SKALA_PARTITION_CACHE_PREPARE(CACHE,ATOM,CELL,SHELL,IAT,X,STRESS,LIMIT)
    TYPE(PAW_SKALA_PARTITION_CACHE),INTENT(INOUT) :: CACHE
    REAL(8),INTENT(IN) :: ATOM(:,:),CELL(3,3),X(:,:)
    INTEGER,INTENT(IN) :: SHELL,IAT
    LOGICAL,INTENT(IN) :: STRESS
    INTEGER(8),INTENT(IN) :: LIMIT
    INTEGER :: NAT,NP,IOS
    INTEGER(8) :: BYTES,ROWBYTES,KEYBYTES
    LOGICAL :: SAME
    NAT=SIZE(ATOM,1)
    NP=SIZE(X,1)
    ! The budget covers array payloads for all atom blocks on this MPI rank.
    KEYBYTES=3_8*INT(NAT,8)*(STORAGE_SIZE(0.D0)/8)
    ROWBYTES=(3_8*INT(NAT,8)+3_8)*(STORAGE_SIZE(0.D0)/8)+STORAGE_SIZE(.TRUE.)/8
    IF(STRESS) ROWBYTES=ROWBYTES+22_8*(STORAGE_SIZE(0.D0)/8)
    IF(LIMIT.LT.KEYBYTES.OR.NP.LE.0) THEN
      CALL CACHE_CLEAR(CACHE)
      RETURN
    END IF
    IF(INT(NP,8).GT.(LIMIT-KEYBYTES)/ROWBYTES) THEN
      CALL CACHE_CLEAR(CACHE)
      RETURN
    END IF
    BYTES=KEYBYTES+INT(NP,8)*ROWBYTES
    SAME=.FALSE.
    IF(ALLOCATED(CACHE%VALID)) THEN
      IF(SIZE(CACHE%ATOM,1).EQ.NAT.AND.SIZE(CACHE%POINT,1).EQ.NP) THEN
        SAME=CACHE%IAT.EQ.IAT.AND.CACHE%SHELL.EQ.SHELL &
     &       .AND.(CACHE%STRESS.EQV.STRESS)
        IF(SAME) SAME=ALL(CACHE%ATOM.EQ.ATOM).AND.ALL(CACHE%CELL.EQ.CELL) &
     &               .AND.ALL(CACHE%POINT.EQ.X)
      END IF
    END IF
    IF(SAME) RETURN
    CALL CACHE_CLEAR(CACHE)
    ALLOCATE(CACHE%ATOM(NAT,3),CACHE%POINT(NP,3),CACHE%DE(3,NAT,NP) &
     &      ,CACHE%VALID(NP),STAT=IOS)
    IF(IOS.EQ.0.AND.STRESS) THEN
      ALLOCATE(CACHE%ME(3,3,NP),CACHE%WD(NP),CACHE%DD(3,1,NP) &
     &        ,CACHE%MD(3,3,NP),STAT=IOS)
    END IF
    IF(IOS.NE.0) THEN
      CALL CACHE_CLEAR(CACHE)
      RETURN
    END IF
    CACHE%ATOM=ATOM
    CACHE%CELL=CELL
    CACHE%POINT=X
    CACHE%IAT=IAT
    CACHE%SHELL=SHELL
    CACHE%STRESS=STRESS
    CACHE%BYTES=BYTES
    CACHE%VALID=.FALSE.
  END SUBROUTINE

  SUBROUTINE PAW_SKALA_PARTITION_CACHE_GET(CACHE,IP,DE,ME,WD,DD,MD,HIT)
    TYPE(PAW_SKALA_PARTITION_CACHE),INTENT(IN) :: CACHE
    INTEGER,INTENT(IN) :: IP
    REAL(8),INTENT(OUT) :: DE(:,:),ME(3,3),WD,DD(3,1),MD(3,3)
    LOGICAL,INTENT(OUT) :: HIT
    HIT=.FALSE.
    DE=0.D0
    ME=0.D0
    WD=0.D0
    DD=0.D0
    MD=0.D0
    IF(.NOT.ALLOCATED(CACHE%VALID)) RETURN
    IF(IP.LT.1.OR.IP.GT.SIZE(CACHE%VALID)) RETURN
    IF(.NOT.CACHE%VALID(IP)) RETURN
    DE=CACHE%DE(:,:,IP)
    IF(CACHE%STRESS) THEN
      ME=CACHE%ME(:,:,IP)
      WD=CACHE%WD(IP)
      DD=CACHE%DD(:,:,IP)
      MD=CACHE%MD(:,:,IP)
    END IF
    HIT=.TRUE.
  END SUBROUTINE

  SUBROUTINE PAW_SKALA_PARTITION_CACHE_PUT(CACHE,IP,DE,ME,WD,DD,MD)
    TYPE(PAW_SKALA_PARTITION_CACHE),INTENT(INOUT) :: CACHE
    INTEGER,INTENT(IN) :: IP
    REAL(8),INTENT(IN) :: DE(:,:),ME(3,3),WD,DD(3,1),MD(3,3)
    IF(.NOT.ALLOCATED(CACHE%VALID)) RETURN
    IF(IP.LT.1.OR.IP.GT.SIZE(CACHE%VALID)) RETURN
    CACHE%DE(:,:,IP)=DE
    IF(CACHE%STRESS) THEN
      CACHE%ME(:,:,IP)=ME
      CACHE%WD(IP)=WD
      CACHE%DD(:,:,IP)=DD
      CACHE%MD(:,:,IP)=MD
    END IF
    CACHE%VALID(IP)=.TRUE.
  END SUBROUTINE

  SUBROUTINE PAW_SKALA_PARTITION_WINDOW_TEST(ERROR)
    REAL(8),INTENT(OUT) :: ERROR
    TYPE(PAW_SKALA_PERIODIC_LAYOUT) :: L,P
    REAL(8) :: X(3),XP(3),C,CP,CM,DC(3),IGNORE(3),H
    INTEGER :: I,J
    L%SHELL=1
    L%CELL=RESHAPE((/4.D0,0.D0,0.D0,0.3D0,5.D0,0.D0,0.1D0,0.2D0,6.D0/),(/3,3/))
    CALL PAW_SKALA_INVERSE3(L%CELL,L%AINV)
    X=MATMUL(L%CELL,(/1.2D0,-1.6D0,0.2D0/))
    H=1.D-6
    ERROR=0.D0
    CALL COMPACT_WINDOW(L,X,C,DC)
    DO I=1,3
      XP=X
      XP(I)=X(I)+H
      CALL COMPACT_WINDOW(L,XP,CP,IGNORE)
      XP(I)=X(I)-H
      CALL COMPACT_WINDOW(L,XP,CM,IGNORE)
      ERROR=MAX(ERROR,ABS((CP-CM)/(2.D0*H)-DC(I)))
      DO J=1,3
        P=L
        P%CELL(I,:)=L%CELL(I,:)+H*L%CELL(J,:)
        CALL PAW_SKALA_INVERSE3(P%CELL,P%AINV)
        CALL COMPACT_WINDOW(P,X,CP,IGNORE)
        P%CELL(I,:)=L%CELL(I,:)-H*L%CELL(J,:)
        CALL PAW_SKALA_INVERSE3(P%CELL,P%AINV)
        CALL COMPACT_WINDOW(P,X,CM,IGNORE)
        ERROR=MAX(ERROR,ABS((CP-CM)/(2.D0*H)+DC(I)*X(J)))
      END DO
    END DO
  END SUBROUTINE

  SUBROUTINE PAW_SKALA_PERIODIC_INIT(LAYOUT,NAT,ATOM,CELL,SHELL)
    TYPE(PAW_SKALA_PERIODIC_LAYOUT),INTENT(OUT) :: LAYOUT
    INTEGER,INTENT(IN) :: NAT,SHELL
    REAL(8),INTENT(IN) :: ATOM(NAT,3),CELL(3,3)
    INTEGER :: A,B,K,N1,N2,N3,BASE(3),SHIFT(3)
    REAL(8) :: DIST
    IF(NAT.LT.1.OR.SHELL.LT.1) THEN
      CALL ERROR$MSG('INVALID SKALA PERIODIC PARTITION SIZE')
      CALL ERROR$STOP('PAW_SKALA_PERIODIC_INIT')
    END IF
    LAYOUT%NAT=NAT
    LAYOUT%SHELL=SHELL
    LAYOUT%NNEIGHBOR=NAT*(2*SHELL+3)**3
    LAYOUT%CELL=CELL
    CALL PAW_SKALA_INVERSE3(CELL,LAYOUT%AINV)
    LAYOUT%ATOM=ATOM
    ALLOCATE(LAYOUT%OFFSET(3,LAYOUT%NNEIGHBOR,NAT))
    ALLOCATE(LAYOUT%INVDIST(LAYOUT%NNEIGHBOR,NAT))
    ALLOCATE(LAYOUT%CUTOFF(LAYOUT%NNEIGHBOR,NAT))
    ALLOCATE(LAYOUT%DCUTOFF(3,LAYOUT%NNEIGHBOR,NAT))
    ALLOCATE(LAYOUT%OWNER(LAYOUT%NNEIGHBOR,NAT),LAYOUT%SELF(NAT))
    ! Every image uses its own translated neighbour set, not a common finite
    ! cluster whose edge images have different environments.
    DO A=1,NAT
      K=0
      DO B=1,NAT
        BASE=NINT(MATMUL(LAYOUT%AINV,ATOM(A,:)-ATOM(B,:)))
        DO N3=-SHELL-1,SHELL+1
          DO N2=-SHELL-1,SHELL+1
            DO N1=-SHELL-1,SHELL+1
              SHIFT=BASE+(/N1,N2,N3/)
              K=K+1
              LAYOUT%OWNER(K,A)=B
              LAYOUT%OFFSET(:,K,A)=ATOM(B,:)-ATOM(A,:)+MATMUL(CELL,REAL(SHIFT,KIND=8))
              CALL COMPACT_WINDOW(LAYOUT,LAYOUT%OFFSET(:,K,A) &
     &             ,LAYOUT%CUTOFF(K,A),LAYOUT%DCUTOFF(:,K,A))
              IF(A.EQ.B.AND.ALL(SHIFT.EQ.0)) THEN
                LAYOUT%SELF(A)=K
                LAYOUT%INVDIST(K,A)=0.D0
                CYCLE
              END IF
              DIST=SQRT(SUM(LAYOUT%OFFSET(:,K,A)**2))
              IF(DIST.LT.1.D-10) THEN
                CALL ERROR$MSG('COINCIDENT ATOM IMAGES IN SKALA PARTITION')
                CALL ERROR$STOP('PAW_SKALA_PERIODIC_INIT')
              END IF
              LAYOUT%INVDIST(K,A)=1.D0/DIST
            END DO
          END DO
        END DO
      END DO
    END DO
  END SUBROUTINE

  PURE SUBROUTINE PAIR_SHAPE(MU,S,DS)
    REAL(8),INTENT(IN) :: MU
    REAL(8),INTENT(OUT) :: S,DS
    REAL(8) :: V
    INTEGER :: I
    V=0.5D0*(1.D0-MAX(-1.D0,MIN(1.D0,MU)))
    DS=-0.5D0
    DO I=1,3
      DS=DS*6.D0*V*(1.D0-V)
      V=V*V*(3.D0-2.D0*V)
    END DO
    S=V
  END SUBROUTINE

  PURE SUBROUTINE COMPACT_WINDOW(LAYOUT,X,C,DC)
    TYPE(PAW_SKALA_PERIODIC_LAYOUT),INTENT(IN) :: LAYOUT
    REAL(8),INTENT(IN) :: X(3)
    REAL(8),INTENT(OUT) :: C,DC(3)
    REAL(8) :: F(3),H(3),DH(3),Z
    INTEGER :: D,J
    F=MATMUL(LAYOUT%AINV,X)
    H=1.D0
    DH=0.D0
    DO D=1,3
      Z=ABS(F(D))-REAL(LAYOUT%SHELL,KIND=8)
      IF(Z.GE.1.D0) THEN
        C=0.D0
        DC=0.D0
        RETURN
      END IF
      IF(Z.LE.0.D0) CYCLE
      H(D)=(1.D0-Z)**3*(1.D0+3.D0*Z+6.D0*Z**2)
      DH(D)=-30.D0*Z**2*(1.D0-Z)**2*SIGN(1.D0,F(D))
    END DO
    C=PRODUCT(H)
    DO D=1,3
      DO J=1,3
        IF(J.NE.D) DH(D)=DH(D)*H(J)
      END DO
    END DO
    DC=MATMUL(TRANSPOSE(LAYOUT%AINV),DH)
  END SUBROUTINE

  PURE SUBROUTINE SEED_VALUE(LAYOUT,A,X,Q,ZERO,LOGARITHMIC)
    TYPE(PAW_SKALA_PERIODIC_LAYOUT),INTENT(IN) :: LAYOUT
    INTEGER,INTENT(IN) :: A
    REAL(8),INTENT(IN) :: X(3)
    REAL(8),INTENT(OUT) :: Q
    LOGICAL,INTENT(OUT) :: ZERO
    LOGICAL,INTENT(IN) :: LOGARITHMIC
    REAL(8) :: C,DC(3),RI,RJ,MU,S,DS
    INTEGER :: K
    CALL COMPACT_WINDOW(LAYOUT,X,C,DC)
    ZERO=C.LE.0.D0
    Q=0.D0
    IF(ZERO) RETURN
    Q=C
    IF(LOGARITHMIC) Q=LOG(C)
    RI=SQRT(SUM(X**2))
    DO K=1,LAYOUT%NNEIGHBOR
      IF(K.EQ.LAYOUT%SELF(A)) CYCLE
      IF(LAYOUT%CUTOFF(K,A).EQ.0.D0) CYCLE
      RJ=SQRT(SUM((X-LAYOUT%OFFSET(:,K,A))**2))
      MU=(RI-RJ)*LAYOUT%INVDIST(K,A)
      CALL PAIR_SHAPE(MU,S,DS)
      S=(1.D0-LAYOUT%CUTOFF(K,A))+LAYOUT%CUTOFF(K,A)*S
      IF(S.LE.0.D0) THEN
        Q=0.D0
        ZERO=.TRUE.
        RETURN
      END IF
      IF(LOGARITHMIC) THEN
        Q=Q+LOG(S)
      ELSE
        Q=Q*S
      END IF
    END DO
  END SUBROUTINE

  SUBROUTINE SEED_REVERSE(LAYOUT,A,CENTER,POINT,COEFF,DATOM,MOMENT)
    TYPE(PAW_SKALA_PERIODIC_LAYOUT),INTENT(IN) :: LAYOUT
    INTEGER,INTENT(IN) :: A
    REAL(8),INTENT(IN) :: CENTER(3),POINT(3),COEFF
    REAL(8),INTENT(INOUT) :: DATOM(3,LAYOUT%NAT),MOMENT(3,3)
    REAL(8) :: X(3),Y(3),U(3),V(3),E(3),NEIGHBOR(3),GI(3),GJ(3)
    REAL(8) :: RI,RJ,MU,S,DS,C,DC(3),FACTOR,PAIR
    INTEGER :: K,B,D
    X=POINT-CENTER
    CALL COMPACT_WINDOW(LAYOUT,X,C,DC)
    IF(C.LE.0.D0.OR.COEFF.EQ.0.D0) RETURN
    GI=-COEFF*DC/C
    DATOM(:,A)=DATOM(:,A)+GI
    ! The compact window depends on H^-1 (r-R). Combine its moving-centre
    ! moment and explicit cell derivative before cancellation at the caller.
    DO D=1,3
      MOMENT(:,D)=MOMENT(:,D)+GI*POINT(D)
    END DO
    RI=SQRT(SUM(X**2))
    U=X/MAX(RI,1.D-30)
    DO K=1,LAYOUT%NNEIGHBOR
      IF(K.EQ.LAYOUT%SELF(A)) CYCLE
      IF(LAYOUT%CUTOFF(K,A).EQ.0.D0) CYCLE
      B=LAYOUT%OWNER(K,A)
      Y=X-LAYOUT%OFFSET(:,K,A)
      RJ=SQRT(SUM(Y**2))
      V=Y/MAX(RJ,1.D-30)
      MU=(RI-RJ)*LAYOUT%INVDIST(K,A)
      CALL PAIR_SHAPE(MU,S,DS)
      PAIR=(1.D0-LAYOUT%CUTOFF(K,A))+LAYOUT%CUTOFF(K,A)*S
      IF(PAIR.LE.0.D0) CYCLE
      ! Neighbour membership is also tapered. The cutoff's centre moment
      ! cancels its explicit cell derivative under an affine deformation.
      GI=COEFF*(S-1.D0)/PAIR*LAYOUT%DCUTOFF(:,K,A)
      DATOM(:,A)=DATOM(:,A)-GI
      DATOM(:,B)=DATOM(:,B)+GI
      FACTOR=COEFF*LAYOUT%CUTOFF(K,A)*DS/PAIR*LAYOUT%INVDIST(K,A)
      E=-LAYOUT%OFFSET(:,K,A)*LAYOUT%INVDIST(K,A)
      GI=FACTOR*(-U-MU*E)
      GJ=FACTOR*( V+MU*E)
      DATOM(:,A)=DATOM(:,A)+GI
      DATOM(:,B)=DATOM(:,B)+GJ
      NEIGHBOR=CENTER+LAYOUT%OFFSET(:,K,A)
      DO D=1,3
        MOMENT(:,D)=MOMENT(:,D)+GI*CENTER(D)+GJ*NEIGHBOR(D)
      END DO
    END DO
  END SUBROUTINE

  SUBROUTINE PAW_SKALA_PERIODIC_WEIGHT(LAYOUT,IAT,POINT,WEIGHT,DATOM,MOMENT)
    TYPE(PAW_SKALA_PERIODIC_LAYOUT),INTENT(IN) :: LAYOUT
    INTEGER,INTENT(IN) :: IAT
    REAL(8),INTENT(IN) :: POINT(3)
    REAL(8),INTENT(OUT) :: WEIGHT
    REAL(8),INTENT(OUT),OPTIONAL :: DATOM(3,LAYOUT%NAT),MOMENT(3,3)
    REAL(8) :: CENTERS(3,LAYOUT%NAT*(2*LAYOUT%SHELL+3)**3)
    REAL(8) :: Q(LAYOUT%NAT*(2*LAYOUT%SHELL+3)**3)
    INTEGER :: OWNER(LAYOUT%NAT*(2*LAYOUT%SHELL+3)**3)
    LOGICAL :: ACTIVE(LAYOUT%NAT*(2*LAYOUT%SHELL+3)**3),ZERO
    REAL(8) :: QT,COEFF,F(3,LAYOUT%NAT),M(3,3)
    INTEGER :: A,N1,N2,N3,BASE(3),SHIFT(3),K,T,S,J
    IF(PRESENT(DATOM)) DATOM=0.D0
    IF(PRESENT(MOMENT)) MOMENT=0.D0
    WEIGHT=0.D0
    CALL SEED_VALUE(LAYOUT,IAT,POINT-LAYOUT%ATOM(IAT,:),QT,ZERO,.FALSE.)
    IF(ZERO) RETURN
    K=0
    T=0
    S=LAYOUT%SHELL+1
    DO A=1,LAYOUT%NAT
      BASE=NINT(MATMUL(LAYOUT%AINV,POINT-LAYOUT%ATOM(A,:)))
      DO N3=-S,S
        DO N2=-S,S
          DO N1=-S,S
            SHIFT=BASE+(/N1,N2,N3/)
            K=K+1
            OWNER(K)=A
            CENTERS(:,K)=LAYOUT%ATOM(A,:)+MATMUL(LAYOUT%CELL,REAL(SHIFT,KIND=8))
            CALL SEED_VALUE(LAYOUT,A,POINT-CENTERS(:,K),Q(K),ZERO,.FALSE.)
            ACTIVE(K)=.NOT.ZERO
            IF(A.EQ.IAT.AND.ALL(SHIFT.EQ.0)) T=K
          END DO
        END DO
      END DO
    END DO
    IF(T.EQ.0) THEN
      CALL ERROR$MSG('SKALA PARTITION TARGET OUTSIDE COMPACT SUPPORT SEARCH')
      CALL ERROR$STOP('PAW_SKALA_PERIODIC_WEIGHT')
    END IF
    IF(MAXVAL(Q).LT.1.D-200) THEN
      DO J=1,K
        Q(J)=-HUGE(1.D0)
        IF(.NOT.ACTIVE(J)) CYCLE
        CALL SEED_VALUE(LAYOUT,OWNER(J),POINT-CENTERS(:,J),Q(J),ZERO,.TRUE.)
      END DO
      Q=EXP(Q-MAXVAL(Q))
    END IF
    Q=Q/SUM(Q)
    WEIGHT=Q(T)
    IF(.NOT.PRESENT(DATOM).AND..NOT.PRESENT(MOMENT)) RETURN
    F=0.D0
    M=0.D0
    DO J=1,K
      COEFF=-WEIGHT*Q(J)
      IF(J.EQ.T) COEFF=COEFF+WEIGHT
      IF(COEFF.EQ.0.D0) CYCLE
      CALL SEED_REVERSE(LAYOUT,OWNER(J),CENTERS(:,J),POINT,COEFF,F,M)
    END DO
    IF(PRESENT(DATOM)) DATOM=F
    IF(PRESENT(MOMENT)) MOMENT=M
  END SUBROUTINE
END MODULE
