!*******************************************************************************
!**  CARTESIAN SOLID-HARMONIC PRIMITIVES FOR THE SKALA PAW ATOM GRIDS         **
!*******************************************************************************
MODULE PAW_SKALA_PRIMITIVES_MODULE
  IMPLICIT NONE
  PRIVATE

  TYPE, PUBLIC :: PAW_SKALA_SOLID_BASIS
    INTEGER(4) :: LMAX=-1
    INTEGER(4) :: NPOLY=0
    INTEGER(4) :: LMX=0
    INTEGER(4),ALLOCATABLE :: POWER(:,:) !(3,NPOLY)
    REAL(8),ALLOCATABLE :: COEFF(:,:)    !(NPOLY,LMX)
  END TYPE PAW_SKALA_SOLID_BASIS

  PUBLIC :: PAW_SKALA_SOLID_BASIS_INIT
  PUBLIC :: PAW_SKALA_SOLID_BASIS_EVALUATE
  PUBLIC :: PAW_SKALA_PRIMITIVES_TEST

CONTAINS

  SUBROUTINE PAW_SKALA_SOLID_BASIS_INIT(BASIS,LMAX)
    TYPE(PAW_SKALA_SOLID_BASIS),INTENT(INOUT) :: BASIS
    INTEGER(4),INTENT(IN) :: LMAX
    INTEGER(4) :: I,J,K,N,IND

    IF(LMAX.LT.0) THEN
      CALL ERROR$MSG('LMAX MUST NOT BE NEGATIVE')
      CALL ERROR$I4VAL('LMAX',LMAX)
      CALL ERROR$STOP('PAW_SKALA_SOLID_BASIS_INIT')
    END IF
    IF(ALLOCATED(BASIS%POWER)) DEALLOCATE(BASIS%POWER)
    IF(ALLOCATED(BASIS%COEFF)) DEALLOCATE(BASIS%COEFF)
    BASIS%LMAX=LMAX
    BASIS%NPOLY=(LMAX+1)*(LMAX+2)*(LMAX+3)/6
    BASIS%LMX=(LMAX+1)**2
    ALLOCATE(BASIS%POWER(3,BASIS%NPOLY))
    ALLOCATE(BASIS%COEFF(BASIS%NPOLY,BASIS%LMX))
    IND=0
    DO N=0,LMAX
      DO I=0,N
        DO J=0,N-I
          K=N-I-J
          IND=IND+1
          BASIS%POWER(:,IND)=(/I,J,K/)
        END DO
      END DO
    END DO
    CALL SPHERICAL$YLMPOLYNOMIALS(LMAX,BASIS%NPOLY,BASIS%LMX &
   &                             ,BASIS%COEFF)
  END SUBROUTINE PAW_SKALA_SOLID_BASIS_INIT

  SUBROUTINE PAW_SKALA_SOLID_BASIS_EVALUATE(BASIS,R,SOLID,GRAD)
    TYPE(PAW_SKALA_SOLID_BASIS),INTENT(IN) :: BASIS
    REAL(8),INTENT(IN) :: R(3)
    REAL(8),INTENT(OUT) :: SOLID(BASIS%LMX)
    REAL(8),INTENT(OUT) :: GRAD(3,BASIS%LMX)
    INTEGER(4) :: I,J,K,IND,LM
    REAL(8) :: C,TERM

    IF(.NOT.ALLOCATED(BASIS%COEFF)) THEN
      CALL ERROR$MSG('SOLID-HARMONIC BASIS HAS NOT BEEN INITIALIZED')
      CALL ERROR$STOP('PAW_SKALA_SOLID_BASIS_EVALUATE')
    END IF
    SOLID(:)=0.D0
    GRAD(:,:)=0.D0
    DO LM=1,BASIS%LMX
      DO IND=1,BASIS%NPOLY
        C=BASIS%COEFF(IND,LM)
        IF(C.EQ.0.D0) CYCLE
        I=BASIS%POWER(1,IND)
        J=BASIS%POWER(2,IND)
        K=BASIS%POWER(3,IND)
        TERM=C*R(1)**I*R(2)**J*R(3)**K
        SOLID(LM)=SOLID(LM)+TERM
        IF(I.GT.0) GRAD(1,LM)=GRAD(1,LM) &
       &                    +C*REAL(I,KIND=8)*R(1)**(I-1)*R(2)**J*R(3)**K
        IF(J.GT.0) GRAD(2,LM)=GRAD(2,LM) &
       &                    +C*REAL(J,KIND=8)*R(1)**I*R(2)**(J-1)*R(3)**K
        IF(K.GT.0) GRAD(3,LM)=GRAD(3,LM) &
       &                    +C*REAL(K,KIND=8)*R(1)**I*R(2)**J*R(3)**(K-1)
      END DO
    END DO
  END SUBROUTINE PAW_SKALA_SOLID_BASIS_EVALUATE

  SUBROUTINE PAW_SKALA_PRIMITIVES_TEST(MAXERROR)
    USE PAW_LEBEDEV_MODULE, ONLY: PAW_LEBEDEV_TEST
    IMPLICIT NONE
    REAL(8),INTENT(OUT) :: MAXERROR
    TYPE(PAW_SKALA_SOLID_BASIS) :: BASIS
    INTEGER(4),PARAMETER :: LMAX=4
    INTEGER(4),PARAMETER :: LMX=(LMAX+1)**2
    REAL(8),PARAMETER :: EPS=1.D-6
    REAL(8) :: R(3),RP(3),RM(3),YLM(LMX),YLMP(LMX),YLMM(LMX)
    REAL(8) :: SOLID(LMX),GRAD(3,LMX),REFERENCE,NUMERICAL
    REAL(8) :: RNORM,ERR
    INTEGER(4) :: IDIM,L,LM

    CALL PAW_LEBEDEV_TEST(MAXERROR)
    CALL PAW_SKALA_SOLID_BASIS_INIT(BASIS,LMAX)
    R=(/0.31D0,-0.47D0,0.825D0/)
    CALL PAW_SKALA_SOLID_BASIS_EVALUATE(BASIS,R,SOLID,GRAD)
    CALL SPHERICAL$YLM(LMX,R,YLM)
    RNORM=SQRT(SUM(R**2))
    DO LM=1,LMX
      L=INT(SQRT(REAL(LM-1,KIND=8)))
      REFERENCE=RNORM**L*YLM(LM)
      MAXERROR=MAX(MAXERROR,ABS(SOLID(LM)-REFERENCE))
      DO IDIM=1,3
        RP=R
        RM=R
        RP(IDIM)=RP(IDIM)+EPS
        RM(IDIM)=RM(IDIM)-EPS
        CALL SPHERICAL$YLM(LMX,RP,YLMP)
        CALL SPHERICAL$YLM(LMX,RM,YLMM)
        NUMERICAL=(SQRT(SUM(RP**2))**L*YLMP(LM) &
       &          -SQRT(SUM(RM**2))**L*YLMM(LM))/(2.D0*EPS)
        ERR=ABS(GRAD(IDIM,LM)-NUMERICAL)
        MAXERROR=MAX(MAXERROR,ERR)
      END DO
    END DO
  END SUBROUTINE PAW_SKALA_PRIMITIVES_TEST

END MODULE PAW_SKALA_PRIMITIVES_MODULE
