! SPDX-License-Identifier: GPL-3.0-or-later

      MODULE PAW_SKALA_MODULE
      USE PAW_SKALA_PRIMITIVES_MODULE, ONLY: PAW_SKALA_SOURCE,PAW_SKALA_SOURCE_CACHE
      USE PAW_SKALA_PARTITION_MODULE, ONLY: PAW_SKALA_PARTITION_CACHE
#IF DEFINED(CPPVAR_SKALA_FTORCH)
      USE PAW_SKALA_BRIDGE, ONLY: PAW_SKALA_MODEL, PAW_SKALA_LOAD &
     &                           ,PAW_SKALA_EVALUATE, PAW_SKALA_RELEASE &
     &                           ,PAW_SKALA_CUDA_AVAILABLE
#ENDIF
      IMPLICIT NONE
#IF DEFINED(CPPVAR_SKALA_FTORCH)
      TYPE(PAW_SKALA_MODEL),SAVE :: MODEL
#ENDIF
      LOGICAL(4),SAVE :: TINITIALIZED=.FALSE.
      LOGICAL(4),SAVE :: TON=.FALSE.
      LOGICAL(4),SAVE :: CONFIG_APPLY=.FALSE.
      LOGICAL(4),SAVE :: CONFIG_APPLYSMOOTH=.TRUE.
      LOGICAL(4),SAVE :: CONFIG_APPLYTAU=.TRUE.
      LOGICAL(4),SAVE :: CONFIG_APPLYONECENTER=.TRUE.
      LOGICAL(4),SAVE :: CONFIG_INTERPOLATEPARTITION=.FALSE.
      LOGICAL(4),SAVE :: CONFIG_DISTRIBUTEGPU=.FALSE.
      LOGICAL(4),SAVE :: CONFIG_CHECK=.FALSE.
      LOGICAL(4),SAVE :: CONFIG_NEEDFORCE=.FALSE.
      LOGICAL(4),SAVE :: CONFIG_NEEDSTRESS=.FALSE.
      CHARACTER(2048),SAVE :: CONFIG_MODELFILE=' '
      CHARACTER(16),SAVE :: CONFIG_DEVICE='AUTO'
      LOGICAL(4),SAVE :: TDEVICECUDA=.FALSE.
      LOGICAL(4),SAVE :: TGRIDBACKACC=.FALSE.
      INTEGER(4),SAVE :: CONFIG_DEVICEINDEX=-1
      INTEGER(4),SAVE :: CONFIG_RADIALPOINTS=200
      INTEGER(4),SAVE :: CONFIG_LEBEDEVEXACTNESS=53
      INTEGER(4),SAVE :: CONFIG_LEBEDEVORIENTATIONS=1
      INTEGER(4),SAVE :: CONFIG_IMAGESHELLS=1
      LOGICAL(4),ALLOCATABLE,SAVE :: TONECENTERREPORTED(:)
      LOGICAL(4),SAVE :: TONECENTERCHECKED=.FALSE.
      LOGICAL(4),SAVE :: TSMOOTHREPORTED=.FALSE.
      LOGICAL(4),SAVE :: TSMOOTHREADY=.FALSE.
      INTEGER(4),SAVE :: SMOOTH_NR1=0,SMOOTH_NR2=0,SMOOTH_NR3=0
      INTEGER(4),SAVE :: SMOOTH_NDIMD=0
      REAL(8),SAVE :: SMOOTH_RBAS(3,3)=0.D0
      REAL(8),SAVE :: SMOOTH_DVOL=0.D0
      REAL(8),ALLOCATABLE,SAVE :: SMOOTH_RHO(:,:,:,:)
      REAL(8),ALLOCATABLE,SAVE :: SMOOTH_GRHO(:,:,:,:,:)
      REAL(8),ALLOCATABLE,SAVE :: SMOOTH_TAU(:,:,:,:)
      REAL(8),ALLOCATABLE,SAVE :: SMOOTH_ADJ_RHO(:,:,:,:)
      REAL(8),ALLOCATABLE,SAVE :: SMOOTH_ADJ_GRHO(:,:,:,:,:)
      REAL(8),ALLOCATABLE,SAVE :: SMOOTH_ADJ_TAU(:,:,:,:)
      REAL(8),SAVE :: FORWARD_ENERGY=0.D0
      REAL(8),SAVE :: FORWARD_ELECTRONS=0.D0
      REAL(8),SAVE :: ELECTRON_REFERENCE=0.D0
      LOGICAL(4),SAVE :: TELECTRONREFERENCE=.FALSE.
      REAL(8),SAVE :: FORWARD_TAU=0.D0
      REAL(8),SAVE :: FORWARD_VOLUME=0.D0
      REAL(8),SAVE :: FORWARD_SMOOTH_ELECTRONS=0.D0
      REAL(8),SAVE :: FORWARD_CORRECTION_ELECTRONS=0.D0
      REAL(8),SAVE :: FORWARD_SMOOTH_TAU=0.D0
      REAL(8),SAVE :: FORWARD_CORRECTION_TAU=0.D0
      REAL(8),SAVE :: FORWARD_ONECENTER_ADJOINT_NORM2=0.D0
      REAL(8),SAVE :: FORWARD_ONECENTER_CONTRACTION=0.D0
      REAL(8),SAVE :: FORWARD_SOURCE_CONTRACTION=0.D0
      REAL(8),ALLOCATABLE,SAVE :: FORWARD_ATOM_ENERGY(:)
      INTEGER(4),ALLOCATABLE,SAVE :: FORWARD_ATOM_NPOINT(:)
      REAL(8),ALLOCATABLE,SAVE :: FORWARD_DERIV(:,:)
      REAL(8),ALLOCATABLE,SAVE :: FORWARD_DERIV_MODEL_ATOM(:,:)
      REAL(8),ALLOCATABLE,SAVE :: FORWARD_DERIV_LOCAL_GRID(:,:)
      REAL(8),ALLOCATABLE,SAVE :: FORWARD_DERIV_LOCAL_PRIMITIVE(:,:)
      REAL(8),ALLOCATABLE,SAVE :: FORWARD_DERIV_LOCAL_PARTITION(:,:)
      REAL(8),SAVE :: FORWARD_STRESS(3,3)=0.D0
      REAL(8),SAVE :: FORWARD_STRESS_WEIGHT(3,3)=0.D0
      REAL(8),SAVE :: FORWARD_STRESS_PRIMITIVE(3,3)=0.D0
      REAL(8),SAVE :: FORWARD_STRESS_COORDINATE(3,3)=0.D0
      REAL(8),SAVE :: FORWARD_STRESS_PARTITION(3,3)=0.D0
      REAL(8),SAVE :: FORWARD_STRESS_BLEND(3,3)=0.D0
      LOGICAL(4),SAVE :: TSTRESSREADY=.FALSE.
      INTEGER(4),SAVE :: FORWARD_NPOINT=0
      ! MPE reductions support REAL(8), but not INTEGER(8) diagnostic counters.
      REAL(8),SAVE :: FORWARD_PARTITION_CACHE(3)=0.D0
      REAL(8),SAVE :: FORWARD_SOURCE_CACHE(6)=0.D0
      LOGICAL(4),SAVE :: TFORWARDREPORTED=.FALSE.
      LOGICAL(4),SAVE :: TOPERATORREPORTED=.FALSE.
      LOGICAL(4),SAVE :: TTAUCONTRACTIONREADY=.FALSE.
      REAL(8),SAVE :: SMOOTH_TAU_CONTRACTION=0.D0
      LOGICAL(4),SAVE :: TSCALARCONTRACTIONREADY=.FALSE.
      REAL(8),SAVE :: SMOOTH_SCALAR_CONTRACTION=0.D0
      LOGICAL(4),SAVE :: TONECENTERCONTRACTIONREADY=.FALSE.
      REAL(8),SAVE :: ONECENTER_CONTRACTION=0.D0
      TYPE(PAW_SKALA_SOURCE),ALLOCATABLE,SAVE :: SOURCES(:)
      TYPE SKALA_BLOCK_GRID
        REAL(8),ALLOCATABLE :: X(:,:),W(:),D(:),BASEW(:)
        TYPE(PAW_SKALA_PARTITION_CACHE) :: PARTITION
        TYPE(PAW_SKALA_SOURCE_CACHE),ALLOCATABLE :: SOURCE(:)
      END TYPE SKALA_BLOCK_GRID
      TYPE(SKALA_BLOCK_GRID),ALLOCATABLE,SAVE :: BLOCK_GRID(:)
      REAL(8),ALLOCATABLE,SAVE :: GRID_ATOMS(:,:)
      REAL(8),SAVE :: GRID_INVERSE(3,3)=0.D0
      REAL(8),SAVE :: GRID_CELL(3,3)=0.D0
      END MODULE PAW_SKALA_MODULE

!     ..................................................................
      SUBROUTINE SKALA$SETL4(ID,VAL)
      USE PAW_SKALA_MODULE
      IMPLICIT NONE
      CHARACTER(*),INTENT(IN) :: ID
      LOGICAL(4),INTENT(IN)   :: VAL
      IF(ID.EQ.'ON') THEN
        TON=VAL
      ELSE IF(ID.EQ.'APPLY') THEN
        CONFIG_APPLY=VAL
      ELSE IF(ID.EQ.'APPLYSMOOTH') THEN
        CONFIG_APPLYSMOOTH=VAL
      ELSE IF(ID.EQ.'APPLYTAU') THEN
        CONFIG_APPLYTAU=VAL
      ELSE IF(ID.EQ.'APPLYONECENTER') THEN
        CONFIG_APPLYONECENTER=VAL
      ELSE IF(ID.EQ.'INTERPOLATEPARTITION') THEN
        IF(VAL) THEN
          CALL ERROR$MSG('INTERPOLATEPARTITION=T IS INCOMPATIBLE WITH JOINT SKALA RECONSTRUCTION')
          CALL ERROR$STOP('SKALA$SETL4')
        END IF
        CONFIG_INTERPOLATEPARTITION=VAL
      ELSE IF(ID.EQ.'DISTRIBUTEGPU') THEN
        CONFIG_DISTRIBUTEGPU=VAL
      ELSE IF(ID.EQ.'CHECK') THEN
        CONFIG_CHECK=VAL
      ELSE IF(ID.EQ.'NEEDFORCE') THEN
        CONFIG_NEEDFORCE=VAL
      ELSE IF(ID.EQ.'NEEDSTRESS') THEN
        CONFIG_NEEDSTRESS=VAL
      ELSE
        CALL ERROR$MSG('ID NOT RECOGNIZED')
        CALL ERROR$CHVAL('ID',ID)
        CALL ERROR$STOP('SKALA$SETL4')
      END IF
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$GETL4(ID,VAL)
      USE PAW_SKALA_MODULE
      IMPLICIT NONE
      CHARACTER(*),INTENT(IN) :: ID
      LOGICAL(4),INTENT(OUT)  :: VAL
      IF(ID.EQ.'ON') THEN
        VAL=TON
      ELSE IF(ID.EQ.'APPLY') THEN
        VAL=CONFIG_APPLY
      ELSE IF(ID.EQ.'APPLYSMOOTH') THEN
        VAL=CONFIG_APPLYSMOOTH
      ELSE IF(ID.EQ.'APPLYTAU') THEN
        VAL=CONFIG_APPLYTAU
      ELSE IF(ID.EQ.'APPLYONECENTER') THEN
        VAL=CONFIG_APPLYONECENTER
      ELSE IF(ID.EQ.'INTERPOLATEPARTITION') THEN
        VAL=CONFIG_INTERPOLATEPARTITION
      ELSE IF(ID.EQ.'DISTRIBUTEGPU') THEN
        VAL=CONFIG_DISTRIBUTEGPU
      ELSE IF(ID.EQ.'CUDA') THEN
        IF(TINITIALIZED) THEN
          VAL=TDEVICECUDA
        ELSE IF(TRIM(CONFIG_DEVICE).EQ.'CUDA'.OR. &
     &          TRIM(CONFIG_DEVICE).EQ.'cuda') THEN
          VAL=.TRUE.
        ELSE IF(TRIM(CONFIG_DEVICE).EQ.'AUTO'.OR. &
     &          TRIM(CONFIG_DEVICE).EQ.'auto') THEN
#IF DEFINED(CPPVAR_SKALA_FTORCH)
          VAL=PAW_SKALA_CUDA_AVAILABLE()
#ELSE
          VAL=.FALSE.
#ENDIF
        ELSE
          VAL=.FALSE.
        END IF
      ELSE IF(ID.EQ.'CHECK') THEN
        VAL=CONFIG_CHECK
      ELSE IF(ID.EQ.'NEEDFORCE') THEN
        VAL=CONFIG_NEEDFORCE
      ELSE IF(ID.EQ.'NEEDSTRESS') THEN
        VAL=CONFIG_NEEDSTRESS
      ELSE
        CALL ERROR$MSG('ID NOT RECOGNIZED')
        CALL ERROR$CHVAL('ID',ID)
        CALL ERROR$STOP('SKALA$GETL4')
      END IF
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$SETCH(ID,VAL)
      USE PAW_SKALA_MODULE
      IMPLICIT NONE
      CHARACTER(*),INTENT(IN) :: ID
      CHARACTER(*),INTENT(IN) :: VAL
      IF(ID.EQ.'MODEL') THEN
        CONFIG_MODELFILE=TRIM(VAL)
      ELSE IF(ID.EQ.'DEVICE') THEN
        CONFIG_DEVICE=TRIM(VAL)
      ELSE
        CALL ERROR$MSG('ID NOT RECOGNIZED')
        CALL ERROR$CHVAL('ID',ID)
        CALL ERROR$STOP('SKALA$SETCH')
      END IF
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$SETI4(ID,VAL)
      USE PAW_SKALA_MODULE
      IMPLICIT NONE
      CHARACTER(*),INTENT(IN) :: ID
      INTEGER(4),INTENT(IN)   :: VAL
      IF(ID.EQ.'DEVICEINDEX') THEN
        CONFIG_DEVICEINDEX=VAL
      ELSE IF(ID.EQ.'RADIALPOINTS') THEN
        IF(VAL.LE.0) THEN
          CALL ERROR$MSG('SKALA RADIALPOINTS MUST BE POSITIVE')
          CALL ERROR$I4VAL('RADIALPOINTS',VAL)
          CALL ERROR$STOP('SKALA$SETI4')
        END IF
        CONFIG_RADIALPOINTS=VAL
      ELSE IF(ID.EQ.'LEBEDEVEXACTNESS') THEN
        IF(VAL.LE.0) THEN
          CALL ERROR$MSG('SKALA LEBEDEVEXACTNESS MUST BE POSITIVE')
          CALL ERROR$I4VAL('LEBEDEVEXACTNESS',VAL)
          CALL ERROR$STOP('SKALA$SETI4')
        END IF
        CONFIG_LEBEDEVEXACTNESS=VAL
      ELSE IF(ID.EQ.'LEBEDEVORIENTATIONS') THEN
        IF(VAL.LE.0) THEN
          CALL ERROR$MSG('SKALA LEBEDEVORIENTATIONS MUST BE POSITIVE')
          CALL ERROR$I4VAL('LEBEDEVORIENTATIONS',VAL)
          CALL ERROR$STOP('SKALA$SETI4')
        END IF
        CONFIG_LEBEDEVORIENTATIONS=VAL
      ELSE IF(ID.EQ.'IMAGESHELLS') THEN
        IF(VAL.LT.1) THEN
          CALL ERROR$MSG('SKALA IMAGESHELLS MUST BE POSITIVE')
          CALL ERROR$I4VAL('IMAGESHELLS',VAL)
          CALL ERROR$STOP('SKALA$SETI4')
        END IF
        CONFIG_IMAGESHELLS=VAL
      ELSE
        CALL ERROR$MSG('ID NOT RECOGNIZED')
        CALL ERROR$CHVAL('ID',ID)
        CALL ERROR$STOP('SKALA$SETI4')
      END IF
      IF(ID.NE.'DEVICEINDEX') THEN
        IF(ALLOCATED(BLOCK_GRID)) DEALLOCATE(BLOCK_GRID)
        IF(ALLOCATED(GRID_ATOMS)) DEALLOCATE(GRID_ATOMS)
      END IF
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$REPORT(NFIL)
      USE PAW_SKALA_MODULE
      USE PAW_LEBEDEV_MODULE, ONLY: PAW_LEBEDEV_SIZE
      USE PAW_SKALA_PARTITION_MODULE, ONLY: PAW_SKALA_PARTITION_CACHE_LIMIT
      USE PAW_SKALA_PRIMITIVES_MODULE, ONLY: PAW_SKALA_SOURCE_CACHE_LIMIT &
     &     ,PAW_SKALA_SOURCE_RESIDENT_LIMIT
      IMPLICIT NONE
      INTEGER(4),INTENT(IN) :: NFIL
      INTEGER :: NANG,LEXACT
      INTEGER(8) :: CACHE_LIMIT
      IF(.NOT.TON) RETURN
      CACHE_LIMIT=PAW_SKALA_PARTITION_CACHE_LIMIT()
      WRITE(NFIL,FMT='(/"SKALA 1.1 PAW INTEGRATION"/25("="))')
      WRITE(NFIL,FMT='("STATUS",T30,A)')'JOINT PAW RECONSTRUCTION: UNDER VALIDATION'
      WRITE(NFIL,FMT='("MODEL FILE",T30,A)')TRIM(CONFIG_MODELFILE)
      WRITE(NFIL,FMT='("DEVICE",T30,A)')TRIM(CONFIG_DEVICE)
      WRITE(NFIL,FMT='("DEVICE INDEX",T30,I8)')CONFIG_DEVICEINDEX
      WRITE(NFIL,FMT='("PARTITION CACHE MiB/RANK",T30,I12)') &
     &     CACHE_LIMIT/1048576_8
      WRITE(NFIL,FMT='("SOURCE CACHE MiB/RANK",T30,I12)') &
     &     PAW_SKALA_SOURCE_CACHE_LIMIT()/1048576_8
      WRITE(NFIL,FMT='("SOURCE GPU CACHE MiB/RANK",T30,I12)') &
     &     PAW_SKALA_SOURCE_RESIDENT_LIMIT()/1048576_8
      WRITE(NFIL,FMT='("LOCAL RADIAL POINTS",T30,I8)')CONFIG_RADIALPOINTS
      WRITE(NFIL,FMT='("LEBEDEV EXACTNESS",T30,I8)')CONFIG_LEBEDEVEXACTNESS
      CALL PAW_LEBEDEV_SIZE(CONFIG_LEBEDEVEXACTNESS,NANG,LEXACT)
      WRITE(NFIL,FMT='("ACTUAL LEBEDEV EXACTNESS",T30,I8)')LEXACT
      WRITE(NFIL,FMT='("ANGULAR POINTS PER RULE",T30,I8)')NANG
      WRITE(NFIL,FMT='("LEBEDEV ORIENTATIONS",T30,I8)') &
     &     CONFIG_LEBEDEVORIENTATIONS
      WRITE(NFIL,FMT='("PERIODIC IMAGE SHELLS",T30,I8)')CONFIG_IMAGESHELLS
      WRITE(NFIL,FMT='("APPLY TO HAMILTONIAN",T30,L8)')CONFIG_APPLY
      WRITE(NFIL,FMT='("INTERPOLATE PARTITION",T30,L8)') &
     &     CONFIG_INTERPOLATEPARTITION
      WRITE(NFIL,FMT='("DISTRIBUTE CUDA MODEL",T30,L8)') &
     &     CONFIG_DISTRIBUTEGPU
      WRITE(NFIL,FMT='("CHECK MODEL ADJOINTS",T30,L8)')CONFIG_CHECK
      IF(CONFIG_APPLY) THEN
        WRITE(NFIL,FMT='("APPLY SMOOTH OPERATOR",T30,L8)')CONFIG_APPLYSMOOTH
        WRITE(NFIL,FMT='("APPLY TAU OPERATOR",T30,L8)')CONFIG_APPLYTAU
        WRITE(NFIL,FMT='("APPLY ONE-CENTER OPERATOR",T30,L8)') &
     &       CONFIG_APPLYONECENTER
        WRITE(NFIL,FMT='("ANALYTIC ATOMIC FORCES",T30,A)')'AVAILABLE'
        WRITE(NFIL,FMT='("ANALYTIC STRESS",T30,A)')'AVAILABLE'
      END IF
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$AVAILABLE(TAVAILABLE)
      IMPLICIT NONE
      LOGICAL(4),INTENT(OUT) :: TAVAILABLE
#IF DEFINED(CPPVAR_SKALA_FTORCH)
      TAVAILABLE=.TRUE.
#ELSE
      TAVAILABLE=.FALSE.
#ENDIF
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$INITIALIZE(MODELFILE,DEVICE,DEVICEINDEX)
      USE PAW_SKALA_MODULE
      IMPLICIT NONE
      CHARACTER(*),INTENT(IN) :: MODELFILE
      CHARACTER(*),INTENT(IN) :: DEVICE
      INTEGER(4)  ,INTENT(IN) :: DEVICEINDEX
#IF DEFINED(CPPVAR_SKALA_FTORCH)
      INTEGER(4)              :: STATUS
      CHARACTER(2048)         :: MESSAGE
      CHARACTER(16)           :: DEVICE1

      IF(TINITIALIZED) CALL PAW_SKALA_RELEASE(MODEL)
      DEVICE1=DEVICE
      IF(TRIM(DEVICE1).EQ.'AUTO'.OR.TRIM(DEVICE1).EQ.'auto') THEN
        IF(PAW_SKALA_CUDA_AVAILABLE()) THEN
          DEVICE1='CUDA'
        ELSE
          DEVICE1='CPU'
        END IF
      END IF
      TDEVICECUDA=TRIM(DEVICE1).EQ.'CUDA'.OR.TRIM(DEVICE1).EQ.'cuda'
      CALL PAW_SKALA_LOAD(MODEL,MODELFILE,DEVICE1,DEVICEINDEX,STATUS,MESSAGE)
      IF(STATUS.NE.0) THEN
        CALL ERROR$MSG('FAILED TO INITIALIZE SKALA 1.1')
        CALL ERROR$CHVAL('DETAIL',TRIM(MESSAGE))
        CALL ERROR$STOP('SKALA$INITIALIZE')
      END IF
      TINITIALIZED=.TRUE.
#ELSE
      CALL ERROR$MSG('CP-PAW WAS BUILT WITHOUT THE SKALA/FTORCH BRIDGE')
      CALL ERROR$STOP('SKALA$INITIALIZE')
#ENDIF
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$ENSUREINITIALIZED
      USE PAW_SKALA_MODULE
      IMPLICIT NONE
      IF(TINITIALIZED) RETURN
      IF(.NOT.TON) THEN
        CALL ERROR$MSG('SKALA FUNCTIONAL IS NOT ENABLED')
        CALL ERROR$STOP('SKALA$ENSUREINITIALIZED')
      END IF
      IF(LEN_TRIM(CONFIG_MODELFILE).EQ.0) THEN
        CALL ERROR$MSG('SKALA MODEL FILE HAS NOT BEEN SPECIFIED')
        CALL ERROR$STOP('SKALA$ENSUREINITIALIZED')
      END IF
      CALL SKALA$INITIALIZE(TRIM(CONFIG_MODELFILE),TRIM(CONFIG_DEVICE) &
     &                     ,CONFIG_DEVICEINDEX)
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$FINALIZE
      USE PAW_SKALA_MODULE
      USE PAW_SKALA_GRID_MODULE, ONLY: PAW_SKALA_GRID_BACK_END
      IMPLICIT NONE
      IF(TGRIDBACKACC) THEN
        CALL PAW_SKALA_GRID_BACK_END(SMOOTH_NR1,SMOOTH_NR2,SMOOTH_NR3 &
     &                              ,SMOOTH_NDIMD,SMOOTH_ADJ_RHO &
     &                              ,SMOOTH_ADJ_GRHO,SMOOTH_ADJ_TAU &
     &                              ,TGRIDBACKACC)
      END IF
#IF DEFINED(CPPVAR_SKALA_FTORCH)
      IF(TINITIALIZED) CALL PAW_SKALA_RELEASE(MODEL)
#ENDIF
      TINITIALIZED=.FALSE.
      TDEVICECUDA=.FALSE.
      TSMOOTHREPORTED=.FALSE.
      TSMOOTHREADY=.FALSE.
      TFORWARDREPORTED=.FALSE.
      TOPERATORREPORTED=.FALSE.
      TTAUCONTRACTIONREADY=.FALSE.
      SMOOTH_TAU_CONTRACTION=0.D0
      TSCALARCONTRACTIONREADY=.FALSE.
      SMOOTH_SCALAR_CONTRACTION=0.D0
      TONECENTERCONTRACTIONREADY=.FALSE.
      ONECENTER_CONTRACTION=0.D0
      TSTRESSREADY=.FALSE.
      FORWARD_STRESS=0.D0
      FORWARD_STRESS_WEIGHT=0.D0
      FORWARD_STRESS_PRIMITIVE=0.D0
      FORWARD_STRESS_COORDINATE=0.D0
      FORWARD_STRESS_PARTITION=0.D0
      FORWARD_STRESS_BLEND=0.D0
      IF(ALLOCATED(SOURCES)) DEALLOCATE(SOURCES)
      IF(ALLOCATED(BLOCK_GRID)) DEALLOCATE(BLOCK_GRID)
      IF(ALLOCATED(GRID_ATOMS)) DEALLOCATE(GRID_ATOMS)
      IF(ALLOCATED(TONECENTERREPORTED)) DEALLOCATE(TONECENTERREPORTED)
      IF(ALLOCATED(SMOOTH_RHO)) DEALLOCATE(SMOOTH_RHO)
      IF(ALLOCATED(SMOOTH_GRHO)) DEALLOCATE(SMOOTH_GRHO)
      IF(ALLOCATED(SMOOTH_TAU)) DEALLOCATE(SMOOTH_TAU)
      IF(ALLOCATED(SMOOTH_ADJ_RHO)) DEALLOCATE(SMOOTH_ADJ_RHO)
      IF(ALLOCATED(SMOOTH_ADJ_GRHO)) DEALLOCATE(SMOOTH_ADJ_GRHO)
      IF(ALLOCATED(SMOOTH_ADJ_TAU)) DEALLOCATE(SMOOTH_ADJ_TAU)
      IF(ALLOCATED(FORWARD_ATOM_ENERGY)) DEALLOCATE(FORWARD_ATOM_ENERGY)
      IF(ALLOCATED(FORWARD_ATOM_NPOINT)) DEALLOCATE(FORWARD_ATOM_NPOINT)
      IF(ALLOCATED(FORWARD_DERIV)) DEALLOCATE(FORWARD_DERIV)
      IF(ALLOCATED(FORWARD_DERIV_MODEL_ATOM)) &
     &  DEALLOCATE(FORWARD_DERIV_MODEL_ATOM)
      IF(ALLOCATED(FORWARD_DERIV_LOCAL_GRID)) &
     &  DEALLOCATE(FORWARD_DERIV_LOCAL_GRID)
      IF(ALLOCATED(FORWARD_DERIV_LOCAL_PRIMITIVE)) &
     &  DEALLOCATE(FORWARD_DERIV_LOCAL_PRIMITIVE)
      IF(ALLOCATED(FORWARD_DERIV_LOCAL_PARTITION)) &
     &  DEALLOCATE(FORWARD_DERIV_LOCAL_PARTITION)
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$ELECTRONREFERENCE(VAL)
      USE PAW_SKALA_MODULE
      IMPLICIT NONE
      REAL(8),INTENT(IN) :: VAL
      ELECTRON_REFERENCE=VAL
      TELECTRONREFERENCE=.TRUE.
      END SUBROUTINE SKALA$ELECTRONREFERENCE

!     ..................................................................
      SUBROUTINE SKALA$FORWARDBEGIN
      USE PAW_SKALA_MODULE
      USE PAW_SKALA_GRID_MODULE, ONLY: PAW_SKALA_GRID_BACK_BEGIN &
     &                                ,PAW_SKALA_GRID_BACK_END
      USE MPE_MODULE
      IMPLICIT NONE
      INTEGER(4) :: NAT,NTASKS,THISTASK
      LOGICAL(4) :: TSKALACUDA,TACCELRANK
#IF DEFINED(CPPVAR_ACCEL_PROFILE)
      REAL(8) :: ACCEL_T0,ACCEL_T1,GRID_BACK_BYTES
#ENDIF
      IF(.NOT.TON) RETURN
      IF(.NOT.TSMOOTHREADY) THEN
        CALL ERROR$MSG('SKALA SMOOTH FIELDS ARE NOT AVAILABLE')
        CALL ERROR$STOP('SKALA$FORWARDBEGIN')
      END IF
      FORWARD_ENERGY=0.D0
      FORWARD_ELECTRONS=0.D0
      FORWARD_TAU=0.D0
      FORWARD_SMOOTH_ELECTRONS=0.D0
      FORWARD_CORRECTION_ELECTRONS=0.D0
      FORWARD_SMOOTH_TAU=0.D0
      FORWARD_CORRECTION_TAU=0.D0
      FORWARD_ONECENTER_ADJOINT_NORM2=0.D0
      FORWARD_ONECENTER_CONTRACTION=0.D0
      FORWARD_SOURCE_CONTRACTION=0.D0
      FORWARD_NPOINT=0
      FORWARD_PARTITION_CACHE=0.D0
      FORWARD_SOURCE_CACHE=0.D0
      FORWARD_VOLUME=0.D0
      FORWARD_STRESS=0.D0
      FORWARD_STRESS_WEIGHT=0.D0
      FORWARD_STRESS_PRIMITIVE=0.D0
      FORWARD_STRESS_COORDINATE=0.D0
      FORWARD_STRESS_PARTITION=0.D0
      FORWARD_STRESS_BLEND=0.D0
      TSTRESSREADY=.FALSE.
      CALL ATOMLIST$NATOM(NAT)
      CALL MPE$QUERY('MONOMER',NTASKS,THISTASK)
      CALL SKALA$GETL4('CUDA',TSKALACUDA)
      TACCELRANK=.TRUE.
      IF(TSKALACUDA.AND.(.NOT.CONFIG_DISTRIBUTEGPU)) THEN
        TACCELRANK=THISTASK.EQ.1
      ELSE IF(THISTASK.GT.NAT) THEN
        TACCELRANK=.FALSE.
      END IF
      IF(ALLOCATED(FORWARD_ATOM_ENERGY)) DEALLOCATE(FORWARD_ATOM_ENERGY)
      IF(ALLOCATED(FORWARD_ATOM_NPOINT)) DEALLOCATE(FORWARD_ATOM_NPOINT)
      ALLOCATE(FORWARD_ATOM_ENERGY(NAT),FORWARD_ATOM_NPOINT(NAT))
      FORWARD_ATOM_ENERGY=0.D0
      FORWARD_ATOM_NPOINT=0
      IF(TGRIDBACKACC) THEN
        CALL PAW_SKALA_GRID_BACK_END(SMOOTH_NR1,SMOOTH_NR2,SMOOTH_NR3 &
     &                              ,SMOOTH_NDIMD,SMOOTH_ADJ_RHO &
     &                              ,SMOOTH_ADJ_GRHO,SMOOTH_ADJ_TAU &
     &                              ,TGRIDBACKACC)
      END IF
      IF(ALLOCATED(SMOOTH_ADJ_RHO)) DEALLOCATE(SMOOTH_ADJ_RHO)
      IF(ALLOCATED(SMOOTH_ADJ_GRHO)) DEALLOCATE(SMOOTH_ADJ_GRHO)
      IF(ALLOCATED(SMOOTH_ADJ_TAU)) DEALLOCATE(SMOOTH_ADJ_TAU)
      ALLOCATE(SMOOTH_ADJ_RHO(SMOOTH_NR1,SMOOTH_NR2,SMOOTH_NR3 &
     &                       ,SMOOTH_NDIMD))
      ALLOCATE(SMOOTH_ADJ_GRHO(SMOOTH_NR1,SMOOTH_NR2,SMOOTH_NR3,3 &
     &                        ,SMOOTH_NDIMD))
      ALLOCATE(SMOOTH_ADJ_TAU(SMOOTH_NR1,SMOOTH_NR2,SMOOTH_NR3 &
     &                       ,SMOOTH_NDIMD))
      SMOOTH_ADJ_RHO=0.D0
      SMOOTH_ADJ_GRHO=0.D0
      SMOOTH_ADJ_TAU=0.D0
#IF DEFINED(CPPVAR_ACCEL_PROFILE)
      CALL ACCELPROFILE$NOW(ACCEL_T0)
#ENDIF
      IF(TACCELRANK) THEN
        CALL PAW_SKALA_GRID_BACK_BEGIN(SMOOTH_NR1,SMOOTH_NR2,SMOOTH_NR3 &
     &                                ,SMOOTH_NDIMD,SMOOTH_ADJ_RHO &
     &                                ,SMOOTH_ADJ_GRHO,SMOOTH_ADJ_TAU &
     &                                ,TGRIDBACKACC)
      END IF
#IF DEFINED(CPPVAR_ACCEL_PROFILE)
      IF(TGRIDBACKACC) THEN
        CALL ACCELPROFILE$NOW(ACCEL_T1)
        GRID_BACK_BYTES=40.D0*REAL(SMOOTH_NR1,KIND=8) &
     &                         *REAL(SMOOTH_NR2,KIND=8) &
     &                         *REAL(SMOOTH_NR3,KIND=8) &
     &                         *REAL(SMOOTH_NDIMD,KIND=8)
        CALL ACCELPROFILE$ADD('ACC_COPY_SKALA_GRID_BACK_IN' &
     &      ,INT(SMOOTH_NR1,KIND=8),INT(SMOOTH_NR2,KIND=8) &
     &      ,INT(SMOOTH_NR3,KIND=8),INT(SMOOTH_NDIMD,KIND=8) &
     &      ,0.D0,GRID_BACK_BYTES,ACCEL_T1-ACCEL_T0)
      END IF
#ENDIF
      IF(ALLOCATED(FORWARD_DERIV)) DEALLOCATE(FORWARD_DERIV)
      IF(ALLOCATED(FORWARD_DERIV_MODEL_ATOM)) &
     &  DEALLOCATE(FORWARD_DERIV_MODEL_ATOM)
      IF(ALLOCATED(FORWARD_DERIV_LOCAL_GRID)) &
     &  DEALLOCATE(FORWARD_DERIV_LOCAL_GRID)
      IF(ALLOCATED(FORWARD_DERIV_LOCAL_PRIMITIVE)) &
     &  DEALLOCATE(FORWARD_DERIV_LOCAL_PRIMITIVE)
      IF(ALLOCATED(FORWARD_DERIV_LOCAL_PARTITION)) &
     &  DEALLOCATE(FORWARD_DERIV_LOCAL_PARTITION)
      IF(CONFIG_APPLY.AND.(CONFIG_NEEDFORCE.OR.CONFIG_NEEDSTRESS)) THEN
        ALLOCATE(FORWARD_DERIV(3,NAT))
        ALLOCATE(FORWARD_DERIV_MODEL_ATOM(3,NAT))
        ALLOCATE(FORWARD_DERIV_LOCAL_GRID(3,NAT))
        ALLOCATE(FORWARD_DERIV_LOCAL_PRIMITIVE(3,NAT))
        ALLOCATE(FORWARD_DERIV_LOCAL_PARTITION(3,NAT))
        FORWARD_DERIV=0.D0
        FORWARD_DERIV_MODEL_ATOM=0.D0
        FORWARD_DERIV_LOCAL_GRID=0.D0
        FORWARD_DERIV_LOCAL_PRIMITIVE=0.D0
        FORWARD_DERIV_LOCAL_PARTITION=0.D0
      END IF
      TTAUCONTRACTIONREADY=.FALSE.
      SMOOTH_TAU_CONTRACTION=0.D0
      TSCALARCONTRACTIONREADY=.FALSE.
      SMOOTH_SCALAR_CONTRACTION=0.D0
      TONECENTERCONTRACTIONREADY=.FALSE.
      ONECENTER_CONTRACTION=0.D0
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$PREPARE(NAT,ISP,LMNXX,NDIMD,DENMAT)
      USE PAW_SKALA_MODULE
      USE PAW_SKALA_PRIMITIVES_MODULE, ONLY: PAW_SKALA_SOLID_BASIS_INIT
      USE PAW_SKALA_GRID_MODULE, ONLY: PAW_SKALA_INVERSE3
      IMPLICIT NONE
      INTEGER,INTENT(IN) :: NAT,ISP(NAT),LMNXX,NDIMD
      COMPLEX(8),INTENT(IN) :: DENMAT(LMNXX,LMNXX,NDIMD,NAT)
      INTEGER :: I,GID,NR,LNX,LMNX,J,LAST
      REAL(8),ALLOCATABLE :: CORE(:),COORD(:,:)
      LOGICAL :: CHANGED
      IF(NDIMD.NE.1.AND.NDIMD.NE.2) THEN
        CALL ERROR$MSG('SKALA REQUIRES COLLINEAR DENSITIES')
        CALL ERROR$STOP('SKALA$PREPARE')
      END IF
      IF(.NOT.ALLOCATED(SOURCES)) THEN
        ALLOCATE(SOURCES(NAT))
        DO I=1,NAT
          CALL SETUP$ISELECT(ISP(I))
          CALL SETUP$GETI4('GID',GID)
          CALL RADIAL$GETI4(GID,'NR',NR)
          CALL SETUP$GETI4('LNX',LNX)
          SOURCES(I)%NR=NR
          SOURCES(I)%LNX=LNX
          SOURCES(I)%NDIMD=NDIMD
          ALLOCATE(SOURCES(I)%R(NR),SOURCES(I)%LOX(LNX))
          ALLOCATE(SOURCES(I)%PHI(NR,LNX,2),SOURCES(I)%CORE(NR,2))
          CALL RADIAL$R(GID,NR,SOURCES(I)%R)
          CALL SETUP$GETI4A('LOX',LNX,SOURCES(I)%LOX)
          LMNX=SUM(2*SOURCES(I)%LOX+1)
          SOURCES(I)%LMNX=LMNX
          ALLOCATE(SOURCES(I)%DM(LMNX,LMNX,NDIMD))
          ALLOCATE(SOURCES(I)%DH(LMNX,LMNX,NDIMD))
          CALL SETUP$GETR8A('AEPHI',NR*LNX,SOURCES(I)%PHI(:,:,1))
          CALL SETUP$GETR8A('PSPHI',NR*LNX,SOURCES(I)%PHI(:,:,2))
          ALLOCATE(CORE(NR))
          CALL SETUP$GETR8A('AECORE',NR,SOURCES(I)%CORE(:,1))
          CALL SETUP$GETR8A('PSCORE',NR,CORE)
          SOURCES(I)%CORE(:,1)=SOURCES(I)%CORE(:,1)-CORE
          CALL SETUP$GETR8A('TAUCORE',NR,SOURCES(I)%CORE(:,2))
          DEALLOCATE(CORE)
          CALL SETUP$UNSELECT()
          LAST=1
          DO J=1,NR
            IF(MAXVAL(ABS(SOURCES(I)%PHI(J,:,1)-SOURCES(I)%PHI(J,:,2))) &
     &         .GT.1.D-14.OR.MAXVAL(ABS(SOURCES(I)%CORE(J,:))).GT.1.D-14) LAST=J
          END DO
          SOURCES(I)%RCUT=SOURCES(I)%R(MIN(NR,LAST+3))
          CALL PAW_SKALA_SOLID_BASIS_INIT(SOURCES(I)%BASIS &
     &                                 ,MAXVAL(SOURCES(I)%LOX))
        END DO
      END IF
      DO I=1,NAT
        LMNX=SOURCES(I)%LMNX
        SOURCES(I)%DM=DENMAT(1:LMNX,1:LMNX,:,I)
        SOURCES(I)%DH=(0.D0,0.D0)
      END DO
      ALLOCATE(COORD(3,NAT))
      CALL ATOMLIST$GETR8A('R(0)',0,3*NAT,COORD)
      CHANGED=.TRUE.
      IF(ALLOCATED(GRID_ATOMS)) THEN
        IF(SIZE(GRID_ATOMS,1).EQ.NAT) THEN
          CHANGED=ANY(TRANSPOSE(COORD).NE.GRID_ATOMS) &
     &           .OR.ANY(SMOOTH_RBAS.NE.GRID_CELL)
        END IF
      END IF
      IF(CHANGED) THEN
        IF(ALLOCATED(BLOCK_GRID)) DEALLOCATE(BLOCK_GRID)
        IF(ALLOCATED(GRID_ATOMS)) DEALLOCATE(GRID_ATOMS)
        ALLOCATE(BLOCK_GRID(NAT),GRID_ATOMS(NAT,3))
        GRID_ATOMS=TRANSPOSE(COORD)
        GRID_CELL=SMOOTH_RBAS
        CALL PAW_SKALA_INVERSE3(GRID_CELL,GRID_INVERSE)
      END IF
      END SUBROUTINE SKALA$PREPARE

      SUBROUTINE SKALA_BUILDGRID(IAT)
      USE PAW_SKALA_MODULE
      USE PAW_SKALA_GRID_MODULE
      USE PAW_SKALA_PARTITION_MODULE
      IMPLICIT NONE
      INTEGER,INTENT(IN) :: IAT
      TYPE(PAW_SKALA_PERIODIC_LAYOUT) :: ENERGY_LAYOUT,SELF_LAYOUT
      INTEGER :: NANG,NLOCAL,NPOINT,IP,I
      REAL(8),ALLOCATABLE :: X(:,:),W(:),E(:),D(:)
      REAL(8) :: POINT(3),WE,WD
      LOGICAL,ALLOCATABLE :: KEEP(:)
      IF(ALLOCATED(BLOCK_GRID(IAT)%W)) RETURN
      CALL PAW_SKALA_PERIODIC_INIT(ENERGY_LAYOUT,SIZE(GRID_ATOMS,1) &
     &                           ,GRID_ATOMS,GRID_CELL,CONFIG_IMAGESHELLS)
      CALL PAW_SKALA_PERIODIC_INIT(SELF_LAYOUT,1 &
     &                 ,GRID_ATOMS(IAT:IAT,:),GRID_CELL,CONFIG_IMAGESHELLS)
      CALL PAW_SKALA_LOCAL_GRID_SIZE(CONFIG_RADIALPOINTS &
     &     ,CONFIG_LEBEDEVEXACTNESS,NANG,NLOCAL,CONFIG_LEBEDEVORIENTATIONS)
      ALLOCATE(X(NLOCAL,3),W(NLOCAL),E(NLOCAL),D(NLOCAL),KEEP(NLOCAL))
      CALL PAW_SKALA_LOCAL_GRID(CONFIG_RADIALPOINTS,1.D0 &
     &     ,CONFIG_LEBEDEVEXACTNESS,NLOCAL,X,W &
     &     ,CONFIG_LEBEDEVORIENTATIONS,.TRUE.)
      DO IP=1,NLOCAL
        POINT=GRID_ATOMS(IAT,:)+X(IP,:)
        CALL PAW_SKALA_PERIODIC_WEIGHT(SELF_LAYOUT,1,POINT,WD)
        CALL PAW_SKALA_PERIODIC_WEIGHT(ENERGY_LAYOUT,IAT,POINT,WE)
        D(IP)=W(IP)*PAW_SKALA_PARTITION_TAPER(WD)
        E(IP)=W(IP)*WE
        KEEP(IP)=WD.GT.1.D-12.OR.WE.GT.0.D0
      END DO
      NPOINT=COUNT(KEEP)
      ALLOCATE(BLOCK_GRID(IAT)%X(NPOINT,3))
      ALLOCATE(BLOCK_GRID(IAT)%W(NPOINT),BLOCK_GRID(IAT)%D(NPOINT))
      ALLOCATE(BLOCK_GRID(IAT)%BASEW(NPOINT))
      DO I=1,3
        BLOCK_GRID(IAT)%X(:,I)=PACK(X(:,I),KEEP)
      END DO
      BLOCK_GRID(IAT)%W=PACK(E,KEEP)
      BLOCK_GRID(IAT)%D=PACK(D,KEEP)
      BLOCK_GRID(IAT)%BASEW=PACK(W,KEEP)
      END SUBROUTINE SKALA_BUILDGRID

      SUBROUTINE SKALA_PREPARE_SOURCE_CACHE(IAT,NPOINT,X)
      USE PAW_SKALA_MODULE
      USE PAW_SKALA_PRIMITIVES_MODULE, ONLY: PAW_SKALA_SOURCE_CACHE_PREPARE &
     &     ,PAW_SKALA_SOURCE_CACHE_BYTES,PAW_SKALA_SOURCE_CACHE_LIMIT
      IMPLICIT NONE
      INTEGER,INTENT(IN) :: IAT,NPOINT
      REAL(8),INTENT(IN) :: X(NPOINT,3)
      INTEGER :: J,K
      INTEGER(8) :: AVAILABLE,BYTES
      IF(.NOT.ALLOCATED(BLOCK_GRID(IAT)%SOURCE)) &
     &    ALLOCATE(BLOCK_GRID(IAT)%SOURCE(SIZE(SOURCES)))
      AVAILABLE=PAW_SKALA_SOURCE_CACHE_LIMIT()
      DO J=1,SIZE(BLOCK_GRID)
        IF(.NOT.ALLOCATED(BLOCK_GRID(J)%SOURCE)) CYCLE
        DO K=1,SIZE(BLOCK_GRID(J)%SOURCE)
          AVAILABLE=AVAILABLE-PAW_SKALA_SOURCE_CACHE_BYTES(BLOCK_GRID(J)%SOURCE(K))
        END DO
      END DO
      DO J=1,SIZE(SOURCES)
        AVAILABLE=AVAILABLE+PAW_SKALA_SOURCE_CACHE_BYTES(BLOCK_GRID(IAT)%SOURCE(J))
        CALL PAW_SKALA_SOURCE_CACHE_PREPARE(BLOCK_GRID(IAT)%SOURCE(J) &
     &       ,SOURCES(J),GRID_CELL,GRID_INVERSE,GRID_ATOMS(J,:),X &
     &       ,ALLOCATED(FORWARD_DERIV),MAX(0_8,AVAILABLE))
        BYTES=PAW_SKALA_SOURCE_CACHE_BYTES(BLOCK_GRID(IAT)%SOURCE(J))
        AVAILABLE=AVAILABLE-BYTES
        FORWARD_SOURCE_CACHE(3)=FORWARD_SOURCE_CACHE(3)+REAL(BYTES,KIND=8)
      END DO
      END SUBROUTINE SKALA_PREPARE_SOURCE_CACHE

      SUBROUTINE SKALA_RECONSTRUCT(IAT,IP,POINT,BAR,BACK,VALUE,SKIPROWS)
      USE PAW_SKALA_MODULE
      USE PAW_SKALA_PRIMITIVES_MODULE, ONLY: PAW_SKALA_SOURCE_IMAGES
      IMPLICIT NONE
      INTEGER,INTENT(IN) :: IAT,IP
      REAL(8),INTENT(IN) :: POINT(3),BAR(5,2)
      LOGICAL,INTENT(IN) :: BACK
      REAL(8),INTENT(OUT) :: VALUE(5,2)
      INTEGER,INTENT(IN) :: SKIPROWS(SIZE(SOURCES))
      REAL(8) :: V(5,2),DX(3),MOMENT(3,3),CONTRACTION
      INTEGER :: J,JD
      LOGICAL :: HIT
      VALUE=0.D0
      DO J=1,SIZE(SOURCES)
        IF(BACK.AND.IP.LE.SKIPROWS(J)) CYCLE
        IF(BACK) THEN
          IF(ALLOCATED(FORWARD_DERIV)) THEN
            IF(CONFIG_NEEDSTRESS) THEN
              CALL PAW_SKALA_SOURCE_IMAGES(SOURCES(J),GRID_CELL,GRID_INVERSE &
     &             ,GRID_ATOMS(J,:),POINT,V,BAR,DX,MOMENT,CONTRACTION &
     &             ,BLOCK_GRID(IAT)%SOURCE(J),IP,HIT)
            ELSE
              CALL PAW_SKALA_SOURCE_IMAGES(SOURCES(J),GRID_CELL,GRID_INVERSE &
     &             ,GRID_ATOMS(J,:),POINT,V,BAR,DX,DMCONTRACTION=CONTRACTION &
     &             ,CACHE=BLOCK_GRID(IAT)%SOURCE(J),IP=IP,HIT=HIT)
            END IF
            FORWARD_DERIV(:,IAT)=FORWARD_DERIV(:,IAT)+DX
            FORWARD_DERIV(:,J)=FORWARD_DERIV(:,J)-DX
            FORWARD_DERIV_LOCAL_PRIMITIVE(:,IAT)= &
     &          FORWARD_DERIV_LOCAL_PRIMITIVE(:,IAT)+DX
            FORWARD_DERIV_LOCAL_PRIMITIVE(:,J)= &
     &          FORWARD_DERIV_LOCAL_PRIMITIVE(:,J)-DX
            IF(CONFIG_NEEDSTRESS) THEN
              DO JD=1,3
                FORWARD_STRESS_PRIMITIVE(:,JD)=FORWARD_STRESS_PRIMITIVE(:,JD) &
     &                  +DX*GRID_ATOMS(IAT,JD)-MOMENT(:,JD)
              END DO
            END IF
          ELSE
            CALL PAW_SKALA_SOURCE_IMAGES(SOURCES(J),GRID_CELL,GRID_INVERSE &
     &           ,GRID_ATOMS(J,:),POINT,V,BAR,DMCONTRACTION=CONTRACTION &
     &           ,CACHE=BLOCK_GRID(IAT)%SOURCE(J),IP=IP,HIT=HIT)
          END IF
          FORWARD_SOURCE_CONTRACTION=FORWARD_SOURCE_CONTRACTION+CONTRACTION
        ELSE
          CALL PAW_SKALA_SOURCE_IMAGES(SOURCES(J),GRID_CELL,GRID_INVERSE &
     &         ,GRID_ATOMS(J,:),POINT,V,CACHE=BLOCK_GRID(IAT)%SOURCE(J),IP=IP,HIT=HIT)
        END IF
        IF(HIT) THEN
          FORWARD_SOURCE_CACHE(1)=FORWARD_SOURCE_CACHE(1)+1.D0
        ELSE
          FORWARD_SOURCE_CACHE(2)=FORWARD_SOURCE_CACHE(2)+1.D0
        END IF
        VALUE=VALUE+V
      END DO
      END SUBROUTINE SKALA_RECONSTRUCT

#IF DEFINED(CPPVAR_OPENACC)
      SUBROUTINE SKALA_RECONSTRUCT_BATCH(IAT,NPOINT,X,VALUE)
      USE PAW_SKALA_MODULE
      USE PAW_SKALA_PRIMITIVES_MODULE, ONLY: PAW_SKALA_SOURCE_FORWARD_BATCH &
     &     ,PAW_SKALA_SOURCE_IMAGES
      IMPLICIT NONE
      INTEGER,INTENT(IN) :: IAT,NPOINT
      REAL(8),INTENT(IN) :: X(NPOINT,3)
      REAL(8),INTENT(OUT) :: VALUE(5,2,NPOINT)
      REAL(8),ALLOCATABLE :: BATCH(:,:,:)
      REAL(8) :: V(5,2)
      INTEGER :: J,IP,COVERED
      LOGICAL :: HIT,REUSED
      VALUE=0.D0
      DO J=1,SIZE(SOURCES)
        CALL PAW_SKALA_SOURCE_FORWARD_BATCH(BLOCK_GRID(IAT)%SOURCE(J),SOURCES(J),BATCH,COVERED,REUSED)
        IF(COVERED.GT.0) VALUE(:,:,1:COVERED)=VALUE(:,:,1:COVERED)+BATCH
        FORWARD_SOURCE_CACHE(1)=FORWARD_SOURCE_CACHE(1)+REAL(COVERED,KIND=8)
        FORWARD_SOURCE_CACHE(5)=FORWARD_SOURCE_CACHE(5)+REAL(COVERED,KIND=8)
        IF(REUSED) FORWARD_SOURCE_CACHE(6)=FORWARD_SOURCE_CACHE(6)+REAL(COVERED,KIND=8)
        DO IP=COVERED+1,NPOINT
          CALL PAW_SKALA_SOURCE_IMAGES(SOURCES(J),GRID_CELL,GRID_INVERSE &
     &         ,GRID_ATOMS(J,:),X(IP,:),V,CACHE=BLOCK_GRID(IAT)%SOURCE(J),IP=IP,HIT=HIT)
          VALUE(:,:,IP)=VALUE(:,:,IP)+V
          IF(HIT) THEN
            FORWARD_SOURCE_CACHE(1)=FORWARD_SOURCE_CACHE(1)+1.D0
          ELSE
            FORWARD_SOURCE_CACHE(2)=FORWARD_SOURCE_CACHE(2)+1.D0
          END IF
        END DO
      END DO
      END SUBROUTINE SKALA_RECONSTRUCT_BATCH
#ENDIF

      SUBROUTINE SKALA$SYNCSOURCES
      USE PAW_SKALA_MODULE
      USE MPE_MODULE
      IMPLICIT NONE
      INTEGER :: J,NTASKS,THISTASK
      CALL MPE$QUERY('MONOMER',NTASKS,THISTASK)
      DO J=1,SIZE(SOURCES)
        CALL MPE$COMBINE('MONOMER','+',SOURCES(J)%DH)
        IF(THISTASK.EQ.1) THEN
          FORWARD_ONECENTER_ADJOINT_NORM2=FORWARD_ONECENTER_ADJOINT_NORM2 &
     &                                  +SUM(ABS(SOURCES(J)%DH)**2)
          FORWARD_ONECENTER_CONTRACTION=FORWARD_ONECENTER_CONTRACTION &
     &          +REAL(SUM(CONJG(SOURCES(J)%DM)*SOURCES(J)%DH),KIND=8)
        END IF
      END DO
      END SUBROUTINE SKALA$SYNCSOURCES

      SUBROUTINE SKALA$SOURCEDH(IAT,LMNX,NDIMD,DH)
      USE PAW_SKALA_MODULE
      IMPLICIT NONE
      INTEGER,INTENT(IN) :: IAT,LMNX,NDIMD
      COMPLEX(8),INTENT(OUT) :: DH(LMNX,LMNX,NDIMD)
      DH=SOURCES(IAT)%DH
      END SUBROUTINE SKALA$SOURCEDH

      SUBROUTINE SKALA$ATOMFORWARD(IAT)
      USE PAW_SKALA_MODULE
      USE PAW_SKALA_GRID_MODULE
      USE PAW_SKALA_PARTITION_MODULE
      USE PAW_SKALA_PRIMITIVES_MODULE, ONLY: PAW_SKALA_SOURCE_BACK_BATCH &
     &     ,PAW_SKALA_SOURCE_FORWARD_ACTIVE
      USE, INTRINSIC :: IEEE_ARITHMETIC, ONLY: IEEE_IS_FINITE
      IMPLICIT NONE
      INTEGER,INTENT(IN) :: IAT
      INTEGER :: NPOINT,IP,D,IC,J,JD,NDIMD
      INTEGER :: SOURCE_ROWS(SIZE(SOURCES))
      TYPE(PAW_SKALA_PERIODIC_LAYOUT) :: ENERGY_LAYOUT,SELF_LAYOUT
      REAL(8),ALLOCATABLE :: X(:,:),RHO(:,:),GRAD(:,:,:),TAU(:,:)
      REAL(8),ALLOCATABLE :: ARHO(:,:),AGRAD(:,:,:),ATAU(:,:)
      REAL(8),ALLOCATABLE :: AX(:,:),AW(:),AD(:),DE(:,:),DD(:,:)
      REAL(8) :: AC(1,3),ATOM(1,3),ENERGY,POINT(3),V(5,2),BAR(5,2)
      REAL(8) :: RV(2),GV(3,2),TV(2),DR(3,2),DG(3,3,2),DT(3,2)
      REAL(8) :: PRIM(3),MOVE(3),S,WE,WD,BASEW,DC(3)
      REAL(8) :: ME(3,3),MD(3,3)
#IF DEFINED(CPPVAR_OPENACC)
      REAL(8),ALLOCATABLE :: SOURCE_BAR(:,:,:),SOURCE_VALUE(:,:,:)
      REAL(8) :: SOURCE_CONTRACTION
      INTEGER :: SOURCE_STATUS
#ENDIF
      INTEGER(8) :: SIZES(1)
      INTEGER(8) :: CACHE_AVAILABLE
      LOGICAL :: CACHE_HIT,LAYOUT_READY
      INTEGER :: EMPTYINDEX(0)
#IF DEFINED(CPPVAR_ACCEL_PROFILE)
      REAL(8) :: T0,T1,TP,TNEXT,TADJOINT(4)
      CALL ACCELPROFILE$NOW(T0)
      TADJOINT=0.D0
#ENDIF
      CALL SKALA_BUILDGRID(IAT)
      NPOINT=SIZE(BLOCK_GRID(IAT)%W)
      NDIMD=SMOOTH_NDIMD
      ALLOCATE(X(NPOINT,3),RHO(NPOINT,2),GRAD(NPOINT,3,2),TAU(NPOINT,2))
      ALLOCATE(ARHO(NPOINT,2),AGRAD(NPOINT,3,2),ATAU(NPOINT,2))
      ALLOCATE(AX(NPOINT,3),AW(NPOINT),AD(NPOINT))
      ATOM=GRID_ATOMS(IAT:IAT,:)
      DO IC=1,3
        X(:,IC)=BLOCK_GRID(IAT)%X(:,IC)+ATOM(1,IC)
      END DO
      BAR=0.D0
      SOURCE_ROWS=0
      CALL TIMING$CLOCKON('SKALA:RECONSTRUCT')
      CALL SKALA_PREPARE_SOURCE_CACHE(IAT,NPOINT,X)
#IF DEFINED(CPPVAR_OPENACC)
      IF(PAW_SKALA_SOURCE_FORWARD_ACTIVE()) THEN
        ALLOCATE(SOURCE_VALUE(5,2,NPOINT),STAT=SOURCE_STATUS)
        IF(SOURCE_STATUS.EQ.0) CALL SKALA_RECONSTRUCT_BATCH(IAT,NPOINT,X,SOURCE_VALUE)
      END IF
#ENDIF
      DO IP=1,NPOINT
        POINT=X(IP,:)
        CALL PAW_SKALA_GRID_INTERPOLATE_PRIMITIVES &
     &       (SMOOTH_NR1,SMOOTH_NR2,SMOOTH_NR3,SMOOTH_RBAS,NDIMD &
     &       ,SMOOTH_RHO,SMOOTH_GRHO,SMOOTH_TAU,POINT &
     &       ,RV(1:NDIMD),GV(:,1:NDIMD),TV(1:NDIMD))
        DO D=1,2
          RHO(IP,D)=0.5D0*RV(1)
          GRAD(IP,:,D)=0.5D0*GV(:,1)
          TAU(IP,D)=0.5D0*TV(1)
          IF(NDIMD.EQ.2) THEN
            S=MERGE(0.5D0,-0.5D0,D.EQ.1)
            RHO(IP,D)=RHO(IP,D)+S*RV(2)
            GRAD(IP,:,D)=GRAD(IP,:,D)+S*GV(:,2)
            TAU(IP,D)=TAU(IP,D)+S*TV(2)
          END IF
        END DO
        FORWARD_SMOOTH_ELECTRONS=FORWARD_SMOOTH_ELECTRONS &
     &       +BLOCK_GRID(IAT)%W(IP)*SUM(RHO(IP,:))
        FORWARD_SMOOTH_TAU=FORWARD_SMOOTH_TAU &
     &       +BLOCK_GRID(IAT)%W(IP)*SUM(TAU(IP,:))
#IF DEFINED(CPPVAR_OPENACC)
        IF(ALLOCATED(SOURCE_VALUE)) THEN
          V=SOURCE_VALUE(:,:,IP)
        ELSE
#ENDIF
          CALL SKALA_RECONSTRUCT(IAT,IP,POINT,BAR,.FALSE.,V,SOURCE_ROWS)
#IF DEFINED(CPPVAR_OPENACC)
        END IF
#ENDIF
        RHO(IP,:)=RHO(IP,:)+V(1,:)
        GRAD(IP,:,:)=GRAD(IP,:,:)+V(2:4,:)
        TAU(IP,:)=TAU(IP,:)+V(5,:)
        FORWARD_CORRECTION_ELECTRONS=FORWARD_CORRECTION_ELECTRONS &
     &       +BLOCK_GRID(IAT)%W(IP)*SUM(V(1,:))
        FORWARD_CORRECTION_TAU=FORWARD_CORRECTION_TAU &
     &       +BLOCK_GRID(IAT)%W(IP)*SUM(V(5,:))
      END DO
#IF DEFINED(CPPVAR_OPENACC)
      IF(ALLOCATED(SOURCE_VALUE)) DEALLOCATE(SOURCE_VALUE)
#ENDIF
      CALL TIMING$CLOCKOFF('SKALA:RECONSTRUCT')
      SIZES(1)=INT(NPOINT,KIND=8)
      CALL TIMING$CLOCKON('SKALA:MODEL')
      CALL SKALA$EVALUATE(NPOINT,1,RHO,GRAD,TAU,X,BLOCK_GRID(IAT)%W &
     &     ,ATOM,BLOCK_GRID(IAT)%D,SIZES,ENERGY &
     &     ,ARHO,AGRAD,ATAU,AX,AW,AC,AD)
      CALL TIMING$CLOCKOFF('SKALA:MODEL')
      IF(.NOT.IEEE_IS_FINITE(ENERGY).OR.ANY(.NOT.IEEE_IS_FINITE(ARHO)) &
     &   .OR.ANY(.NOT.IEEE_IS_FINITE(AGRAD)).OR.ANY(.NOT.IEEE_IS_FINITE(ATAU)) &
     &   .OR.ANY(.NOT.IEEE_IS_FINITE(AX)).OR.ANY(.NOT.IEEE_IS_FINITE(AW)) &
     &   .OR.ANY(.NOT.IEEE_IS_FINITE(AC)).OR.ANY(.NOT.IEEE_IS_FINITE(AD))) THEN
        CALL ERROR$MSG('NONFINITE SKALA ENERGY OR ADJOINT')
        CALL ERROR$I4VAL('ATOM',IAT)
        CALL ERROR$STOP('SKALA$ATOMFORWARD')
      END IF
      IF(ALLOCATED(FORWARD_DERIV)) THEN
        CACHE_AVAILABLE=PAW_SKALA_PARTITION_CACHE_LIMIT()
        DO J=1,SIZE(BLOCK_GRID)
          IF(J.EQ.IAT) CYCLE
          CACHE_AVAILABLE=CACHE_AVAILABLE &
     &                   -PAW_SKALA_PARTITION_CACHE_BYTES(BLOCK_GRID(J)%PARTITION)
        END DO
        CALL PAW_SKALA_PARTITION_CACHE_PREPARE(BLOCK_GRID(IAT)%PARTITION &
     &       ,GRID_ATOMS,GRID_CELL,CONFIG_IMAGESHELLS,IAT,X &
     &       ,CONFIG_NEEDSTRESS,MAX(0_8,CACHE_AVAILABLE))
        FORWARD_PARTITION_CACHE(3)=FORWARD_PARTITION_CACHE(3) &
     &       +REAL(PAW_SKALA_PARTITION_CACHE_BYTES(BLOCK_GRID(IAT)%PARTITION),KIND=8)
        LAYOUT_READY=.FALSE.
        ALLOCATE(DE(3,SIZE(GRID_ATOMS,1)),DD(3,1))
        FORWARD_DERIV(:,IAT)=FORWARD_DERIV(:,IAT)+AC(1,:)
        FORWARD_DERIV_MODEL_ATOM(:,IAT)= &
     &      FORWARD_DERIV_MODEL_ATOM(:,IAT)+AC(1,:)
        IF(CONFIG_NEEDSTRESS) THEN
          DO JD=1,3
            FORWARD_STRESS_COORDINATE(:,JD)=FORWARD_STRESS_COORDINATE(:,JD) &
     &                                      +AC(1,:)*ATOM(1,JD)
          END DO
        END IF
      END IF
      CALL TIMING$CLOCKON('SKALA:ADJOINT')
#IF DEFINED(CPPVAR_ACCEL_PROFILE)
      CALL ACCELPROFILE$NOW(TP)
#ENDIF
#IF DEFINED(CPPVAR_OPENACC)
      ALLOCATE(SOURCE_BAR(5,2,NPOINT))
      DO IP=1,NPOINT
        SOURCE_BAR(1,:,IP)=ARHO(IP,:)
        SOURCE_BAR(2:4,:,IP)=AGRAD(IP,:,:)
        SOURCE_BAR(5,:,IP)=ATAU(IP,:)
      END DO
      DO J=1,SIZE(SOURCES)
        CALL PAW_SKALA_SOURCE_BACK_BATCH(BLOCK_GRID(IAT)%SOURCE(J),SOURCES(J) &
     &       ,SOURCE_BAR,ALLOCATED(FORWARD_DERIV),CONFIG_NEEDSTRESS &
     &       ,DC,ME,SOURCE_CONTRACTION,SOURCE_ROWS(J))
        FORWARD_SOURCE_CONTRACTION=FORWARD_SOURCE_CONTRACTION+SOURCE_CONTRACTION
        FORWARD_SOURCE_CACHE(1)=FORWARD_SOURCE_CACHE(1)+REAL(SOURCE_ROWS(J),KIND=8)
        FORWARD_SOURCE_CACHE(4)=FORWARD_SOURCE_CACHE(4)+REAL(SOURCE_ROWS(J),KIND=8)
        IF(ALLOCATED(FORWARD_DERIV)) THEN
          FORWARD_DERIV(:,IAT)=FORWARD_DERIV(:,IAT)+DC
          FORWARD_DERIV(:,J)=FORWARD_DERIV(:,J)-DC
          FORWARD_DERIV_LOCAL_PRIMITIVE(:,IAT)=FORWARD_DERIV_LOCAL_PRIMITIVE(:,IAT)+DC
          FORWARD_DERIV_LOCAL_PRIMITIVE(:,J)=FORWARD_DERIV_LOCAL_PRIMITIVE(:,J)-DC
          IF(CONFIG_NEEDSTRESS) THEN
            DO JD=1,3
              FORWARD_STRESS_PRIMITIVE(:,JD)=FORWARD_STRESS_PRIMITIVE(:,JD) &
     &                                      +DC*GRID_ATOMS(IAT,JD)-ME(:,JD)
            END DO
          END IF
        END IF
      END DO
      DEALLOCATE(SOURCE_BAR)
#ENDIF
#IF DEFINED(CPPVAR_ACCEL_PROFILE)
      CALL ACCELPROFILE$NOW(TNEXT)
      TADJOINT(1)=TNEXT-TP
#ENDIF
      DO IP=1,NPOINT
#IF DEFINED(CPPVAR_ACCEL_PROFILE)
        CALL ACCELPROFILE$NOW(TP)
#ENDIF
        POINT=X(IP,:)
        BAR(1,:)=ARHO(IP,:)
        BAR(2:4,:)=AGRAD(IP,:,:)
        BAR(5,:)=ATAU(IP,:)
        CALL SKALA_RECONSTRUCT(IAT,IP,POINT,BAR,.TRUE.,V,SOURCE_ROWS)
#IF DEFINED(CPPVAR_ACCEL_PROFILE)
        CALL ACCELPROFILE$NOW(TNEXT)
        TADJOINT(1)=TADJOINT(1)+(TNEXT-TP)
        TP=TNEXT
#ENDIF
        IF(.NOT.ALLOCATED(FORWARD_DERIV)) CYCLE
        CALL PAW_SKALA_GRID_INTERPOLATE_PRIMITIVES &
     &       (SMOOTH_NR1,SMOOTH_NR2,SMOOTH_NR3,SMOOTH_RBAS,NDIMD &
     &       ,SMOOTH_RHO,SMOOTH_GRHO,SMOOTH_TAU,POINT &
     &       ,RV(1:NDIMD),GV(:,1:NDIMD),TV(1:NDIMD) &
     &       ,DR(:,1:NDIMD),DG(:,:,1:NDIMD),DT(:,1:NDIMD))
        PRIM=0.D0
        DO D=1,NDIMD
          S=MERGE(1.D0,-1.D0,D.EQ.1)
          PRIM=PRIM+0.5D0*(ARHO(IP,1)+S*ARHO(IP,2))*DR(:,D) &
     &             +0.5D0*(ATAU(IP,1)+S*ATAU(IP,2))*DT(:,D)
          DO IC=1,3
            PRIM=PRIM+0.5D0*(AGRAD(IP,IC,1)+S*AGRAD(IP,IC,2))*DG(IC,:,D)
          END DO
        END DO
        MOVE=AX(IP,:)+PRIM
        FORWARD_DERIV(:,IAT)=FORWARD_DERIV(:,IAT)+MOVE
        FORWARD_DERIV_LOCAL_GRID(:,IAT)=FORWARD_DERIV_LOCAL_GRID(:,IAT)+AX(IP,:)
        FORWARD_DERIV_LOCAL_PRIMITIVE(:,IAT)= &
     &      FORWARD_DERIV_LOCAL_PRIMITIVE(:,IAT)+PRIM
        IF(CONFIG_NEEDSTRESS) THEN
          DO JD=1,3
            FORWARD_STRESS_COORDINATE(:,JD)=FORWARD_STRESS_COORDINATE(:,JD) &
     &                                    +AX(IP,:)*ATOM(1,JD)
            FORWARD_STRESS_PRIMITIVE(:,JD)=FORWARD_STRESS_PRIMITIVE(:,JD) &
     &                                    -PRIM*BLOCK_GRID(IAT)%X(IP,JD)
          END DO
        END IF
#IF DEFINED(CPPVAR_ACCEL_PROFILE)
        CALL ACCELPROFILE$NOW(TNEXT)
        TADJOINT(2)=TADJOINT(2)+(TNEXT-TP)
        TP=TNEXT
#ENDIF
        CALL PAW_SKALA_PARTITION_CACHE_GET(BLOCK_GRID(IAT)%PARTITION &
     &       ,IP,DE,ME,WD,DD,MD,CACHE_HIT)
        IF(CACHE_HIT) THEN
          FORWARD_PARTITION_CACHE(1)=FORWARD_PARTITION_CACHE(1)+1.D0
        ELSE
          FORWARD_PARTITION_CACHE(2)=FORWARD_PARTITION_CACHE(2)+1.D0
          IF(.NOT.LAYOUT_READY) THEN
            CALL PAW_SKALA_PERIODIC_INIT(ENERGY_LAYOUT,SIZE(GRID_ATOMS,1) &
     &                                 ,GRID_ATOMS,GRID_CELL,CONFIG_IMAGESHELLS)
            IF(CONFIG_NEEDSTRESS) CALL PAW_SKALA_PERIODIC_INIT(SELF_LAYOUT,1 &
     &                                 ,ATOM,GRID_CELL,CONFIG_IMAGESHELLS)
            LAYOUT_READY=.TRUE.
          END IF
          CALL PAW_SKALA_PERIODIC_WEIGHT(ENERGY_LAYOUT,IAT,POINT,WE,DE,ME)
          IF(CONFIG_NEEDSTRESS) CALL PAW_SKALA_PERIODIC_WEIGHT(SELF_LAYOUT,1,POINT,WD,DD,MD)
          CALL PAW_SKALA_PARTITION_CACHE_PUT(BLOCK_GRID(IAT)%PARTITION,IP,DE,ME,WD,DD,MD)
        END IF
        BASEW=BLOCK_GRID(IAT)%BASEW(IP)
        DO J=1,SIZE(GRID_ATOMS,1)
          DC=BASEW*AW(IP)*DE(:,J)
          FORWARD_DERIV(:,J)=FORWARD_DERIV(:,J)+DC
          FORWARD_DERIV(:,IAT)=FORWARD_DERIV(:,IAT)-DC
          FORWARD_DERIV_LOCAL_PARTITION(:,J)=FORWARD_DERIV_LOCAL_PARTITION(:,J)+DC
          FORWARD_DERIV_LOCAL_PARTITION(:,IAT)=FORWARD_DERIV_LOCAL_PARTITION(:,IAT)-DC
        END DO
        IF(CONFIG_NEEDSTRESS) THEN
          DO JD=1,3
            FORWARD_STRESS_PARTITION(:,JD)=FORWARD_STRESS_PARTITION(:,JD) &
     &        +BASEW*AW(IP)*(ME(:,JD)-SUM(DE,DIM=2)*ATOM(1,JD)) &
     &        +BASEW*AD(IP)*PAW_SKALA_PARTITION_TAPER_DERIVATIVE(WD) &
     &                    *(MD(:,JD)-DD(:,1)*ATOM(1,JD))
          END DO
        END IF
#IF DEFINED(CPPVAR_ACCEL_PROFILE)
        CALL ACCELPROFILE$NOW(TNEXT)
        TADJOINT(3)=TADJOINT(3)+(TNEXT-TP)
#ENDIF
      END DO
#IF DEFINED(CPPVAR_ACCEL_PROFILE)
      CALL ACCELPROFILE$NOW(TP)
#ENDIF
      CALL PAW_SKALA_GRID_BACKPROJECT &
     &     (SMOOTH_NR1,SMOOTH_NR2,SMOOTH_NR3,SMOOTH_RBAS,NDIMD &
     &     ,0,NPOINT,EMPTYINDEX,X,ARHO,AGRAD,ATAU &
     &     ,SMOOTH_ADJ_RHO,SMOOTH_ADJ_GRHO,SMOOTH_ADJ_TAU,TGRIDBACKACC)
#IF DEFINED(CPPVAR_ACCEL_PROFILE)
      CALL ACCELPROFILE$NOW(TNEXT)
      TADJOINT(4)=TNEXT-TP
#ENDIF
      CALL TIMING$CLOCKOFF('SKALA:ADJOINT')
      FORWARD_ENERGY=FORWARD_ENERGY+ENERGY
      FORWARD_ATOM_ENERGY(IAT)=ENERGY
      FORWARD_ATOM_NPOINT(IAT)=NPOINT
      FORWARD_ELECTRONS=FORWARD_ELECTRONS+SUM(BLOCK_GRID(IAT)%W*SUM(RHO,DIM=2))
      FORWARD_TAU=FORWARD_TAU+SUM(BLOCK_GRID(IAT)%W*SUM(TAU,DIM=2))
      FORWARD_NPOINT=FORWARD_NPOINT+NPOINT
      FORWARD_VOLUME=FORWARD_VOLUME+SUM(BLOCK_GRID(IAT)%W)
#IF DEFINED(CPPVAR_ACCEL_PROFILE)
      CALL ACCELPROFILE$NOW(T1)
      CALL ACCELPROFILE$ADD('SKALA_ATOM_COMPOSITE' &
     &     ,INT(NPOINT,KIND=8),INT(IAT,KIND=8),0_8,0_8,0.D0,0.D0,T1-T0)
      CALL ACCELPROFILE$ADD('SKALA_ADJOINT_SOURCE' &
     &     ,INT(NPOINT,KIND=8),INT(IAT,KIND=8),0_8,0_8,0.D0,0.D0,TADJOINT(1))
      IF(ALLOCATED(FORWARD_DERIV)) THEN
        CALL ACCELPROFILE$ADD('SKALA_ADJOINT_INTERPOLATION' &
     &     ,INT(NPOINT,KIND=8),INT(IAT,KIND=8),0_8,0_8,0.D0,0.D0,TADJOINT(2))
        CALL ACCELPROFILE$ADD('SKALA_ADJOINT_PARTITION' &
     &     ,INT(NPOINT,KIND=8),INT(IAT,KIND=8),0_8,0_8,0.D0,0.D0,TADJOINT(3))
      END IF
      CALL ACCELPROFILE$ADD('SKALA_ADJOINT_SCATTER' &
     &     ,INT(NPOINT,KIND=8),INT(IAT,KIND=8),0_8,0_8,0.D0,0.D0,TADJOINT(4))
#ENDIF
      END SUBROUTINE SKALA$ATOMFORWARD

!     ..................................................................

!     ..................................................................
      SUBROUTINE SKALA$FORWARDEND
      USE PAW_SKALA_MODULE
      USE PAW_SKALA_GRID_MODULE, ONLY: PAW_SKALA_GRID_BACK_END
      USE MPE_MODULE
      IMPLICIT NONE
      INTEGER(4) :: NTASKS,THISTASK,NFIL,NAT,I,IDIR,JDIR
      REAL(8) :: RHONORM,GRADNORM,TAUNORM,NETFORCE(3)
      REAL(8) :: PRIMITIVECONTRACTION,CELLVOLUME,VOLUMEERROR
      REAL(8),ALLOCATABLE :: FORCE(:,:)
#IF DEFINED(CPPVAR_ACCEL_PROFILE)
      REAL(8) :: ACCEL_T0,ACCEL_T1,GRID_BACK_BYTES
#ENDIF

      IF(.NOT.TON) RETURN
      IF(TGRIDBACKACC) THEN
#IF DEFINED(CPPVAR_ACCEL_PROFILE)
        CALL ACCELPROFILE$NOW(ACCEL_T0)
#ENDIF
        CALL PAW_SKALA_GRID_BACK_END(SMOOTH_NR1,SMOOTH_NR2,SMOOTH_NR3 &
     &                              ,SMOOTH_NDIMD,SMOOTH_ADJ_RHO &
     &                              ,SMOOTH_ADJ_GRHO,SMOOTH_ADJ_TAU &
     &                              ,TGRIDBACKACC)
#IF DEFINED(CPPVAR_ACCEL_PROFILE)
        CALL ACCELPROFILE$NOW(ACCEL_T1)
        GRID_BACK_BYTES=40.D0*REAL(SMOOTH_NR1,KIND=8) &
     &                         *REAL(SMOOTH_NR2,KIND=8) &
     &                         *REAL(SMOOTH_NR3,KIND=8) &
     &                         *REAL(SMOOTH_NDIMD,KIND=8)
        CALL ACCELPROFILE$ADD('ACC_COPY_SKALA_GRID_BACK_OUT' &
     &      ,INT(SMOOTH_NR1,KIND=8),INT(SMOOTH_NR2,KIND=8) &
     &      ,INT(SMOOTH_NR3,KIND=8),INT(SMOOTH_NDIMD,KIND=8) &
     &      ,0.D0,GRID_BACK_BYTES,ACCEL_T1-ACCEL_T0)
#ENDIF
      END IF
      CALL MPE$COMBINE('MONOMER','+',FORWARD_ENERGY)
      CALL MPE$COMBINE('MONOMER','+',FORWARD_ELECTRONS)
      CALL MPE$COMBINE('MONOMER','+',FORWARD_TAU)
      CALL MPE$COMBINE('MONOMER','+',FORWARD_SMOOTH_ELECTRONS)
      CALL MPE$COMBINE('MONOMER','+',FORWARD_CORRECTION_ELECTRONS)
      CALL MPE$COMBINE('MONOMER','+',FORWARD_SMOOTH_TAU)
      CALL MPE$COMBINE('MONOMER','+',FORWARD_CORRECTION_TAU)
      CALL MPE$COMBINE('MONOMER','+',FORWARD_ONECENTER_ADJOINT_NORM2)
      CALL MPE$COMBINE('MONOMER','+',FORWARD_ONECENTER_CONTRACTION)
      CALL MPE$COMBINE('MONOMER','+',FORWARD_SOURCE_CONTRACTION)
      CALL MPE$COMBINE('MONOMER','+',FORWARD_NPOINT)
      CALL MPE$COMBINE('MONOMER','+',FORWARD_PARTITION_CACHE)
      CALL MPE$COMBINE('MONOMER','+',FORWARD_SOURCE_CACHE)
      CALL MPE$COMBINE('MONOMER','+',FORWARD_VOLUME)
      CALL MPE$COMBINE('MONOMER','+',FORWARD_ATOM_ENERGY)
      CALL MPE$COMBINE('MONOMER','+',FORWARD_ATOM_NPOINT)
      CALL MPE$COMBINE('MONOMER','+',SMOOTH_ADJ_RHO)
      CALL MPE$COMBINE('MONOMER','+',SMOOTH_ADJ_GRHO)
      CALL MPE$COMBINE('MONOMER','+',SMOOTH_ADJ_TAU)
      CALL MPE$QUERY('MONOMER',NTASKS,THISTASK)
      ONECENTER_CONTRACTION=FORWARD_ONECENTER_CONTRACTION
      TONECENTERCONTRACTIONREADY=.TRUE.
      IF(ALLOCATED(FORWARD_DERIV)) THEN
        CALL MPE$COMBINE('MONOMER','+',FORWARD_DERIV)
        CALL MPE$COMBINE('MONOMER','+',FORWARD_DERIV_MODEL_ATOM)
        CALL MPE$COMBINE('MONOMER','+',FORWARD_DERIV_LOCAL_GRID)
        CALL MPE$COMBINE('MONOMER','+',FORWARD_DERIV_LOCAL_PRIMITIVE)
        CALL MPE$COMBINE('MONOMER','+',FORWARD_DERIV_LOCAL_PARTITION)
        IF(CONFIG_NEEDSTRESS) THEN
          CALL MPE$COMBINE('MONOMER','+',FORWARD_STRESS_WEIGHT)
          CALL MPE$COMBINE('MONOMER','+',FORWARD_STRESS_PRIMITIVE)
          CALL MPE$COMBINE('MONOMER','+',FORWARD_STRESS_COORDINATE)
          CALL MPE$COMBINE('MONOMER','+',FORWARD_STRESS_PARTITION)
          CALL MPE$COMBINE('MONOMER','+',FORWARD_STRESS_BLEND)
        END IF
        NAT=SIZE(FORWARD_DERIV,2)
        IF(THISTASK.EQ.1) THEN
          IF(CONFIG_NEEDSTRESS) THEN
            PRIMITIVECONTRACTION=SUM(SMOOTH_ADJ_RHO*SMOOTH_RHO) &
     &                          +SUM(SMOOTH_ADJ_GRHO*SMOOTH_GRHO) &
     &                          +SUM(SMOOTH_ADJ_TAU*SMOOTH_TAU)
            DO IDIR=1,3
              FORWARD_STRESS_PRIMITIVE(IDIR,IDIR)= &
     &          FORWARD_STRESS_PRIMITIVE(IDIR,IDIR) &
     &         -PRIMITIVECONTRACTION
              DO JDIR=1,3
                FORWARD_STRESS_PRIMITIVE(IDIR,JDIR)= &
     &            FORWARD_STRESS_PRIMITIVE(IDIR,JDIR) &
     &           -SUM(SMOOTH_ADJ_GRHO(:,:,:,JDIR,:) &
     &               *SMOOTH_GRHO(:,:,:,IDIR,:))
              END DO
            END DO
          END IF
        END IF
        CALL MPE$BROADCAST('MONOMER',1,FORWARD_DERIV)
        IF(CONFIG_NEEDFORCE) THEN
          ALLOCATE(FORCE(3,NAT))
          CALL ATOMLIST$GETR8A('FORCE',0,3*NAT,FORCE)
          FORCE=FORCE-FORWARD_DERIV
          CALL ATOMLIST$SETR8A('FORCE',0,3*NAT,FORCE)
          DEALLOCATE(FORCE)
        END IF
        IF(CONFIG_NEEDSTRESS) THEN
          CALL MPE$BROADCAST('MONOMER',1,FORWARD_STRESS_WEIGHT)
          CALL MPE$BROADCAST('MONOMER',1,FORWARD_STRESS_PRIMITIVE)
          CALL MPE$BROADCAST('MONOMER',1,FORWARD_STRESS_COORDINATE)
          CALL MPE$BROADCAST('MONOMER',1,FORWARD_STRESS_PARTITION)
          CALL MPE$BROADCAST('MONOMER',1,FORWARD_STRESS_BLEND)
          FORWARD_STRESS=FORWARD_STRESS_WEIGHT+FORWARD_STRESS_PRIMITIVE &
     &                  +FORWARD_STRESS_COORDINATE &
     &                  +FORWARD_STRESS_PARTITION+FORWARD_STRESS_BLEND
          TSTRESSREADY=.TRUE.
        END IF
      END IF
      IF(SMOOTH_DVOL.LE.0.D0) THEN
        CALL ERROR$MSG('SKALA SMOOTH GRID VOLUME IS INVALID')
        CALL ERROR$STOP('SKALA$FORWARDEND')
      END IF
      SMOOTH_ADJ_RHO=SMOOTH_ADJ_RHO/SMOOTH_DVOL
      SMOOTH_ADJ_GRHO=SMOOTH_ADJ_GRHO/SMOOTH_DVOL
      SMOOTH_ADJ_TAU=SMOOTH_ADJ_TAU/SMOOTH_DVOL
      RHONORM=SQRT(SUM(SMOOTH_ADJ_RHO**2))
      GRADNORM=SQRT(SUM(SMOOTH_ADJ_GRHO**2))
      TAUNORM=SQRT(SUM(SMOOTH_ADJ_TAU**2))
      IF(CONFIG_APPLY) THEN
        CALL ENERGYLIST$ADD('TOTAL ENERGY',FORWARD_ENERGY)
        CALL ENERGYLIST$ADD('AE  EXCHANGE-CORRELATION',FORWARD_ENERGY)
        CALL ENERGYLIST$ADD('PS  EXCHANGE-CORRELATION',FORWARD_ENERGY)
      END IF
      IF(THISTASK.EQ.1.AND.(CONFIG_CHECK.OR..NOT.TFORWARDREPORTED)) THEN
        CALL FILEHANDLER$UNIT('PROT',NFIL)
        WRITE(NFIL,FMT='(/"SKALA COMPLETE PAW ATOM BLOCKS"/30("="))')
        WRITE(NFIL,FMT='("ATOM-GRID ROWS",T34,I12)')FORWARD_NPOINT
        IF(CONFIG_CHECK) THEN
          WRITE(NFIL,'(A,T34,I18)')'PARTITION CACHE HITS',INT(FORWARD_PARTITION_CACHE(1),KIND=8)
          WRITE(NFIL,'(A,T34,I18)')'PARTITION CACHE MISSES',INT(FORWARD_PARTITION_CACHE(2),KIND=8)
          WRITE(NFIL,'(A,T34,I18)')'PARTITION CACHE BYTES ALL RANKS',INT(FORWARD_PARTITION_CACHE(3),KIND=8)
          WRITE(NFIL,'(A,T34,I18)')'SOURCE CACHE HITS',INT(FORWARD_SOURCE_CACHE(1),KIND=8)
          WRITE(NFIL,'(A,T34,I18)')'SOURCE CACHE MISSES',INT(FORWARD_SOURCE_CACHE(2),KIND=8)
          WRITE(NFIL,'(A,T34,I18)')'SOURCE CACHE BYTES ALL RANKS',INT(FORWARD_SOURCE_CACHE(3),KIND=8)
          WRITE(NFIL,'(A,T34,I18)')'SOURCE GPU REVERSE ROWS',INT(FORWARD_SOURCE_CACHE(4),KIND=8)
          WRITE(NFIL,'(A,T34,I18)')'SOURCE GPU FORWARD ROWS',INT(FORWARD_SOURCE_CACHE(5),KIND=8)
          WRITE(NFIL,'(A,T34,I18)')'SOURCE GPU REUSED ROWS',INT(FORWARD_SOURCE_CACHE(6),KIND=8)
        END IF
        WRITE(NFIL,FMT='("SOURCE RECONSTRUCTION",T34,A)')'ALL ATOMS AND IMAGES'
        WRITE(NFIL,FMT='("DESCRIPTOR WINDOW",T34,A)')'SELF IMAGES ONLY'
        WRITE(NFIL,FMT='("PERIODIC PARTITION",T34,A)')'COMPACT PERIODIZED BECKE'
        CELLVOLUME=SMOOTH_DVOL*REAL(SMOOTH_NR1,KIND=8) &
     &                       *REAL(SMOOTH_NR2,KIND=8)*REAL(SMOOTH_NR3,KIND=8)
        VOLUMEERROR=(FORWARD_VOLUME-CELLVOLUME)/CELLVOLUME
        WRITE(NFIL,FMT='("PARTITION VOLUME",T34,ES24.14)')FORWARD_VOLUME
        WRITE(NFIL,FMT='("EXACT CELL VOLUME",T34,ES24.14)')CELLVOLUME
        WRITE(NFIL,FMT='("PARTITION VOLUME RELATIVE ERROR",T34,ES24.14)')VOLUMEERROR
        IF(ABS(VOLUMEERROR).GT.1.D-4) THEN
          WRITE(NFIL,FMT='(A)')'WARNING: SKALA PERIODIC QUADRATURE IS NOT CONVERGED'
          WRITE(NFIL,FMT='(A)')'CONVERGE IMAGESHELLS AND RADIAL/ANGULAR GRID INDEPENDENTLY'
        END IF
        WRITE(NFIL,FMT='("SMOOTH ELECTRONS",T34,ES24.14)') &
     &       FORWARD_SMOOTH_ELECTRONS
        WRITE(NFIL,FMT='("AE-PS ELECTRONS",T34,ES24.14)') &
     &       FORWARD_CORRECTION_ELECTRONS
        WRITE(NFIL,FMT='("COMPOSITE ELECTRONS",T34,ES24.14)')FORWARD_ELECTRONS
        IF(CONFIG_CHECK.AND.TELECTRONREFERENCE) THEN
          WRITE(NFIL,'(A,T34,ES24.14)')'PAW ALL ELECTRON TRACE',ELECTRON_REFERENCE
          WRITE(NFIL,'(A,T34,ES24.14)')'COMPOSITE MINUS TRACE' &
     &                             ,FORWARD_ELECTRONS-ELECTRON_REFERENCE
        END IF
        WRITE(NFIL,FMT='("SMOOTH POSITIVE TAU",T34,ES24.14)')FORWARD_SMOOTH_TAU
        WRITE(NFIL,FMT='("AE-PS POSITIVE TAU",T34,ES24.14)') &
     &       FORWARD_CORRECTION_TAU
        WRITE(NFIL,FMT='("COMPOSITE POSITIVE TAU",T34,ES24.14)')FORWARD_TAU
        WRITE(NFIL,FMT='("MODEL XC ENERGY",T34,ES24.14)')FORWARD_ENERGY
        IF(CONFIG_CHECK) THEN
          DO I=1,SIZE(FORWARD_ATOM_ENERGY)
            WRITE(NFIL,FMT='("ATOM BLOCK",I6," ROWS",I10 &
     &                    ," ENERGY",ES24.14)') &
     &           I,FORWARD_ATOM_NPOINT(I),FORWARD_ATOM_ENERGY(I)
          END DO
        END IF
        WRITE(NFIL,FMT='("SMOOTH GRID DVOL",T34,ES24.14)')SMOOTH_DVOL
        WRITE(NFIL,FMT='("SMOOTH RHO ADJOINT L2",T34,ES24.14)')RHONORM
        WRITE(NFIL,FMT='("SMOOTH GRAD ADJOINT L2",T34,ES24.14)')GRADNORM
        WRITE(NFIL,FMT='("SMOOTH TAU ADJOINT L2",T34,ES24.14)')TAUNORM
        WRITE(NFIL,FMT='("ONE-CENTER ADJOINT L2",T34,ES24.14)') &
     &       SQRT(FORWARD_ONECENTER_ADJOINT_NORM2)
        WRITE(NFIL,FMT='("ONE-CENTER MATRIX DIFFERENCE",T36,ES24.14)') &
     &       FORWARD_ONECENTER_CONTRACTION-FORWARD_SOURCE_CONTRACTION
        IF(ALLOCATED(FORWARD_DERIV)) THEN
          NETFORCE=-SUM(FORWARD_DERIV,DIM=2)
          WRITE(NFIL,FMT='("SKALA FORCE L2",T34,ES24.14)') &
     &         SQRT(SUM(FORWARD_DERIV**2))
          WRITE(NFIL,FMT='("SKALA NET FORCE",T34,3ES16.7)')NETFORCE
          IF(CONFIG_CHECK) THEN
            DO I=1,SIZE(FORWARD_DERIV,2)
              WRITE(NFIL,FMT='("SKALA FORCE ATOM",I6,3ES24.14)') &
     &             I,-FORWARD_DERIV(:,I)
              WRITE(NFIL,FMT='("MODEL COORD FORCE ATOM",I6,3ES24.14)') &
     &             I,-FORWARD_DERIV_MODEL_ATOM(:,I)
              WRITE(NFIL,FMT='("LOCAL GRID FORCE ATOM",I6,3ES24.14)') &
     &             I,-FORWARD_DERIV_LOCAL_GRID(:,I)
              WRITE(NFIL,FMT='("LOCAL PRIMITIVE FORCE ATOM",I6 &
     &                    ,3ES24.14)') &
     &             I,-FORWARD_DERIV_LOCAL_PRIMITIVE(:,I)
              WRITE(NFIL,FMT='("LOCAL PARTITION FORCE ATOM",I6 &
     &                    ,3ES24.14)') &
     &             I,-FORWARD_DERIV_LOCAL_PARTITION(:,I)
            END DO
          END IF
          WRITE(NFIL,FMT='("MODEL ATOM FORCE L2",T34,ES24.14)') &
     &         SQRT(SUM(FORWARD_DERIV_MODEL_ATOM**2))
          NETFORCE=-SUM(FORWARD_DERIV_MODEL_ATOM,DIM=2)
          WRITE(NFIL,FMT='("MODEL ATOM NET FORCE",T34,3ES16.7)')NETFORCE
          WRITE(NFIL,FMT='("LOCAL GRID FORCE L2",T34,ES24.14)') &
     &         SQRT(SUM(FORWARD_DERIV_LOCAL_GRID**2))
          NETFORCE=-SUM(FORWARD_DERIV_LOCAL_GRID,DIM=2)
          WRITE(NFIL,FMT='("LOCAL GRID NET FORCE",T34,3ES16.7)')NETFORCE
          WRITE(NFIL,FMT='("LOCAL PRIMITIVE FORCE L2",T34,ES24.14)') &
     &         SQRT(SUM(FORWARD_DERIV_LOCAL_PRIMITIVE**2))
          NETFORCE=-SUM(FORWARD_DERIV_LOCAL_PRIMITIVE,DIM=2)
          WRITE(NFIL,FMT='("LOCAL PRIMITIVE NET FORCE",T34,3ES16.7)')NETFORCE
          WRITE(NFIL,FMT='("LOCAL PARTITION FORCE L2",T34,ES24.14)') &
     &         SQRT(SUM(FORWARD_DERIV_LOCAL_PARTITION**2))
          NETFORCE=-SUM(FORWARD_DERIV_LOCAL_PARTITION,DIM=2)
          WRITE(NFIL,FMT='("LOCAL PARTITION NET FORCE",T34,3ES16.7)')NETFORCE
        END IF
        IF(CONFIG_NEEDSTRESS) THEN
          WRITE(NFIL,FMT='("SKALA MODEL D E / D STRAIN")')
          DO I=1,3
            WRITE(NFIL,FMT='("SKALA STRESS",3ES24.14)') &
     &           FORWARD_STRESS(I,:)
          END DO
          IF(CONFIG_CHECK) THEN
            DO I=1,3
              WRITE(NFIL,FMT='("SKALA WEIGHT STRESS",3ES24.14)') &
     &             FORWARD_STRESS_WEIGHT(I,:)
              WRITE(NFIL,FMT='("SKALA PRIMITIVE STRESS",3ES24.14)') &
     &             FORWARD_STRESS_PRIMITIVE(I,:)
              WRITE(NFIL,FMT='("SKALA COORDINATE STRESS",3ES24.14)') &
     &             FORWARD_STRESS_COORDINATE(I,:)
              WRITE(NFIL,FMT='("SKALA PARTITION STRESS",3ES24.14)') &
     &             FORWARD_STRESS_PARTITION(I,:)
              WRITE(NFIL,FMT='("SKALA BLEND STRESS",3ES24.14)') &
     &             FORWARD_STRESS_BLEND(I,:)
            END DO
          END IF
        END IF
      END IF
      TFORWARDREPORTED=.TRUE.
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$STRESSGET(STRESS)
      USE PAW_SKALA_MODULE
      IMPLICIT NONE
      REAL(8),INTENT(OUT) :: STRESS(3,3)

      STRESS=0.D0
      IF(.NOT.TON.OR..NOT.CONFIG_APPLY.OR..NOT.CONFIG_NEEDSTRESS) RETURN
      IF(.NOT.TSTRESSREADY) THEN
        CALL ERROR$MSG('SKALA MODEL STRESS IS NOT AVAILABLE')
        CALL ERROR$STOP('SKALA$STRESSGET')
      END IF
      STRESS=FORWARD_STRESS
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$TOTALFORCEREPORT(NAT,FORCE)
      USE PAW_SKALA_MODULE
      USE MPE_MODULE
      IMPLICIT NONE
      INTEGER(4),INTENT(IN) :: NAT
      REAL(8),INTENT(IN) :: FORCE(3,NAT)
      INTEGER(4) :: NTASKS,THISTASK,NFIL,IAT
      REAL(8) :: ETOT

      IF(.NOT.TON) RETURN
      IF(.NOT.CONFIG_APPLY.AND..NOT.CONFIG_CHECK) RETURN
      CALL MPE$QUERY('MONOMER',NTASKS,THISTASK)
      IF(THISTASK.NE.1) RETURN
      CALL FILEHANDLER$UNIT('PROT',NFIL)
      CALL ENERGYLIST$GET('TOTAL ENERGY',ETOT)
      IF(.NOT.CONFIG_NEEDFORCE) THEN
        WRITE(NFIL,'(/A)')'SKALA TOTAL ENERGY DIAGNOSTIC'
        WRITE(NFIL,'(A,T20,ES26.16)')'TOTAL ENERGY',ETOT
        WRITE(NFIL,'(A)')'NUCLEAR FORCES NOT CALCULATED'
        RETURN
      END IF
      WRITE(NFIL,FMT='(/"SKALA TOTAL FORCE DIAGNOSTIC"/28("="))')
      WRITE(NFIL,FMT='("TOTAL ENERGY",T20,ES26.16)')ETOT
      DO IAT=1,NAT
        WRITE(NFIL,FMT='("ATOM",I6,3ES24.14)')IAT,FORCE(:,IAT)
      END DO
      WRITE(NFIL,FMT='("NET FORCE",T12,3ES24.14)')SUM(FORCE,DIM=2)
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$TOTALSTRESSREPORT(MODELSTRESS,CORESTRESS &
     &                                  ,TAUSTRESS,TOTALSTRESS &
     &                                  ,KINETICSTRESS,PROJECTORSTRESS,OTHERSTRESS)
      USE PAW_SKALA_MODULE
      USE MPE_MODULE
      IMPLICIT NONE
      REAL(8),INTENT(IN) :: MODELSTRESS(3,3)
      REAL(8),INTENT(IN) :: CORESTRESS(3,3)
      REAL(8),INTENT(IN) :: TAUSTRESS(3,3)
      REAL(8),INTENT(IN) :: TOTALSTRESS(3,3)
      REAL(8),INTENT(IN) :: KINETICSTRESS(3,3),PROJECTORSTRESS(3,3),OTHERSTRESS(3,3)
      INTEGER(4) :: NTASKS,THISTASK,NFIL,I

      IF(.NOT.TON.OR..NOT.CONFIG_NEEDSTRESS) RETURN
      IF(.NOT.CONFIG_APPLY.AND..NOT.CONFIG_CHECK) RETURN
      CALL MPE$QUERY('MONOMER',NTASKS,THISTASK)
      IF(THISTASK.NE.1) RETURN
      CALL FILEHANDLER$UNIT('PROT',NFIL)
      WRITE(NFIL,FMT='(/"SKALA TOTAL STRESS DIAGNOSTIC"/29("="))')
      DO I=1,3
        WRITE(NFIL,FMT='("SKALA MODEL D E / D STRAIN",3ES24.14)') &
     &       MODELSTRESS(I,:)
      END DO
      DO I=1,3
        WRITE(NFIL,FMT='("SKALA CORE D E / D STRAIN",3ES24.14)') &
     &       CORESTRESS(I,:)
      END DO
      DO I=1,3
        WRITE(NFIL,FMT='("SKALA TAU D E / D STRAIN",3ES24.14)') &
     &       TAUSTRESS(I,:)
      END DO
      IF(CONFIG_CHECK) THEN
        DO I=1,3
          WRITE(NFIL,FMT='("PAW KINETIC D E / D STRAIN",3ES24.14)')KINETICSTRESS(I,:)
          WRITE(NFIL,FMT='("PAW PROJECTOR D E / D STRAIN",3ES24.14)')PROJECTORSTRESS(I,:)
          WRITE(NFIL,FMT='("PAW OTHER D E / D STRAIN",3ES24.14)')OTHERSTRESS(I,:)
        END DO
      END IF
      DO I=1,3
        WRITE(NFIL,FMT='("TOTAL D E / D STRAIN",3ES24.14)') &
     &       TOTALSTRESS(I,:)
      END DO
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$SMOOTHADJOINTGET(NR1START,NR1L,NR1,NR2,NR3 &
     &                                  ,NDIMD,VRHO,VGRAD,VTAU)
      USE PAW_SKALA_MODULE
      IMPLICIT NONE
      INTEGER(4),INTENT(IN) :: NR1START,NR1L,NR1,NR2,NR3,NDIMD
      REAL(8),INTENT(OUT) :: VRHO(NR1L*NR2*NR3,NDIMD)
      REAL(8),INTENT(OUT) :: VGRAD(NR1L*NR2*NR3,3,NDIMD)
      REAL(8),INTENT(OUT) :: VTAU(NR1L*NR2*NR3,NDIMD)
      INTEGER(4) :: IEND,IDIM,ICART

      IF(.NOT.ALLOCATED(SMOOTH_ADJ_RHO) &
     &   .OR..NOT.ALLOCATED(SMOOTH_ADJ_GRHO) &
     &   .OR..NOT.ALLOCATED(SMOOTH_ADJ_TAU)) THEN
        CALL ERROR$MSG('SKALA SMOOTH ADJOINTS ARE NOT AVAILABLE')
        CALL ERROR$STOP('SKALA$SMOOTHADJOINTGET')
      END IF
      IEND=NR1START+NR1L-1
      IF(NR1.NE.SMOOTH_NR1.OR.NR2.NE.SMOOTH_NR2 &
     &   .OR.NR3.NE.SMOOTH_NR3.OR.NDIMD.NE.SMOOTH_NDIMD &
     &   .OR.NR1START.LT.1.OR.IEND.GT.NR1) THEN
        CALL ERROR$MSG('SKALA SMOOTH ADJOINT GRID IS INCONSISTENT')
        CALL ERROR$I4VAL('NR1',NR1)
        CALL ERROR$I4VAL('CACHED NR1',SMOOTH_NR1)
        CALL ERROR$I4VAL('NR1START',NR1START)
        CALL ERROR$I4VAL('NR1L',NR1L)
        CALL ERROR$STOP('SKALA$SMOOTHADJOINTGET')
      END IF
      DO IDIM=1,NDIMD
        VRHO(:,IDIM)=RESHAPE(SMOOTH_ADJ_RHO(NR1START:IEND,:,:,IDIM) &
     &                      ,(/NR1L*NR2*NR3/))
        VTAU(:,IDIM)=RESHAPE(SMOOTH_ADJ_TAU(NR1START:IEND,:,:,IDIM) &
     &                      ,(/NR1L*NR2*NR3/))
        DO ICART=1,3
          VGRAD(:,ICART,IDIM)=RESHAPE &
     &       (SMOOTH_ADJ_GRHO(NR1START:IEND,:,:,ICART,IDIM) &
     &       ,(/NR1L*NR2*NR3/))
        END DO
      END DO
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$SMOOTHFIELDSGET(NR1START,NR1L,NR1,NR2,NR3 &
     &                                 ,NDIMD,RHO,GRHO,TAU,DVOL)
      USE PAW_SKALA_MODULE
      IMPLICIT NONE
      INTEGER(4),INTENT(IN) :: NR1START,NR1L,NR1,NR2,NR3,NDIMD
      REAL(8),INTENT(OUT) :: RHO(NR1L*NR2*NR3,NDIMD)
      REAL(8),INTENT(OUT) :: GRHO(NR1L*NR2*NR3,3,NDIMD)
      REAL(8),INTENT(OUT) :: TAU(NR1L*NR2*NR3,NDIMD),DVOL
      INTEGER(4) :: IEND,IDIM,ICART

      IF(.NOT.TSMOOTHREADY) THEN
        CALL ERROR$MSG('SKALA SMOOTH FIELDS ARE NOT AVAILABLE')
        CALL ERROR$STOP('SKALA$SMOOTHFIELDSGET')
      END IF
      IEND=NR1START+NR1L-1
      IF(NR1.NE.SMOOTH_NR1.OR.NR2.NE.SMOOTH_NR2 &
     &   .OR.NR3.NE.SMOOTH_NR3.OR.NDIMD.NE.SMOOTH_NDIMD &
     &   .OR.NR1START.LT.1.OR.IEND.GT.NR1) THEN
        CALL ERROR$MSG('SKALA SMOOTH FIELD GRID IS INCONSISTENT')
        CALL ERROR$STOP('SKALA$SMOOTHFIELDSGET')
      END IF
      DO IDIM=1,NDIMD
        RHO(:,IDIM)=RESHAPE(SMOOTH_RHO(NR1START:IEND,:,:,IDIM) &
     &                     ,(/NR1L*NR2*NR3/))
        TAU(:,IDIM)=RESHAPE(SMOOTH_TAU(NR1START:IEND,:,:,IDIM) &
     &                     ,(/NR1L*NR2*NR3/))
        DO ICART=1,3
          GRHO(:,ICART,IDIM)=RESHAPE &
     &       (SMOOTH_GRHO(NR1START:IEND,:,:,ICART,IDIM) &
     &       ,(/NR1L*NR2*NR3/))
        END DO
      END DO
      DVOL=SMOOTH_DVOL
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$SMOOTHSCALARCONTRACTION(VAL)
      USE PAW_SKALA_MODULE
      USE MPE_MODULE
      IMPLICIT NONE
      REAL(8),INTENT(IN) :: VAL

      SMOOTH_SCALAR_CONTRACTION=VAL
      CALL MPE$COMBINE('MONOMER','+',SMOOTH_SCALAR_CONTRACTION)
      TSCALARCONTRACTIONREADY=.TRUE.
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$SMOOTHOPERATORCHECK(LEFT,RIGHT,TAUCONTR)
      USE PAW_SKALA_MODULE
      USE MPE_MODULE
      IMPLICIT NONE
      REAL(8),INTENT(IN) :: LEFT,RIGHT,TAUCONTR
      REAL(8) :: LEFT1,RIGHT1,TAUCONTR1
      INTEGER(4) :: NTASKS,THISTASK,NFIL

      LEFT1=LEFT
      RIGHT1=RIGHT
      TAUCONTR1=TAUCONTR
      CALL MPE$COMBINE('MONOMER','+',LEFT1)
      CALL MPE$COMBINE('MONOMER','+',RIGHT1)
      CALL MPE$COMBINE('MONOMER','+',TAUCONTR1)
      SMOOTH_TAU_CONTRACTION=TAUCONTR1
      TTAUCONTRACTIONREADY=.TRUE.
      CALL MPE$QUERY('MONOMER',NTASKS,THISTASK)
      IF(THISTASK.EQ.1) THEN
        CALL FILEHANDLER$UNIT('PROT',NFIL)
        WRITE(NFIL,FMT='("SMOOTH OPERATOR CONTRACTION",T34,ES24.14)')LEFT1
        WRITE(NFIL,FMT='("PRIMITIVE GRAD CONTRACTION",T34,ES24.14)')RIGHT1
        WRITE(NFIL,FMT='("GRAD ADJOINT DIFFERENCE",T34,ES24.14)')LEFT1-RIGHT1
        WRITE(NFIL,FMT='("TAU ADJOINT CONTRACTION",T34,ES24.14)')TAUCONTR1
      END IF
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$TAUOPERATORCHECK(EXPECTATION)
      USE PAW_SKALA_MODULE
      USE MPE_MODULE
      IMPLICIT NONE
      REAL(8),INTENT(IN) :: EXPECTATION
      REAL(8) :: EXPECTATION1,TOTAL
      INTEGER(4) :: NTASKS,THISTASK,NFIL

      IF(.NOT.TTAUCONTRACTIONREADY) THEN
        CALL ERROR$MSG('SKALA TAU CONTRACTION IS NOT AVAILABLE')
        CALL ERROR$STOP('SKALA$TAUOPERATORCHECK')
      END IF
      IF(.NOT.TSCALARCONTRACTIONREADY) THEN
        CALL ERROR$MSG('SKALA SCALAR CONTRACTION IS NOT AVAILABLE')
        CALL ERROR$STOP('SKALA$TAUOPERATORCHECK')
      END IF
      IF(.NOT.TONECENTERCONTRACTIONREADY) THEN
        CALL ERROR$MSG('SKALA ONE-CENTER CONTRACTION IS NOT AVAILABLE')
        CALL ERROR$STOP('SKALA$TAUOPERATORCHECK')
      END IF
      EXPECTATION1=EXPECTATION
      CALL MPE$COMBINE('MONOMER','+',EXPECTATION1)
      CALL MPE$QUERY('MONOMER',NTASKS,THISTASK)
      IF(THISTASK.EQ.1) THEN
        CALL FILEHANDLER$UNIT('PROT',NFIL)
        WRITE(NFIL,FMT='("TAU OPERATOR EXPECTATION",T34,ES24.14)')EXPECTATION1
        WRITE(NFIL,FMT='("TAU OPERATOR DIFFERENCE",T34,ES24.14)') &
     &       EXPECTATION1-SMOOTH_TAU_CONTRACTION
        WRITE(NFIL,FMT='("SMOOTH SCALAR VALENCE CONTRACTION",T42,ES24.14)') &
     &       SMOOTH_SCALAR_CONTRACTION
        WRITE(NFIL,FMT='("ONE-CENTER VALENCE CONTRACTION",T42,ES24.14)') &
     &       ONECENTER_CONTRACTION
        TOTAL=SMOOTH_SCALAR_CONTRACTION+EXPECTATION1+ONECENTER_CONTRACTION
        WRITE(NFIL,FMT='("FULL ELECTRONIC OPERATOR CONTRACTION",T42,ES24.14)') &
     &       TOTAL
      END IF
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$SMOOTHOPERATORREPORT(POTNORM2,TAUNORM2)
      USE PAW_SKALA_MODULE
      USE MPE_MODULE
      IMPLICIT NONE
      REAL(8),INTENT(IN) :: POTNORM2,TAUNORM2
      REAL(8) :: POTNORM21,TAUNORM21
      INTEGER(4) :: NTASKS,THISTASK,NFIL

      IF(TOPERATORREPORTED.AND..NOT.CONFIG_CHECK) RETURN
      POTNORM21=POTNORM2
      TAUNORM21=TAUNORM2
      CALL MPE$COMBINE('K','+',POTNORM21)
      CALL MPE$COMBINE('K','+',TAUNORM21)
      CALL MPE$QUERY('MONOMER',NTASKS,THISTASK)
      IF(THISTASK.EQ.1) THEN
        CALL FILEHANDLER$UNIT('PROT',NFIL)
        WRITE(NFIL,FMT='("SMOOTH SCALAR OPERATOR L2",T34,ES24.14)') &
     &       SQRT(POTNORM21)
        WRITE(NFIL,FMT='("SMOOTH TAU OPERATOR L2",T34,ES24.14)') &
     &       SQRT(TAUNORM21)
      END IF
      TOPERATORREPORTED=.TRUE.
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$SMOOTHSET(NR1START,NR1L,NR1,NR2,NR3,NDIMD &
     &                          ,RHO,GRHO,TAUPOS,RBAS)
      USE PAW_SKALA_MODULE
      USE MPE_MODULE
      IMPLICIT NONE
      INTEGER(4),INTENT(IN) :: NR1START,NR1L,NR1,NR2,NR3,NDIMD
      REAL(8),INTENT(IN) :: RHO(NR1L*NR2*NR3,NDIMD)
      REAL(8),INTENT(IN) :: GRHO(NR1L*NR2*NR3,3,NDIMD)
      REAL(8),INTENT(IN) :: TAUPOS(NR1L*NR2*NR3,NDIMD)
      REAL(8),INTENT(IN) :: RBAS(3,3)
      INTEGER(4) :: IDIM,ICART,IEND

      IF(.NOT.TON) RETURN
      IF(NDIMD.NE.1.AND.NDIMD.NE.2) THEN
        CALL ERROR$MSG('SKALA SMOOTH CACHE REQUIRES COLLINEAR SPIN')
        CALL ERROR$I4VAL('NDIMD',NDIMD)
        CALL ERROR$STOP('SKALA$SMOOTHSET')
      END IF
      IEND=NR1START+NR1L-1
      IF(NR1START.LT.1.OR.IEND.GT.NR1) THEN
        CALL ERROR$MSG('INVALID LOCAL SKALA GRID SLAB')
        CALL ERROR$I4VAL('NR1START',NR1START)
        CALL ERROR$I4VAL('NR1L',NR1L)
        CALL ERROR$I4VAL('NR1',NR1)
        CALL ERROR$STOP('SKALA$SMOOTHSET')
      END IF
      IF(ALLOCATED(SMOOTH_RHO)) DEALLOCATE(SMOOTH_RHO)
      IF(ALLOCATED(SMOOTH_GRHO)) DEALLOCATE(SMOOTH_GRHO)
      IF(ALLOCATED(SMOOTH_TAU)) DEALLOCATE(SMOOTH_TAU)
      ALLOCATE(SMOOTH_RHO(NR1,NR2,NR3,NDIMD))
      ALLOCATE(SMOOTH_GRHO(NR1,NR2,NR3,3,NDIMD))
      ALLOCATE(SMOOTH_TAU(NR1,NR2,NR3,NDIMD))
      SMOOTH_RHO=0.D0
      SMOOTH_GRHO=0.D0
      SMOOTH_TAU=0.D0
      DO IDIM=1,NDIMD
        SMOOTH_RHO(NR1START:IEND,:,:,IDIM)= &
     &      RESHAPE(RHO(:,IDIM),(/NR1L,NR2,NR3/))
        SMOOTH_TAU(NR1START:IEND,:,:,IDIM)= &
     &      RESHAPE(TAUPOS(:,IDIM),(/NR1L,NR2,NR3/))
        DO ICART=1,3
          SMOOTH_GRHO(NR1START:IEND,:,:,ICART,IDIM)= &
     &        RESHAPE(GRHO(:,ICART,IDIM),(/NR1L,NR2,NR3/))
        END DO
      END DO
      CALL MPE$COMBINE('MONOMER','+',SMOOTH_RHO)
      CALL MPE$COMBINE('MONOMER','+',SMOOTH_GRHO)
      CALL MPE$COMBINE('MONOMER','+',SMOOTH_TAU)
      SMOOTH_NR1=NR1
      SMOOTH_NR2=NR2
      SMOOTH_NR3=NR3
      SMOOTH_NDIMD=NDIMD
      SMOOTH_RBAS=RBAS
      SMOOTH_DVOL=ABS(RBAS(1,1)*(RBAS(2,2)*RBAS(3,3) &
     &                              -RBAS(2,3)*RBAS(3,2)) &
     &                -RBAS(1,2)*(RBAS(2,1)*RBAS(3,3) &
     &                              -RBAS(2,3)*RBAS(3,1)) &
     &                +RBAS(1,3)*(RBAS(2,1)*RBAS(3,2) &
     &                              -RBAS(2,2)*RBAS(3,1))) &
     &             /(REAL(NR1,KIND=8)*REAL(NR2,KIND=8) &
     &                                *REAL(NR3,KIND=8))
      TSMOOTHREADY=.TRUE.
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$SMOOTHVALIDATE(NRL,NDIMD,RHO,GRHO,TAUPOS &
     &                               ,NGRIDGLOBAL,CELLVOL)
      USE PAW_SKALA_MODULE
      USE MPE_MODULE
      IMPLICIT NONE
      INTEGER(4),INTENT(IN) :: NRL,NDIMD,NGRIDGLOBAL
      REAL(8),INTENT(IN) :: RHO(NRL,NDIMD)
      REAL(8),INTENT(IN) :: GRHO(NRL,3,NDIMD)
      REAL(8),INTENT(IN) :: TAUPOS(NRL,NDIMD)
      REAL(8),INTENT(IN) :: CELLVOL
      REAL(8) :: RWEIGHT,RHOINT,SPININT,TAUINT,GRADNORM
      INTEGER(4) :: NTASKS,THISTASK,NFIL

      IF(.NOT.TON.OR.TSMOOTHREPORTED) RETURN
      IF(NDIMD.NE.1.AND.NDIMD.NE.2) THEN
        CALL ERROR$MSG('SKALA SMOOTH PRIMITIVES REQUIRE COLLINEAR SPIN')
        CALL ERROR$I4VAL('NDIMD',NDIMD)
        CALL ERROR$STOP('SKALA$SMOOTHVALIDATE')
      END IF
      RWEIGHT=CELLVOL/REAL(NGRIDGLOBAL,KIND=8)
      RHOINT=SUM(RHO(:,1))*RWEIGHT
      TAUINT=SUM(TAUPOS(:,1))*RWEIGHT
      GRADNORM=SUM(GRHO(:,:,1)**2)*RWEIGHT
      SPININT=0.D0
      IF(NDIMD.EQ.2) SPININT=SUM(RHO(:,2))*RWEIGHT
      CALL MPE$COMBINE('MONOMER','+',RHOINT)
      CALL MPE$COMBINE('MONOMER','+',TAUINT)
      CALL MPE$COMBINE('MONOMER','+',GRADNORM)
      CALL MPE$COMBINE('MONOMER','+',SPININT)
      CALL MPE$QUERY('MONOMER',NTASKS,THISTASK)
      IF(THISTASK.EQ.1) THEN
        CALL FILEHANDLER$UNIT('PROT',NFIL)
        WRITE(NFIL,FMT='(/"SKALA SMOOTH PRIMITIVES"/23("="))')
        WRITE(NFIL,FMT='("GRID POINTS",T34,I12)')NGRIDGLOBAL
        WRITE(NFIL,FMT='("SMOOTH ELECTRONS WITH CORE",T34,ES24.14)')RHOINT
        IF(NDIMD.EQ.2) THEN
          WRITE(NFIL,FMT='("SMOOTH SPIN",T34,ES24.14)')SPININT
        END IF
        WRITE(NFIL,FMT='("POSITIVE TAU",T34,ES24.14)')TAUINT
        WRITE(NFIL,FMT='("DENSITY GRADIENT L2",T34,ES24.14)')SQRT(GRADNORM)
      END IF
      TSMOOTHREPORTED=.TRUE.
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$ONECENTERVALIDATE(IAT,ISP,GID,NR,LNX,LOX,LMNX,LMRX &
     &                                  ,NDIMD,DENMAT,AEPHI,PSPHI &
     &                                  ,AECORE,PSCORE,AERHOL,PSRHOL &
     &                                  ,RCUT,EKINNL)
      USE PAW_SKALA_MODULE
      USE PAW_SKALA_PRIMITIVES_MODULE, ONLY: &
     &     PAW_SKALA_ONECENTER_GRID_SIZE,PAW_SKALA_ONECENTER_PRIMITIVES &
     &    ,PAW_SKALA_ONECENTER_REFERENCE,PAW_SKALA_ONECENTER_CHECK_EXACTNESS
      IMPLICIT NONE
      INTEGER(4),INTENT(IN) :: IAT,ISP,GID,NR,LNX,LOX(LNX),LMNX,LMRX,NDIMD
      COMPLEX(8),INTENT(IN) :: DENMAT(LMNX,LMNX,NDIMD)
      REAL(8),INTENT(IN) :: AEPHI(NR,LNX),PSPHI(NR,LNX)
      REAL(8),INTENT(IN) :: AECORE(NR),PSCORE(NR)
      REAL(8),INTENT(IN) :: AERHOL(NR,LMRX,NDIMD),PSRHOL(NR,LMRX,NDIMD)
      REAL(8),INTENT(IN) :: RCUT,EKINNL
      REAL(8),PARAMETER :: PI=4.D0*ATAN(1.D0)
      LOGICAL(4),ALLOCATABLE :: TREPORTED1(:)
      REAL(8),ALLOCATABLE :: RELCOORD(:,:),WEIGHT(:)
      REAL(8),ALLOCATABLE :: AERHO(:,:),PSRHO(:,:),AETAU(:,:),PSTAU(:,:)
      REAL(8),ALLOCATABLE :: AEGRAD(:,:,:),PSGRAD(:,:,:)
      REAL(8) :: R(NR),WORK(NR),INTEGRAL(NR)
      REAL(8) :: AECOUNT,PSCOUNT,AECOUNTREF,PSCOUNTREF,TAUDIFF
      REAL(8) :: TAUAE_REF,TAUPS_REF,DUMMY,TAUFULL,RELTAU,RELBOUND,KESTIMATE
      REAL(8) :: RADTAUAE(NR),RADTAUPS(NR),SURFAE(NR),SURFPS(NR)
      REAL(8) :: AEPOT(NR),DREL(NR)
      REAL(8) :: TAE(NR,LNX),TPS(NR,LNX),ZERO(NR),DCOEFF,NUMKIN
      CHARACTER(32) :: RELTYPE,SETUPTYPE
      INTEGER(4) :: NRUSE,NANG,NPOINT,NFIL,LN1,LN2,LM1,LM2,M,CHECK_EXACTNESS

      IF(.NOT.TON) RETURN
      IF(IAT.LE.0) RETURN
      IF(.NOT.ALLOCATED(TONECENTERREPORTED)) THEN
        ALLOCATE(TONECENTERREPORTED(IAT))
        TONECENTERREPORTED(:)=.FALSE.
      ELSE IF(SIZE(TONECENTERREPORTED).LT.IAT) THEN
        ALLOCATE(TREPORTED1(IAT))
        TREPORTED1(:)=.FALSE.
        TREPORTED1(1:SIZE(TONECENTERREPORTED))=TONECENTERREPORTED
        CALL MOVE_ALLOC(TREPORTED1,TONECENTERREPORTED)
      END IF
      IF(TONECENTERREPORTED(IAT)) RETURN

      CHECK_EXACTNESS=PAW_SKALA_ONECENTER_CHECK_EXACTNESS(CONFIG_LEBEDEVEXACTNESS,LOX)
      CALL PAW_SKALA_ONECENTER_GRID_SIZE(GID,NR,RCUT &
     &                                  ,CHECK_EXACTNESS &
     &                                  ,NRUSE,NANG,NPOINT)
      ALLOCATE(RELCOORD(NPOINT,3),WEIGHT(NPOINT))
      ALLOCATE(AERHO(NPOINT,2),PSRHO(NPOINT,2))
      ALLOCATE(AEGRAD(NPOINT,3,2),PSGRAD(NPOINT,3,2))
      ALLOCATE(AETAU(NPOINT,2),PSTAU(NPOINT,2))
      CALL PAW_SKALA_ONECENTER_PRIMITIVES(GID,NR,LNX,LOX,LMNX,NDIMD &
     &                                   ,DENMAT,AEPHI,PSPHI,AECORE,PSCORE &
     &                                   ,RCUT,CHECK_EXACTNESS,NPOINT &
     &                                   ,RELCOORD,WEIGHT,AERHO,AEGRAD,AETAU &
     &                                   ,PSRHO,PSGRAD,PSTAU)

      AECOUNT=SUM(WEIGHT*(AERHO(:,1)+AERHO(:,2)))
      PSCOUNT=SUM(WEIGHT*(PSRHO(:,1)+PSRHO(:,2)))
      TAUDIFF=SUM(WEIGHT*(AETAU(:,1)+AETAU(:,2) &
     &                         -PSTAU(:,1)-PSTAU(:,2)))
      CALL RADIAL$R(GID,NR,R)
      WORK(:)=(AERHOL(:,1,1)+AECORE)*R**2
      CALL RADIAL$INTEGRATE(GID,NR,WORK,INTEGRAL)
      AECOUNTREF=SQRT(4.D0*PI)*INTEGRAL(NRUSE)
      WORK(:)=(PSRHOL(:,1,1)+PSCORE)*R**2
      CALL RADIAL$INTEGRATE(GID,NR,WORK,INTEGRAL)
      PSCOUNTREF=SQRT(4.D0*PI)*INTEGRAL(NRUSE)

      CALL PAW_SKALA_ONECENTER_REFERENCE(GID,NR,NRUSE,LNX,LOX,LMNX &
     &     ,DENMAT(:,:,1),AEPHI,AECORE,.FALSE.,DUMMY,TAUAE_REF &
     &     ,RADTAUAE,SURFAE)
      CALL PAW_SKALA_ONECENTER_REFERENCE(GID,NR,NRUSE,LNX,LOX,LMNX &
     &     ,DENMAT(:,:,1),PSPHI,PSCORE,.FALSE.,DUMMY,TAUPS_REF &
     &     ,RADTAUPS,SURFPS)
      CALL RADIAL$INTEGRATE(GID,NR,RADTAUAE-RADTAUPS,INTEGRAL)
      TAUFULL=INTEGRAL(NR-3)
      CALL SETUP$ISELECT(ISP)
      CALL SETUP$GETCH('RELTYPE',RELTYPE)
      CALL SETUP$GETCH('TYPE',SETUPTYPE)
      CALL SETUP$GETR8A('AEPOT',NR,AEPOT)
      CALL SETUP$UNSELECT()
      DREL=0.D0
      IF(RELTYPE.EQ.'ZORA') CALL SCHROEDINGER$DREL(GID,NR,AEPOT,0.D0,DREL)
      CALL RADIAL$INTEGRATE(GID,NR,DREL*RADTAUAE,INTEGRAL)
      RELTAU=INTEGRAL(NR-3)
      RELBOUND=(1.D0+DREL(NR-3))*SURFAE(NR-3)-SURFPS(NR-3)
      KESTIMATE=TAUFULL+RELTAU-RELBOUND

      CALL FILEHANDLER$UNIT('PROT',NFIL)
      WRITE(NFIL,FMT='(/"SKALA PAW ONE-CENTER PRIMITIVES"/31("="))')
      WRITE(NFIL,FMT='("ATOM INDEX",T34,I10)')IAT
      WRITE(NFIL,FMT='("LEBEDEV EXACTNESS",T34,I10)') &
     &     CHECK_EXACTNESS
      WRITE(NFIL,FMT='("ATOM-GRID REQUESTED EXACTNESS",T34,I10)') &
     &     CONFIG_LEBEDEVEXACTNESS
      WRITE(NFIL,FMT='("RADIAL POINTS",T34,I10)')NRUSE
      WRITE(NFIL,FMT='("ANGULAR POINTS",T34,I10)')NANG
      WRITE(NFIL,FMT='("TOTAL POINTS",T34,I10)')NPOINT
      WRITE(NFIL,FMT='("AE ELECTRONS",T34,ES24.14)')AECOUNT
      WRITE(NFIL,FMT='("AE ELECTRON ERROR",T34,ES24.14)')AECOUNT-AECOUNTREF
      WRITE(NFIL,FMT='("PS ELECTRONS",T34,ES24.14)')PSCOUNT
      WRITE(NFIL,FMT='("PS ELECTRON ERROR",T34,ES24.14)')PSCOUNT-PSCOUNTREF
      WRITE(NFIL,FMT='("POSITIVE TAU AE-PS",T34,ES24.14)')TAUDIFF
      WRITE(NFIL,FMT='("ONE-CENTER TAU CONTENT",T34,A)')'VALENCE ONLY'
      WRITE(NFIL,FMT='("ONE-CENTER KINETIC",T34,ES24.14)')EKINNL
      WRITE(NFIL,FMT='("TAU-KINETIC DIFFERENCE",T34,ES24.14)')TAUDIFF-EKINNL
      WRITE(NFIL,FMT='("TAU RADIAL REFERENCE",T34,ES24.14)')TAUAE_REF-TAUPS_REF
      WRITE(NFIL,FMT='("TAU ANGULAR-RADIAL ERROR",T34,ES24.14)') &
     &     TAUDIFF-(TAUAE_REF-TAUPS_REF)
      WRITE(NFIL,FMT='("TAU GRID OUTER RADIUS",T34,ES24.14)')R(NRUSE)
      WRITE(NFIL,FMT='("SETUP OUTER RADIUS",T34,ES24.14)')R(NR-3)
      WRITE(NFIL,FMT='("TAU OUTER-DOMAIN CONTRIBUTION",T34,ES24.14)') &
     &     TAUFULL-(TAUAE_REF-TAUPS_REF)
      WRITE(NFIL,FMT='("TAU NONREL SURFACE TERM",T34,ES24.14)') &
     &     SURFAE(NR-3)-SURFPS(NR-3)
      WRITE(NFIL,FMT='("SETUP CONSTRUCTION",T34,A)')TRIM(SETUPTYPE)
      WRITE(NFIL,FMT='("SETUP RELATIVITY",T34,A)')TRIM(RELTYPE)
      ! Compare with the nominal nonrelativistic PS/common AE ZORA operator.
      ! HBS replaces PS tails and stores an equation-based kinetic action;
      ! equality to that setup matrix is not assumed. Do not redefine model tau.
      IF(SETUPTYPE.EQ.'HBS'.AND.(RELTYPE.EQ.'ZORA'.OR.RELTYPE.EQ.'NONREL')) THEN
        WRITE(NFIL,FMT='("TAU AE ZORA CORRECTION",T34,ES24.14)')RELTAU
        WRITE(NFIL,FMT='("TAU SETUP SURFACE TERM",T34,ES24.14)')RELBOUND
        WRITE(NFIL,FMT='("GRADIENT SETUP KINETIC ESTIMATE",T34,ES24.14)')KESTIMATE
        WRITE(NFIL,FMT='("SETUP KINETIC ESTIMATE RESIDUAL",T34,ES24.14)') &
     &       KESTIMATE-EKINNL
        ZERO=0.D0
        DO LN1=1,LNX
          CALL SCHROEDINGER$EKINPSI(GID,NR,AEPOT,DREL,0,LOX(LN1) &
     &                              ,AEPHI(:,LN1),TAE(:,LN1))
          CALL SCHROEDINGER$EKINPSI(GID,NR,AEPOT,ZERO,0,LOX(LN1) &
     &                              ,PSPHI(:,LN1),TPS(:,LN1))
        END DO
        WORK=0.D0
        LM1=0
        DO LN1=1,LNX
          LM2=0
          DO LN2=1,LNX
            IF(LOX(LN1).EQ.LOX(LN2)) THEN
              DCOEFF=0.D0
              DO M=1,2*LOX(LN1)+1
                DCOEFF=DCOEFF+REAL(DENMAT(LM1+M,LM2+M,1),KIND=8)
              END DO
              WORK=WORK+DCOEFF*R**2 &
     &             *(AEPHI(:,LN1)*TAE(:,LN2)-PSPHI(:,LN1)*TPS(:,LN2))
            END IF
            LM2=LM2+2*LOX(LN2)+1
          END DO
          LM1=LM1+2*LOX(LN1)+1
        END DO
        CALL RADIAL$INTEGRATE(GID,NR,WORK,INTEGRAL)
        NUMKIN=INTEGRAL(NR-3)
        WRITE(NFIL,FMT='("NUMERICAL SETUP KINETIC",T34,ES24.14)')NUMKIN
        WRITE(NFIL,FMT='("GRADIENT-OPERATOR DIFFERENCE",T34,ES24.14)')KESTIMATE-NUMKIN
        WRITE(NFIL,FMT='("OPERATOR-SETUP DIFFERENCE",T34,ES24.14)')NUMKIN-EKINNL
      END IF
      TONECENTERREPORTED(IAT)=.TRUE.

      DEALLOCATE(RELCOORD,WEIGHT,AERHO,PSRHO,AEGRAD,PSGRAD,AETAU,PSTAU)
      RETURN
      END

!     ..................................................................
      SUBROUTINE SKALA$EVALUATE(NPOINT,NATOM,DENSITY,GRAD,KIN &
     &                         ,GRIDCOORDS,GRIDWEIGHTS,ATOMCOORDS &
     &                         ,ATOMICGRIDWEIGHTS,ATOMICGRIDSIZES,ENERGY &
     &                         ,DDENSITY,DGRAD,DKIN,DGRIDCOORDS &
     &                         ,DGRIDWEIGHTS,DATOMCOORDS,DATOMICGRIDWEIGHTS)
      USE PAW_SKALA_MODULE
      IMPLICIT NONE
      INTEGER(4),INTENT(IN)  :: NPOINT
      INTEGER(4),INTENT(IN)  :: NATOM
      REAL(8)   ,INTENT(IN)  :: DENSITY(NPOINT,2)
      REAL(8)   ,INTENT(IN)  :: GRAD(NPOINT,3,2)
      REAL(8)   ,INTENT(IN)  :: KIN(NPOINT,2)
      REAL(8)   ,INTENT(IN)  :: GRIDCOORDS(NPOINT,3)
      REAL(8)   ,INTENT(IN)  :: GRIDWEIGHTS(NPOINT)
      REAL(8)   ,INTENT(IN)  :: ATOMCOORDS(NATOM,3)
      REAL(8)   ,INTENT(IN)  :: ATOMICGRIDWEIGHTS(NPOINT)
      INTEGER(8),INTENT(IN)  :: ATOMICGRIDSIZES(NATOM)
      REAL(8)   ,INTENT(OUT) :: ENERGY
      REAL(8)   ,INTENT(OUT) :: DDENSITY(NPOINT,2)
      REAL(8)   ,INTENT(OUT) :: DGRAD(NPOINT,3,2)
      REAL(8)   ,INTENT(OUT) :: DKIN(NPOINT,2)
      REAL(8)   ,INTENT(OUT) :: DGRIDCOORDS(NPOINT,3)
      REAL(8)   ,INTENT(OUT) :: DGRIDWEIGHTS(NPOINT)
      REAL(8)   ,INTENT(OUT) :: DATOMCOORDS(NATOM,3)
      REAL(8)   ,INTENT(OUT) :: DATOMICGRIDWEIGHTS(NPOINT)
#IF DEFINED(CPPVAR_SKALA_FTORCH)
      INTEGER(4)             :: STATUS
      CHARACTER(2048)        :: MESSAGE

      IF(.NOT.TINITIALIZED) CALL SKALA$ENSUREINITIALIZED
      CALL PAW_SKALA_EVALUATE(MODEL,DENSITY,GRAD,KIN,GRIDCOORDS,GRIDWEIGHTS &
     &                       ,ATOMCOORDS,ATOMICGRIDWEIGHTS,ATOMICGRIDSIZES &
     &                       ,ENERGY,DDENSITY,DGRAD,DKIN,STATUS,MESSAGE &
     &                       ,DGRIDCOORDS,DGRIDWEIGHTS,DATOMCOORDS &
     &                       ,DATOMICGRIDWEIGHTS)
      IF(STATUS.NE.0) THEN
        CALL ERROR$MSG('SKALA 1.1 EVALUATION FAILED')
        CALL ERROR$CHVAL('DETAIL',TRIM(MESSAGE))
        CALL ERROR$STOP('SKALA$EVALUATE')
      END IF
#ELSE
      CALL ERROR$MSG('CP-PAW WAS BUILT WITHOUT THE SKALA/FTORCH BRIDGE')
      CALL ERROR$STOP('SKALA$EVALUATE')
#ENDIF
      RETURN
      END
