! SPDX-License-Identifier: GPL-3.0-or-later
!**  PERIODIC ATOM PARTITION AND NATIVE-GRID INTERPOLATION FOR SKALA PAW      **

MODULE PAW_SKALA_GRID_MODULE
#IF DEFINED(CPPVAR_OPENACC)
  USE OPENACC, ONLY: ACC_GET_NUM_DEVICES, ACC_DEVICE_NVIDIA
#ENDIF
  IMPLICIT NONE
  PRIVATE
  INTEGER(4),PARAMETER :: INTERP_MIN=-3
  INTEGER(4),PARAMETER :: INTERP_MAX=4
  INTEGER(4),PARAMETER :: INTERP_N=INTERP_MAX-INTERP_MIN+1
  LOGICAL(4),SAVE :: GRID_BACK_CONFIG_READY=.FALSE.
  LOGICAL(4),SAVE :: GRID_BACK_ACC_ENABLED=.FALSE.
  INTEGER(8),SAVE :: GRID_BACK_ACC_MIN_POINTS=32768_8

  PUBLIC :: PAW_SKALA_SMOOTH_PARTITION
  PUBLIC :: PAW_SKALA_SMOOTH_PARTITION_DERIVATIVES
  PUBLIC :: PAW_SKALA_NEAREST_IMAGE
  PUBLIC :: PAW_SKALA_INVERSE3
  PUBLIC :: PAW_SKALA_PARTITION_TAPER
  PUBLIC :: PAW_SKALA_PARTITION_TAPER_DERIVATIVE
  PUBLIC :: PAW_SKALA_RADIAL_BLEND
  PUBLIC :: PAW_SKALA_RADIAL_BLEND_DERIVATIVE
  PUBLIC :: PAW_SKALA_LOCAL_GRID_SIZE
  PUBLIC :: PAW_SKALA_LOCAL_GRID
  PUBLIC :: PAW_SKALA_GRID_INTERPOLATE
  PUBLIC :: PAW_SKALA_GRID_INTERPOLATE_PRIMITIVES
  PUBLIC :: PAW_SKALA_GRID_INTERPOLATE_GRADIENT
  PUBLIC :: PAW_SKALA_GRID_INTERPOLATION_ADJOINT
  PUBLIC :: PAW_SKALA_GRID_PRIMITIVES_ADJOINT
  PUBLIC :: PAW_SKALA_GRID_BACK_BEGIN
  PUBLIC :: PAW_SKALA_GRID_BACK_END
  PUBLIC :: PAW_SKALA_GRID_BACKPROJECT
  PUBLIC :: PAW_SKALA_GRID_TEST

CONTAINS

  SUBROUTINE PAW_SKALA_GRID_BACK_INIT_CONFIG
    IMPLICIT NONE
    CHARACTER(128) :: VALUE
    INTEGER(4) :: STATUS,IOS

    IF(GRID_BACK_CONFIG_READY) RETURN
    GRID_BACK_CONFIG_READY=.TRUE.
    CALL GET_ENVIRONMENT_VARIABLE('CPPAW_SKALA_GRID_BACK_ACC',VALUE &
 &                               ,STATUS=STATUS)
    IF(STATUS.EQ.0.AND.LEN_TRIM(VALUE).GT.0) THEN
      VALUE=ADJUSTL(VALUE)
      SELECT CASE(VALUE(1:MIN(LEN(VALUE),LEN_TRIM(VALUE))))
      CASE('0','no','NO','false','FALSE','off','OFF')
        GRID_BACK_ACC_ENABLED=.FALSE.
      CASE DEFAULT
        GRID_BACK_ACC_ENABLED=.TRUE.
      END SELECT
    END IF
    CALL GET_ENVIRONMENT_VARIABLE('CPPAW_SKALA_GRID_BACK_ACC_MIN_POINTS' &
 &                               ,VALUE,STATUS=STATUS)
    IF(STATUS.EQ.0) THEN
      READ(VALUE,*,IOSTAT=IOS) GRID_BACK_ACC_MIN_POINTS
      IF(IOS.NE.0) GRID_BACK_ACC_MIN_POINTS=32768_8
      GRID_BACK_ACC_MIN_POINTS=MAX(1_8,GRID_BACK_ACC_MIN_POINTS)
    END IF
  END SUBROUTINE PAW_SKALA_GRID_BACK_INIT_CONFIG

  SUBROUTINE PAW_SKALA_GRID_BACK_BEGIN(NR1,NR2,NR3,NDIMD &
 &                                    ,RHO,GRHO,TAU,TACC)
    IMPLICIT NONE
    INTEGER(4),INTENT(IN) :: NR1,NR2,NR3,NDIMD
    REAL(8),INTENT(INOUT) :: RHO(NR1,NR2,NR3,NDIMD)
    REAL(8),INTENT(INOUT) :: GRHO(NR1,NR2,NR3,3,NDIMD)
    REAL(8),INTENT(INOUT) :: TAU(NR1,NR2,NR3,NDIMD)
    LOGICAL(4),INTENT(OUT) :: TACC
    INTEGER(8) :: NGRID

    TACC=.FALSE.
    CALL PAW_SKALA_GRID_BACK_INIT_CONFIG
#IF DEFINED(CPPVAR_OPENACC)
    NGRID=INT(NR1,KIND=8)*INT(NR2,KIND=8)*INT(NR3,KIND=8)
    IF(.NOT.GRID_BACK_ACC_ENABLED) RETURN
    IF(NGRID.LT.GRID_BACK_ACC_MIN_POINTS) RETURN
    IF(ACC_GET_NUM_DEVICES(ACC_DEVICE_NVIDIA).LE.0) RETURN
!$ACC ENTER DATA COPYIN(RHO,GRHO,TAU)
    TACC=.TRUE.
#ELSE
    NGRID=0_8
#ENDIF
  END SUBROUTINE PAW_SKALA_GRID_BACK_BEGIN

  SUBROUTINE PAW_SKALA_GRID_BACK_END(NR1,NR2,NR3,NDIMD &
 &                                  ,RHO,GRHO,TAU,TACC)
    IMPLICIT NONE
    INTEGER(4),INTENT(IN) :: NR1,NR2,NR3,NDIMD
    REAL(8),INTENT(INOUT) :: RHO(NR1,NR2,NR3,NDIMD)
    REAL(8),INTENT(INOUT) :: GRHO(NR1,NR2,NR3,3,NDIMD)
    REAL(8),INTENT(INOUT) :: TAU(NR1,NR2,NR3,NDIMD)
    LOGICAL(4),INTENT(INOUT) :: TACC

#IF DEFINED(CPPVAR_OPENACC)
    IF(TACC) THEN
!$ACC UPDATE SELF(RHO,GRHO,TAU)
!$ACC EXIT DATA DELETE(RHO,GRHO,TAU)
    END IF
#ENDIF
    TACC=.FALSE.
  END SUBROUTINE PAW_SKALA_GRID_BACK_END

  SUBROUTINE PAW_SKALA_GRID_BACKPROJECT(NR1,NR2,NR3,RBAS,NDIMD &
 &                                     ,NSMOOTH,NPOINT,SMOOTHINDEX &
 &                                     ,POINTS,DDENSITY,DGRAD,DKIN &
 &                                     ,RHO,GRHO,TAU,TACC)
    IMPLICIT NONE
    INTEGER(4),INTENT(IN) :: NR1,NR2,NR3,NDIMD,NSMOOTH,NPOINT
    INTEGER(4),INTENT(IN) :: SMOOTHINDEX(NSMOOTH)
    REAL(8),INTENT(IN) :: RBAS(3,3),POINTS(NPOINT,3)
    REAL(8),INTENT(IN) :: DDENSITY(NPOINT,2),DGRAD(NPOINT,3,2)
    REAL(8),INTENT(IN) :: DKIN(NPOINT,2)
    REAL(8),INTENT(INOUT) :: RHO(NR1,NR2,NR3,NDIMD)
    REAL(8),INTENT(INOUT) :: GRHO(NR1,NR2,NR3,3,NDIMD)
    REAL(8),INTENT(INOUT) :: TAU(NR1,NR2,NR3,NDIMD)
    LOGICAL(4),INTENT(IN) :: TACC
    INTEGER(4) :: IP,IWORK,I1,I2,I3,J1,J2,J3,IDIM,ICART,IW,JW
    INTEGER(4) :: BASE1,BASE2,BASE3
    REAL(8) :: FACTOR,ADJRHO(2),ADJTAU(2),ADJGRAD(3,2)
    REAL(8) :: AINV(3,3),REL1,REL2,REL3,FRAC1,FRAC2,FRAC3
    REAL(8) :: W1(INTERP_N),W2(INTERP_N),W3(INTERP_N)
    REAL(8) :: NUM1,NUM2,NUM3,DENOM,NODEI,NODEJ,COEFFICIENT

    IF(NSMOOTH.LT.0.OR.NSMOOTH.GT.NPOINT) THEN
      CALL ERROR$MSG('INVALID SKALA GRID BACK-PROJECTION EXTENTS')
      CALL ERROR$I4VAL('NSMOOTH',NSMOOTH)
      CALL ERROR$I4VAL('NPOINT',NPOINT)
      CALL ERROR$STOP('PAW_SKALA_GRID_BACKPROJECT')
    END IF
#IF DEFINED(CPPVAR_OPENACC)
    IF(TACC) THEN
      CALL PAW_SKALA_INVERSE3(RBAS,AINV)
!$ACC DATA COPYIN(SMOOTHINDEX,POINTS,DDENSITY,DGRAD,DKIN,AINV) &
!$ACC& PRESENT(RHO,GRHO,TAU)
!$ACC PARALLEL LOOP GANG VECTOR &
!$ACC& PRESENT(SMOOTHINDEX,DDENSITY,DGRAD,DKIN,RHO,GRHO,TAU) &
!$ACC& PRIVATE(IWORK,I1,I2,I3,IDIM,ICART,FACTOR)
      DO IP=1,NSMOOTH
        IWORK=SMOOTHINDEX(IP)-1
        I1=MOD(IWORK,NR1)+1
        IWORK=IWORK/NR1
        I2=MOD(IWORK,NR2)+1
        I3=IWORK/NR2+1
        DO IDIM=1,NDIMD
          FACTOR=MERGE(1.D0,-1.D0,IDIM.EQ.1)
          RHO(I1,I2,I3,IDIM)=RHO(I1,I2,I3,IDIM) &
 &            +0.5D0*(DDENSITY(IP,1)+FACTOR*DDENSITY(IP,2))
          TAU(I1,I2,I3,IDIM)=TAU(I1,I2,I3,IDIM) &
 &            +0.5D0*(DKIN(IP,1)+FACTOR*DKIN(IP,2))
          DO ICART=1,3
            GRHO(I1,I2,I3,ICART,IDIM)=GRHO(I1,I2,I3,ICART,IDIM) &
 &              +0.5D0*(DGRAD(IP,ICART,1) &
 &                      +FACTOR*DGRAD(IP,ICART,2))
          END DO
        END DO
      END DO
!$ACC PARALLEL LOOP GANG VECTOR &
!$ACC& PRESENT(POINTS,DDENSITY,DGRAD,DKIN,AINV,RHO,GRHO,TAU) &
!$ACC& PRIVATE(I1,I2,I3,J1,J2,J3,IDIM,ICART,IW,JW &
!$ACC&        ,BASE1,BASE2,BASE3,FACTOR,ADJRHO,ADJTAU,ADJGRAD &
!$ACC&        ,REL1,REL2,REL3,FRAC1,FRAC2,FRAC3,W1,W2,W3 &
!$ACC&        ,NUM1,NUM2,NUM3,DENOM,NODEI,NODEJ,COEFFICIENT)
      DO IP=NSMOOTH+1,NPOINT
        DO IDIM=1,NDIMD
          FACTOR=MERGE(1.D0,-1.D0,IDIM.EQ.1)
          ADJRHO(IDIM)=0.5D0*(DDENSITY(IP,1) &
 &                                  +FACTOR*DDENSITY(IP,2))
          ADJTAU(IDIM)=0.5D0*(DKIN(IP,1)+FACTOR*DKIN(IP,2))
          DO ICART=1,3
            ADJGRAD(ICART,IDIM)=0.5D0*(DGRAD(IP,ICART,1) &
 &                                          +FACTOR*DGRAD(IP,ICART,2))
          END DO
        END DO
        REL1=(AINV(1,1)*POINTS(IP,1)+AINV(1,2)*POINTS(IP,2) &
 &           +AINV(1,3)*POINTS(IP,3))*REAL(NR1,KIND=8)
        REL2=(AINV(2,1)*POINTS(IP,1)+AINV(2,2)*POINTS(IP,2) &
 &           +AINV(2,3)*POINTS(IP,3))*REAL(NR2,KIND=8)
        REL3=(AINV(3,1)*POINTS(IP,1)+AINV(3,2)*POINTS(IP,2) &
 &           +AINV(3,3)*POINTS(IP,3))*REAL(NR3,KIND=8)
        REL1=REL1-REAL(FLOOR(REL1/REAL(NR1,KIND=8)),KIND=8) &
 &                 *REAL(NR1,KIND=8)
        REL2=REL2-REAL(FLOOR(REL2/REAL(NR2,KIND=8)),KIND=8) &
 &                 *REAL(NR2,KIND=8)
        REL3=REL3-REAL(FLOOR(REL3/REAL(NR3,KIND=8)),KIND=8) &
 &                 *REAL(NR3,KIND=8)
        BASE1=FLOOR(REL1)
        BASE2=FLOOR(REL2)
        BASE3=FLOOR(REL3)
        FRAC1=REL1-REAL(BASE1,KIND=8)
        FRAC2=REL2-REAL(BASE2,KIND=8)
        FRAC3=REL3-REAL(BASE3,KIND=8)
        DO IW=1,INTERP_N
          NODEI=REAL(INTERP_MIN+IW-1,KIND=8)
          NUM1=1.D0
          NUM2=1.D0
          NUM3=1.D0
          DENOM=1.D0
          DO JW=1,INTERP_N
            IF(JW.EQ.IW) CYCLE
            NODEJ=REAL(INTERP_MIN+JW-1,KIND=8)
            NUM1=NUM1*(FRAC1-NODEJ)
            NUM2=NUM2*(FRAC2-NODEJ)
            NUM3=NUM3*(FRAC3-NODEJ)
            DENOM=DENOM*(NODEI-NODEJ)
          END DO
          W1(IW)=NUM1/DENOM
          W2(IW)=NUM2/DENOM
          W3(IW)=NUM3/DENOM
        END DO
        DO I3=INTERP_MIN,INTERP_MAX
          J3=MOD(BASE3+I3,NR3)
          IF(J3.LT.0) J3=J3+NR3
          J3=J3+1
          DO I2=INTERP_MIN,INTERP_MAX
            J2=MOD(BASE2+I2,NR2)
            IF(J2.LT.0) J2=J2+NR2
            J2=J2+1
            DO I1=INTERP_MIN,INTERP_MAX
              J1=MOD(BASE1+I1,NR1)
              IF(J1.LT.0) J1=J1+NR1
              J1=J1+1
              COEFFICIENT=W1(I1-INTERP_MIN+1) &
 &                       *W2(I2-INTERP_MIN+1)*W3(I3-INTERP_MIN+1)
              DO IDIM=1,NDIMD
!$ACC ATOMIC UPDATE
                RHO(J1,J2,J3,IDIM)=RHO(J1,J2,J3,IDIM) &
 &                                  +COEFFICIENT*ADJRHO(IDIM)
!$ACC ATOMIC UPDATE
                TAU(J1,J2,J3,IDIM)=TAU(J1,J2,J3,IDIM) &
 &                                  +COEFFICIENT*ADJTAU(IDIM)
                DO ICART=1,3
!$ACC ATOMIC UPDATE
                  GRHO(J1,J2,J3,ICART,IDIM)= &
 &                  GRHO(J1,J2,J3,ICART,IDIM) &
 &                  +COEFFICIENT*ADJGRAD(ICART,IDIM)
                END DO
              END DO
            END DO
          END DO
        END DO
      END DO
!$ACC END DATA
      RETURN
    END IF
#ENDIF
    DO IP=1,NSMOOTH
      IWORK=SMOOTHINDEX(IP)-1
      I1=MOD(IWORK,NR1)+1
      IWORK=IWORK/NR1
      I2=MOD(IWORK,NR2)+1
      I3=IWORK/NR2+1
      DO IDIM=1,NDIMD
        FACTOR=MERGE(1.D0,-1.D0,IDIM.EQ.1)
        RHO(I1,I2,I3,IDIM)=RHO(I1,I2,I3,IDIM) &
 &           +0.5D0*(DDENSITY(IP,1)+FACTOR*DDENSITY(IP,2))
        TAU(I1,I2,I3,IDIM)=TAU(I1,I2,I3,IDIM) &
 &           +0.5D0*(DKIN(IP,1)+FACTOR*DKIN(IP,2))
        DO ICART=1,3
          GRHO(I1,I2,I3,ICART,IDIM)=GRHO(I1,I2,I3,ICART,IDIM) &
 &             +0.5D0*(DGRAD(IP,ICART,1)+FACTOR*DGRAD(IP,ICART,2))
        END DO
      END DO
    END DO
    DO IP=NSMOOTH+1,NPOINT
      DO IDIM=1,NDIMD
        FACTOR=MERGE(1.D0,-1.D0,IDIM.EQ.1)
        ADJRHO(IDIM)=0.5D0*(DDENSITY(IP,1)+FACTOR*DDENSITY(IP,2))
        ADJTAU(IDIM)=0.5D0*(DKIN(IP,1)+FACTOR*DKIN(IP,2))
        DO ICART=1,3
          ADJGRAD(ICART,IDIM)=0.5D0*(DGRAD(IP,ICART,1) &
 &                                      +FACTOR*DGRAD(IP,ICART,2))
        END DO
      END DO
      CALL PAW_SKALA_GRID_PRIMITIVES_ADJOINT(NR1,NR2,NR3,RBAS,NDIMD &
 &                                           ,RHO,GRHO,TAU,POINTS(IP,:) &
 &                                           ,ADJRHO(1:NDIMD) &
 &                                           ,ADJGRAD(:,1:NDIMD) &
 &                                           ,ADJTAU(1:NDIMD))
    END DO
  END SUBROUTINE PAW_SKALA_GRID_BACKPROJECT

  SUBROUTINE PAW_SKALA_LOCAL_GRID_SIZE(NRADIAL,LEBEDEV_L,NANG,NPOINT &
 &                                    ,NORIENTATION)
    USE PAW_LEBEDEV_MODULE, ONLY: PAW_LEBEDEV_SIZE
    IMPLICIT NONE
    INTEGER(4),INTENT(IN) :: NRADIAL,LEBEDEV_L
    INTEGER(4),INTENT(OUT) :: NANG,NPOINT
    INTEGER(4),INTENT(IN),OPTIONAL :: NORIENTATION
    INTEGER(4) :: NBASE,NORIENTATION1

    IF(NRADIAL.LE.0) THEN
      CALL ERROR$MSG('SKALA LOCAL RADIAL GRID SIZE MUST BE POSITIVE')
      CALL ERROR$I4VAL('NRADIAL',NRADIAL)
      CALL ERROR$STOP('PAW_SKALA_LOCAL_GRID_SIZE')
    END IF
    NORIENTATION1=1
    IF(PRESENT(NORIENTATION)) NORIENTATION1=NORIENTATION
    IF(NORIENTATION1.LE.0) THEN
      CALL ERROR$MSG('SKALA LEBEDEV ORIENTATION COUNT MUST BE POSITIVE')
      CALL ERROR$I4VAL('NORIENTATION',NORIENTATION1)
      CALL ERROR$STOP('PAW_SKALA_LOCAL_GRID_SIZE')
    END IF
    CALL PAW_LEBEDEV_SIZE(LEBEDEV_L,NBASE)
    NANG=NBASE*NORIENTATION1
    NPOINT=NRADIAL*NANG
  END SUBROUTINE PAW_SKALA_LOCAL_GRID_SIZE

  SUBROUTINE PAW_SKALA_LOCAL_GRID(NRADIAL,RCUT,LEBEDEV_L,NPOINT &
 &                                ,RELCOORD,WEIGHT,NORIENTATION)
    USE PAW_LEBEDEV_MODULE, ONLY: PAW_LEBEDEV_GET
    IMPLICIT NONE
    INTEGER(4),INTENT(IN) :: NRADIAL,LEBEDEV_L,NPOINT
    REAL(8),INTENT(IN) :: RCUT
    REAL(8),INTENT(OUT) :: RELCOORD(NPOINT,3),WEIGHT(NPOINT)
    INTEGER(4),INTENT(IN),OPTIONAL :: NORIENTATION
    REAL(8),PARAMETER :: PI=4.D0*ATAN(1.D0)
    REAL(8),ALLOCATABLE :: DIRECTION(:,:),ANGWEIGHT(:)
    REAL(8),ALLOCATABLE :: ALLDIRECTION(:,:),ALLANGWEIGHT(:)
    REAL(8),ALLOCATABLE :: RADIUS(:),RADWEIGHT(:)
    REAL(8) :: Z,ZOLD,P0,P1,P2,DP,ROTATION(3,3)
    INTEGER(4) :: NANG,NBASE,NPOINT1,NORIENTATION1
    INTEGER(4) :: I,J,M,IR,IA,IP,IORIENTATION

    IF(RCUT.LE.0.D0) THEN
      CALL ERROR$MSG('SKALA LOCAL GRID CUTOFF MUST BE POSITIVE')
      CALL ERROR$R8VAL('RCUT',RCUT)
      CALL ERROR$STOP('PAW_SKALA_LOCAL_GRID')
    END IF
    NORIENTATION1=1
    IF(PRESENT(NORIENTATION)) NORIENTATION1=NORIENTATION
    CALL PAW_SKALA_LOCAL_GRID_SIZE(NRADIAL,LEBEDEV_L,NANG,NPOINT1 &
 &                                ,NORIENTATION1)
    IF(NPOINT.NE.NPOINT1) THEN
      CALL ERROR$MSG('SKALA LOCAL GRID SIZE IS INCONSISTENT')
      CALL ERROR$I4VAL('NPOINT',NPOINT)
      CALL ERROR$I4VAL('EXPECTED',NPOINT1)
      CALL ERROR$STOP('PAW_SKALA_LOCAL_GRID')
    END IF
    NBASE=NANG/NORIENTATION1
    ALLOCATE(DIRECTION(3,NBASE),ANGWEIGHT(NBASE))
    ALLOCATE(ALLDIRECTION(3,NANG),ALLANGWEIGHT(NANG))
    ALLOCATE(RADIUS(NRADIAL),RADWEIGHT(NRADIAL))
    CALL PAW_LEBEDEV_GET(LEBEDEV_L,NBASE,DIRECTION,ANGWEIGHT)
    IP=0
    DO IORIENTATION=1,NORIENTATION1
      CALL PAW_SKALA_GRID_ROTATION(IORIENTATION,ROTATION)
      DO IA=1,NBASE
        IP=IP+1
        ALLDIRECTION(:,IP)=MATMUL(ROTATION,DIRECTION(:,IA))
        ALLANGWEIGHT(IP)=ANGWEIGHT(IA)/REAL(NORIENTATION1,KIND=8)
      END DO
    END DO

    M=(NRADIAL+1)/2
    DO I=1,M
      Z=COS(PI*(REAL(I,KIND=8)-0.25D0) &
 &          /(REAL(NRADIAL,KIND=8)+0.5D0))
      DO
        P1=1.D0
        P2=0.D0
        DO J=1,NRADIAL
          P0=P2
          P2=P1
          P1=((2.D0*REAL(J,KIND=8)-1.D0)*Z*P2 &
 &           -(REAL(J,KIND=8)-1.D0)*P0)/REAL(J,KIND=8)
        END DO
        DP=REAL(NRADIAL,KIND=8)*(Z*P1-P2)/(Z*Z-1.D0)
        ZOLD=Z
        Z=ZOLD-P1/DP
        IF(ABS(Z-ZOLD).LE.4.D0*EPSILON(Z)) EXIT
      END DO
      RADIUS(I)=0.5D0*RCUT*(1.D0-Z)
      RADIUS(NRADIAL+1-I)=0.5D0*RCUT*(1.D0+Z)
      RADWEIGHT(I)=RCUT/((1.D0-Z*Z)*DP*DP)
      RADWEIGHT(NRADIAL+1-I)=RADWEIGHT(I)
    END DO

    IP=0
    DO IR=1,NRADIAL
      DO IA=1,NANG
        IP=IP+1
        RELCOORD(IP,:)=RADIUS(IR)*ALLDIRECTION(:,IA)
        WEIGHT(IP)=4.D0*PI*RADWEIGHT(IR)*RADIUS(IR)**2 &
 &                *ALLANGWEIGHT(IA)
      END DO
    END DO
    DEALLOCATE(DIRECTION,ANGWEIGHT,ALLDIRECTION,ALLANGWEIGHT)
    DEALLOCATE(RADIUS,RADWEIGHT)
  END SUBROUTINE PAW_SKALA_LOCAL_GRID

  SUBROUTINE PAW_SKALA_GRID_ROTATION(IORIENTATION,ROTATION)
    IMPLICIT NONE
    INTEGER(4),INTENT(IN) :: IORIENTATION
    REAL(8),INTENT(OUT) :: ROTATION(3,3)
    REAL(8),PARAMETER :: PI=4.D0*ATAN(1.D0)
    REAL(8),PARAMETER :: A1=0.75487766624669276005D0
    REAL(8),PARAMETER :: A2=0.56984029099805326591D0
    REAL(8),PARAMETER :: A3=0.43857902174395766334D0
    REAL(8) :: U1,U2,U3,QX,QY,QZ,QW
    INTEGER(4) :: K

    IF(IORIENTATION.LE.0) THEN
      CALL ERROR$MSG('SKALA GRID ORIENTATION INDEX MUST BE POSITIVE')
      CALL ERROR$I4VAL('IORIENTATION',IORIENTATION)
      CALL ERROR$STOP('PAW_SKALA_GRID_ROTATION')
    END IF
    IF(IORIENTATION.EQ.1) THEN
      ROTATION=0.D0
      ROTATION(1,1)=1.D0
      ROTATION(2,2)=1.D0
      ROTATION(3,3)=1.D0
      RETURN
    END IF
    K=IORIENTATION-1
    U1=MODULO(REAL(K,KIND=8)*A1,1.D0)
    U2=MODULO(REAL(K,KIND=8)*A2,1.D0)
    U3=MODULO(REAL(K,KIND=8)*A3,1.D0)
    QX=SQRT(1.D0-U1)*SIN(2.D0*PI*U2)
    QY=SQRT(1.D0-U1)*COS(2.D0*PI*U2)
    QZ=SQRT(U1)*SIN(2.D0*PI*U3)
    QW=SQRT(U1)*COS(2.D0*PI*U3)
    ROTATION(1,1)=1.D0-2.D0*(QY*QY+QZ*QZ)
    ROTATION(1,2)=2.D0*(QX*QY-QZ*QW)
    ROTATION(1,3)=2.D0*(QX*QZ+QY*QW)
    ROTATION(2,1)=2.D0*(QX*QY+QZ*QW)
    ROTATION(2,2)=1.D0-2.D0*(QX*QX+QZ*QZ)
    ROTATION(2,3)=2.D0*(QY*QZ-QX*QW)
    ROTATION(3,1)=2.D0*(QX*QZ-QY*QW)
    ROTATION(3,2)=2.D0*(QY*QZ+QX*QW)
    ROTATION(3,3)=1.D0-2.D0*(QX*QX+QY*QY)
  END SUBROUTINE PAW_SKALA_GRID_ROTATION

  SUBROUTINE PAW_SKALA_INVERSE3(A,AINV)
    IMPLICIT NONE
    REAL(8),INTENT(IN) :: A(3,3)
    REAL(8),INTENT(OUT) :: AINV(3,3)
    REAL(8) :: DET

    DET=A(1,1)*(A(2,2)*A(3,3)-A(2,3)*A(3,2)) &
 &     -A(1,2)*(A(2,1)*A(3,3)-A(2,3)*A(3,1)) &
 &     +A(1,3)*(A(2,1)*A(3,2)-A(2,2)*A(3,1))
    IF(ABS(DET).LE.TINY(DET)) THEN
      CALL ERROR$MSG('SINGULAR CELL IN SKALA GRID OPERATION')
      CALL ERROR$STOP('PAW_SKALA_INVERSE3')
    END IF
    AINV(1,1)=(A(2,2)*A(3,3)-A(2,3)*A(3,2))/DET
    AINV(1,2)=(A(1,3)*A(3,2)-A(1,2)*A(3,3))/DET
    AINV(1,3)=(A(1,2)*A(2,3)-A(1,3)*A(2,2))/DET
    AINV(2,1)=(A(2,3)*A(3,1)-A(2,1)*A(3,3))/DET
    AINV(2,2)=(A(1,1)*A(3,3)-A(1,3)*A(3,1))/DET
    AINV(2,3)=(A(1,3)*A(2,1)-A(1,1)*A(2,3))/DET
    AINV(3,1)=(A(2,1)*A(3,2)-A(2,2)*A(3,1))/DET
    AINV(3,2)=(A(1,2)*A(3,1)-A(1,1)*A(3,2))/DET
    AINV(3,3)=(A(1,1)*A(2,2)-A(1,2)*A(2,1))/DET
  END SUBROUTINE PAW_SKALA_INVERSE3

  SUBROUTINE PAW_SKALA_LAGRANGE_WEIGHTS(FRACTION,WEIGHT,DWEIGHT)
    IMPLICIT NONE
    REAL(8),INTENT(IN) :: FRACTION
    REAL(8),INTENT(OUT) :: WEIGHT(INTERP_N)
    REAL(8),INTENT(OUT),OPTIONAL :: DWEIGHT(INTERP_N)
    REAL(8) :: NODE(INTERP_N),NUMERATOR,DENOMINATOR,DERIVATIVE
    INTEGER(4) :: I,J,K

    DO I=1,INTERP_N
      NODE(I)=REAL(INTERP_MIN+I-1,KIND=8)
    END DO
    DO I=1,INTERP_N
      NUMERATOR=1.D0
      DENOMINATOR=1.D0
      DO J=1,INTERP_N
        IF(J.EQ.I) CYCLE
        NUMERATOR=NUMERATOR*(FRACTION-NODE(J))
        DENOMINATOR=DENOMINATOR*(NODE(I)-NODE(J))
      END DO
      WEIGHT(I)=NUMERATOR/DENOMINATOR
      IF(PRESENT(DWEIGHT)) THEN
        DERIVATIVE=0.D0
        DO K=1,INTERP_N
          IF(K.EQ.I) CYCLE
          NUMERATOR=1.D0
          DO J=1,INTERP_N
            IF(J.EQ.I.OR.J.EQ.K) CYCLE
            NUMERATOR=NUMERATOR*(FRACTION-NODE(J))
          END DO
          DERIVATIVE=DERIVATIVE+NUMERATOR/DENOMINATOR
        END DO
        DWEIGHT(I)=DERIVATIVE
      END IF
    END DO
  END SUBROUTINE PAW_SKALA_LAGRANGE_WEIGHTS

  SUBROUTINE PAW_SKALA_INTERPOLATION_DATA(NR1,NR2,NR3,RBAS,POINT &
 &                                        ,BASE,WEIGHT,DWEIGHT,AINV)
    IMPLICIT NONE
    INTEGER(4),INTENT(IN) :: NR1,NR2,NR3
    REAL(8),INTENT(IN) :: RBAS(3,3),POINT(3)
    INTEGER(4),INTENT(OUT) :: BASE(3)
    REAL(8),INTENT(OUT) :: WEIGHT(INTERP_N,3),AINV(3,3)
    REAL(8),INTENT(OUT),OPTIONAL :: DWEIGHT(INTERP_N,3)
    REAL(8) :: RELATIVE(3),FRACTION
    INTEGER(4) :: IDIR,NGRID(3)

    NGRID=(/NR1,NR2,NR3/)
    CALL PAW_SKALA_INVERSE3(RBAS,AINV)
    RELATIVE=MATMUL(AINV,POINT)*REAL(NGRID,KIND=8)
    DO IDIR=1,3
      RELATIVE(IDIR)=MODULO(RELATIVE(IDIR),REAL(NGRID(IDIR),KIND=8))
      BASE(IDIR)=FLOOR(RELATIVE(IDIR))
      FRACTION=RELATIVE(IDIR)-REAL(BASE(IDIR),KIND=8)
      IF(PRESENT(DWEIGHT)) THEN
        CALL PAW_SKALA_LAGRANGE_WEIGHTS(FRACTION,WEIGHT(:,IDIR) &
 &                                      ,DWEIGHT(:,IDIR))
      ELSE
        CALL PAW_SKALA_LAGRANGE_WEIGHTS(FRACTION,WEIGHT(:,IDIR))
      END IF
    END DO
  END SUBROUTINE PAW_SKALA_INTERPOLATION_DATA

  SUBROUTINE PAW_SKALA_GRID_INTERPOLATE(NR1,NR2,NR3,RBAS,FIELD,POINT,VALUE)
    IMPLICIT NONE
    INTEGER(4),INTENT(IN) :: NR1,NR2,NR3
    REAL(8),INTENT(IN) :: RBAS(3,3),FIELD(NR1,NR2,NR3),POINT(3)
    REAL(8),INTENT(OUT) :: VALUE
    INTEGER(4) :: BASE(3),I1,I2,I3,J1,J2,J3
    REAL(8) :: WEIGHT(INTERP_N,3),AINV(3,3),COEFFICIENT

    CALL PAW_SKALA_INTERPOLATION_DATA(NR1,NR2,NR3,RBAS,POINT &
 &                                    ,BASE,WEIGHT,AINV=AINV)
    VALUE=0.D0
    DO I3=INTERP_MIN,INTERP_MAX
      J3=MODULO(BASE(3)+I3,NR3)+1
      DO I2=INTERP_MIN,INTERP_MAX
        J2=MODULO(BASE(2)+I2,NR2)+1
        DO I1=INTERP_MIN,INTERP_MAX
          J1=MODULO(BASE(1)+I1,NR1)+1
          COEFFICIENT=WEIGHT(I1-INTERP_MIN+1,1) &
 &                   *WEIGHT(I2-INTERP_MIN+1,2) &
 &                   *WEIGHT(I3-INTERP_MIN+1,3)
          VALUE=VALUE+COEFFICIENT*FIELD(J1,J2,J3)
        END DO
      END DO
    END DO
  END SUBROUTINE PAW_SKALA_GRID_INTERPOLATE

  SUBROUTINE PAW_SKALA_GRID_INTERPOLATE_PRIMITIVES(NR1,NR2,NR3,RBAS &
 &                                                ,NDIMD,RHO,GRHO,TAU &
 &                                                ,POINT,RHOVAL,GRADVAL &
 &                                                ,TAUVAL,DRHOVAL &
 &                                                ,DGRADVAL,DTAUVAL)
    IMPLICIT NONE
    INTEGER(4),INTENT(IN) :: NR1,NR2,NR3,NDIMD
    REAL(8),INTENT(IN) :: RBAS(3,3),POINT(3)
    REAL(8),INTENT(IN) :: RHO(NR1,NR2,NR3,NDIMD)
    REAL(8),INTENT(IN) :: GRHO(NR1,NR2,NR3,3,NDIMD)
    REAL(8),INTENT(IN) :: TAU(NR1,NR2,NR3,NDIMD)
    REAL(8),INTENT(OUT) :: RHOVAL(NDIMD),GRADVAL(3,NDIMD),TAUVAL(NDIMD)
    REAL(8),INTENT(OUT),OPTIONAL :: DRHOVAL(3,NDIMD)
    REAL(8),INTENT(OUT),OPTIONAL :: DGRADVAL(3,3,NDIMD),DTAUVAL(3,NDIMD)
    INTEGER(4) :: BASE(3),I1,I2,I3,J1,J2,J3,IDIM,ICART,IDIR,JDIR
    INTEGER(4) :: INDEX(3),NGRID(3)
    REAL(8) :: WEIGHT(INTERP_N,3),DWEIGHT(INTERP_N,3),AINV(3,3)
    REAL(8) :: COEFFICIENT,DCOEFFICIENT
    REAL(8) :: DRHOREL(3,NDIMD),DGRADREL(3,3,NDIMD),DTAUREL(3,NDIMD)
    LOGICAL(4) :: TDERIV

    TDERIV=PRESENT(DRHOVAL).OR.PRESENT(DGRADVAL).OR.PRESENT(DTAUVAL)
    IF(TDERIV.AND.(.NOT.PRESENT(DRHOVAL).OR..NOT.PRESENT(DGRADVAL) &
 &                 .OR..NOT.PRESENT(DTAUVAL))) THEN
      CALL ERROR$MSG('ALL SKALA PRIMITIVE SPATIAL DERIVATIVES ARE REQUIRED')
      CALL ERROR$STOP('PAW_SKALA_GRID_INTERPOLATE_PRIMITIVES')
    END IF
    IF(TDERIV) THEN
      CALL PAW_SKALA_INTERPOLATION_DATA(NR1,NR2,NR3,RBAS,POINT &
 &                                      ,BASE,WEIGHT,DWEIGHT,AINV)
      DRHOREL=0.D0
      DGRADREL=0.D0
      DTAUREL=0.D0
    ELSE
      CALL PAW_SKALA_INTERPOLATION_DATA(NR1,NR2,NR3,RBAS,POINT &
 &                                      ,BASE,WEIGHT,AINV=AINV)
    END IF
    RHOVAL=0.D0
    GRADVAL=0.D0
    TAUVAL=0.D0
    DO I3=INTERP_MIN,INTERP_MAX
      J3=MODULO(BASE(3)+I3,NR3)+1
      DO I2=INTERP_MIN,INTERP_MAX
        J2=MODULO(BASE(2)+I2,NR2)+1
        DO I1=INTERP_MIN,INTERP_MAX
          J1=MODULO(BASE(1)+I1,NR1)+1
          INDEX=(/I1-INTERP_MIN+1,I2-INTERP_MIN+1,I3-INTERP_MIN+1/)
          COEFFICIENT=WEIGHT(I1-INTERP_MIN+1,1) &
 &                   *WEIGHT(I2-INTERP_MIN+1,2) &
 &                   *WEIGHT(I3-INTERP_MIN+1,3)
          DO IDIM=1,NDIMD
            RHOVAL(IDIM)=RHOVAL(IDIM)+COEFFICIENT*RHO(J1,J2,J3,IDIM)
            TAUVAL(IDIM)=TAUVAL(IDIM)+COEFFICIENT*TAU(J1,J2,J3,IDIM)
            DO ICART=1,3
              GRADVAL(ICART,IDIM)=GRADVAL(ICART,IDIM) &
 &                         +COEFFICIENT*GRHO(J1,J2,J3,ICART,IDIM)
            END DO
            IF(TDERIV) THEN
              DO IDIR=1,3
                DCOEFFICIENT=1.D0
                DO JDIR=1,3
                  IF(JDIR.EQ.IDIR) THEN
                    DCOEFFICIENT=DCOEFFICIENT &
 &                              *DWEIGHT(INDEX(JDIR),JDIR)
                  ELSE
                    DCOEFFICIENT=DCOEFFICIENT*WEIGHT(INDEX(JDIR),JDIR)
                  END IF
                END DO
                DRHOREL(IDIR,IDIM)=DRHOREL(IDIR,IDIM) &
 &                           +DCOEFFICIENT*RHO(J1,J2,J3,IDIM)
                DTAUREL(IDIR,IDIM)=DTAUREL(IDIR,IDIM) &
 &                           +DCOEFFICIENT*TAU(J1,J2,J3,IDIM)
                DO ICART=1,3
                  DGRADREL(ICART,IDIR,IDIM)= &
 &                    DGRADREL(ICART,IDIR,IDIM) &
 &                    +DCOEFFICIENT*GRHO(J1,J2,J3,ICART,IDIM)
                END DO
              END DO
            END IF
          END DO
        END DO
      END DO
    END DO
    IF(TDERIV) THEN
      NGRID=(/NR1,NR2,NR3/)
      DO IDIM=1,NDIMD
        DRHOVAL(:,IDIM)=MATMUL(TRANSPOSE(AINV) &
 &                            ,REAL(NGRID,KIND=8)*DRHOREL(:,IDIM))
        DTAUVAL(:,IDIM)=MATMUL(TRANSPOSE(AINV) &
 &                            ,REAL(NGRID,KIND=8)*DTAUREL(:,IDIM))
        DO ICART=1,3
          DGRADVAL(ICART,:,IDIM)=MATMUL(TRANSPOSE(AINV) &
 &              ,REAL(NGRID,KIND=8)*DGRADREL(ICART,:,IDIM))
        END DO
      END DO
    END IF
  END SUBROUTINE PAW_SKALA_GRID_INTERPOLATE_PRIMITIVES

  SUBROUTINE PAW_SKALA_GRID_INTERPOLATE_GRADIENT(NR1,NR2,NR3,RBAS &
 &                                               ,FIELD,POINT,GRADIENT)
    IMPLICIT NONE
    INTEGER(4),INTENT(IN) :: NR1,NR2,NR3
    REAL(8),INTENT(IN) :: RBAS(3,3),FIELD(NR1,NR2,NR3),POINT(3)
    REAL(8),INTENT(OUT) :: GRADIENT(3)
    INTEGER(4) :: BASE(3),I1,I2,I3,J1,J2,J3,IDIR,JDIR,INDEX(3),NGRID(3)
    REAL(8) :: WEIGHT(INTERP_N,3),DWEIGHT(INTERP_N,3),AINV(3,3)
    REAL(8) :: COEFFICIENT,GRADREL(3)

    CALL PAW_SKALA_INTERPOLATION_DATA(NR1,NR2,NR3,RBAS,POINT &
 &                                    ,BASE,WEIGHT,DWEIGHT,AINV)
    NGRID=(/NR1,NR2,NR3/)
    GRADREL=0.D0
    DO I3=INTERP_MIN,INTERP_MAX
      J3=MODULO(BASE(3)+I3,NR3)+1
      DO I2=INTERP_MIN,INTERP_MAX
        J2=MODULO(BASE(2)+I2,NR2)+1
        DO I1=INTERP_MIN,INTERP_MAX
          J1=MODULO(BASE(1)+I1,NR1)+1
          INDEX=(/I1-INTERP_MIN+1,I2-INTERP_MIN+1,I3-INTERP_MIN+1/)
          DO IDIR=1,3
            COEFFICIENT=1.D0
            DO JDIR=1,3
              IF(JDIR.EQ.IDIR) THEN
                COEFFICIENT=COEFFICIENT*DWEIGHT(INDEX(JDIR),JDIR)
              ELSE
                COEFFICIENT=COEFFICIENT*WEIGHT(INDEX(JDIR),JDIR)
              END IF
            END DO
            GRADREL(IDIR)=GRADREL(IDIR)+COEFFICIENT*FIELD(J1,J2,J3)
          END DO
        END DO
      END DO
    END DO
    GRADIENT=MATMUL(TRANSPOSE(AINV),REAL(NGRID,KIND=8)*GRADREL)
  END SUBROUTINE PAW_SKALA_GRID_INTERPOLATE_GRADIENT

  SUBROUTINE PAW_SKALA_GRID_INTERPOLATION_ADJOINT(NR1,NR2,NR3,RBAS &
 &                                                ,FIELD,POINT,VALUE)
    IMPLICIT NONE
    INTEGER(4),INTENT(IN) :: NR1,NR2,NR3
    REAL(8),INTENT(IN) :: RBAS(3,3),POINT(3),VALUE
    REAL(8),INTENT(INOUT) :: FIELD(NR1,NR2,NR3)
    INTEGER(4) :: BASE(3),I1,I2,I3,J1,J2,J3
    REAL(8) :: WEIGHT(INTERP_N,3),AINV(3,3),COEFFICIENT

    CALL PAW_SKALA_INTERPOLATION_DATA(NR1,NR2,NR3,RBAS,POINT &
 &                                    ,BASE,WEIGHT,AINV=AINV)
    DO I3=INTERP_MIN,INTERP_MAX
      J3=MODULO(BASE(3)+I3,NR3)+1
      DO I2=INTERP_MIN,INTERP_MAX
        J2=MODULO(BASE(2)+I2,NR2)+1
        DO I1=INTERP_MIN,INTERP_MAX
          J1=MODULO(BASE(1)+I1,NR1)+1
          COEFFICIENT=WEIGHT(I1-INTERP_MIN+1,1) &
 &                   *WEIGHT(I2-INTERP_MIN+1,2) &
 &                   *WEIGHT(I3-INTERP_MIN+1,3)
          FIELD(J1,J2,J3)=FIELD(J1,J2,J3)+COEFFICIENT*VALUE
        END DO
      END DO
    END DO
  END SUBROUTINE PAW_SKALA_GRID_INTERPOLATION_ADJOINT

  SUBROUTINE PAW_SKALA_GRID_PRIMITIVES_ADJOINT(NR1,NR2,NR3,RBAS,NDIMD &
 &                                             ,RHO,GRHO,TAU,POINT &
 &                                             ,RHOVAL,GRADVAL,TAUVAL)
    IMPLICIT NONE
    INTEGER(4),INTENT(IN) :: NR1,NR2,NR3,NDIMD
    REAL(8),INTENT(IN) :: RBAS(3,3),POINT(3)
    REAL(8),INTENT(IN) :: RHOVAL(NDIMD),GRADVAL(3,NDIMD),TAUVAL(NDIMD)
    REAL(8),INTENT(INOUT) :: RHO(NR1,NR2,NR3,NDIMD)
    REAL(8),INTENT(INOUT) :: GRHO(NR1,NR2,NR3,3,NDIMD)
    REAL(8),INTENT(INOUT) :: TAU(NR1,NR2,NR3,NDIMD)
    INTEGER(4) :: BASE(3),I1,I2,I3,J1,J2,J3,IDIM,ICART
    REAL(8) :: WEIGHT(INTERP_N,3),AINV(3,3),COEFFICIENT

    CALL PAW_SKALA_INTERPOLATION_DATA(NR1,NR2,NR3,RBAS,POINT &
 &                                    ,BASE,WEIGHT,AINV=AINV)
    DO I3=INTERP_MIN,INTERP_MAX
      J3=MODULO(BASE(3)+I3,NR3)+1
      DO I2=INTERP_MIN,INTERP_MAX
        J2=MODULO(BASE(2)+I2,NR2)+1
        DO I1=INTERP_MIN,INTERP_MAX
          J1=MODULO(BASE(1)+I1,NR1)+1
          COEFFICIENT=WEIGHT(I1-INTERP_MIN+1,1) &
 &                   *WEIGHT(I2-INTERP_MIN+1,2) &
 &                   *WEIGHT(I3-INTERP_MIN+1,3)
          DO IDIM=1,NDIMD
            RHO(J1,J2,J3,IDIM)=RHO(J1,J2,J3,IDIM) &
 &                             +COEFFICIENT*RHOVAL(IDIM)
            TAU(J1,J2,J3,IDIM)=TAU(J1,J2,J3,IDIM) &
 &                             +COEFFICIENT*TAUVAL(IDIM)
            DO ICART=1,3
              GRHO(J1,J2,J3,ICART,IDIM)=GRHO(J1,J2,J3,ICART,IDIM) &
 &                                  +COEFFICIENT*GRADVAL(ICART,IDIM)
            END DO
          END DO
        END DO
      END DO
    END DO
  END SUBROUTINE PAW_SKALA_GRID_PRIMITIVES_ADJOINT

  PURE REAL(8) FUNCTION PAW_SKALA_BECKE_SHAPE(MU)
    IMPLICIT NONE
    REAL(8),INTENT(IN) :: MU
    INTEGER(4) :: I
    PAW_SKALA_BECKE_SHAPE=MU
    DO I=1,3
      PAW_SKALA_BECKE_SHAPE=0.5D0*PAW_SKALA_BECKE_SHAPE &
 &                         *(3.D0-PAW_SKALA_BECKE_SHAPE**2)
    END DO
  END FUNCTION PAW_SKALA_BECKE_SHAPE

  PURE REAL(8) FUNCTION PAW_SKALA_BECKE_SHAPE_DERIVATIVE(MU)
    IMPLICIT NONE
    REAL(8),INTENT(IN) :: MU
    REAL(8) :: VALUE
    INTEGER(4) :: I

    VALUE=MU
    PAW_SKALA_BECKE_SHAPE_DERIVATIVE=1.D0
    DO I=1,3
      PAW_SKALA_BECKE_SHAPE_DERIVATIVE= &
 &        1.5D0*(1.D0-VALUE**2)*PAW_SKALA_BECKE_SHAPE_DERIVATIVE
      VALUE=0.5D0*VALUE*(3.D0-VALUE**2)
    END DO
  END FUNCTION PAW_SKALA_BECKE_SHAPE_DERIVATIVE

  PURE REAL(8) FUNCTION PAW_SKALA_PARTITION_TAPER(WEIGHT)
    IMPLICIT NONE
    REAL(8),INTENT(IN) :: WEIGHT
    REAL(8),PARAMETER :: START=1.D-12,FINISH=1.D-11
    REAL(8) :: X

    IF(WEIGHT.LE.START) THEN
      PAW_SKALA_PARTITION_TAPER=0.D0
    ELSE IF(WEIGHT.GE.FINISH) THEN
      PAW_SKALA_PARTITION_TAPER=1.D0
    ELSE
      X=(WEIGHT-START)/(FINISH-START)
      PAW_SKALA_PARTITION_TAPER=X**3*(10.D0+X*(-15.D0+6.D0*X))
    END IF
  END FUNCTION PAW_SKALA_PARTITION_TAPER

  PURE REAL(8) FUNCTION PAW_SKALA_PARTITION_TAPER_DERIVATIVE(WEIGHT)
    IMPLICIT NONE
    REAL(8),INTENT(IN) :: WEIGHT
    REAL(8),PARAMETER :: START=1.D-12,FINISH=1.D-11
    REAL(8) :: X

    IF(WEIGHT.LE.START.OR.WEIGHT.GE.FINISH) THEN
      PAW_SKALA_PARTITION_TAPER_DERIVATIVE=0.D0
    ELSE
      X=(WEIGHT-START)/(FINISH-START)
      PAW_SKALA_PARTITION_TAPER_DERIVATIVE= &
 &        30.D0*X**2*(1.D0-X)**2/(FINISH-START)
    END IF
  END FUNCTION PAW_SKALA_PARTITION_TAPER_DERIVATIVE

  PURE REAL(8) FUNCTION PAW_SKALA_RADIAL_BLEND(DISTANCE,RCUT)
    IMPLICIT NONE
    REAL(8),INTENT(IN) :: DISTANCE,RCUT
    REAL(8),PARAMETER :: INNER_FRACTION=0.8D0
    REAL(8) :: INNER,X

    INNER=INNER_FRACTION*RCUT
    IF(DISTANCE.LE.INNER) THEN
      PAW_SKALA_RADIAL_BLEND=1.D0
    ELSE IF(DISTANCE.GE.RCUT) THEN
      PAW_SKALA_RADIAL_BLEND=0.D0
    ELSE
      X=(DISTANCE-INNER)/(RCUT-INNER)
      PAW_SKALA_RADIAL_BLEND=1.D0-X**3*(10.D0+X*(-15.D0+6.D0*X))
    END IF
  END FUNCTION PAW_SKALA_RADIAL_BLEND

  PURE REAL(8) FUNCTION PAW_SKALA_RADIAL_BLEND_DERIVATIVE(DISTANCE,RCUT)
    IMPLICIT NONE
    REAL(8),INTENT(IN) :: DISTANCE,RCUT
    REAL(8),PARAMETER :: INNER_FRACTION=0.8D0
    REAL(8) :: INNER,X

    INNER=INNER_FRACTION*RCUT
    IF(DISTANCE.LE.INNER.OR.DISTANCE.GE.RCUT) THEN
      PAW_SKALA_RADIAL_BLEND_DERIVATIVE=0.D0
    ELSE
      X=(DISTANCE-INNER)/(RCUT-INNER)
      PAW_SKALA_RADIAL_BLEND_DERIVATIVE= &
 &       -30.D0*X**2*(1.D0-X)**2/(RCUT-INNER)
    END IF
  END FUNCTION PAW_SKALA_RADIAL_BLEND_DERIVATIVE

  SUBROUTINE PAW_SKALA_NEAREST_IMAGE(POINT,ATOM,RBAS,IMAGE,DISTANCE,AINV_IN)
    IMPLICIT NONE
    REAL(8),INTENT(IN) :: POINT(3),ATOM(3),RBAS(3,3)
    REAL(8),INTENT(OUT) :: IMAGE(3),DISTANCE
    REAL(8),INTENT(IN),OPTIONAL :: AINV_IN(3,3)
    REAL(8) :: AINV(3,3),DR(3),TRIAL(3),BEST2,R2
    INTEGER(4) :: CENTER(3),SHIFT(3),I1,I2,I3

    IF(PRESENT(AINV_IN)) THEN
      AINV=AINV_IN
    ELSE
      CALL PAW_SKALA_INVERSE3(RBAS,AINV)
    END IF
    DR=ATOM-POINT
    CENTER=NINT(MATMUL(AINV,DR))
    BEST2=HUGE(BEST2)
    DO I3=-1,1
      DO I2=-1,1
        DO I1=-1,1
          SHIFT=CENTER+(/I1,I2,I3/)
          TRIAL=DR-MATMUL(RBAS,REAL(SHIFT,KIND=8))
          R2=DOT_PRODUCT(TRIAL,TRIAL)
          IF(R2.LT.BEST2) THEN
            BEST2=R2
            IMAGE=POINT+TRIAL
          END IF
        END DO
      END DO
    END DO
    DISTANCE=SQRT(BEST2)
  END SUBROUTINE PAW_SKALA_NEAREST_IMAGE

  SUBROUTINE PAW_SKALA_SMOOTH_PARTITION(POINT,NAT,ATOMCOORD,RBAS,WEIGHT)
    IMPLICIT NONE
    INTEGER(4),INTENT(IN) :: NAT
    REAL(8),INTENT(IN) :: POINT(3),ATOMCOORD(NAT,3),RBAS(3,3)
    REAL(8),INTENT(OUT) :: WEIGHT(NAT)
    REAL(8) :: IMAGE(NAT,3),DISTANCE(NAT),PAIR(3),RAB,MU,SWITCH,TOTAL
    REAL(8) :: AINV(3,3)
    INTEGER(4) :: I,J,IMIN

    CALL PAW_SKALA_INVERSE3(RBAS,AINV)
    DO I=1,NAT
      CALL PAW_SKALA_NEAREST_IMAGE(POINT,ATOMCOORD(I,:),RBAS &
 &                                 ,IMAGE(I,:),DISTANCE(I),AINV)
    END DO
    WEIGHT=1.D0
    DO I=1,NAT-1
      DO J=I+1,NAT
        PAIR=IMAGE(I,:)-IMAGE(J,:)
        RAB=SQRT(DOT_PRODUCT(PAIR,PAIR))
        IF(RAB.LE.1.D-14) CYCLE
        MU=(DISTANCE(I)-DISTANCE(J))/RAB
        MU=MAX(-1.D0,MIN(1.D0,MU))
        SWITCH=0.5D0*(1.D0-PAW_SKALA_BECKE_SHAPE(MU))
        WEIGHT(I)=WEIGHT(I)*SWITCH
        WEIGHT(J)=WEIGHT(J)*(1.D0-SWITCH)
      END DO
    END DO
    TOTAL=SUM(WEIGHT)
    IF(TOTAL.GT.0.D0) THEN
      WEIGHT=WEIGHT/TOTAL
    ELSE
      IMIN=MINLOC(DISTANCE,DIM=1)
      WEIGHT=0.D0
      WEIGHT(IMIN)=1.D0
    END IF
  END SUBROUTINE PAW_SKALA_SMOOTH_PARTITION

  SUBROUTINE PAW_SKALA_SMOOTH_PARTITION_DERIVATIVES(POINT,NAT,ATOMCOORD &
 &                                                  ,RBAS,WEIGHT &
 &                                                  ,DWEIGHT_DATOM &
 &                                                  ,DWEIGHT_DPOINT &
 &                                                  ,DWEIGHT_DSTRAIN &
 &                                                  ,POINT_STRAIN_COORD)
    IMPLICIT NONE
    INTEGER(4),INTENT(IN) :: NAT
    REAL(8),INTENT(IN) :: POINT(3),ATOMCOORD(NAT,3),RBAS(3,3)
    REAL(8),INTENT(OUT) :: WEIGHT(NAT),DWEIGHT_DATOM(3,NAT,NAT)
    REAL(8),INTENT(OUT) :: DWEIGHT_DPOINT(3,NAT)
    REAL(8),INTENT(OUT),OPTIONAL :: DWEIGHT_DSTRAIN(3,3,NAT)
    REAL(8),INTENT(IN),OPTIONAL :: POINT_STRAIN_COORD(3)
    REAL(8) :: AINV(3,3),IMAGE(NAT,3),DISTANCE(NAT),RVECS(NAT,3)
    REAL(8) :: UNIT_RVEC(NAT,3),RAW_WEIGHT(NAT),DLOG(3,NAT,NAT)
    REAL(8) :: MEAN_DLOG(3,NAT),PAIR(3),UNIT_PAIR(3)
    REAL(8) :: RAB,DIST_DIFF,MU_RAW,MU,SWITCH,ONE_MINUS_SWITCH,DS_DMU
    REAL(8) :: DMU_I(3),DMU_J(3),DS_I(3),DS_J(3),TOTAL
    REAL(8) :: POINT_RESPONSE(3)
    INTEGER(4) :: I,J,K,IMIN,IDIR,JDIR

    WEIGHT=0.D0
    DWEIGHT_DATOM=0.D0
    DWEIGHT_DPOINT=0.D0
    IF(PRESENT(DWEIGHT_DSTRAIN)) DWEIGHT_DSTRAIN=0.D0
    RAW_WEIGHT=1.D0
    DLOG=0.D0
    CALL PAW_SKALA_INVERSE3(RBAS,AINV)
    DO I=1,NAT
      CALL PAW_SKALA_NEAREST_IMAGE(POINT,ATOMCOORD(I,:),RBAS &
 &                                 ,IMAGE(I,:),DISTANCE(I),AINV)
      RVECS(I,:)=POINT-IMAGE(I,:)
      IF(DISTANCE(I).GT.1.D-14) THEN
        UNIT_RVEC(I,:)=RVECS(I,:)/DISTANCE(I)
      ELSE
        UNIT_RVEC(I,:)=0.D0
      END IF
    END DO

    DO I=1,NAT-1
      DO J=I+1,NAT
        PAIR=IMAGE(I,:)-IMAGE(J,:)
        RAB=SQRT(DOT_PRODUCT(PAIR,PAIR))
        IF(RAB.LE.1.D-14) CYCLE
        UNIT_PAIR=PAIR/RAB
        DIST_DIFF=DISTANCE(I)-DISTANCE(J)
        MU_RAW=DIST_DIFF/RAB
        MU=MAX(-1.D0,MIN(1.D0,MU_RAW))
        SWITCH=0.5D0*(1.D0-PAW_SKALA_BECKE_SHAPE(MU))
        ONE_MINUS_SWITCH=1.D0-SWITCH
        DS_DMU=0.D0
        IF(ABS(MU_RAW).LT.1.D0) THEN
          DS_DMU=-0.5D0*PAW_SKALA_BECKE_SHAPE_DERIVATIVE(MU)
        END IF
        IF(ABS(DS_DMU).GT.0.D0.AND.SWITCH.GT.TINY(SWITCH) &
 &         .AND.ONE_MINUS_SWITCH.GT.TINY(ONE_MINUS_SWITCH)) THEN
          DMU_I=(-UNIT_RVEC(I,:)*RAB-DIST_DIFF*UNIT_PAIR)/RAB**2
          DMU_J=( UNIT_RVEC(J,:)*RAB+DIST_DIFF*UNIT_PAIR)/RAB**2
          DS_I=DS_DMU*DMU_I
          DS_J=DS_DMU*DMU_J
          DLOG(:,I,I)=DLOG(:,I,I)+DS_I/SWITCH
          DLOG(:,I,J)=DLOG(:,I,J)-DS_I/ONE_MINUS_SWITCH
          DLOG(:,J,I)=DLOG(:,J,I)+DS_J/SWITCH
          DLOG(:,J,J)=DLOG(:,J,J)-DS_J/ONE_MINUS_SWITCH
        END IF
        RAW_WEIGHT(I)=RAW_WEIGHT(I)*SWITCH
        RAW_WEIGHT(J)=RAW_WEIGHT(J)*ONE_MINUS_SWITCH
      END DO
    END DO

    TOTAL=SUM(RAW_WEIGHT)
    IF(TOTAL.LE.0.D0) THEN
      IMIN=MINLOC(DISTANCE,DIM=1)
      WEIGHT(IMIN)=1.D0
      RETURN
    END IF
    WEIGHT=RAW_WEIGHT/TOTAL
    MEAN_DLOG=0.D0
    DO I=1,NAT
      DO J=1,NAT
        MEAN_DLOG(:,J)=MEAN_DLOG(:,J)+WEIGHT(I)*DLOG(:,J,I)
      END DO
    END DO
    DO I=1,NAT
      DO J=1,NAT
        DWEIGHT_DATOM(:,J,I)=WEIGHT(I) &
 &                          *(DLOG(:,J,I)-MEAN_DLOG(:,J))
      END DO
      DO J=1,NAT
        DWEIGHT_DPOINT(:,I)=DWEIGHT_DPOINT(:,I) &
 &                         -DWEIGHT_DATOM(:,J,I)
      END DO
    END DO
    IF(PRESENT(DWEIGHT_DSTRAIN)) THEN
      POINT_RESPONSE=POINT
      IF(PRESENT(POINT_STRAIN_COORD)) POINT_RESPONSE=POINT_STRAIN_COORD
      DO I=1,NAT
        DO IDIR=1,3
          DO JDIR=1,3
            DWEIGHT_DSTRAIN(IDIR,JDIR,I)= &
 &              DWEIGHT_DPOINT(IDIR,I)*POINT_RESPONSE(JDIR)
            DO J=1,NAT
              DWEIGHT_DSTRAIN(IDIR,JDIR,I)= &
 &              DWEIGHT_DSTRAIN(IDIR,JDIR,I) &
 &             +DWEIGHT_DATOM(IDIR,J,I)*IMAGE(J,JDIR)
            END DO
          END DO
        END DO
      END DO
    END IF
  END SUBROUTINE PAW_SKALA_SMOOTH_PARTITION_DERIVATIVES

  SUBROUTINE PAW_SKALA_GRID_TEST(MAXERROR)
    IMPLICIT NONE
    REAL(8),INTENT(OUT) :: MAXERROR
    INTEGER(4),PARAMETER :: NR1=12,NR2=11,NR3=10,NAT=2,NDIMD=2
    INTEGER(4),PARAMETER :: NBACK=4,NSBACK=2
    REAL(8) :: RBAS(3,3),FIELD(NR1,NR2,NR3),ADJOINT(NR1,NR2,NR3)
    REAL(8) :: RHO(NR1,NR2,NR3,NDIMD),TAU(NR1,NR2,NR3,NDIMD)
    REAL(8) :: GRHO(NR1,NR2,NR3,3,NDIMD)
    REAL(8) :: ADJRHO(NR1,NR2,NR3,NDIMD)
    REAL(8) :: ADJTAU(NR1,NR2,NR3,NDIMD)
    REAL(8) :: ADJGRHO(NR1,NR2,NR3,3,NDIMD)
    REAL(8) :: BACKRHO(NR1,NR2,NR3,NDIMD)
    REAL(8) :: BACKTAU(NR1,NR2,NR3,NDIMD)
    REAL(8) :: BACKGRHO(NR1,NR2,NR3,3,NDIMD)
    REAL(8) :: REFRHO(NR1,NR2,NR3,NDIMD)
    REAL(8) :: REFTAU(NR1,NR2,NR3,NDIMD)
    REAL(8) :: REFGRHO(NR1,NR2,NR3,3,NDIMD)
    REAL(8) :: BACKPOINT(NBACK,3),BACKDENSITY(NBACK,2)
    REAL(8) :: BACKGRAD(NBACK,3,2),BACKKIN(NBACK,2)
    REAL(8) :: POINT(3),POINT2(3),ATOMCOORD(NAT,3),WEIGHT(NAT),WEIGHT2(NAT)
    REAL(8) :: ATOMPERT(NAT,3),WEIGHTP(NAT),WEIGHTM(NAT)
    REAL(8) :: DWEIGHT_DATOM(3,NAT,NAT),DWEIGHT_DPOINT(3,NAT)
    REAL(8) :: DWEIGHT_DSTRAIN(3,3,NAT),DWEIGHT_DSTRAIN_LOCAL(3,3,NAT)
    REAL(8) :: RBASPERT(3,3),DEFORM(3,3),LOCALCENTER(3),LOCALOFFSET(3)
    REAL(8),ALLOCATABLE :: LOCALCOORD(:,:),LOCALWEIGHT(:)
    REAL(8) :: VALUE,VALUE1,LHS,RHS,GRAD(3),GRADFD(3),STEP,RCUT,VOLUME
    REAL(8) :: RHOVAL(NDIMD),TAUVAL(NDIMD),GRADVAL(3,NDIMD)
    REAL(8) :: RHOVALP(NDIMD),TAUVALP(NDIMD),GRADVALP(3,NDIMD)
    REAL(8) :: RHOVALM(NDIMD),TAUVALM(NDIMD),GRADVALM(3,NDIMD)
    REAL(8) :: DRHOVAL(3,NDIMD),DTAUVAL(3,NDIMD)
    REAL(8) :: DGRADVAL(3,3,NDIMD)
    REAL(8) :: RHOBAR(NDIMD),TAUBAR(NDIMD),GRADBAR(3,NDIMD)
    INTEGER(4) :: I1,I2,I3,IDIR,JDIR,IDIM,ICART,IAT,NANG,NLOCAL
    INTEGER(4) :: IP,IWORK,BACKINDEX(NSBACK)
    LOGICAL(4) :: TBACKACC

    RBAS=RESHAPE((/8.D0,0.D0,0.D0,1.2D0,7.D0,0.D0 &
 &                ,0.4D0,0.8D0,6.D0/),(/3,3/))
    DO I3=1,NR3
      DO I2=1,NR2
        DO I1=1,NR1
          FIELD(I1,I2,I3)=SIN(0.31D0*REAL(I1,KIND=8)) &
 &                       +COS(0.27D0*REAL(I2,KIND=8)) &
 &                       +0.03D0*REAL(I3**2,KIND=8)
        END DO
      END DO
    END DO
    POINT=MATMUL(RBAS,(/3.D0/NR1,4.D0/NR2,2.D0/NR3/))
    CALL PAW_SKALA_GRID_INTERPOLATE(NR1,NR2,NR3,RBAS,FIELD,POINT,VALUE)
    MAXERROR=ABS(VALUE-FIELD(4,5,3))
    MAXERROR=MAX(MAXERROR,ABS(9.D-12 &
 &      *PAW_SKALA_PARTITION_TAPER_DERIVATIVE(5.5D-12)-1.875D0))
    RCUT=4.D0
    STEP=1.D-6
    VALUE=PAW_SKALA_RADIAL_BLEND(3.6D0,RCUT)
    LHS=PAW_SKALA_RADIAL_BLEND(3.6D0+STEP,RCUT)
    RHS=PAW_SKALA_RADIAL_BLEND(3.6D0-STEP,RCUT)
    MAXERROR=MAX(MAXERROR,ABS(PAW_SKALA_RADIAL_BLEND_DERIVATIVE &
 &                 (3.6D0,RCUT)-(LHS-RHS)/(2.D0*STEP)))
    MAXERROR=MAX(MAXERROR,ABS(VALUE-0.5D0))
    MAXERROR=MAX(MAXERROR,ABS(PAW_SKALA_RADIAL_BLEND(3.2D0,RCUT)-1.D0))
    MAXERROR=MAX(MAXERROR,ABS(PAW_SKALA_RADIAL_BLEND(4.D0,RCUT)))

    POINT=MATMUL(RBAS,(/0.237D0,0.419D0,0.713D0/))
    VALUE1=-0.371D0
    CALL PAW_SKALA_GRID_INTERPOLATE(NR1,NR2,NR3,RBAS,FIELD,POINT,VALUE)
    ADJOINT=0.D0
    CALL PAW_SKALA_GRID_INTERPOLATION_ADJOINT(NR1,NR2,NR3,RBAS &
 &                                            ,ADJOINT,POINT,VALUE1)
    LHS=VALUE*VALUE1
    RHS=SUM(FIELD*ADJOINT)
    MAXERROR=MAX(MAXERROR,ABS(LHS-RHS))

    CALL PAW_SKALA_GRID_INTERPOLATE_GRADIENT(NR1,NR2,NR3,RBAS &
 &                                            ,FIELD,POINT,GRAD)
    STEP=1.D-5
    DO IDIR=1,3
      POINT2=POINT
      POINT2(IDIR)=POINT2(IDIR)+STEP
      CALL PAW_SKALA_GRID_INTERPOLATE(NR1,NR2,NR3,RBAS,FIELD,POINT2,LHS)
      POINT2(IDIR)=POINT(IDIR)-STEP
      CALL PAW_SKALA_GRID_INTERPOLATE(NR1,NR2,NR3,RBAS,FIELD,POINT2,RHS)
      GRADFD(IDIR)=(LHS-RHS)/(2.D0*STEP)
    END DO
    MAXERROR=MAX(MAXERROR,MAXVAL(ABS(GRAD-GRADFD)))

    DO IDIM=1,NDIMD
      RHO(:,:,:,IDIM)=(0.2D0+0.3D0*REAL(IDIM,KIND=8))*FIELD+0.1D0
      TAU(:,:,:,IDIM)=(-0.4D0+0.2D0*REAL(IDIM,KIND=8))*FIELD-0.3D0
      DO ICART=1,3
        GRHO(:,:,:,ICART,IDIM)=REAL(ICART+2*IDIM,KIND=8)*FIELD/7.D0
      END DO
    END DO
    CALL PAW_SKALA_GRID_INTERPOLATE_PRIMITIVES(NR1,NR2,NR3,RBAS,NDIMD &
 &                                             ,RHO,GRHO,TAU,POINT &
 &                                             ,RHOVAL,GRADVAL,TAUVAL &
 &                                             ,DRHOVAL,DGRADVAL,DTAUVAL)
    DO IDIM=1,NDIMD
      CALL PAW_SKALA_GRID_INTERPOLATE(NR1,NR2,NR3,RBAS &
 &                                   ,RHO(:,:,:,IDIM),POINT,VALUE)
      MAXERROR=MAX(MAXERROR,ABS(RHOVAL(IDIM)-VALUE))
      CALL PAW_SKALA_GRID_INTERPOLATE(NR1,NR2,NR3,RBAS &
 &                                   ,TAU(:,:,:,IDIM),POINT,VALUE)
      MAXERROR=MAX(MAXERROR,ABS(TAUVAL(IDIM)-VALUE))
      DO ICART=1,3
        CALL PAW_SKALA_GRID_INTERPOLATE(NR1,NR2,NR3,RBAS &
 &                              ,GRHO(:,:,:,ICART,IDIM),POINT,VALUE)
        MAXERROR=MAX(MAXERROR,ABS(GRADVAL(ICART,IDIM)-VALUE))
      END DO
    END DO
    STEP=1.D-5
    DO IDIR=1,3
      POINT2=POINT
      POINT2(IDIR)=POINT2(IDIR)+STEP
      CALL PAW_SKALA_GRID_INTERPOLATE_PRIMITIVES &
 &         (NR1,NR2,NR3,RBAS,NDIMD,RHO,GRHO,TAU,POINT2 &
 &         ,RHOVALP,GRADVALP,TAUVALP)
      POINT2(IDIR)=POINT(IDIR)-STEP
      CALL PAW_SKALA_GRID_INTERPOLATE_PRIMITIVES &
 &         (NR1,NR2,NR3,RBAS,NDIMD,RHO,GRHO,TAU,POINT2 &
 &         ,RHOVALM,GRADVALM,TAUVALM)
      MAXERROR=MAX(MAXERROR,MAXVAL(ABS(DRHOVAL(IDIR,:) &
 &                                  -(RHOVALP-RHOVALM)/(2.D0*STEP))))
      MAXERROR=MAX(MAXERROR,MAXVAL(ABS(DTAUVAL(IDIR,:) &
 &                                  -(TAUVALP-TAUVALM)/(2.D0*STEP))))
      MAXERROR=MAX(MAXERROR,MAXVAL(ABS(DGRADVAL(:,IDIR,:) &
 &                                  -(GRADVALP-GRADVALM)/(2.D0*STEP))))
    END DO
    LOCALCENTER=MATMUL(RBAS,(/0.19D0,0.37D0,0.43D0/))
    LOCALOFFSET=(/0.17D0,-0.11D0,0.09D0/)
    POINT=LOCALCENTER+LOCALOFFSET
    CALL PAW_SKALA_GRID_INTERPOLATE_PRIMITIVES(NR1,NR2,NR3,RBAS,NDIMD &
 &                                             ,RHO,GRHO,TAU,POINT &
 &                                             ,RHOVAL,GRADVAL,TAUVAL &
 &                                             ,DRHOVAL,DGRADVAL,DTAUVAL)
    STEP=3.D-6
    DO IDIR=1,3
      DO JDIR=1,3
        DEFORM=0.D0
        DEFORM(1,1)=1.D0
        DEFORM(2,2)=1.D0
        DEFORM(3,3)=1.D0
        DEFORM(IDIR,JDIR)=DEFORM(IDIR,JDIR)+STEP
        RBASPERT=MATMUL(DEFORM,RBAS)
        POINT2=MATMUL(DEFORM,LOCALCENTER)+LOCALOFFSET
        CALL PAW_SKALA_GRID_INTERPOLATE_PRIMITIVES &
 &           (NR1,NR2,NR3,RBASPERT,NDIMD,RHO,GRHO,TAU,POINT2 &
 &           ,RHOVALP,GRADVALP,TAUVALP)
        DEFORM(IDIR,JDIR)=DEFORM(IDIR,JDIR)-2.D0*STEP
        RBASPERT=MATMUL(DEFORM,RBAS)
        POINT2=MATMUL(DEFORM,LOCALCENTER)+LOCALOFFSET
        CALL PAW_SKALA_GRID_INTERPOLATE_PRIMITIVES &
 &           (NR1,NR2,NR3,RBASPERT,NDIMD,RHO,GRHO,TAU,POINT2 &
 &           ,RHOVALM,GRADVALM,TAUVALM)
        MAXERROR=MAX(MAXERROR,MAXVAL(ABS(-DRHOVAL(IDIR,:) &
 &                    *LOCALOFFSET(JDIR)-(RHOVALP-RHOVALM)/(2.D0*STEP))))
        MAXERROR=MAX(MAXERROR,MAXVAL(ABS(-DTAUVAL(IDIR,:) &
 &                    *LOCALOFFSET(JDIR)-(TAUVALP-TAUVALM)/(2.D0*STEP))))
        MAXERROR=MAX(MAXERROR,MAXVAL(ABS(-DGRADVAL(:,IDIR,:) &
 &                    *LOCALOFFSET(JDIR)-(GRADVALP-GRADVALM)/(2.D0*STEP))))
      END DO
    END DO
    RHOBAR=(/0.31D0,-0.27D0/)
    TAUBAR=(/-0.19D0,0.23D0/)
    GRADBAR=RESHAPE((/0.11D0,-0.13D0,0.17D0,-0.29D0,0.37D0,-0.41D0/) &
 &                 ,SHAPE(GRADBAR))
    ADJRHO=0.D0
    ADJGRHO=0.D0
    ADJTAU=0.D0
    CALL PAW_SKALA_GRID_PRIMITIVES_ADJOINT(NR1,NR2,NR3,RBAS,NDIMD &
 &                                         ,ADJRHO,ADJGRHO,ADJTAU,POINT &
 &                                         ,RHOBAR,GRADBAR,TAUBAR)
    LHS=SUM(RHOVAL*RHOBAR)+SUM(GRADVAL*GRADBAR)+SUM(TAUVAL*TAUBAR)
    RHS=SUM(RHO*ADJRHO)+SUM(GRHO*ADJGRHO)+SUM(TAU*ADJTAU)
    MAXERROR=MAX(MAXERROR,ABS(LHS-RHS))

    BACKINDEX(1)=1
    BACKINDEX(2)=2+NR1*((3-1)+NR2*(4-1))
    BACKPOINT=0.D0
    BACKPOINT(3,:)=MATMUL(RBAS,(/0.237D0,0.419D0,0.713D0/))
    BACKPOINT(4,:)=MATMUL(RBAS,(/0.913D0,0.071D0,0.337D0/))
    DO IP=1,NBACK
      BACKDENSITY(IP,1)=0.07D0*REAL(IP,KIND=8)-0.19D0
      BACKDENSITY(IP,2)=-0.05D0*REAL(IP,KIND=8)+0.11D0
      BACKKIN(IP,1)=0.03D0*REAL(IP,KIND=8)+0.13D0
      BACKKIN(IP,2)=-0.09D0*REAL(IP,KIND=8)+0.17D0
      DO ICART=1,3
        BACKGRAD(IP,ICART,1)=0.01D0*REAL(IP+2*ICART,KIND=8)
        BACKGRAD(IP,ICART,2)=-0.02D0*REAL(2*IP+ICART,KIND=8)
      END DO
    END DO
    REFRHO=0.D0
    REFGRHO=0.D0
    REFTAU=0.D0
    DO IP=1,NSBACK
      IWORK=BACKINDEX(IP)-1
      I1=MOD(IWORK,NR1)+1
      IWORK=IWORK/NR1
      I2=MOD(IWORK,NR2)+1
      I3=IWORK/NR2+1
      DO IDIM=1,NDIMD
        VALUE=MERGE(1.D0,-1.D0,IDIM.EQ.1)
        REFRHO(I1,I2,I3,IDIM)=REFRHO(I1,I2,I3,IDIM) &
 &        +0.5D0*(BACKDENSITY(IP,1)+VALUE*BACKDENSITY(IP,2))
        REFTAU(I1,I2,I3,IDIM)=REFTAU(I1,I2,I3,IDIM) &
 &        +0.5D0*(BACKKIN(IP,1)+VALUE*BACKKIN(IP,2))
        DO ICART=1,3
          REFGRHO(I1,I2,I3,ICART,IDIM)= &
 &          REFGRHO(I1,I2,I3,ICART,IDIM) &
 &          +0.5D0*(BACKGRAD(IP,ICART,1) &
 &                  +VALUE*BACKGRAD(IP,ICART,2))
        END DO
      END DO
    END DO
    DO IP=NSBACK+1,NBACK
      DO IDIM=1,NDIMD
        VALUE=MERGE(1.D0,-1.D0,IDIM.EQ.1)
        RHOBAR(IDIM)=0.5D0*(BACKDENSITY(IP,1) &
 &                                +VALUE*BACKDENSITY(IP,2))
        TAUBAR(IDIM)=0.5D0*(BACKKIN(IP,1)+VALUE*BACKKIN(IP,2))
        DO ICART=1,3
          GRADBAR(ICART,IDIM)=0.5D0*(BACKGRAD(IP,ICART,1) &
 &                                         +VALUE*BACKGRAD(IP,ICART,2))
        END DO
      END DO
      CALL PAW_SKALA_GRID_PRIMITIVES_ADJOINT(NR1,NR2,NR3,RBAS,NDIMD &
 &                                           ,REFRHO,REFGRHO,REFTAU &
 &                                           ,BACKPOINT(IP,:),RHOBAR &
 &                                           ,GRADBAR,TAUBAR)
    END DO
    BACKRHO=0.D0
    BACKGRHO=0.D0
    BACKTAU=0.D0
    CALL PAW_SKALA_GRID_BACK_BEGIN(NR1,NR2,NR3,NDIMD &
 &                                ,BACKRHO,BACKGRHO,BACKTAU,TBACKACC)
    CALL PAW_SKALA_GRID_BACKPROJECT(NR1,NR2,NR3,RBAS,NDIMD &
 &                                 ,NSBACK,NBACK,BACKINDEX,BACKPOINT &
 &                                 ,BACKDENSITY,BACKGRAD,BACKKIN &
 &                                 ,BACKRHO,BACKGRHO,BACKTAU,TBACKACC)
    CALL PAW_SKALA_GRID_BACK_END(NR1,NR2,NR3,NDIMD &
 &                              ,BACKRHO,BACKGRHO,BACKTAU,TBACKACC)
    MAXERROR=MAX(MAXERROR,MAXVAL(ABS(BACKRHO-REFRHO)))
    MAXERROR=MAX(MAXERROR,MAXVAL(ABS(BACKGRHO-REFGRHO)))
    MAXERROR=MAX(MAXERROR,MAXVAL(ABS(BACKTAU-REFTAU)))

    ATOMCOORD(1,:)=MATMUL(RBAS,(/0.1D0,0.2D0,0.3D0/))
    ATOMCOORD(2,:)=MATMUL(RBAS,(/0.6D0,0.2D0,0.3D0/))
    POINT=0.5D0*(ATOMCOORD(1,:)+ATOMCOORD(2,:))
    CALL PAW_SKALA_SMOOTH_PARTITION(POINT,NAT,ATOMCOORD,RBAS,WEIGHT)
    POINT2=POINT+RBAS(:,1)
    CALL PAW_SKALA_SMOOTH_PARTITION(POINT2,NAT,ATOMCOORD,RBAS,WEIGHT2)
    MAXERROR=MAX(MAXERROR,ABS(SUM(WEIGHT)-1.D0))
    MAXERROR=MAX(MAXERROR,MAXVAL(ABS(WEIGHT-WEIGHT2)))
    MAXERROR=MAX(MAXERROR,ABS(WEIGHT(1)-0.5D0),ABS(WEIGHT(2)-0.5D0))
    MAXERROR=MAX(MAXERROR,ABS(PAW_SKALA_PARTITION_TAPER(0.D0)))
    MAXERROR=MAX(MAXERROR,ABS(PAW_SKALA_PARTITION_TAPER(1.D0)-1.D0))

    POINT=MATMUL(RBAS,(/0.31D0,0.23D0,0.37D0/))
    CALL PAW_SKALA_SMOOTH_PARTITION_DERIVATIVES(POINT,NAT,ATOMCOORD,RBAS &
 &                                             ,WEIGHT,DWEIGHT_DATOM &
 &                                             ,DWEIGHT_DPOINT &
 &                                             ,DWEIGHT_DSTRAIN)
    STEP=1.D-6
    DO IAT=1,NAT
      DO IDIR=1,3
        ATOMPERT=ATOMCOORD
        ATOMPERT(IAT,IDIR)=ATOMPERT(IAT,IDIR)+STEP
        CALL PAW_SKALA_SMOOTH_PARTITION(POINT,NAT,ATOMPERT,RBAS,WEIGHTP)
        ATOMPERT(IAT,IDIR)=ATOMPERT(IAT,IDIR)-2.D0*STEP
        CALL PAW_SKALA_SMOOTH_PARTITION(POINT,NAT,ATOMPERT,RBAS,WEIGHTM)
        MAXERROR=MAX(MAXERROR,MAXVAL(ABS(DWEIGHT_DATOM(IDIR,IAT,:) &
 &                                -(WEIGHTP-WEIGHTM)/(2.D0*STEP))))
      END DO
    END DO
    DO IDIR=1,3
      POINT2=POINT
      POINT2(IDIR)=POINT2(IDIR)+STEP
      CALL PAW_SKALA_SMOOTH_PARTITION(POINT2,NAT,ATOMCOORD,RBAS,WEIGHTP)
      POINT2(IDIR)=POINT(IDIR)-STEP
      CALL PAW_SKALA_SMOOTH_PARTITION(POINT2,NAT,ATOMCOORD,RBAS,WEIGHTM)
      MAXERROR=MAX(MAXERROR,MAXVAL(ABS(DWEIGHT_DPOINT(IDIR,:) &
 &                              -(WEIGHTP-WEIGHTM)/(2.D0*STEP))))
    END DO
    MAXERROR=MAX(MAXERROR,MAXVAL(ABS(SUM(DWEIGHT_DATOM,DIM=3))))
    MAXERROR=MAX(MAXERROR,MAXVAL(ABS(DWEIGHT_DPOINT &
 &                                 +SUM(DWEIGHT_DATOM,DIM=2))))
    DO IDIR=1,3
      DO JDIR=1,3
        DEFORM=0.D0
        DEFORM(1,1)=1.D0
        DEFORM(2,2)=1.D0
        DEFORM(3,3)=1.D0
        DEFORM(IDIR,JDIR)=DEFORM(IDIR,JDIR)+STEP
        RBASPERT=MATMUL(DEFORM,RBAS)
        ATOMPERT=TRANSPOSE(MATMUL(DEFORM,TRANSPOSE(ATOMCOORD)))
        POINT2=MATMUL(DEFORM,POINT)
        CALL PAW_SKALA_SMOOTH_PARTITION(POINT2,NAT,ATOMPERT,RBASPERT &
 &                                     ,WEIGHTP)
        DEFORM(IDIR,JDIR)=DEFORM(IDIR,JDIR)-2.D0*STEP
        RBASPERT=MATMUL(DEFORM,RBAS)
        ATOMPERT=TRANSPOSE(MATMUL(DEFORM,TRANSPOSE(ATOMCOORD)))
        POINT2=MATMUL(DEFORM,POINT)
        CALL PAW_SKALA_SMOOTH_PARTITION(POINT2,NAT,ATOMPERT,RBASPERT &
 &                                     ,WEIGHTM)
        MAXERROR=MAX(MAXERROR,MAXVAL(ABS(DWEIGHT_DSTRAIN(IDIR,JDIR,:) &
 &                              -(WEIGHTP-WEIGHTM)/(2.D0*STEP))))
      END DO
    END DO

    LOCALOFFSET=(/0.17D0,-0.11D0,0.09D0/)
    POINT=ATOMCOORD(1,:)+LOCALOFFSET
    CALL PAW_SKALA_SMOOTH_PARTITION_DERIVATIVES(POINT,NAT,ATOMCOORD,RBAS &
 &                                             ,WEIGHT,DWEIGHT_DATOM &
 &                                             ,DWEIGHT_DPOINT &
 &                                             ,DWEIGHT_DSTRAIN_LOCAL &
 &                                             ,ATOMCOORD(1,:))
    DO IDIR=1,3
      DO JDIR=1,3
        DEFORM=0.D0
        DEFORM(1,1)=1.D0
        DEFORM(2,2)=1.D0
        DEFORM(3,3)=1.D0
        DEFORM(IDIR,JDIR)=DEFORM(IDIR,JDIR)+STEP
        RBASPERT=MATMUL(DEFORM,RBAS)
        ATOMPERT=TRANSPOSE(MATMUL(DEFORM,TRANSPOSE(ATOMCOORD)))
        POINT2=ATOMPERT(1,:)+LOCALOFFSET
        CALL PAW_SKALA_SMOOTH_PARTITION(POINT2,NAT,ATOMPERT,RBASPERT &
 &                                     ,WEIGHTP)
        DEFORM(IDIR,JDIR)=DEFORM(IDIR,JDIR)-2.D0*STEP
        RBASPERT=MATMUL(DEFORM,RBAS)
        ATOMPERT=TRANSPOSE(MATMUL(DEFORM,TRANSPOSE(ATOMCOORD)))
        POINT2=ATOMPERT(1,:)+LOCALOFFSET
        CALL PAW_SKALA_SMOOTH_PARTITION(POINT2,NAT,ATOMPERT,RBASPERT &
 &                                     ,WEIGHTM)
        MAXERROR=MAX(MAXERROR &
 &            ,MAXVAL(ABS(DWEIGHT_DSTRAIN_LOCAL(IDIR,JDIR,:) &
 &                        -(WEIGHTP-WEIGHTM)/(2.D0*STEP))))
      END DO
    END DO

    RCUT=2.3D0
    CALL PAW_SKALA_LOCAL_GRID_SIZE(20,17,NANG,NLOCAL,3)
    ALLOCATE(LOCALCOORD(NLOCAL,3),LOCALWEIGHT(NLOCAL))
    CALL PAW_SKALA_LOCAL_GRID(20,RCUT,17,NLOCAL,LOCALCOORD,LOCALWEIGHT,3)
    VOLUME=4.D0*ACOS(-1.D0)*RCUT**3/3.D0
    MAXERROR=MAX(MAXERROR,ABS(SUM(LOCALWEIGHT)-VOLUME))
    MAXERROR=MAX(MAXERROR,ABS(SUM(LOCALWEIGHT*LOCALCOORD(:,1)**2) &
 &                              -4.D0*ACOS(-1.D0)*RCUT**5/15.D0))
    DEALLOCATE(LOCALCOORD,LOCALWEIGHT)
  END SUBROUTINE PAW_SKALA_GRID_TEST

END MODULE PAW_SKALA_GRID_MODULE
