!***************************************************************************
!**  @(#) 1.16.1.1 src/ppe/poe/include/mpif.h, ppe.poe.mpi, ppe_r2.4, r2_4s17a 96/08/28 15:48:55
!**
!**  Name: mpif.h
!**
!**  Description:
!**
!**  Licensed Materials - Property of IBM
!**
!**  5765-144 5765-543 (C) Copyright IBM Corp. 1994,1995
!**
!**   All rights reserved.
!**   US Government Users Restricted Rights - Use, Duplication or Disclosure
!**   restricted by GSA ADP Schedule Contract with IBM Corp.
!**
!*****************************************************************************
INTEGER,PARAMETER :: MPI_SUCCESS=0
INTEGER,PARAMETER :: MPI_ERR_BUFFER=50
INTEGER,PARAMETER :: MPI_ERR_COUNT=51
INTEGER,PARAMETER :: MPI_ERR_TYPE=52
INTEGER,PARAMETER :: MPI_ERR_TAG=53
INTEGER,PARAMETER :: MPI_ERR_COMM=54
INTEGER,PARAMETER :: MPI_ERR_RANK=55
INTEGER,PARAMETER :: MPI_ERR_REQUEST=56
INTEGER,PARAMETER :: MPI_ERR_ROOT=57
INTEGER,PARAMETER :: MPI_ERR_GROUP=58
INTEGER,PARAMETER :: MPI_ERR_OP=59
INTEGER,PARAMETER :: MPI_ERR_TOPOLOGY=60
INTEGER,PARAMETER :: MPI_ERR_DIMS=61
INTEGER,PARAMETER :: MPI_ERR_ARG=62
INTEGER,PARAMETER :: MPI_ERR_UNKNOWN=63
INTEGER,PARAMETER :: MPI_ERR_TRUNCATE=64
INTEGER,PARAMETER :: MPI_ERR_OTHER=65
INTEGER,PARAMETER :: MPI_ERR_INTERN=66
INTEGER,PARAMETER :: MPI_ERR_IN_STATUS=67
INTEGER,PARAMETER :: MPI_PENDING=68
INTEGER,PARAMETER :: MPI_ERR_PENDING=68
INTEGER,PARAMETER :: MPI_ERR_LASTCODE=175
!
INTEGER,PARAMETER :: MPI_PROC_NULL=-3
INTEGER,PARAMETER :: MPI_ANY_SOURCE=-1
INTEGER,PARAMETER :: MPI_ANY_TAG=-1
INTEGER,PARAMETER :: MPI_UNDEFINED=-1
!
INTEGER,PARAMETER :: MPI_STATUS_SIZE=8
INTEGER,PARAMETER :: MPI_SOURCE=1
INTEGER,PARAMETER :: MPI_TAG=2
INTEGER,PARAMETER :: MPI_ERROR=3
!
INTEGER,PARAMETER :: MPI_ERRORS_ARE_FATAL=0
INTEGER,PARAMETER :: MPI_ERRORS_RETURN=1
INTEGER,PARAMETER ::  MPE_ERRORS_WARN=2
!
INTEGER,PARAMETER :: MPI_MAX_PROCESSOR_NAME=256
INTEGER,PARAMETER :: MPI_MAX_ERROR_STRING=128
!
INTEGER,PARAMETER :: MPI_BSEND_OVERHEAD=16
!
INTEGER,PARAMETER :: MPI_LB=0
INTEGER,PARAMETER :: MPI_UB=1
INTEGER,PARAMETER :: MPI_BYTE=2
INTEGER,PARAMETER :: MPI_PACKED=3
!
INTEGER,PARAMETER :: MPI_INTEGER1=16
INTEGER,PARAMETER :: MPI_INTEGER2=17
INTEGER,PARAMETER :: MPI_INTEGER4=18
INTEGER,PARAMETER :: MPI_INTEGER=18
INTEGER,PARAMETER :: MPI_REAL4=19
INTEGER,PARAMETER :: MPI_REAL=19
INTEGER,PARAMETER :: MPI_REAL8=20
INTEGER,PARAMETER :: MPI_DOUBLE_PRECISION=20
INTEGER,PARAMETER :: MPI_REAL16=21
INTEGER,PARAMETER :: MPI_COMPLEX8=22
INTEGER,PARAMETER :: MPI_COMPLEX=22
INTEGER,PARAMETER :: MPI_COMPLEX16=23
INTEGER,PARAMETER :: MPI_DOUBLE_COMPLEX=23
INTEGER,PARAMETER :: MPI_COMPLEX32=24
INTEGER,PARAMETER :: MPI_LOGICAL1=25
INTEGER,PARAMETER :: MPI_LOGICAL2=26
INTEGER,PARAMETER :: MPI_LOGICAL4=27
INTEGER,PARAMETER :: MPI_LOGICAL=27
INTEGER,PARAMETER :: MPI_CHARACTER=28
!
INTEGER,PARAMETER :: MPI_2REAL=35
INTEGER,PARAMETER :: MPI_2DOUBLE_PRECISION=36
INTEGER,PARAMETER :: MPI_2INTEGER=37
INTEGER,PARAMETER :: MPI_2COMPLEX=38
!
INTEGER,PARAMETER :: MPI_COMM_WORLD=0
INTEGER,PARAMETER :: MPI_COMM_SELF=1
!
INTEGER,PARAMETER :: MPI_IDENT=0
INTEGER,PARAMETER :: MPI_CONGRUENT=1
INTEGER,PARAMETER :: MPI_SIMILAR=2
INTEGER,PARAMETER :: MPI_UNEQUAL=3
!
INTEGER,PARAMETER :: MPI_TAG_UB=0
INTEGER,PARAMETER :: MPI_IO=1
INTEGER,PARAMETER :: MPI_HOST=2
INTEGER,PARAMETER :: MPI_WTIME_IS_GLOBAL=3
! 
INTEGER,PARAMETER :: MPI_MAX=0
INTEGER,PARAMETER :: MPI_MIN=1
INTEGER,PARAMETER :: MPI_SUM=2
INTEGER,PARAMETER :: MPI_PROD=3
INTEGER,PARAMETER :: MPI_MAXLOC=4
INTEGER,PARAMETER :: MPI_MINLOC=5
INTEGER,PARAMETER :: MPI_BAND=6
INTEGER,PARAMETER :: MPI_BOR=7
INTEGER,PARAMETER :: MPI_BXOR=8
INTEGER,PARAMETER :: MPI_LAND=9
INTEGER,PARAMETER :: MPI_LOR=10
INTEGER,PARAMETER :: MPI_LXOR=11
INTEGER,PARAMETER :: MAX_OP=12
! 
INTEGER,PARAMETER :: MPI_GROUP_NULL=-1
INTEGER,PARAMETER :: MPI_COMM_NULL=-1
INTEGER,PARAMETER :: MPI_DATATYPE_NULL=-1
INTEGER,PARAMETER :: MPI_REQUEST_NULL=-1
INTEGER,PARAMETER :: MPI_OP_NULL=-1
INTEGER,PARAMETER :: MPI_ERRHANDLER_NULL=-1
!
INTEGER,PARAMETER :: MPI_GROUP_EMPTY=-1 
!
INTEGER,PARAMETER :: MPI_GRAPH=0
INTEGER,PARAMETER :: MPI_CART=1 
!
INTEGER,PARAMETER :: MPI_KEYVAL_INVALID=-1
!
DOUBLE PRECISION MPI_WTICK,MPI_WTIME
EXTERNAL MPI_WTICK,MPI_WTIME
! 
EXTERNAL MPI_NULL_COPY_FN,MPI_DUP_FN,MPI_NULL_DELETE_FN
EXTERNAL MPI_BOTTOM
!
