#!/bin/sh
#
#  extracts the dependencies from a list of fortran files
#
CURRDIR=$(pwd)
PAWDIR=${CURRDIR%/src/F90PP}
FILES1="${PAWDIR}/src/*.f90" 
FILES2="${PAWDIR}/src/Tools/*/*.f90"
#
#  scan all files for dependencies and write them into 
#  the file "dependencies
#
g95 -o finddependencies.x finddependencies.f90
rm dependencies
touch dependencies
for FILE in $FILES1; do
  finddependencies.x ${FILE} >> dependencies
  echo $FILE considered...
done
for FILE in $FILES2; do
  finddependencies.x ${FILE} >> dependencies
  echo $FILE considered...
done
rm finddependencies.x 
#
# check for duplicated and circular dependencies
#
g95 -o circulardependencies.x circulardependencies.f90
circulardependencies.x <dependencies
rm circulardependencies.x 